legal-api/src/legal_api/services/document_meta.py
legal-api/tests/unit/services/test_document_meta.py

*Issue #:* /bcgov/entity#5275
Updated document list as per task, and updated corresponding test

5275 legal api update document list

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/src/legal_api/services/filings/validations/validation.py

*Issue #:* /bcgov/entity#6584
Include validation in share structures for alterations.

Include share structure validation for alterations.

---

lear-db/lear_db.sql
legal-api/migrations/versions/2dedf50a17ef_added_court_order_columns_to_filings_.py
legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/models/filing.py
legal-api/tests/unit/models/test_filing.py

*Issue #:* /bcgov/entity#6416
- Added columns to the model;
- Added migration;
- Added test;
- Added columns to lear_db.sql.

6416 - LEGAL API - Court Order and Plan of Arrangement

---

queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/filings.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_filing.py
queue_services/entity-filer/tests/unit/filing_processors/test_alteration.py

*Issue #:* /bcgov/entity#6658
- added courtOrder processing to Alteration Filings.

added courtOrder processing to Alteration Filings.

---

legal-api/report-templates/noticeOfArticles.html
legal-api/report-templates/template-parts/common/benefitCompanyStmt.html
legal-api/report-templates/transitionApplication.html

*Issue #:* /bcgov/entity#6839
Bug fix for resolution date in notice of articles.

6839-Fix for resolution date in noa.

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt

*Issue #:* /bcgov/entity#6417
- Update schema version 

Updated schema version

---

legal-api/src/legal_api/resources/namerequest.py
legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/namex.py
legal-api/tests/unit/api/test_name_requests.py
legal-api/tests/unit/services/filings/validations/test_alteration.py

*Issue #:* /bcgov/entity#6902
* Just refactored bug fix to prevent Json conversion only where required.

Refactored Nr Query bug fix

---

legal-api/migrations/versions/b18741f7c4d3_technical_filing_corrections.py
legal-api/requirements/dev.txt
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/core/test_filing.py

*Issue #:* /bcgov/entity#6618
- added technical json feature to model & core
- fixed lint issue in reports

added technical json to filings

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/test_business.py

*Issue #:* /bcgov/entity#6928
-Added good standing property to business to show if it is meeting current good standing requirements

Added good standing property to business to show if it is meeting current good standing requirements

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/test_business.py

*Issue #:* /bcgov/entity#6928
good standing needed to be added to the api

needed to add good standing to the api

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/tests/unit/services/filings/validations/test_alteration.py

*Issue #:* /bcgov/entity#7100
add validation that the legal type is benefit company

7100 - validate that the alteration type is benefit company

---

queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/test_worker/test_technical_correction.py

*Issue #:* /bcgov/entity#6618
- added tech_correction_json processing to the Filer, this overrides any client supplied json

added tech_correction_json processing to the Filer

---

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_name_request.py
queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py

*Issue #:* /bcgov/entity#7158
- loading an existing incorporation, will create the entity in LEAR

added loading of an existing coop incorporation

---

legal-api/migrations/versions/78ddb7f6f8b5_add_locked_flag_to_filings.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/business/business_filings.py
legal-api/tests/unit/api/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#7101
- Added deletion_locked to filings table; 
- Added logic to avoid deletion; 
- Added tests.

Legal API - prevent LTDs and ULCs from deleting draft alteration

---

queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py

*Issue #:* /bcgov/entity#6766
receipt fields required in future

6766 - added fields for receipts

---

queue_services/entity-filer/requirements.txt

* Updated one conflicting dependency in requirements.txt

4711 fix entity filer dependency conflict

---

legal-api/src/legal_api/services/document_meta.py
legal-api/src/legal_api/services/filings/validations/annual_report.py

7291 added report type to identify different type in alteration

---

legal-api/src/legal_api/reports/report.py
queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/BC-ALT-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/BC-ALT-PAID.html
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/email_processors/test_filing_notification.py

*Issue #:* /bcgov/entity#4612
/bcgov/entity#5031
/bcgov/entity#5032
/bcgov/entity#5033
- Immediate alteration filing successful (i.e. PAID but not COMPLETED)
- Immediate alteration filing successful (COMPLETED)
- Future effective alteration filing (FILED)
- Future effective alteration filing (COMPLETED)
Notes:
- <del>**entity type** is not included by referring to the  existing template in business info and future effective alteration filing (COMPLETED). (_**entity type** Name: **Company Name**_ and _The alteration filing for **entity type** **business name** is now effective_)</del> discussed with Linda and Sienna to remove entity type from requirement
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

4612 Email Notifications upon filing alteration

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/filings/validations/annual_report.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/correction.py

7191 Must have a minimum of one share class

---

legal-api/requirements.txt
legal-api/src/legal_api/__init__.py
legal-api/src/legal_api/resources/business/business_filings.py
legal-api/src/legal_api/services/filings/validations/annual_report.py

*Issue #:* n/a
- updated requirements
- cleaned lint issues
- cleaned tests to green

updated reqs, lints and test

---

legal-api/src/legal_api/services/document_meta.py
legal-api/tests/unit/services/test_document_meta.py
queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py

*Issue #:* /bcgov/entity#7421
- 7421 change of name certificate - if the company changes its legal name
- 6766 bug - pay api receipt

7421 change of name certificate - if the company changes its legal name

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/src/entity_filer/filing_processors/conversion.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_conversion.py

* Added conversion ledger processor
* Added conversion ledger tests 
* Updated incorporation applications tests to test filings from Colin for LTDs, ULCs and CCCs

4711 entity filer updates for data loader

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py
queue_services/entity-pay/src/entity_pay/version.py

*Issue #:* /bcgov/entity#6214
* Updated version numbers for release 2.22 for following components
* legal api
* colin api
* entity filer
* entity emailer
* entity pay

6214 update version numbers for release 2.22

---

legal-api/src/legal_api/services/business_details_version.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py

7483 Skip delivery address if empty

---

legal-api/src/legal_api/models/party_role.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py
queue_services/entity-filer/src/entity_filer/filing_processors/voluntary_dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_voluntary_dissolution.py

*Issue #:* /bcgov/entity#7313
- updated for parties
- updated for parties with partial addresses
- updated part roles to include **custodian**

updated to match incoming dissolution filing information

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/business/business_filings.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/filings/validations/court_order.py
legal-api/src/legal_api/services/filings/validations/registrars_notation.py
legal-api/src/legal_api/services/filings/validations/registrars_order.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/tests/unit/api/test_business_filings/test_filing_notations.py
legal-api/tests/unit/services/filings/test_schemas.py
legal-api/tests/unit/services/test_authorization.py

4390 - New Filing Types: Registrar's Notation, Registrar's Order, Court Order

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/court_order.py
queue_services/entity-filer/src/entity_filer/filing_processors/registrars_notation.py
queue_services/entity-filer/src/entity_filer/filing_processors/registrars_order.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_court_order.py
queue_services/entity-filer/tests/unit/filing_processors/test_registrars_notation.py
queue_services/entity-filer/tests/unit/filing_processors/test_registrars_order.py

6488 filer changes for Notations

---

jobs/filings-notebook-report/daily/incorpfilings.ipynb

*Issue #:* /bcgov/entity#7768
Incorporation Filings Daily Stats Updated

Incorporation Filings Daily Stats Updated #7768

---

legal-api/src/legal_api/core/utils.py
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/core/test_filing_diff.py

*Issue #:* /bcgov/entity#7514
- Fixed diff_dict method; 
- Fixed date and time format.
- Added test

7514 - Fixed corrected label and datetime format

---

legal-api/report-templates/alterationNotice.html
legal-api/report-templates/incorporationApplication.html
legal-api/report-templates/noticeOfArticles.html
legal-api/report-templates/template-parts/common/benefitCompanyStmt.html
legal-api/report-templates/template-parts/common/statement.html
legal-api/report-templates/template-parts/incorporation-application/benefitCompanyStmt.html
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/reports/report.py

*Issue #:*
bcgov/entity#7721
bcgov/entity#7722
bcgov/entity#7726
- Update Incorporation Application output
- Updated Notice of Articles output
- Update Alteration Notice output

7721, 7722, 7726 updates to outputs

---

legal-api/migrations/versions/d21f6be7bd21_submitter_roles.py
legal-api/setup.cfg
legal-api/src/legal_api/config.py
legal-api/src/legal_api/core/constants.py
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/models/__init__.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/models/user.py
legal-api/src/legal_api/resources/business/business_filings.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/document_meta.py
legal-api/tests/unit/api/test_business_filings/test_filings.py
legal-api/tests/unit/api/test_business_filings/test_filings_ledger.py
legal-api/tests/unit/core/test_filing.py
legal-api/tests/unit/core/test_filing_ledger.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/models/test_filing.py

*Issue #:* /bcgov/entity#7195
- update business_filings to return the ledger list for /filings
- update the /filings/{id} for a singular filing

change filings end-point for single filings and ledger search

---

legal-api/report-templates/bcAddressChange.html
legal-api/report-templates/bcDirectorChange.html
legal-api/src/legal_api/reports/report.py

*Issue #:* 
bcgov/entity#7723
bcgov/entity#7724

7723, 7724 Address Change and Director Change output updates

---

colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/resources/filing.py
colin-api/src/colin_api/utils/__init__.py

*Issue #:* /bcgov/entity#7338
* Update datetime related conversion methods to use UTC as opposed to UTC pacific time

7338 updated datetime related conversion methods to use UTC

---

legal-api/src/legal_api/models/filing.py

6954 fee code for BC, ULC, CC

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#7788
* bumped version numbers for colin and legal api

7788 version number updates for release 9.5

---

jobs/email-reminder/email_reminder.py

3796 query fix

---

jobs/email-reminder/config.py
jobs/email-reminder/devops/vaults.json
jobs/email-reminder/email_reminder.py
jobs/email-reminder/k8s/templates/cronjob.yaml

8062 vaults values change

---

queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#7788
* bump `entity-emailer` version

7788 version number bump to entity emailer AR reminder release

---

queue_services/entity-emailer/pre-hook-update-db.sh

*Issue #:* /bcgov/entity#7882
* Update pre-hook update script to run properly as python script

7882 fix tracker db pre-hook update script to run properly

---

jobs/email-reminder/email_reminder.py

*Issue #:* /bcgov/entity#3796
* add debug logging for troubleshooting purposes

3796 add debug logging to email reminder job

---

.github/workflows/entity-emailer-ci.yml
jobs/email-reminder/config.py
jobs/email-reminder/email_reminder.py
queue_services/entity-emailer/requirements/dev.txt
queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py

8048 outstanding bcomps ar reminder

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/utils/datetime.py
legal-api/src/legal_api/utils/legislation_datetime.py
legal-api/tests/__init__.py
legal-api/tests/unit/api/test_business_tasks.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/services/filings/validations/annual_report/test_validate_ar_year.py

*Issue #:* /bcgov/entity#7776
- Fixed ar_max_date (added 1 year and limited to today)
- Fixed nextAnnualReport time offset
- Added and improved tests

7776 - Fix for AR max date

---

legal-api/prism.sh
legal-api/src/legal_api/core/filing.py
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py
queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#8238
- changes to support a corrected alteration
- fixed prism error, allowing pay integration test to run

changes to support corrected alteration

---

queue_services/entity-emailer/src/entity_emailer/email_processors/nr_expiry.py
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-EXPIRED.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_nr_expiry.py
queue_services/entity-emailer/tests/unit/test_worker.py

7388 nr before expiry and expired email

---

queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-RENEWAL.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-UPGRADE.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/email_processors/test_nr_notification.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* /bcgov/entity#8165, /bcgov/entity#8166

8165 - 8166: email nr renewal and upgrade

---

queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-REFUND.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/email_processors/test_nr_notification.py
queue_services/entity-emailer/tests/unit/test_tracker.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* bcgov/entity#7388, bcgov/entity#7389

7388 changed to cloud event msg type & 7389 Refund of NR email

---

jobs/email-reminder/Makefile
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#8318
* changes for release 2.26.0

8318 Release 2.26.0

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/tests/unit/services/filings/validations/__init__.py
legal-api/tests/unit/services/filings/validations/test_incorporation_application.py

*Issue #:* /bcgov/entity#8353
* Add validation rules for directors in an incorporation application filing
* Add/update tests to support new validation rules

8353 Coop IA people and roles validation updates

---

colin-api/.devcontainer/Dockerfile
colin-api/.devcontainer/devcontainer.json
colin-api/setup.cfg
colin-api/src/colin_api/__init__.py
colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/db.py
legal-api/src/legal_api/core/filing.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py
queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#8238
- fixes for "bad director" 

8238 alteration correction

---

colin-api/src/colin_api/models/filing.py

- missed from earlier change to match schema naming

missed from earlier change to match schema naming

---

queue_services/entity-emailer/src/entity_emailer/email_processors/name_request.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* /bcgov/entity#8647
- receipt notification fix for name requests 

nr receipt notification fix

---

legal-api/report-templates/incorporationApplication.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/common/style.html
legal-api/report-templates/template-parts/incorporation-application/completingParty.html
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/utils/legislation_datetime.py

8290 ux review fixes

---

queue_services/entity-emailer/src/entity_emailer/email_processors/name_request.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* /bcgov/entity#8647
- readded in get payments call (would've been nicer if namex_pay was giving the id instead of the token or if we could use the payment token for the pdfs, but alas)
- choose payment with correct payment token and get its pdf

8647 nr email bug

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#8639
- Bumped versions for release 10.3

8639 - Bumped versions for release 10.3

---

legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/report.py

Incorporation Number in IA when filing status is COMPLETED

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt

*Issue #:* /bcgov/entity#8780
- Updated schema version

8780 - updated schema version

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/src/legal_api/services/namex.py
legal-api/tests/unit/api/test_name_requests.py

8844 use NR State - CONSUMED, EXPIRED

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/report.py

8292 support static report

---

legal-api/setup.cfg
legal-api/src/legal_api/resources/business/business_filings.py
legal-api/tests/docker-compose.yml
legal-api/tests/unit/api/test_business_tasks.py

n/a
- fixed lint issues. 
- added bucket creation for minio.
- fixed tests

fixed lint issues. added bucket creation for minio. fixed tests

---

legal-api/src/legal_api/config.py
legal-api/src/legal_api/models/document.py

*Issue #:* /bcgov/entity#8368
- Added document types; 
- Fixed fonts path config.

8368 - Document types

---

legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/src/legal_api/services/minio.py
legal-api/tests/unit/services/filings/validations/test_incorporation_application.py

*Issue #:* /bcgov/entity#8439
* Implement document property and file size checks in IA Validators.
* Updated unit tests.

8439 Coop IA Document validations

---

legal-api/src/legal_api/services/filings/validations/incorporation_application.py

*Issue #:* /bcgov/entity#8439
* Upped allowed file sizes to be measured in bytes

Upped allowed file sizes to measure in bytes

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/devops/vaults.json
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#8368
- Added vaults for entity-filer; 
- bumped up versions

8368 - Added vaults for entity-filer and bumped up versions

---

queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py

9271 Email with the Receipt and the IA not being generated

---

queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/tests/unit/test_tracker.py

email tracker to consider option prop

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

fixed behaviour difference between v1/v2 business endpoint for Temp Registrations

fixed behaviour difference between v1/v2 business endpoint

---

legal-api/src/legal_api/services/pdf_service.py
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/prod.txt
queue_services/entity-filer/src/entity_filer/config.py
queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/tests/docker-compose.yml
queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py

*Issue #:* /bcgov/entity#9015
- entity-filer changes

9015 Refactor entity-filer logic to use a generic folder "businesses"

---

.github/workflows/legal-api-ci.yml
legal-api/requirements.txt
legal-api/requirements/prod.txt
legal-api/setup.cfg
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

- added documents endpoint for filing outputs.

added documents endpoint for filing outputs.

---

legal-api/requirements.txt
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/docker-compose.1.yml
legal-api/tests/docker-compose.yml.ci

*Issue #:* n/a
- lint cleanup
- test bucket cleanup

lint and test cleanups on buckets

---

legal-api/setup.cfg
legal-api/src/legal_api/config.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

- adding proxy for receipt through the document end-point

adding proxy for receipt through the document end-point

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

- corrected receipt date format
- added documents IA tests for COOP & BEN

corrected receipt date format, added documents IA tests.

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

- lowercased the filing names
- removed primary doc

lowercased the filing names, removed primary doc

---

legal-api/report-templates/template-parts/incorporation-application/incorporator.html
legal-api/report-templates/template-parts/notice-of-articles/directors.html
legal-api/src/legal_api/services/document_meta.py
legal-api/tests/unit/services/test_document_meta.py

*Issue #:* /bcgov/entity#8927
- Added CORRECTED status to document_meta; 
- Fixed NOA output; 
- Added test.

8927 - Fixes for the outputs (Corrected status and Organization terms)

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/tests/unit/core/test_filing.py
legal-api/tests/unit/models/test_filing_lock.py

*Issue #:* /bcgov/entity#9734 - part 2
- fix manual deletion lock on filings
- change effective_date to either be in the future, or when the filing is paid for.
- is_future_effective, is set by the Filer, calling set_processed() of Filings, which will set the effective_date

9734 filing dates

---

queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#9603
* bumped entity emailer version num

9603 bump emailer version num for names 11.2 release

---

queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_nr_notification.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* /bcgov/entity#9703
* hotfix for nr notification bug for NR refund emails

9703 hotfix for nr notification bug for NR refund emails

---

legal-api/src/legal_api/core/filing.py

*Issue #:* /bcgov/entity#9638
* Added filter for filing documents when the filing storage contains the paper_only flag.

9638 paper only docs

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#9284
* bump legal api version num 

9284 bump version num for ledger refactor release

---

legal-api/.vscode/launch.json
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v1/business/business_filings.py
legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#9287
- Added fee codes; 
- Added tests

9287 - Fee codes for dissolutions

---

legal-api/requirements.txt
legal-api/src/legal_api/services/filings/validations/dissolution.py
legal-api/src/legal_api/services/filings/validations/special_resolution.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/tests/postman/legal-api.postman_collection.json
legal-api/tests/unit/services/filings/validations/__init__.py
legal-api/tests/unit/services/filings/validations/test_dissolution.py
legal-api/tests/unit/services/filings/validations/test_special_resolution.py

*Issue #:* /bcgov/entity#8914
* Update voluntary dissolution validation logic to support stacked(`dissolution` and `specialResolution` filling) filings for COOP voluntary dissolutions
* Update special resolution validation logic according to schema changes
* removal of document fields as no longer require document upload
* add validation for new special resolution fields
* Update dissolution and special resolution validation tests
* Update postman tests

8914 Update dissolution and special resolution validation logic

---

legal-api/tests/postman/legal-api.postman_collection.json

*Issue #:* /bcgov/entity#9287
- Added fee code tests to postman collection

9287 - Added fee code tests to postman collection

---

legal-api/src/legal_api/models/document.py

- Added Affidavit document type

9016 - Added Affidavit document type

---

legal-api/report-templates/certificateOfDissolution.html
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/reports/test_report.py

*Issue #:* /bcgov/entity#8289
Added the template for certificate of dissolution
Added the entry to report meta
Updated the unit test

Certificate of dissolution output

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/models/user.py
legal-api/src/legal_api/resources/v2/business/business.py

9053 get modified user for business

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#8288
Updated the meta info to include dissolution o/ps for diff entities
Updated tests

Update Document List - Dissolution

---

legal-api/report-templates/specialResolution.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/common/style.html
legal-api/report-templates/template-parts/resolution.html
legal-api/report-templates/template-parts/special-resolution/resolution.html
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/reports/test_report.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#10110
New template and framework updates for special resolution 
Modified common style as per UX feedback
Added tests

Output - Special Resolution

---

queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/requirements/bcregistry-libraries.txt
queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py
queue_services/entity-emailer/src/entity_emailer/email_processors/dissolution_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/DIS-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/DIS-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-information.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/footer.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/style.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_dissolution_notification.py

8287 dissolution emails

---

legal-api/src/legal_api/reports/report.py
queue_services/entity-emailer/src/entity_emailer/email_processors/dissolution_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/DIS-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/DIS-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-information.html

8287 ux fix

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/src/entity_filer/filing_meta.py
queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/src/entity_filer/utils.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
queue_services/entity-filer/tests/unit/test_filing_meta.py
queue_services/entity-filer/tests/utils.py

- updated dissolution filer processor;
- added tests
- added dissolution_type to FilingMeta

9016 - filer dissolution

---

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py

*Issue #:* /bcgov/entity#10161

10161 track name change in filing_meta correction

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#10161

10161 conditional outputs

---

legal-api/migrations/versions/026f42f4f654_add_custodialoffice_to_office_types.py

- Added custodialOffice to office_types table

9016 - Filer dissolution - Added custodialOffice to office_types table

---

legal-api/src/legal_api/resources/v1/business/business_filings.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

9225 delete file from minio

---

queue_services/entity-filer/src/entity_filer/filing_processors/special_resolution.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_special_resolution.py

Added processor for special resolution
Added test

Filing processor - special resolution

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/tests/postman/legal-api.postman_collection.json
legal-api/tests/unit/services/filings/validations/test_alteration.py

*Issue #:* /bcgov/entity#9000
- Waiting for schema changes to be merged

9000 - share classes become optional in alteration

---

queue_services/entity-emailer/.devcontainer/Dockerfile
queue_services/entity-emailer/.devcontainer/db/docker_postgres_init.sql
queue_services/entity-emailer/.devcontainer/devcontainer.json
queue_services/entity-emailer/.devcontainer/docker-compose.yml
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* [/bcgov/entity/9731](https://github.com/bcgov/entity/issues/9731)
1. add devcontrainer setup;
2. add email payload validation in send_email function;

9731 - Add devcontainer config and email payload validation.

---

jobs/update-colin-filings/update_colin_filings.py

*Issue #:* /bcgov/entity#10143

10143 remove is_test_coop

---

queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py

*Issue #:* /bcgov/entity#10403
Added an optional argument to update parties method to indicate whether parties should be deleted and created or just appended.
Updated test 

 Filer fix - Dissolution processor deleting existing party info

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/report.py
queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py

9331 optional shareClass in alteration report

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py

*Issue #:* /bcgov/entity#9348
Updated the incorporation and dissolution filer processors to update business object with state
Updated tests

Filer changes - business state

---

colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/models/office.py
colin-api/src/colin_api/resources/filing.py
colin-api/tests/postman/colin-api.postman_collection.json

*Issue #:* /bcgov/entity#9032
* Updates to colin api filings endpoint to support POSTing of voluntary dissolution filings for COOPs and CORPs
* Updates to colin api to support POSTing of special resolutions which are included in in COOP dissolution filings
* Added postman tests

9032 Update Colin API to support pushing of voluntary dissolution and special resolution filings

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/test_business.py
queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py

*Issue #:* /bcgov/entity#9348
Changes to populate time to dissolution date.

Dissolution date as date time

---

colin-api/src/colin_api/version.py

*Issue #:* /bcgov/entity#10434
* Update colin api version number for colin api release

10434 Update colin api version number for colin api release

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#9387
* bump version numbers for legal-api, entity-filer and entity-emailer

9387 bump version numbers for voluntary dissolution release

---

legal-api/src/legal_api/models/party.py
legal-api/src/legal_api/models/party_role.py
legal-api/src/legal_api/resources/v2/business/__init__.py
legal-api/src/legal_api/resources/v2/business/business_address.py
legal-api/src/legal_api/resources/v2/business/business_aliases.py
legal-api/src/legal_api/resources/v2/business/business_directors.py
legal-api/src/legal_api/resources/v2/business/business_parties.py
legal-api/src/legal_api/resources/v2/business/business_resolutions.py
legal-api/src/legal_api/resources/v2/business/business_share_classes.py
legal-api/tests/unit/models/test_party_role.py
legal-api/tests/unit/resources/v2/test_business_parties.py

*Issue #:* /bcgov/entity#10415
Added endpoint for parties
Added tests

Parties endpoint

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt

*Issue #:* /bcgov/entity#10491

10491 allow null deliveryInstructions

---

legal-api/tests/postman/legal-api.postman_collection.json

*Issue #:* /bcgov/entity#10415
Added parties endpoint to postman collection

Adding parties endpoint to legal api postman collection

---

legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py

Increase file upload size to 30MB

---

legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/resources/v2/test_business.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
legal-api/tests/unit/services/test_authorization.py

9329 Determine allowable filings actions

---

legal-api/src/legal_api/models/filing.py
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/conversion.py
queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py
queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/src/entity_filer/filing_processors/transition.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_parties.py
queue_services/entity-filer/tests/unit/filing_processors/test_conversion.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
queue_services/entity-filer/tests/unit/filing_processors/test_transition.py

*Issue #:* /bcgov/entity#10494, /bcgov/entity#10556
Changed the party processor
Updated tests

Filer changes - Adding party info for a filing

---

queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/tests/unit/filing_processors/test_alteration.py

*Issue #:* /bcgov/entity#10555

10555 update meta for named to numbered company alteration

---

legal-api/report-templates/certificateOfNameChange.html
legal-api/report-templates/template-parts/common/legalNameChange.html
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/reports/test_report.py
legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py

*Issue #:* /bcgov/entity#10557

10557 name change from meta_data

---

tests/data/README.md

*Issue #:* /bcgov/entity#2295
- README for the setup

simple README

---

legal-api/scripts/manual_db_scripts/2022_jan_6_business_state_update.sql

*Issue #:* /bcgov/entity#10596
* Add transaction handling to script
* Add verification sql for update scenarios
* Collapsed scenario 1 & 2 to reduce sql commands

10596 tweak manual business state update sql

---

legal-api/report-templates/businessSummary.html
legal-api/report-templates/template-parts/common/nameTranslation.html
legal-api/report-templates/template-parts/notice-of-articles/directors.html
legal-api/src/legal_api/reports/__init__.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/resources/v2/business/business_documents.py
legal-api/tests/unit/reports/test_business_document.py

Add directors, addresses and translations to business summary

---

legal-api/report-templates/businessSummary.html
legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/report-templates/template-parts/business-summary/nameChanges.html
legal-api/report-templates/template-parts/business-summary/recordKeeper.html
legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/notice-of-articles/directors.html
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/business_document.py
legal-api/tests/unit/reports/test_business_document.py

Added state changes, name changes, record keepers and more business details

Business Summary - state changes, record keepers, name changes etc

---

jobs/sftp-gazette/notebook/generate_files.ipynb

*Issue #:* /bcgov/entity#8272
Updated codes so it will generate for COOP only

Send COOP Gazette messaging #8272

---

queue_services/entity-emailer/src/entity_emailer/email_templates/NR-EXPIRED.html
queue_services/entity-emailer/tests/unit/email_processors/test_nr_notification.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* /bcgov/entity#8679
Updated Email Body of Expired Email

8679 update expired email body

---

legal-api/report-templates/businessSummary.html
legal-api/report-templates/template-parts/business-summary/alterations.html
legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/report-templates/template-parts/business-summary/nameChanges.html
legal-api/report-templates/template-parts/common/style.html
legal-api/report-templates/template-parts/notice-of-articles/directors.html
legal-api/src/legal_api/reports/business_document.py

Added alterations, epoch filing details etc

Alterations , Epoch filing and more to business summary

---

queue_services/entity-emailer/tests/unit/email_processors/test_nr_notification.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* /bcgov/entity#8679
Updated original ticket with two pytest assertions

8679 expired email added two asserts

---

legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/report-templates/template-parts/common/style.html
legal-api/src/legal_api/reports/business_document.py

summary - text changes + ux feedback

---

legal-api/report-templates/businessSummary.html
legal-api/report-templates/template-parts/business-summary/amalgamations.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/common/style.html
legal-api/src/legal_api/reports/business_document.py

Added amalgamation to business summary

---

legal-api/report-templates/businessSummary.html
legal-api/report-templates/template-parts/business-summary/amalgamations.html
legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/report-templates/template-parts/business-summary/liquidation.html
legal-api/report-templates/template-parts/business-summary/recordKeeper.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/notice-of-articles/directors.html
legal-api/src/legal_api/reports/business_document.py

Business Summary - Voluntary Liquidation

---

legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#10834

Business summary - Bug fixes

---

legal-api/src/legal_api/reports/business_document.py

Additional legacy filing types in prod

---

legal-api/report-templates/businessSummary.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#10876
Removed CP Liquidation template reference
Updated the display state to Active

Remove CP Liquidation

---

tests/data/Alterations_update_metadata/fix_alteration_filing_metadata.ipynb

*Issue #:* /bcgov/entity#10907

Notebook for fixing alteration metadata

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v1/business/business.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/services/bootstrap.py
legal-api/src/legal_api/services/document_meta.py
legal-api/tests/unit/resources/v1/test_business.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#10703

10703 minimal Registration filing

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/models/party_role.py
legal-api/src/legal_api/services/filings/validations/registration.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/tests/unit/services/filings/validations/test_registration.py

9250 registration validation

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#10835
* bump version numbers to `2.36.0` for legal api, filer and emailer 

10835 bump version numbers for release 2.36.0

---

legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#10876
Changes to display the entity as historical if there is a voluntary liquidation filing
Changes to display the liquidation filing under dissolution/restoration
Added error logging

Modified Liquidation section as per the new requirement

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/src/legal_api/services/filings/validations/registration.py
legal-api/tests/postman/legal-api.postman_collection.json
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#11134

11134 moving business object into registration schema

---

legal-api/report-templates/alterationNotice.html
legal-api/report-templates/template-parts/alteration-notice/businessTypeChange.html
legal-api/report-templates/template-parts/alteration-notice/legalNameChange.html
legal-api/report-templates/template-parts/alteration-notice/statement.html
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#11096

Fixes - Alteration Report

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#11108
* increment legal api version number

11108 bump version number for release

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#10758
Updated document list for change of registration  filing
Updated unit tests

Change of registration - Document list update

---

legal-api/report-templates/registration.html
legal-api/report-templates/template-parts/registration/addresses.html
legal-api/report-templates/template-parts/registration/nameRequest.html
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/resources/v1/business/business_filings.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

- registration payment creation 
- report fix

registration payment creation and report fix

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#11238
* bump legal api version to 2.38.0

11238 bump version number for release

---

legal-api/src/legal_api/models/address.py
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/__init__.py
queue_services/entity-filer/tests/unit/test_worker/test_change_of_registration.py

*Issue #:* /bcgov/entity#10777
Added new processor for change of registration
Added upsert functionality for parties
Added tests

Filer - SP/GP Change Filing

---

queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py

Change filer fix

---

queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/requirements/bcregistry-libraries.txt
queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py
queue_services/entity-emailer/src/entity_emailer/email_processors/bn_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/registration_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/BC-BN.html
queue_services/entity-emailer/src/entity_emailer/email_templates/REG-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/REG-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/reg-business-info.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_registration_notification.py
queue_services/entity-emailer/tests/unit/test_tracker.py
queue_services/entity-filer/src/entity_filer/filing_processors/registration.py

9254 SP/GP email template

---

legal-api/report-templates/amendedRegistrationStatement.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/registration-statement/business-info.html
legal-api/report-templates/template-parts/registration-statement/party.html
legal-api/report-templates/template-parts/registration/party.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#10612
There may be a follow up PR for this based on whether the business decides to include the completing party information for the amended registration statement

Amended Registration Statement Output

---

legal-api/devops/vaults.json
legal-api/src/legal_api/config.py
legal-api/src/legal_api/services/__init__.py
legal-api/src/legal_api/services/filings/validations/change_of_registration.py
legal-api/src/legal_api/services/filings/validations/registration.py
legal-api/src/legal_api/services/naics.py
legal-api/tests/unit/services/filings/validations/test_change_of_registration.py
legal-api/tests/unit/services/filings/validations/test_registration.py

*Issue #:* /bcgov/entity#11385

11385 naics service (api call) + validation

---

legal-api/report-templates/amendedRegistrationStatement.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/registration-statement/business-info.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#10612

Amended Registration - UX feedback + completing party info

---

legal-api/report-templates/template-parts/registration-statement/completingParty.html

*Issue #:* /bcgov/entity#10612

Completing Party Template

---

legal-api/src/legal_api/services/naics.py
queue_services/entity-filer/devops/vaults.json
queue_services/entity-filer/src/entity_filer/config.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py
queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
queue_services/entity-filer/tests/unit/filing_processors/test_registration.py
queue_services/entity-filer/tests/unit/test_worker/test_change_of_registration.py

*Issue #:* /bcgov/entity#11385

11385 naics api call - filer

---

legal-api/migrations/versions/f4f654026f42_businessoffice_office_types.py
legal-api/report-templates/template-parts/registration-statement/business-info.html
legal-api/src/legal_api/models/office.py
legal-api/src/legal_api/services/filings/validations/change_of_registration.py
legal-api/src/legal_api/services/filings/validations/registration.py
legal-api/src/legal_api/services/naics.py

9843 businessOffice type

---

queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
queue_services/entity-filer/tests/unit/filing_processors/test_registration.py
queue_services/entity-filer/tests/unit/test_worker/test_worker.py

9843 filer change

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#11477
* bump version to 2.39.0 for legal api, filer and emailer

11477 bump version nums for release

---

legal-api/src/legal_api/models/business.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py

- fallback to middleName if middleInitial not present
- businessOffice as mailing_address and delivery_address if registeredOffice is not available

fallback to middleName if middleInitial not present

---

legal-api/report-templates/amendedRegistrationStatement.html
legal-api/report-templates/changeOfRegistration.html
legal-api/report-templates/template-parts/change-of-registration/addresses.html
legal-api/report-templates/template-parts/change-of-registration/completingParty.html
legal-api/report-templates/template-parts/change-of-registration/legal-name.html
legal-api/report-templates/template-parts/change-of-registration/nature-of-business.html
legal-api/report-templates/template-parts/change-of-registration/partner.html
legal-api/report-templates/template-parts/change-of-registration/proprietor.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/common/style.html
legal-api/report-templates/template-parts/macros.html
legal-api/report-templates/template-parts/registration-statement/business-info.html
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/business_details_version.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py

*Issue #:* /bcgov/entity#11225
Added Change of registration template files
Added the logic to identify the differences in the change filing
Removed the completing party info from amended registration statement
Fixed the party middle name issue in the change filer

Change of Registration Output

---

.github/workflows/entity-filer-ci.yml
.github/workflows/entity-pay-ci.yml
queue_services/common/src/entity_queue_common/messages.py
queue_services/entity-filer/tests/docker-compose.yml
queue_services/entity-filer/tests/unit/test_worker/test_incorporation.py
queue_services/entity-pay/Makefile
queue_services/entity-pay/requirements/dev.txt
queue_services/entity-pay/setup.cfg
queue_services/entity-pay/src/entity_pay/config.py
queue_services/entity-pay/src/entity_pay/worker.py
queue_services/entity-pay/tests/conftest.py
queue_services/entity-pay/tests/integration/test_worker_queue.py

*Issue #:* /bcgov/entity#5239
Make entity-filler and entity-pay CI work

Unit test on queue jobs of CI flow. #5293

---

legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#11624

Name change reporting for special resolution

---

legal-api/src/legal_api/reports/business_document.py

Changes to report name changes for a compound filing where the name change metadata will be under the change of name legal filing (eg: CP special resolution)

CP Special Resolution Business Summary updates

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_name.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_change_of_name.py
queue_services/entity-filer/tests/unit/test_worker/test_special_resolution.py

*Issue #:* /bcgov/entity#11628

11628 coop special resolution with change of name - filer

---

legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#11567

Effective date in Business Summary header

---

legal-api/src/legal_api/core/filing.py

*Issue #:* /bcgov/entity#11626

11626 suppress change of name output for MVP since the design is outdated

---

legal-api/report-templates/template-parts/change-of-registration/partner.html
legal-api/report-templates/template-parts/registration-statement/party.html

*Issue #:* /bcgov/entity#11708

Changes in Registration output

---

queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_name.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py
queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#11713

11713 remove check before consume NR

---

legal-api/report-templates/certificateOfNameChange.html
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#11719,  /bcgov/entity#11720
Added certificate of name change to the special resolution documents list based on condition
Made the change of name certificate template generic for any future filings that may need this certificate
Modified the report framework to pass the data correctly for the certificate

Co-op Special Resolution Certificate of Name Change

---

data-tool/Makefile
data-tool/README.md
data-tool/docker-compose.yaml
data-tool/flows/__init__.py
data-tool/flows/common/__init__.py
data-tool/flows/common/custom_exceptions.py
data-tool/flows/common/transform_utils.py
data-tool/flows/common/validation_utils.py
data-tool/flows/config.py
data-tool/flows/tasks/__init__.py
data-tool/flows/tasks/task_utils.py
data-tool/flows/test_flow.py
data-tool/requirements.txt

*Issue #:* /bcgov/entity#11475
* Added POC ETL pipeline(`/data-tool/flows/test_flow.py`).  Refer to readme in `data-tool` folder for more details.
Screenshots of UI for visualization, monitoring, debugging and executing flows.

11475 Create POC ETL pipeline

---

legal-api/src/legal_api/models/party.py
legal-api/tests/unit/models/test_party.py
legal-api/tests/unit/models/test_party_role.py

Adding id to the officer object to support edit functionality

Adding id to the party json

---

legal-api/report-templates/changeOfRegistration.html
legal-api/report-templates/template-parts/change-of-registration/completingParty.html
legal-api/report-templates/template-parts/change-of-registration/partner.html
legal-api/report-templates/template-parts/change-of-registration/proprietor.html
legal-api/report-templates/template-parts/registration-statement/business-info.html
legal-api/src/legal_api/services/business_details_version.py
queue_services/entity-emailer/src/entity_emailer/email_templates/CHGREG-COMPLETED.html

*Issue #:* /bcgov/entity#10759

UX feedback Change of Registration Outputs + Email template

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity
* bump version numbers for legal api, filer and emailer

bump version nums

---

legal-api/src/legal_api/models/party.py
legal-api/src/legal_api/resources/v2/business/business_parties.py
legal-api/tests/unit/models/test_party.py
legal-api/tests/unit/models/test_party_role.py

*Issue #:* /bcgov/entity#11799
- Changed the role structure in parties endpoint response to match the schema
- Added email to the party json
- Updated tests

Changes in parties endpoint response

---

legal-api/src/legal_api/resources/v1/business/business_filings.py

*Issue #:* /bcgov/entity#11850
Fixed issue where any staff filed filing using v1 PUT filings endpoint would result in ledger filed by display name revealing staff idir even if user requesting ledger items was a regular user.
* Update v1 PUT filings endpoint to populate `filings.submitter_roles` field for special roles. 

11850 Update v1 PUT filings endpoint to populate submitter_roles field in filings model

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#11820

bump version num

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#11951

bump version num 2.43.0

---

legal-api/src/legal_api/core/filing.py

*Issue #:* /bcgov/entity#11405

NOA missing after alteration

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#12036
* bump legal api version num to 2.44.0

12036 bump version num

---

legal-api/src/legal_api/services/filings/validations/dissolution.py
legal-api/tests/unit/services/filings/validations/test_dissolution.py

https://github.com/bcgov/entity/issues/11410
Add support for SP and GP

11410 Add support for SP GP

---

colin-api/src/colin_api/config.py
colin-api/src/colin_api/models/__init__.py
colin-api/src/colin_api/models/program_account.py
colin-api/src/colin_api/resources/__init__.py
colin-api/src/colin_api/resources/program_account.py
colin-api/tests/unit/api/test_program_account.py

*Issue #:* /bcgov/entity#12232

12232 new endpoint Program account

---

colin-api/src/colin_api/models/program_account.py

*Issue #:* /bcgov/entity#12232

12232 query fix

---

colin-api/src/colin_api/version.py

*Issue #:* /bcgov/entity#12036

12036 bump version num 2.44.0

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/conversion.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py
queue_services/entity-filer/tests/unit/test_worker/test_conversion.py

*Issue #:* /bcgov/entity#11890

Conversion Filer

---

queue_services/entity-bn/src/entity_bn/bn_processors/__init__.py
queue_services/entity-bn/src/entity_bn/bn_processors/change_of_registration.py
queue_services/entity-bn/src/entity_bn/bn_templates/change_address.xml
queue_services/entity-bn/src/entity_bn/bn_templates/change_name.xml
queue_services/entity-bn/src/entity_bn/worker.py
queue_services/entity-bn/tests/unit/__init__.py
queue_services/entity-bn/tests/unit/bn_processors/test_change_of_registration.py

*Issue #:* /bcgov/entity#12084

12084 Change of Name and Address

---

legal-api/src/legal_api/resources/v1/business/business_filings.py

https://github.com/bcgov/entity/issues/12308
Added priority flag in payload header

Bug 12308 added priority fee to be included in invoice

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/services/filings/validations/conversion.py
legal-api/tests/unit/services/filings/validations/test_conversion.py

*Issue #:* /bcgov/entity#11889
Added validator for firms conversion
Added the fee code
Added tests

Record Conversion Validator

---

legal-api/src/legal_api/models/filing.py

*Issue #:* /bcgov/entity#12332

Fee code - Conversion

---

legal-api/src/legal_api/core/filing.py

*Issue #:* /bcgov/entity#12332

Change to hide view documents button in UI

---

queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:*[/bcgov/entity/10296](https://github.com/bcgov/entity/issues/10296)
Add in AccountService calls to dissolution and correction.

10296 - Part 2/2 - Modify entity_filter to update AUTH-API entities.state 

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

Updating version

---

queue_services/entity-bn/src/entity_bn/bn_processors/__init__.py
queue_services/entity-bn/src/entity_bn/bn_processors/change_of_registration.py
queue_services/entity-bn/src/entity_bn/bn_processors/dissolution.py
queue_services/entity-bn/src/entity_bn/bn_processors/registration.py
queue_services/entity-bn/src/entity_bn/bn_templates/change_address.xml
queue_services/entity-bn/src/entity_bn/bn_templates/change_name.xml
queue_services/entity-bn/src/entity_bn/bn_templates/change_status.xml
queue_services/entity-bn/src/entity_bn/bn_templates/create_program_account_request.xml
queue_services/entity-bn/src/entity_bn/worker.py
queue_services/entity-bn/tests/unit/bn_processors/test_change_of_registration.py
queue_services/entity-bn/tests/unit/bn_processors/test_dissolution.py

*Issue #:* /bcgov/entity#12277

12277 change of status and party

---

legal-api/report-templates/template-parts/common/style.html

*Issue #:* /bcgov/entity#12213

Certificate layout fix

---

queue_services/entity-filer/src/entity_filer/worker.py

10296 - entity_filer - Forgot .name in enum

---

queue_services/entity-bn/src/entity_bn/version.py

*Issue #:* /bcgov/entity#12166

bump version num 2.45.0

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#10955

Dissolution documents list for firms

---

legal-api/report-templates/dissolution.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/common/completingParty.html
legal-api/report-templates/template-parts/dissolution/firmsDissolutionDate.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#10954

Firms dissolution output

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#12167
* bump version numbers for legal api and entity filer for upcoming release

12167 bump version nums for release

---

queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-information.html

*Issue #:* /bcgov/entity#10953

Emailer template fixes

---

data-tool/flows/common/event_filing_service.py
data-tool/flows/common/firm_filing_base_json.py
data-tool/flows/common/firm_filing_data_utils.py
data-tool/flows/common/firm_filing_json_factory_service.py
data-tool/flows/common/firm_queries.py
data-tool/flows/common/processing_status_service.py
data-tool/flows/custom_filer/filer.py
data-tool/flows/custom_filer/filing_processors/dissolution.py
data-tool/flows/migrate_sp_gp_flow.py

*Issue #:* /bcgov/entity#12271
* Updated pipeline to support dissolution filings
* Added custom filer for dissolution filings
* Refactored some filing json transformation code to be more generic and reusable across filing types

12271 Add dissolution filings support to SP/GP pipeline

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#12168
* bump version numbers for legal api and emailer

12168 bump version numbers

---

legal-api/report-templates/businessSummary.html
legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/report-templates/template-parts/business-summary/parties.html
legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/report-templates/template-parts/common/addresses.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/business_document.py

Firms Business Summary

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/setup.cfg
queue_services/entity-filer/src/entity_filer/filing_processors/put_back_on.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_put_back_on.py

https://github.com/bcgov/entity/issues/12094
entity-filer changes to process putBackOn filing

Feature 12092 - Support for putback on filer changes

---

legal-api/src/legal_api/core/meta/filing.py

Title for put back on filing

---

legal-api/src/legal_api/services/filings/validations/dissolution.py

https://github.com/bcgov/entity/issues/12614
Add support for admin dissolution

Feature 12614 Add support for admin dissolution

---

legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/business_document.py

Firms Business Summary - UX fixes

---

legal-api/src/legal_api/core/meta/filing.py
queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/filings.py

https://github.com/bcgov/entity/issues/12614
Support for admin dissolution

Feature 12614 Support for admin dissolution

---

queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
queue_services/entity-filer/tests/unit/filing_processors/test_registration.py

Business Start Date fix

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

https://github.com/bcgov/entity/issues/12614
Support for No Fee code for admin dissolution

Feature 12614 - Support for NOFEE code for admin dissolution

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#12037

12037 bump version

---

data-tool/flows/common/custom_exceptions.py
data-tool/flows/common/event_filing_service.py
data-tool/flows/common/firm_filing_data_utils.py
data-tool/flows/common/firm_queries.py
data-tool/flows/common/lear_data_utils.py
data-tool/flows/common/processing_status_service.py
data-tool/flows/config.py
data-tool/flows/custom_filer/filer.py
data-tool/flows/custom_filer/filing_processors/change_of_registration.py
data-tool/flows/custom_filer/filing_processors/registration.py
data-tool/flows/migrate_sp_gp_flow.py

*Issue #:* /bcgov/entity#12446
* Add support to be able to resume data loading for firms where a filing is not supported yet and also when a new event/filing 
* Add support to be able to load/apply new filings for a SP/GP where all filings were already loaded at a point in time
* Add tracking and environment related to make loading to different environments easier
* Improved corp processing tracking code to make it easier to surface partial and failed loads.

12446 Add incremental event/filing processing support to SP/GP pipeline

---

legal-api/report-templates/certificateOfGoodStanding.html
legal-api/report-templates/template-parts/common/certificateStyle.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#12389
Added a new template for certificate of good standing
Updated the business document framework

Certificate of good standing report template

---

legal-api/report-templates/certificateOfGoodStanding.html

Fix - Certificate of Good Standing

---

legal-api/src/legal_api/resources/v2/business/business_tasks.py
legal-api/tests/unit/resources/v2/test_business_tasks.py

*Issue #:* /bcgov/entity#12298

Tasks endpoint update for SP/GP

---

data-tool/flows/common/event_filing_service.py
data-tool/flows/common/firm_filing_base_json.py
data-tool/flows/common/firm_filing_json_factory_service.py
data-tool/flows/common/firm_queries.py
data-tool/flows/common/lear_data_utils.py
data-tool/flows/custom_filer/filer.py
data-tool/flows/custom_filer/filing_processors/conversion.py
data-tool/flows/custom_filer/filing_processors/filing_components/filings.py
data-tool/flows/migrate_sp_gp_flow.py

*Issue #:* /bcgov/entity#12618
* Updated pipeline to support conversion filings
* Added custom filer for conversion filings

12618 Add support for conversion filings to SP/GP pipeline

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#12825
* bump version numbers for legal api and entity filer

12825 bump version nums

---

queue_services/entity-bn/src/entity_bn/bn_processors/admin.py
queue_services/entity-bn/src/entity_bn/bn_processors/registration.py
queue_services/entity-bn/src/entity_bn/bn_templates/change_name.xml
queue_services/entity-bn/src/entity_bn/bn_templates/create_program_account_request.xml
queue_services/entity-bn/src/entity_bn/worker.py
queue_services/entity-bn/tests/unit/bn_processors/test_admin.py

*Issue #:* /bcgov/entity#12786

12786 entity bn support admin

---

legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/services/test_authorization.py

Added SP and GP to the staff correction allowable entities

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

*Issue #:* /bcgov/entity#12749

Support filtering filing history by date and time

---

legal-api/src/legal_api/services/bootstrap.py

*Issue #:* /bcgov/entity#12845
_Note: the change in this PR is required to make changes in a subsequent filer PR_
* Add passcode param to `create_affiliation` function in `AccountService` class

12845 Add passcode param to create_affiliation function (part 1)

---

legal-api/src/legal_api/services/bootstrap.py
queue_services/entity-filer/setup.cfg
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py
queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
queue_services/entity-filer/tests/unit/filing_processors/test_registration.py

*Issue #:* /bcgov/entity#12845
Note: this is a PR that contains fixes for the firm affiliation bug that have already made it into `main`.  These updates have been cherry picked into the release branch so only these additional changes will make it into test.

12845 firm affiliation bug

---

queue_services/entity-bn/src/entity_bn/bn_processors/dissolution.py
queue_services/entity-bn/src/entity_bn/bn_templates/change_address.xml
queue_services/entity-bn/src/entity_bn/bn_templates/create_program_account_request.xml

*Issue #:* /bcgov/entity#12786

12786 entity bn fix xml

---

queue_services/common/src/entity_queue_common/service_utils/service_logger.py

*Issue #:* https://www.github.com/bcgov/entity/issues/12261
Add in environment variable to disable HTTP access logging.

12261 - Add in environment variable to disable HTTP access logging.

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt

Updating schema version in legal api

---

legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#12794

Added retrieved date and time to the generated reports

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#12996

12996 bump version

---

legal-api/src/legal_api/core/meta/filing.py

*Issue #:* [/bcgov/entity#12136](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12136)
- Changed `displayName` to "Change of Registration Application" for `changeOfRegistration`

Lear API: Change of Registration bugs

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/services/filings/validations/correction.py
legal-api/tests/unit/__init__.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/resources/v2/test_business.py
legal-api/tests/unit/services/filings/validations/test_correction_firms.py

*Issue #:* /bcgov/entity#12803

Legal API changes for firms corrections

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#13062
* bump version nums for legal api and filer

13062 bump version numbers

---

queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py

*Issue #:*/entity/issues/12957
Add check in entity filer for COOP AD.

12957 - Admin dissolution for COOP

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/services/filings/validations/correction.py

Firms Validator fix

---

legal-api/report-templates/certificateOfStatus.html
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/resources/v2/business/business_documents.py
legal-api/src/legal_api/services/business/__init__.py
legal-api/src/legal_api/services/business/validations/__init__.py
legal-api/src/legal_api/services/business/validations/validator.py
legal-api/tests/unit/services/business/__init__.py
legal-api/tests/unit/services/business/validations/__init__.py
legal-api/tests/unit/services/business/validations/test_validator.py

*Issue #:* /bcgov/entity#12680

Certificate of status

---

legal-api/report-templates/amendedRegistrationStatement.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#13160

Corrected Registration Statement

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#13050

13050 Fix change of registration application output issues related to SP/GPs loaded from COLIN

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#13115

13115 bump version

---

legal-api/report-templates/firmCorrection.html
legal-api/report-templates/template-parts/change-of-registration/addresses.html
legal-api/report-templates/template-parts/change-of-registration/completingParty.html
legal-api/report-templates/template-parts/change-of-registration/legal-name.html
legal-api/report-templates/template-parts/change-of-registration/partner.html
legal-api/report-templates/template-parts/change-of-registration/proprietor.html
legal-api/report-templates/template-parts/correction/businessDetails.html
legal-api/report-templates/template-parts/macros.html
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/business/validations/validator.py
legal-api/tests/unit/services/business/validations/test_validator.py

*Issue #:* /bcgov/entity#13159

Register Correction Application Output

---

legal-api/src/legal_api/reports/report.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py

Filer changes to process naics without naics code

---

legal-api/report-templates/letterUnderSeal.html
legal-api/report-templates/template-parts/common/style.html
legal-api/src/legal_api/__init__.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#12663

12663 lus ux 1

---

queue_services/entity-bn/src/entity_bn/bn_processors/dissolution_or_put_back_on.py
queue_services/entity-bn/src/entity_bn/worker.py
queue_services/entity-bn/tests/unit/bn_processors/test_dissolution_or_put_back_on.py

*Issue #:* /bcgov/entity#12964

12964 put back on

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v1/business/business_filings.py

*Issue #:* /bcgov/entity#13227
- specialResolution (with changeOfName) filing_json doesn't contain business object
- additional condition to not fetch SP and GP

13227 colin api error fix

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v1/business/business_filings.py

Reverts bcgov/lear#1618
Moving to release branch 2.53.0

Revert "13227 colin api error fix"

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v1/business/business_filings.py

This reverts commit ec6199031d64e452ec1a3e57dceb49382ada503e.

Revert "Revert "13227 colin api error fix (#1618)" (#1620)"

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/tests/unit/services/filings/test_schemas.py

*Issue #:* [/bcgov/entity#13058](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/13058)
- added unit test for schema change: [first_name and middle_name](https://github.com/bcgov/business-schemas/pull/101/files)

13058 COLIN API failure - Front and Backend Change validation of the first name field in Coop IA UI and/or Corp Party table

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#13116
- update BN version to 2.51.1

13116 Update BN Version

---

legal-api/report-templates/template-parts/common/footerMOCS.html
legal-api/report-templates/template-parts/common/style.html
legal-api/report-templates/template-parts/common/styleLetterOverride.html

*Issue #:* /bcgov/entity#12663

12663 lus template ux 1

---

queue_services/entity-bn/src/entity_bn/bn_processors/change_of_registration.py
queue_services/entity-bn/src/entity_bn/bn_processors/correction.py
queue_services/entity-bn/src/entity_bn/worker.py
queue_services/entity-bn/tests/unit/bn_processors/test_correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/special_resolution.py

*Issue #:* /bcgov/entity#13216

13216 BN messaging for SP/GP Correction

---

legal-api/report-templates/letterUnderSeal.html
legal-api/report-templates/template-parts/business-summary/parties.html
legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/__init__.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/resources/v2/business/business_documents.py
legal-api/src/legal_api/services/business/validations/validator.py
legal-api/src/legal_api/utils/legislation_datetime.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/reports/test_business_document.py

*Issue #:* /bcgov/entity#12871
- json option for business docs

12871 business docs json

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/tests/unit/services/filings/validations/test_alteration.py

*Issue #:* bcgov/entity/issues/12898
Support SR for COOP

Feature 12898 Support SR for COOP

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/tests/unit/services/filings/validations/test_alteration.py

*Issue #:* /bcgov/entity/issues/12898
Added support for alteration which is a subpart in SR for COOP

Feature  12898 Support for SR for COOP

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#12995
* bump version nums for legal api and filer

12995 bump version nums

---

queue_services/entity-bn/src/entity_bn/bn_processors/__init__.py
queue_services/entity-bn/src/entity_bn/bn_processors/admin.py
queue_services/entity-bn/src/entity_bn/bn_processors/registration.py
queue_services/entity-bn/src/entity_bn/config.py
queue_services/entity-bn/src/entity_bn/worker.py
queue_services/entity-bn/tests/unit/bn_processors/test_admin.py
queue_services/entity-bn/tests/unit/bn_processors/test_registration.py

*Issue #:* /bcgov/entity#13173

13173 publish a bn email message to nats

---

queue_services/entity-bn/bn_service.py

*Issue #:* /bcgov/entity#13173

13173 fix import

---

legal-api/src/legal_api/resources/v1/business/business_filings.py
legal-api/src/legal_api/resources/v1/business/internal_services.py

*Issue #:* /bcgov/entity#13227

13227 skip missing business from colin tax_id update

---

data-tool/flows/common/event_filing_service.py
data-tool/flows/common/firm_filing_base_json.py
data-tool/flows/common/firm_filing_json_factory_service.py
data-tool/flows/common/firm_queries.py
data-tool/flows/common/lear_data_utils.py
data-tool/flows/custom_filer/filer.py
data-tool/flows/custom_filer/filing_processors/correction.py
data-tool/flows/custom_filer/filing_processors/filing_components/correction.py
data-tool/flows/custom_filer/filing_processors/registration.py
data-tool/flows/migrate_sp_gp_flow.py

*Issue #:* /bcgov/entity#12274
* Updated pipeline to correction filings
* Added custom filer for correction filings
* Fixed bug where naics description wasn't updated when naics code was not available

12274 Add correction filing support to SP/GP pipeline

---

legal-api/src/legal_api/models/business.py

Added start date to the mapper 

---

data-tool/flows/common/firm_queries.py
data-tool/flows/common/lear_data_utils.py
data-tool/flows/migrate_sp_gp_flow.py
legal-api/src/legal_api/models/user.py
legal-api/tests/unit/models/test_user.py

*Issue #:* /bcgov/entity#13046

13046 Update SP/GP pipeline to support filing user data

---

legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/report-templates/template-parts/change-of-registration/nature-of-business.html
legal-api/report-templates/template-parts/registration-statement/business-info.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#13346

Report fixes

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v1/business/internal_services.py

*Issue #:* /bcgov/entity#13341

13341 Excludes SP/GP from colin sync

---

legal-api/src/legal_api/config.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/services/__init__.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/bootstrap.py
legal-api/tests/unit/services/test_registraion_bootstrap_service.py

*Issue #:* /bcgov/entity#13262

Return account info in business response

---

data-tool/flows/common/firm_filing_base_json.py
data-tool/flows/common/firm_filing_data_cleaning_utils.py
data-tool/flows/common/firm_filing_json_factory_service.py
data-tool/flows/common/lear_data_utils.py
data-tool/flows/custom_filer/filer.py
data-tool/flows/custom_filer/filing_processors/change_of_registration.py
data-tool/flows/custom_filer/filing_processors/conversion.py
data-tool/flows/custom_filer/filing_processors/filing_components/__init__.py
data-tool/flows/custom_filer/filing_processors/filing_components/correction.py
data-tool/flows/custom_filer/filing_processors/registration.py
data-tool/flows/migrate_sp_gp_flow.py

*Issue #:* /bcgov/entity#13432
* Auto populate COLIN event and filing effective timestamps where this info isn't available.  The previous filings effective timestamp plus 1 second is used.  Without this, outputs are unable to be generated accurately.
* Fixed multiple rows were found loading issue 
* Fixed "Attempt to change/add person had invalid data" loading error
* Fixed issue where an orphaned transaction id was created for filings
* Update custom filers to use newly added `businesses.start_date` field in LEAR
* Add/update logic for mapping COLIN `ledger_text` table to LEAR

13432 misc SP/GP pipeline bug fixes and updates

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/setup.cfg
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/setup.cfg
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#13061

13061 bump version

---

legal-api/report-templates/template-parts/notice-of-articles/directors.html
legal-api/src/legal_api/__init__.py

Bsummary hotfix

---

data-tool/flows/common/firm_filing_json_factory_service.py
data-tool/flows/common/lear_data_utils.py
data-tool/flows/config.py

Fix sp/gp pipeline loading issue - multiple rows were found for one_or_none

---

legal-api/src/legal_api/core/meta/filing.py

*Issue #:* /bcgov/entity#13310

Removed corrected label from the original filing

---

legal-api/devops/vaults.json
legal-api/src/legal_api/__init__.py
legal-api/src/legal_api/config.py
legal-api/src/legal_api/services/__init__.py
legal-api/src/legal_api/services/digital_credentials.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py
legal-api/tests/unit/services/test_digital_credentials.py

*Issue #:* /bcgov/entity#13533

13533 digital credentials - Registration Business Schema

---

legal-api/src/legal_api/services/filings/validations/conversion.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/src/legal_api/services/warnings/business/business_checks/__init__.py
legal-api/src/legal_api/services/warnings/business/business_checks/firms.py
legal-api/tests/unit/resources/v2/test_business.py
legal-api/tests/unit/resources/v2/test_business_tasks.py
legal-api/tests/unit/services/filings/validations/test_conversion.py
legal-api/tests/unit/services/warnings/__init__.py
legal-api/tests/unit/services/warnings/business/business_checks/test_firms.py
legal-api/tests/unit/services/warnings/test_warnings.py
queue_services/entity-filer/src/entity_filer/filing_processors/conversion.py

*Issue #:* /bcgov/entity#13509

Add start date support for conversion filing and warnings check

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

- change lear version from 2.57.0 -> 2.58.0

Version update 2.57.0 -> 2.58.0

---

data-tool/flows/common/event_filing_service.py
data-tool/flows/common/firm_filing_base_json.py
data-tool/flows/common/firm_filing_json_factory_service.py

*Issue #:* /bcgov/entity#13530
* Update various filings to populate contact info in filings json.  Note that this is not used by the custom filers as we do not yet have an account to work with when data loading occurs but it may be used for affiliation script.
* Update pipeline to support scenario where business office does not have a mailing address
* Update pipeline to support scenario where party identifier has no value
* Fix issue where unsupported COLIN event/filing type was not being handled correctly by pipeline
* Update to always populate partners/proprietors with appointment date by using previous party data in order to be able to find corresponding LEAR partner/proprietor entry
By submitting this pull request, I confirm that you can use, modify, copy, …

13530 SP/GP pipeline misc bug fixes and updates

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#12669

Court Order Indicator in Business Response

---

legal-api/src/legal_api/resources/v2/__init__.py
legal-api/src/legal_api/resources/v2/business/business_digital_credentials.py
legal-api/src/legal_api/services/digital_credentials.py
legal-api/tests/unit/resources/v2/test_business_digital_credentials.py

*Issue #:* /bcgov/entity#13392

13392 digital credentials invitation and connection

---

legal-api/requirements.txt
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#13330
- updated schemas version in requirements.txt
- updated lega-api version

13330 Update the Legal API to apply BEN IA correction changes 

---

data-tool/flows/common/affiliation_processing_status_service.py
data-tool/flows/common/affiliation_queries.py
data-tool/flows/common/lear_data_utils.py
data-tool/flows/sp_gp_affiliation_flow.py
data-tool/scripts/affiliation_processing_table.sql
data-tool/scripts/corp_processing_table.sql

*Issue #:* /bcgov/entity#12887
* Created a prefect flow to affiliate SP/GP entities to an account as well as push contact email.  The intended use of this flow is a csv file is imported into the `affiliation_processing` table which has constraints filter out duplicates or invalid entries.  The affiliation flow will then use this table to determine which firms needed to be affiliated as well as track the processing statuses.
* Added create sql for `affilation_processing` table.
* Added create sql for `corp_processing` table.  note: this is misc work that isn't really associated with this ticket.

12887 Create SP/GP affiliation script

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

Version increment for 14,5 release

2.58.0 -> 2.59.0 legal-api & queue_services 14.5b

---

queue_services/entity-filer/requirements/dev.txt
queue_services/entity-filer/src/entity_filer/version.py
queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#10911
- Add legal type to set processed.
- Version number to 2.58.0 -> 2.59.0 for commit to test

10911 add business type to set processed

---

.github/workflows/filings-notebook-report-ci.yml
jobs/filings-notebook-report/daily/incorpfilings.ipynb
jobs/filings-notebook-report/monthly/cooperative.ipynb
jobs/filings-notebook-report/monthly/coopfilings.ipynb
jobs/filings-notebook-report/monthly/firm-registration-filings.ipynb
jobs/filings-notebook-report/notebookreport.py
jobs/filings-notebook-report/openshift/templates/cronjob.yaml
jobs/filings-notebook-report/requirements.txt
jobs/filings-notebook-report/requirements/prod.txt
jobs/filings-notebook-report/tests/unit/test_job.py

*Issue #:* /bcgov/entity12806
REPORTS - create a firms by city/postcode report

REPORTS - create a firms by city/postcode report#12806

---

legal-api/src/legal_api/models/dc_issued_credential.py
legal-api/src/legal_api/resources/v2/business/business_digital_credentials.py
legal-api/src/legal_api/services/digital_credentials.py
legal-api/tests/conftest.py
legal-api/tests/unit/models/test_dc_connection.py
legal-api/tests/unit/models/test_dc_issued_credential.py
legal-api/tests/unit/resources/v2/test_business_digital_credentials.py

*Issue #:* /bcgov/entity#13393

13393 digital credentials - issue business credentials

---

legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#13568

Business Summary - Firms Start Date fix

---

legal-api/src/legal_api/models/dc_connection.py
legal-api/src/legal_api/models/dc_issued_credential.py

*Issue #:* /bcgov/entity#13393

13393 bug fix

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/src/entity_filer/filing_processors/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/shares.py
queue_services/entity-filer/tests/unit/test_worker/test_correction_firms.py

*Issue #:* /bcgov/entity#13330
- allowed `correct_business_data` to process 'BEN' legal type
- update `business.share_classes` and `business.resolutions` if "shareStructure" is found in "correction"
- update `business.restriction_ind` if "provisionsRemoved" is found in "correction"

13330 Update the Entity Filer to apply BEN IA correction changes

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#13666
* bump legal api version number

13666 bump version nums

---

data-tool/flows/common/firm_filing_json_factory_service.py
data-tool/flows/common/firm_queries.py
data-tool/flows/custom_filer/filer.py
data-tool/flows/migrate_sp_gp_flow.py
data-tool/requirements.txt

*Issue #:* /bcgov/entity#13660
*  update custom filer to pass in legal type to `filing.set_processed update` function
*  update  `corp_party.bus_company_num` logic to only pre-pend `BC` only when existing value is number of length less than 7 
*  mark CONVFMRCP events with null filing as paper only
*  removal of unused payment info
*  update use latest schema version

13660 misc updates and bug fixes to SP/GP pipeline

---

legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/services/warnings/business/business_checks/firms.py
legal-api/tests/unit/services/warnings/__init__.py
legal-api/tests/unit/services/warnings/business/business_checks/test_firms.py
legal-api/tests/unit/services/warnings/test_warnings.py

*Issue #:* /bcgov/entity#12421
- added filter for cessation is None

12421 legal-api - missing business info warning check returning warnings for deleted/ceased partners

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#13758
* update legal api version num

13758 bump version nums

---

data-tool/flows/custom_filer/filing_processors/dissolution.py

*Issue #:* /bcgov/entity#13754
* update custom dissolution filer processor to map ledger text to filings comment 

13754 SP/GP pipeline - update ledger text to map to filings comment for dissolution filing

---

data-tool/flows/common/firm_filing_base_json.py
data-tool/flows/common/firm_filing_json_factory_service.py
data-tool/flows/common/firm_queries.py
data-tool/flows/custom_filer/filing_processors/filing_components/business_info.py
data-tool/flows/custom_filer/filing_processors/registration.py

*Issue #:* /bcgov/entity#13802
* Fix bug where BN was not being populated properly in businesses.tax_id column for registration filings
* Update save logic for BN such that BN 9 is used when BN 15 is not provided

13802 SP/GP pipeline - BN bug fix and update to save logic

---

legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#12882

Dissolution date in state filings in summary

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/resources/v2/__init__.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/resources/v2/internal_services.py
legal-api/tests/unit/resources/v2/test_internal_services.py

*Issue #:* /bcgov/entity#13668

13668 endpoint for BN Move

---

legal-api/devops/vaults.json
legal-api/src/legal_api/config.py
legal-api/src/legal_api/resources/v2/internal_services.py
legal-api/src/legal_api/services/__init__.py
legal-api/tests/unit/resources/v2/test_internal_services.py
queue_services/entity-emailer/src/entity_emailer/email_processors/bn_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/BN-MOVE.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/style.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/integration/test_publish_event.py
queue_services/entity-emailer/tests/unit/email_processors/test_bn_notification.py
queue_services/entity-emailer/tests/unit/test_tracker.py

*Issue #:* /bcgov/entity#11995

11995  send email with BN move

---

legal-api/devops/vaults.json

*Issue #:* /bcgov/entity#11995

11995 reset vault

---

legal-api/report-templates/template-parts/change-of-registration/completingParty.html
legal-api/report-templates/template-parts/registration-statement/completingParty.html
legal-api/report-templates/template-parts/registration/completingParty.html

*Issue #:* /bcgov/entity#13126

Template changes to support organization as completing party

---

legal-api/report-templates/template-parts/registration-statement/business-info.html

*Issue #:* /bcgov/entity#13183

Fix - Unable to download Amended Statement of Registration for data loaded firm

---

jobs/update-legal-filings/config.py
jobs/update-legal-filings/devops/vaults.json
jobs/update-legal-filings/update_legal_filings.py
legal-api/src/legal_api/__init__.py
legal-api/src/legal_api/resources/v2/internal_services.py
legal-api/src/legal_api/services/__init__.py
legal-api/tests/unit/resources/v2/test_internal_services.py
queue_services/entity-bn/setup.cfg
queue_services/entity-bn/src/entity_bn/bn_processors/__init__.py
queue_services/entity-bn/src/entity_bn/bn_processors/registration.py
queue_services/entity-bn/src/entity_bn/config.py
queue_services/entity-bn/src/entity_bn/worker.py
queue_services/entity-bn/tests/unit/bn_processors/test_admin.py
queue_services/entity-bn/tests/unit/bn_processors/test_registration.py

*Issue #:* /bcgov/entity#13572

updated all BN services to publish for search-solr-updater

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#13851
* bump version nums for legal api, emailer, filer and entity-bn

13851 bump version nums

---

queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/shares.py
queue_services/entity-filer/tests/unit/test_worker/test_correction_ben.py

*Issue #:* /bcgov/entity#13330
- updated method to update existing share class in db
- unit test

13330 New update method for share class 

---

legal-api/report-templates/template-parts/common/businessDetails.html

*Issue #:* /bcgov/entity#13036
Registration date comes from recognition date not the formatted founding date

13036 Recognition date is the registration date.

---

legal-api/src/legal_api/reports/business_document.py
queue_services/entity-filer/src/entity_filer/filing_processors/put_back_on.py
queue_services/entity-filer/tests/unit/filing_processors/test_put_back_on.py

*Issue #:* /bcgov/entity#13195, /bcgov/entity#12922

Added put back on and admin dissolution to business summary

---

queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-EXPIRED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-REFUND.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-RENEWAL.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-UPGRADE.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/nr-footer-html.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/nr-footer.html
queue_services/entity-emailer/src/entity_emailer/worker.py

*Issue #:* [/bcgov/entity/13429](https://github.com/bcgov/entity/issues/13429)
1. convert the Name request emails (no attachment) to plain text format;

13429 convert email template.

---

queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-EXPIRED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-REFUND.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-RENEWAL.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NR-UPGRADE.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/nr-footer.html

*Issue #:* [13429](https://github.com/bcgov/entity/issues/13429)
1. added more space between footer and content.
2. removed the link of phone number; The link shows incorrectly in web browser view.
3. Fixed a link break issue on refund template.

13429 convert email template

---

data-tool/flows/common/event_filing_service.py
data-tool/flows/common/firm_filing_data_cleaning_utils.py
data-tool/flows/common/firm_queries.py
data-tool/flows/config.py
data-tool/flows/custom_filer/filing_processors/dissolution.py
data-tool/flows/custom_filer/filing_processors/put_back_on.py
data-tool/flows/custom_filer/filing_processors/registration.py
data-tool/flows/migrate_sp_gp_flow.py

*Issue #:* /bcgov/entity#13547
* Update SP/GP pipeline to skip events where it's not possible to corrected data using end event id
* Misc updates
* Remove debug statements
* Added sqlalchemy options config for db pool options
* raise exception when affiliation fails
* update pipeline to not reprocess failed firms as default action

13547 SP/GP pipeline - fix unable to find corrected filing id issue

---

legal-api/src/legal_api/resources/v2/business/business_tasks.py

*Issue #:* /bcgov/entity#13897

13897 not provide conversion todo when pending conversion filing exists

---

queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py

*Issue #:* /bcgov/entity#13834
* Updated filer dissolution processor to use dissolution date from filing for voluntary dissolutions
* Updated filer dissolution tests

13834 Update filer to use dissolution date in filing for voluntary dissolution filings

---

legal-api/src/legal_api/services/bootstrap.py
queue_services/entity-filer/requirements.txt

Entity filer fix

---

colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/version.py

*Issue #:* /bcgov/entity#13574

added fbo/fio to party type options

---

legal-api/src/legal_api/services/bootstrap.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py
queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
queue_services/entity-filer/tests/unit/filing_processors/test_registration.py

*Issue #:* /bcgov/entity#13942

Fix - Filer not setting party tax id

---

colin-api/src/colin_api/resources/filing.py

*Issue #:* /bcgov/entity#13574

comment out broken schema validation

---

queue_services/entity-filer/tests/integration/test_worker_queue.py

Fix failing test in filer

---

colin-api/src/colin_api/resources/business.py

*Issue #:* /bcgov/entity#13574

colin-api allow all legal types on get business

---

legal-api/src/legal_api/resources/v2/internal_services.py
legal-api/tests/unit/resources/v2/test_internal_services.py

*Issue #:* /bcgov/entity#13587

13587 registrars notation filing while updating tax_id (BN Move)

---

colin-api/src/colin_api/models/business.py

*Issue #:* /bcgov/entity#13574

added corp state class to business resp

---

data-tool/flows/custom_filer/filing_processors/registration.py

* Update to populate business.founding_date with COLIN recognition date instead of registration filing effective date

SP/GP pipeline - fix business founding date issue

---

queue_services/entity-bn/src/entity_bn/bn_processors/registration.py

*Issue #:* /bcgov/entity#13979

13979 skip retrying resubmit bn request

---

legal-api/src/legal_api/services/filings/validations/conversion.py
legal-api/tests/unit/services/filings/validations/test_conversion.py

*Issue #:* /bcgov/entity#13997

Removed start date validation for firms conversion

---

jobs/sftp-icbc-report/openshift/templates/cronjob.yaml
jobs/sftp-nuans-report/openshift/templates/cronjob.yaml

*Issue #:* /bcgov/entity###12809
SFTP SP/GP report from openshift to Pimento for NUANS
DBA from home team will merge this report with the home team data on Pimento. Then send the merged report to NUANS

REPORTS - create NUANS report for SP/GPs#12809

---

data-tool/flows/common/firm_filing_data_cleaning_utils.py
data-tool/flows/common/firm_filing_data_utils.py
data-tool/flows/common/firm_queries.py

SP/GP pipeline - update party cleaning logic to support more bad data scenarios

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#14022
* bump legal api version for patch release

14022 bump version nums

---

legal-api/src/legal_api/services/filings/validations/conversion.py
legal-api/src/legal_api/version.py
legal-api/tests/unit/services/filings/validations/test_conversion.py

*Issue #:* /bcgov/entity#14022
This is a PR for cherry picked commits from `main` branch that need to go into the patch release branch
* cherry picked commit for legal api conversion business start date validation removal
* cherry picked commit for legal api version bump

14022 patch release commits

---

jobs/sftp-icbc-report/sftpicbc.py

Signed-off-by: Steven Chen <steven.chen@gov.bc.ca>
*Issue #:* /bcgov/entity###13967
SFTP SP/GP report from openshift to Pimento for ICBC
DBA from home team will merge this report with the home team data on Pimento. Then send the merged report to ICBC

SFTP SP/GP report from openshift to Pimento for ICBC#13967

---

colin-api/src/colin_api/version.py
queue_services/entity-bn/src/entity_bn/version.py

*Issue #:* /bcgov/entity#14021

 14021 bump version

---

legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/report-templates/template-parts/business-summary/parties.html
legal-api/report-templates/template-parts/common/addresses.html
legal-api/report-templates/template-parts/registration-statement/business-info.html

*Issue #:* /bcgov/entity#13181
- added conditions to display "Not Available" in output templates

13181 Legal API: outputs will display 'Not Available' if information is missing

---

colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/resources/parties.py

*Issue #:* /bcgov/entity#13992
- get parties is used for business that do not require 3 directors.
- added check for legal type on business with less than 3 directors.

13992 Sentry error less than 3 directors

---

legal-api/requirements.txt

*Issue #:* /bcgov/entity#14052
* Update legal api to use latest schema version

14052 Update to use latest schema version which supports longer party organization names

---

legal-api/src/legal_api/models/request_tracker.py
legal-api/src/legal_api/models/user.py
legal-api/src/legal_api/resources/v2/administrative_bn.py
legal-api/src/legal_api/resources/v2/request_tracker.py
legal-api/tests/unit/resources/v2/test_administrative_bn.py
legal-api/tests/unit/resources/v2/test_request_tracker.py

*Issue #:* /bcgov/entity#14004

14004 BN Administrative - Improvement

---

queue_services/entity-filer/src/entity_filer/utils.py

*Issue #:* /bcgov/entity#14059

Bug fix - Incorrect registrar stamp in the CP dissolution affidavit

---

legal-api/report-templates/template-parts/common/addresses.html

*Issue #:* /bcgov/entity#14073

14073 unable to download business summary output

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

*Issue #:* /bcgov/entity#14061

Fix - Affidavit not getting charged in CP dissolution

---

legal-api/requirements.txt
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/src/legal_api/version.py
legal-api/tests/unit/services/filings/validations/__init__.py
legal-api/tests/unit/services/filings/validations/test_incorporation_application.py

*Issue #:* /bcgov/entity#14136
* Cherry picked commit to fix completing party first name max length issue
* bumped legal api version num to 2.63.0b for patch release

14136 patch release commits

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/business_details_version.py
legal-api/src/legal_api/services/filings/validations/change_of_address.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
queue_services/entity-bn/src/entity_bn/bn_templates/change_address.xml
queue_services/entity-bn/src/entity_bn/bn_templates/create_program_account_request.xml

*Issue #:* /bcgov/entity#14097

14097 update address fields to empty when none - reports

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#14122

14122 bump up version

---

legal-api/src/legal_api/reports/business_document.py

…
*Issue #:* /bcgov/entity#14198

Fix: Business Summary not getting downloaded when the from legal type is 'C'

---

legal-api/src/legal_api/models/business.py

*Issue #:* /bcgov/entity#14191

14191 numbered description

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#14236
* bump legal api version num

14236 bump version num

---

queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py
queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-info.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-information.html
queue_services/entity-emailer/tests/unit/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_filing_notification.py

*Issue #:* /bcgov/entity#14191

14191 email template updates for ULC, CC and BC

---

queue_services/entity-bn/src/entity_bn/bn_processors/registration.py
queue_services/entity-bn/tests/unit/bn_processors/test_admin.py

*Issue #:* /bcgov/entity#14250

14250 admin override bn9 to empty

---

legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/tests/unit/services/filings/validations/test_incorporation_application.py

*Issue #:* /bcgov/entity#14187

IA Validator updates for ULC, CC and BC

---

legal-api/src/legal_api/resources/v1/business/business.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/services/bootstrap.py

*Issue #:* /bcgov/entity#14219

14219 bootstrap with legalType

---

legal-api/report-templates/template-parts/common/addresses.html

Fix - Records office not getting displayed in any reports

---

legal-api/src/legal_api/services/bootstrap.py

*Issue #:* /bcgov/entity#14341

14341 include corpSubTypeCode when not none

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#14242
Update version number

release 15.4b

---

legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#14308

Document list updates for AR

---

legal-api/report-templates/template-parts/registration-statement/party.html

*Issue #:* /bcgov/entity#14216

Party middle name in statement of registration

---

legal-api/report-templates/bcAddressChange.html
legal-api/report-templates/bcAnnualReport.html
legal-api/report-templates/bcDirectorChange.html
legal-api/report-templates/incorporationApplication.html
legal-api/report-templates/template-parts/bc-annual-report/legalObligations.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#14303

14303 Annual Report Outputs

---

jobs/email-reminder/config.py
jobs/email-reminder/devops/vaults.json
jobs/email-reminder/email_reminder.py
jobs/email-reminder/requirements.txt
jobs/email-reminder/requirements/bcregistry-libraries.txt
queue_services/entity-emailer/src/entity_emailer/email_templates/AR-REMINDER.html

*Issue #:* /bcgov/entity#14339
- included pagination 
- feature flag enable-bc-ccc-ulc

14339 AR reminder for ULC, CCC, BC

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#14368
Update release versions for legal-api and entity-emailer

15.5a Update release versions

---

legal-api/requirements.txt

*Issue #:* /bcgov/entity#14282
* Update dependencies to resolve prefect 2 conflicts

14282 Update dependencies

---

legal-api/report-templates/businessSummary.html
legal-api/report-templates/template-parts/common/courtOrder.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#12672

Court Order in Business Summary

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt

*Issue #:* /bcgov/entity#14410
- update business-schema import to 2.15.39 to allow alteration correction filings.

14410 Update business-schemas to allow alteration corrections.

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#14463

14463 version update

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/tests/unit/services/filings/validations/test_alteration.py

*Issue #:* /bcgov/entity#14515

Name Request legal type validation for alteration

---

queue_services/entity-bn/requirements/dev.txt
queue_services/entity-bn/src/entity_bn/bn_processors/__init__.py
queue_services/entity-bn/src/entity_bn/bn_processors/change_of_registration.py
queue_services/entity-bn/src/entity_bn/bn_processors/correction.py
queue_services/entity-bn/src/entity_bn/bn_processors/dissolution_or_put_back_on.py
queue_services/entity-bn/tests/conftest.py
queue_services/entity-bn/tests/unit/bn_processors/test_change_of_registration.py
queue_services/entity-bn/tests/unit/bn_processors/test_correction.py
queue_services/entity-bn/tests/unit/bn_processors/test_dissolution_or_put_back_on.py

*Issue #:* /bcgov/entity#14535

14535 Generate BN request (skip processing) if BN15 is not available instead of generating the Sentry errors

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py

*Issue #:* /bcgov/entity#14573
Update Version to 2.69.0 for 15.6a push to test for 
lear and entity bn

14573 Update version for 15.6a release to test

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/tests/unit/services/filings/validations/test_alteration.py

*Issue #:* /bcgov/entity#14689

14689 Fix alteration validation issue for BC/ULC/CC legal types

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/tests/unit/services/filings/validations/test_alteration.py

*Issue #:* /bcgov/entity#14689
* Fixed alteration validation to support legal type of CC

14689 Update alteration validation logic for corps

---

.github/workflows/colin-api-cd.yml
.github/workflows/colin-api-ci.yml
.github/workflows/data-reset-tool-cd.yml
.github/workflows/data-reset-tool-ci.yml
.github/workflows/email-reminder-cd.yml
.github/workflows/email-reminder-ci.yml
.github/workflows/entity-bn-cd.yml
.github/workflows/entity-bn-ci.yml
.github/workflows/entity-emailer-cd.yml
.github/workflows/entity-emailer-ci.yml
.github/workflows/entity-filer-cd.yml
.github/workflows/entity-filer-ci.yml
.github/workflows/entity-pay-cd.yml
.github/workflows/entity-pay-ci.yml
.github/workflows/filings-notebook-report-cd.yml
.github/workflows/filings-notebook-report-ci.yml
.github/workflows/future-effective-filings-cd.yml
.github/workflows/future-effective-filings-ci.yml
.github/workflows/legal-api-cd.yml
.github/workflows/legal-api-ci.yml
.github/workflows/sftp-icbc-report-cd.yml
.github/workflows/sftp-icbc-report-ci.yml
.github/workflows/sftp-nuans-report-cd.yml
.github/workflows/sftp-nuans-report-ci.yml
.github/workflows/update-colin-filings-cd.yml
.github/workflows/update-colin-filings-ci.yml
.github/workflows/update-legal-filings-cd.yml
.github/workflows/update-legal-filings-ci.yml

*Issue #:* /bcgov/entity/14257
Upgrade codecov version and checkout action version,

14257-Upgrade CI/CD.

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/services/filings/validations/correction.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/services/filings/validations/test_correction_ia.py

*Issue #:* /bcgov/entity#13503

Correction - Validator Update

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#14574
* bump version num for legal api and emailer

14574 bump version nums

---

legal-api/src/legal_api/services/filings/validations/correction.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/tests/unit/services/filings/validations/test_correction_ia.py

*Issue #:* /bcgov/entity#14759

14759 update correction validation

---

data-tool/scripts/README_COLIN_Corps_Extract.md
data-tool/scripts/colin_corps_extract_postgres_ddl
data-tool/scripts/misc_extract_corps_queries.sql
data-tool/scripts/transfer_cprd_corps.sql

*Issue #:* /bcgov/entity#14486
* Added script(`data-tool/transfer_cprd_corps.sql`) for transferring COLIN corps data to a postgres extract db.  This postgres extract db will be used by the corps data migration pipeline to clean/transform and push corps into LEAR db.
* Added ddl for postgres extract db
* Added README(`README_COLIN_Corps_Extract`) providing details of extract process
Example of a full corp extract from COLIN:

14486 extract COLIN corp data script

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/tests/unit/__init__.py
queue_services/entity-filer/tests/unit/test_worker/test_correction_bcia.py

*Issue #:* /bcgov/entity#14620

14620 Correction of name translation

---

legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/tests/unit/services/filings/validations/test_incorporation_application.py

*Issue #:* /bcgov/entity#14284 
- Reverting the validation changes I made to the IA

14284 Reverted code changes due to business requirements change

---

legal-api/src/legal_api/core/filing.py
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/court_order.py
queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/rules_and_memorandum.py
queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_alteration.py
queue_services/entity-filer/tests/unit/filing_processors/test_court_order.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py

*Issue #:* /bcgov/entity#14604
- file_name and content_type is removed from document table 

14604 uploaded court order - filer

---

legal-api/src/legal_api/services/filings/validations/correction.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/tests/unit/services/filings/validations/test_correction_ia.py

*Issue #:* /bcgov/entity#14759
* cherry pick commit that fixes correction filing validation issue(#14759)

14759 update correction validation (#1864)

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#14815

14815 show current registrar's signature in annual report

---

legal-api/report-templates/correction.html
legal-api/src/legal_api/reports/report.py
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/tests/unit/filing_processors/test_alteration.py
queue_services/entity-filer/tests/unit/test_worker/test_correction_bcia.py

*Issue #:* /bcgov/entity#13978

13978 set provisionsRemoved only through alteration

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#14576

14576 bump version nums

---

legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/tests/unit/services/filings/validations/test_incorporation_application.py

*Issue #:* /bcgov/entity#14969

14969 optional court order in IA

---

queue_services/entity-pay/src/entity_pay/worker.py

Update entity pay to skip unprocessable messages and update back off retry count

---

legal-api/src/legal_api/models/share_class.py
legal-api/src/legal_api/models/share_series.py

*Issue #:* /bcgov/entity#14417
* Add skip listener flags to `share_classes` and `share_series` models to support loading of corp data from COLIN

14417 Update model listener for share_class and share_series

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#14575
* bump version numbers for legal api, filer and emailer

14575 bump version nums

---

queue_services/entity-emailer/src/entity_emailer/email_processors/change_of_registration_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py
queue_services/entity-emailer/tests/unit/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_change_of_registration_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_filing_notification.py

*Issue #:* /bcgov/entity#14988

14988 add completing party into recipients (alteration, changeOfRegistration)

---

legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/tests/unit/services/filings/validations/test_restoration.py

*Issue #:* /bcgov/entity#14639

14639 validation fix

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/services/filings/validations/registration.py
legal-api/tests/unit/services/filings/validations/test_registration.py
queue_services/entity-emailer/src/entity_emailer/email_processors/change_of_registration_notification.py

*Issue #:* /bcgov/entity#15123

15123 update taxId validation

---

queue_services/entity-pay/src/entity_pay/worker.py

15114 Fix no app context issue in entity pay

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py
queue_services/entity-pay/src/entity_pay/version.py

*Issue #:* /bcgov/entity#15166
Update version for release 16.2c
- Entity Filer v2.73.0
- Legal API v2.73.0
- Entity-emailer v2.73.0
- Entity-pay v2.73.0

Update version for release 16.2c

---

queue_services/entity-pay/q_cli.py

* Update `q_cli.py` to support new args so we can use it manually from pod to process filings that weren't picked up by entity pay for whatever reason

15114 Update entity pay q_cli.py to support new args(filing id and corp type)

---

queue_services/entity-pay/src/entity_pay/worker.py
queue_services/entity-pay/tests/integration/test_worker_queue.py
queue_services/entity-pay/tests/unit/test_worker.py

15114 Fix entity pay bug

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py
queue_services/entity-filer/src/entity_filer/filing_processors/restoration.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/__init__.py
queue_services/entity-filer/tests/unit/test_worker/test_restoration.py

*Issue #:* /bcgov/entity#14641

14641 restoration

---

queue_services/entity-pay/q_cli.py
queue_services/entity-pay/src/entity_pay/worker.py
queue_services/entity-pay/tests/integration/test_worker_queue.py
queue_services/entity-pay/tests/integration/utils.py
queue_services/entity-pay/tests/unit/test_worker.py

15114 Revert code in entity pay to use payment id to find filing

---

queue_services/entity-pay/q_cli.py
queue_services/entity-pay/src/entity_pay/worker.py
queue_services/entity-pay/tests/integration/test_worker_queue.py
queue_services/entity-pay/tests/integration/utils.py
queue_services/entity-pay/tests/unit/test_worker.py

* Cherry entity pay commits into release branch

15114 entity pay cherry pick commits

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v1/business/business_filings.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#15043

15043 Fee codes and allowable filings for Consent Continuation Out

---

legal-api/report-templates/certificateOfRestoration.html
legal-api/report-templates/template-parts/common/certificateStyle.html
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/business_details_version.py
legal-api/src/legal_api/services/filings/validations/restoration.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
legal-api/tests/unit/services/filings/validations/test_restoration.py
queue_services/entity-filer/src/entity_filer/filing_processors/restoration.py

*Issue #:* /bcgov/entity#15230

15230 Certificate of Restoration

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/resources/v2/business/test.py
legal-api/src/legal_api/version.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#15176

15176 get affiliated businesses

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#15215
Updated version numbers for release.

Updated version number 16.3a

---

legal-api/src/legal_api/services/filings/validations/alteration.py

*Issue #:* /bcgov/entity#7503
Update Alterations error message.

7503_update_error_message

---

legal-api/src/legal_api/services/filings/validations/alteration.py

*Issue #:* /bcgov/entity#7503
Change alteration message

7503_change_alteration_message

---

jobs/sftp-nuans-report/notebook/generate_files.ipynb

*Issue #:* /bcgov/entity### 15484
Fixed the query for the NUANS notebook report

Update NUANS notebook report for SP/GP#15484

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/resources/v2/business/business_tasks.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/warnings/business/business_checks/__init__.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#15281
* Add `allowableActions` to business response on GET business endpoint
* Update `ALLOWABLE_FILINGS` dict to support various blocker checks(warnings, invalid/valid state filings and other business level checks) in an extensible manner.  Some of the blocker check logic was implemented based on the [allowable actions logic currently in the FE](https://github.com/bcgov/business-filings-ui/blob/main/src/mixins/allowable-actions-mixin.ts).  Note that it is known that some transitions should not be allowed to occur but the filings have not been implemented yet.  As filings are implemented, the `ALLOWABLE_FILINGS` will be updated.
* Added and updated tests
**Examples:**
Note there are a lot of scenarios so only a handful of scenarios have …

15281 Add allowable actions to business response

---

data-tool/flows/migrate_sp_gp_flow.py
data-tool/flows/sp_gp_affiliation_flow.py

*Issue #:* /bcgov/entity#15501
* Update firm affiliation pipeline to work with prefect 2

15501 Update firm affiliation pipeline

---

legal-api/report-templates/certificateOfRestoration.html

*Issue #:* /bcgov/entity#15534

15534 certificate of restoration wording fix

---

legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/version.py
legal-api/test.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#15273
PR for response schema change: https://github.com/bcgov/business-schemas/pull/128

15273 affiliaitons data endpoint

---

legal-api/src/legal_api/resources/v2/business/business.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#15273

fixed lint err on == None in sqlalchemy comp

---

legal-api/report-templates/restoration.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/common/style.html
legal-api/report-templates/template-parts/restoration-application/applicant.html
legal-api/report-templates/template-parts/restoration-application/approvalType.html
legal-api/report-templates/template-parts/restoration-application/expiry.html
legal-api/report-templates/template-parts/restoration-application/legalName.html
legal-api/report-templates/template-parts/restoration-application/legalNameDissolution.html
legal-api/report-templates/template-parts/restoration-application/nameRequest.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#14642
* Create restoration application outputs for Full + Limited + Extension + Conversion Restoration
Example of outputs
* [Full](https://github.com/bcgov/lear/files/10936815/fr.pdf)
* [Limited](https://github.com/bcgov/lear/files/10936823/lr.pdf)
* [Extension](https://github.com/bcgov/lear/files/10936826/lre.pdf)
* [Conversion Restoration](https://github.com/bcgov/lear/files/10936835/lrf.pdf)

14642 Add restoration application outputs

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#15215
Updated version numbers for release.

Updated version number

---

legal-api/report-templates/template-parts/business-summary/businessDetails.html

*Issue #:* /bcgov/entity#15543
Update contact phone number

update contact phone number

---

legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/src/legal_api/config.py
legal-api/src/legal_api/resources/v1/business/business.py
legal-api/src/legal_api/resources/v1/business/business_address.py
legal-api/src/legal_api/resources/v1/business/business_directors.py
legal-api/src/legal_api/resources/v1/business/business_filings.py
legal-api/src/legal_api/resources/v1/business/business_resolutions.py
legal-api/src/legal_api/resources/v1/business/business_share_classes.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/resources/v2/business/business_address.py
legal-api/src/legal_api/resources/v2/business/business_directors.py
legal-api/src/legal_api/resources/v2/business/business_parties.py
legal-api/src/legal_api/resources/v2/business/business_resolutions.py
legal-api/src/legal_api/resources/v2/business/business_share_classes.py
legal-api/src/legal_api/services/__init__.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/resources/v2/test_business.py
legal-api/tests/unit/resources/v2/test_business_address.py
legal-api/tests/unit/resources/v2/test_business_director.py
legal-api/tests/unit/resources/v2/test_business_parties.py
legal-api/tests/unit/resources/v2/test_business_resolutions.py
legal-api/tests/unit/resources/v2/test_business_share_classes.py

*Issue #:* /bcgov/entity#15039

secured protected business endpoints with auth check

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/restoration.py
legal-api/tests/unit/services/filings/validations/test_restoration.py

*Issue #:* /bcgov/entity#15445
Add the validation for restoration NR request code type

Legal API: validate restoration NR request type code

---

queue_services/entity-bn/devops/vaults.json
queue_services/entity-bn/src/entity_bn/bn_processors/__init__.py
queue_services/entity-bn/src/entity_bn/bn_processors/registration.py
queue_services/entity-bn/src/entity_bn/bn_templates/create_program_account_request.xml
queue_services/entity-bn/src/entity_bn/config.py
queue_services/entity-bn/src/entity_bn/version.py

*Issue #:* /bcgov/entity#15681

15681 Update BN functionality for SP/GP

---

queue_services/entity-bn/src/entity_bn/config.py

*Issue #:* /bcgov/entity#15681

15681 config update

---

legal-api/src/legal_api/resources/v2/business/business.py

remove auth check on business json for now

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#15680
* bump legal api and filer version numbers

15680 bump version numbers

---

colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/filing.py

*Issue #:* /bcgov/entity#13535

13535 BEN Correction

---

legal-api/src/legal_api/services/filings/validations/restoration.py
legal-api/tests/unit/services/filings/validations/test_restoration.py

*Issue #:* /bcgov/entity#15915
Fix limitedRestorationExtension.expiry_date duration (3 -> 2 years)

15915 updated limited restoration extension expiry date

---

jobs/email-reminder/email_reminder.py
jobs/email-reminder/setup.cfg

*Issue #:* /bcgov/entity#14746

14746 updated ar reminder

---

legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#14953
* Used the versioned business instead

14953 - Attempting to fix the problem with Business Summary

---

legal-api/src/legal_api/reports/business_document.py

* Fix business summary bug where  BC LTD companies were not taken into account for dissolution related display info.

Fix dissolution related business summary bug

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#15843
- Bumped up the version numbers for release 16.7a

Bumped version numbers up for release 16.7a

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#15977
Update change of name so it provides a billing code

15977 - Update change of name so it provides a billing code.

---

legal-api/src/legal_api/services/filings/validations/restoration.py
legal-api/tests/unit/services/filings/validations/test_restoration.py

*Issue #:* /bcgov/entity#15966

15966 update limited restoration extension validation to not allow name change

---

legal-api/src/legal_api/models/filing.py
legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py

Legal type wouldn't return for registration for SP or GP.

Small tweak to json_legal_type, also small unit test fix.

---

legal-api/src/legal_api/models/filing.py

Fix to look in registration

---

legal-api/report-templates/template-parts/business-summary/businessDetails.html
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/utils/legislation_datetime.py

*Issue #:* /bcgov/entity#14953
* Used the date from the meta info & cleaned up comments

14953 - Fixing up the Business Summary expiry dates by grabbing date from different source.

---

legal-api/report-templates/correction.html
legal-api/report-templates/template-parts/correction/legalNameChange.html
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#15894

15894 display name change for COA and COD, title change in report

---

legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#16049
* Cherry pick commit 6789b26 from `main` into release branch

16049 Update allowable actions to allow dissolution filings for firms

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#15999
* Increment legal api version num

15999 bump version nums

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/consent_continuation_out.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_consent_continuation_out.py

*Issue #:* /bcgov/entity#15045
add a consent_continuation_out filer

15045 Add ConsentContinuationOut Filer

---

queue_services/entity-bn/src/entity_bn/bn_templates/create_program_account_request.xml

*Issue #:* /bcgov/entity#16240

16240 include user credentials in cra header

---

queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#16014
Bump up version

16014-bump up version for release

---

colin-api/requirements.txt
jobs/email-reminder/requirements.txt
jobs/future-effective-filings/requirements.txt
jobs/update-colin-filings/requirements.txt
jobs/update-legal-filings/requirements.txt
legal-api/requirements.txt
queue_services/entity-bn/requirements.txt
queue_services/entity-emailer/requirements.txt
queue_services/entity-filer/requirements.txt
queue_services/entity-pay/requirements.txt

*Issue #: [15861](https://github.com/bcgov/entity/issues/15861)

bump sentry sdk version

---

jobs/update-legal-filings/update_legal_filings.py

*Issue #:* /bcgov/entity#16135

16135 avoid deadlock in update legal filings job

---

jobs/update-legal-filings/update_legal_filings.py

Revert "16135 avoid deadlock in update legal filings job"

---

colin-api/src/colin_api/models/filing.py

*Issue #:* /bcgov/entity#15749

15749 Freeze BEN Companies on colin IA

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#16374
* Fix bug where draft alteration/correction filings could not be saved/submitted - 401 was returned
* Add/update draft tests for allowable actions code

16374 Fix draft filing allowable actions bug

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py
queue_services/entity-pay/src/entity_pay/version.py

*Issue #:* /bcgov/entity#16307
- Bumped version numbers up for release 17.3b

Bump version numbers up for release 17.3b

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#16346
- Bump version numbers for release 17.4a

Bump version numbers for release 17.4a

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#16258
- Add parametrized tests for staff & general user with state filing of "continuation out"
- Update requirement files for legal api

16258 Legal API - Update allowable actions on filing completion

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#16347

Bump version number for release 17.4b

---

legal-api/report-templates/letterOfConsent.html
legal-api/src/legal_api/models/consent_continuation_out.py
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#16539
- include jurisdiction in letter of consent

16539 update consent letter

---

queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#16347

Bump version number of emailer for release 17.4b

---

legal-api/src/legal_api/resources/v2/business/business.py

*Issue #:* /bcgov/entity#16658

16658 using v2 save filings

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#16580

16580 update completed filings blocker check logic

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/test_business.py

*Issue #:* /bcgov/entity#15988

15988 business in limited restoration is not in good standing

---

legal-api/src/legal_api/resources/v2/business/business_documents.py
legal-api/src/legal_api/services/document_meta.py
legal-api/src/legal_api/services/filings/validations/continuation_out.py
legal-api/src/legal_api/utils/legislation_datetime.py
legal-api/tests/unit/models/test_consent_continuation_out.py
legal-api/tests/unit/services/test_document_meta.py

*Issue #:* /bcgov/entity#16460

16460 helper func LegislationDatetime

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/business_details_version.py
legal-api/src/legal_api/utils/legislation_datetime.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/reports/test_report.py

*Issue #:* /bcgov/entity#16460

16460 using format_as_legislation_date

---

queue_services/entity-bn/src/entity_bn/version.py

*Issue #:* /bcgov/entity#16743
* updated entity-bn version num to match version nums of components that went out with last release.  this should have gone out too but was missed.

16743 bump entity bn version num

---

legal-api/src/legal_api/models/consent_continuation_out.py
legal-api/src/legal_api/services/filings/validations/continuation_out.py
legal-api/tests/unit/models/test_consent_continuation_out.py
legal-api/tests/unit/services/filings/validations/test_continuation_out.py

*Issue #:* /bcgov/entity#16786

16786 continuation out date should be greater than or equal to the consent filing date

---

legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/filings/validations/continuation_out.py

*Issue #:* /bcgov/entity#16824

16824 continuation out - business summary

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#16564
- Bump the version numbers up for release 17.6b

Bump version numbers up for release 17.6b

---

legal-api/report-templates/specialResolutionApplication.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/template-parts/special-resolution/resolution.html
legal-api/report-templates/template-parts/special-resolution/resolutionApplication.html
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/pdf_service.py
legal-api/tests/unit/reports/test_report.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
legal-api/tests/unit/services/test_pdf_service.py
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/rules_and_memorandum.py
queue_services/entity-filer/src/entity_filer/utils.py
queue_services/entity-filer/tests/unit/filing_processors/test_alteration.py

*Issue #:* /bcgov/entity#you 16167
[response.pdf](https://github.com/bcgov/lear/files/11852392/response.pdf)
- Entity Filer Test
The entity_filer doesn't import `create_registrars_stamp` function (that is in the legal_api, I made update). It imports original legal_api.

16167 Special Resolution Outputs

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py
queue_services/entity-filer/src/entity_filer/filing_processors/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/resolutions.py
queue_services/entity-filer/tests/unit/test_worker/test_correction_special_resolution.py

*Issue #:* /bcgov/entity[15955](https://github.com/bcgov/entity/issues/15955)
1. Allow correction on a special resolution correction and unit test updates
2. lear display name update for special resolution correction

15955 filer bug fix - correction on a special resolution correction

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#16916
Suppress certificate dissolution pdf for admin dissolution.

16916 Suppress Certificate Dissolution for Admin Dissolution

---

queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/requirements/bcregistry-libraries.txt
queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/special_resolution_helper.py
queue_services/entity-emailer/src/entity_emailer/email_processors/special_resolution_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/CP-SR-CRCTN-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/CP-SR-CRCTN-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/SR-CP-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/SR-CP-PAID.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_correction_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_cp_special_resolution_notification.py
queue_services/entity-emailer/tests/unit/test_tracker.py
queue_services/entity-emailer/tests/unit/test_worker.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/resolutions.py
queue_services/entity-filer/tests/unit/test_worker/test_correction_special_resolution.py

*Issue #:* [/bcgov/entity/16160](https://github.com/bcgov/entity/issues/16160)
2. Send email notification when Special Resolution and Correction have been filed
3. Filer fix - coopAssociatiionType and signing_date for special resolution correction

16160 - EMAILER - Special Resolution and Correction

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#16897

16897 Bump version numbers up

---

legal-api/report-templates/template-parts/special-resolution/resolution.html
legal-api/report-templates/template-parts/special-resolution/resolutionApplication.html
legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

Special Resolution - Outputs - Minor fixes based on UX and testing

---

queue_services/entity-emailer/src/entity_emailer/email_processors/dissolution_notification.py

*Issue #:* /bcgov/entity#16916

16916 Suppress admin certificate dissolution at email

---

legal-api/report-templates/specialResolutionCorrectionApplication.html
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/filing_helper.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
queue_services/entity-emailer/Makefile
queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/special_resolution_helper.py
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/src/entity_filer/filing_processors/correction.py

https://github.com/bcgov/entity/issues/16446
Changes for special resolution correction reporting
A special thanks to @kzdev420 

16466 - Changes for special resolution correction reporting

---

colin-api/src/colin_api/models/address.py
colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/resources/parties.py
colin-api/src/colin_api/version.py
colin-api/tests/postman/colin-api.postman_collection.json

*Issue #:* /bcgov/entity#16025

colin-api updates to support getting all parties / address types

---

queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/special_resolution_helper.py
queue_services/entity-emailer/src/entity_emailer/email_templates/CP-SR-CRCTN-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/SR-CP-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/tests/unit/email_processors/test_correction_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_cp_special_resolution_notification.py
queue_services/entity-emailer/tests/unit/test_tracker.py

*Issue #:* /bcgov/entity[16160](https://github.com/bcgov/entity/issues/16160)

16160_2 - Emailer attachment text change and few outputs path change

---

legal-api/report-templates/template-parts/special-resolution/resolutionApplicationCorrection.html
legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py

*Issue #:* /bcgov/entity#16466

16466 - QA/ UX tweaks for outputs

---

colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/version.py
colin-api/tests/postman/colin-api.postman_collection.json

*Issue #:* /bcgov/entity#16894

return email in get business resp

---

legal-api/migrations/versions/4aed1fbbba29_.py
legal-api/src/legal_api/core/filing_helper.py
legal-api/src/legal_api/models/consent_continuation_out.py
legal-api/src/legal_api/models/legal_entity.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/filings/validations/consent_continuation_out.py
legal-api/src/legal_api/services/filings/validations/continuation_out.py
legal-api/src/legal_api/services/filings/validations/correction.py
legal-api/tests/unit/models/test_comments.py
legal-api/tests/unit/models/test_consent_continuation_out.py
legal-api/tests/unit/services/filings/validations/test_consent_continuation_out.py
legal-api/tests/unit/services/filings/validations/test_correction_coa.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#17095

17095 misc fix

---

legal-api/report-templates/template-parts/special-resolution/resolutionApplicationCorrection.html

Typo in resolutionApplicationCorrection.html

---

legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql

* small update to transfer_to_new_lear.sql for updated column name in cco table

Update transfer_to_new_lear.sql script to match column name change for cco table

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#16898
* bump version numbers for filer, legal api, emailer and colin api

16898 bump version numbers

---

queue_services/entity-emailer/devops/vaults.json
queue_services/entity-emailer/flags.json
queue_services/entity-emailer/src/entity_emailer/config.py
queue_services/entity-emailer/src/entity_emailer/email_processors/ar_reminder_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/AR-REMINDER.html
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/email_processors/test_ar_reminder_notification.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* /bcgov/entity#17028
- Feature flagged to remove Dye & Durham references. ~A new feature flag `enable-specific-service-provider` should be added. Any advice for its name?~ A new feature flag `disable-specific-service-provider` should be added. Default value of this FF is `false`.
- Add replacement text. See below(*updated*).
Hyperlink in the screenshot: https://www.bcregistry.gov.bc.ca/filing
Further details can be seen here: https://docs.google.com/document/d/1RSuZ9PiOoNsdhaDKRYqHa6lL46djjDPJpUCl9OskQPU/edit?usp=drive_link

17028 Remove Dye & Durham references - Feature Flag

---

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql

*Issue #:* /bcgov/entity#17121
Note: 
After discussion with Thor and Vysakh, there will be additional updates that will need to be made to the migration scripts outside of the work done in this PR.
In particular, we will need to re-construct the versioning history for some tables like entity_roles, addresses, share classes, share versions and etc such that every filing will essentially cut new history rows for relevant rows to make retrieving active and historical information easier.  
With this being said, I would still like to get these updates into the "dev_legal_name_changes" branch.  Most of these changes are still relevant with some of the migration script logic likely changing a bit for the tables mentioned above.
* Update scripts not include current row …

17121 versioning data tweaks to legal name migration scripts

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#17074
- bump version numbers up for the release of 18.2b

bump version numbers up for release 18.2b

---

legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/utils/formatting.py

*Issue #:* /bcgov/entity#15320

15320 format par value

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#17197
update version for release

17197-update version for release

---

legal-api/report-templates/template-parts/special-resolution/resolutionApplication.html

Fix certified by for special resolution.

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#17171

17171 compare sorted name

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#17198
Bump version numbers up for release 18.4a

bump version numbers up for release 18.4a

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#17294
update version for release 18.5a

update version for release 18.5a

---

legal-api/src/legal_api/resources/v2/business/business_tasks.py
legal-api/tests/unit/resources/v2/test_business_tasks.py

8692 provide IA tasks according filing status

---

queue_services/entity-emailer/src/entity_emailer/email_templates/NR-EXPIRED.html

*Issue #:* bcgov/entity#17213
*Description of changes:* update letter design 

updated design for expired nr letter

---

colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/version.py

*Issue #:* /bcgov/entity#15978

colin-api: added good standing logic

---

jobs/update-legal-filings/update_legal_filings.py

*Issue #:* /bcgov/entity#17443
* Add debug logging to update-legal-filings job in attempt to figure out why colin api call with auth fails

17443 Add debug logging

---

queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY.html

*Issue #:* https://github.com/bcgov/entity/issues/17213

fix letter typos

---

colin-api/src/colin_api/models/business.py

*Issue #:* /bcgov/entity#15978

colin-api: good standing is false if in LIQ, LRL or LRS

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#17833
* Bump version nums for legal api, filer, emailer and entity-bn 

17833 bump version numbers

---

legal-api/src/legal_api/models/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#18030
- added the agm location change fee codes and tests.

18030 added agml change location fee codes and tests

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/services/filings/validations/agm_location_change.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/src/legal_api/services/utils.py
legal-api/tests/unit/services/filings/validations/test_agm_location_change.py

*Issue #:* /bcgov/entity#17940

17940 Validate AGM Location Change

---

legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#18026
- Added not in good standing unit tests

18026 Added not in good standing unit tests

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#18061
- Bumped the version numbers up for release 19.2b

bump version numbers for release 19.2b

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#18000
- Removed Certified Memorandum and Certified Rules from Coop Voluntary Dissolution List

18000 Legal api: Remove documents from Coop Voluntary Dissolution List

---

legal-api/src/legal_api/resources/v2/namerequest.py
legal-api/src/legal_api/services/bootstrap.py

*Issue #:* /bcgov/entity#17157
1. `{{url}}/api/v2/nameRequests/NR 2254890/validate`
Response:
When NR is not affiliated
`The request must include email or phone number.` with 403
2. `{{url}}/api/v2/nameRequests/NR 2254894/validate?email=aaa@gov.bc.ca@phone=1232323`
Sample Response
- Failed
`NR 2254894 not found` with 404
`Invalid email or phone number.` with 400
- Successful
```
{
"actions": [
{
"URL": null,
"entitiesFilingName": "incorporationApplication",
"filingName": "Incorporation",
"learTemplate": "{'filing': {'header': {'name': {entitiesFilingName} }, '{entitiesFilingName}': {'nameRequest': {'nrNumber': '{nrNumber}', 'legalName': '{legalName}', 'legalType': '{legalType}'}}}}"
},
{
"URL": null,
"entitiesFilingName": "manual",
"filingName": "Amalgamation", …
```

17157 update fetch NR

---

legal-api/src/legal_api/resources/v2/namerequest.py

*Issue #:* /bcgov/entity#17157

17157_update phone and email validation process

---

legal-api/report-templates/agmLocationChange.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#17938
- Added output for AGM Location Change

17938 AGM Location Change Outputs

---

legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#18198
- added business name to business summary

18198 added business name to business summary

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#18232
- Bump version numbers for release 19.3a
@argush3 Argus, I won't merge before I get the green light from you (after DB alembic version update).

bump version numbers up for release 19.3a

---

queue_services/entity-bn/src/entity_bn/config.py

*Issue #:* /bcgov/entity#17821

17821 update colin_api config

---

queue_services/entity-emailer/src/entity_emailer/email_processors/agm_location_change_notification.py
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/tests/unit/email_processors/test_agm_location_change_notification.py

*Issue #:* /bcgov/entity#17939
- Fix QueueException for AGM Location Change

17939 Fix AGM Location Change QueueException

---

legal-api/requirements.txt
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#17929
- added allowable actions for agm extension

17929 added agm extension allowable actions

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#18233
* bump version numbers for following:
* legal api
* filer
* entity-bn
* emailer 

18233 bump version nums

---

legal-api/report-templates/letterOfAgmLocationChange.html

*Issue #:* /bcgov/entity#18458
*Description of changes:* Remove "city of" agmLocationChange PDF

remove city of from agmLocationChange PDF

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#17671
Add futureEffective when doing alteration

17671 - add futureEffective for alteration

---

.github/workflows/business-api-cd.yml
.github/workflows/business-auth-cd.yml
.github/workflows/business-bn-cd.yml
.github/workflows/business-email-reminder-cd.yml
.github/workflows/business-emailer-cd.yml
.github/workflows/business-filer-cd.yml
.github/workflows/business-future-effective-filings-cd.yml
.github/workflows/business-pay-cd.yml
.github/workflows/business-update-colin-filings-cd.yml
.github/workflows/business-update-legal-filings-cd.yml

Add CD pipelines for GCP.

---

.github/workflows/business-api-cd.yml
.github/workflows/business-auth-cd.yml
.github/workflows/business-bn-cd.yml
.github/workflows/business-email-reminder-cd.yml
.github/workflows/business-emailer-cd.yml
.github/workflows/business-filer-cd.yml
.github/workflows/business-future-effective-filings-cd.yml
.github/workflows/business-pay-cd.yml
.github/workflows/business-update-colin-filings-cd.yml
.github/workflows/business-update-legal-filings-cd.yml

Update reuseable-workflow repo.

---

.github/workflows/business-api-cd.yml
.github/workflows/business-auth-cd.yml
.github/workflows/business-bn-cd.yml
.github/workflows/business-email-reminder-cd.yml
.github/workflows/business-emailer-cd.yml
.github/workflows/business-filer-cd.yml
.github/workflows/business-future-effective-filings-cd.yml
.github/workflows/business-pay-cd.yml
.github/workflows/business-update-colin-filings-cd.yml
.github/workflows/business-update-legal-filings-cd.yml

Update workflow repo and branch name.

---

legal-api/src/legal_api/resources/v2/namerequest.py

*Issue #:* /bcgov/entity#18557

18557 remove old fetch nr endpoint

---

queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY.html

https://github.com/bcgov/entity/issues/18240
update the text "register your business" to "complete your applicatoon"

18240 update some words in NR before expiry letter

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#18523
- Bumping version numbers up for release 19.5a

bump version numbers up for release 19.5a

---

legal-api/src/legal_api/resources/v2/ops.py
legal-api/tests/unit/resources/v2/test_ops.py

*Issue #:* /bcgov/entity#18499
- Added back the healthz and readyz endpoints
- Added unit tests for endpoints

18499 added readyz and healthz endpoints

---

legal-api/migrations/versions/004f7558063f_second.py
legal-api/scripts/manual_db_scripts/legal_name_change/README.md
legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql

*Issue #:* /bcgov/entity#18451
- Updated data migration scripts
- Updated `README.md`

18451 Update data migration scripts to include digital credential and other model changes

---

queue_services/entity-digital-credentials/Dockerfile
queue_services/entity-digital-credentials/Makefile
queue_services/entity-digital-credentials/devops/vaults.json
queue_services/entity-digital-credentials/requirements/dev.txt
queue_services/entity-digital-credentials/setup.cfg
queue_services/entity-digital-credentials/src/entity_digital_credentials/config.py

*Issue #:* /bcgov/entity#18521
* Add req'd config items to `vault.json`
* Added missing Dockerfile
* Added `SENTRY_DSN` and `PROJECT_ROOT` to `config.py`
* other misc updates

18521 Add config for entity-dc queue listener

---

queue_services/entity-digital-credentials/devops/vaults.json

*Issue #:* /bcgov/entity#18521
* Add sentry vault to `vault.json`

18521 Add missed sentry config for entity dc queue listener

---

legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql

*Issue #:* /bcgov/entity#18751
- Fix json columns issue in transfer script

18751 Fix json columns issue in transfer script

---

legal-api/report-templates/letterOfAgmExtension.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#17931
*Description of changes:* Add 3 PDFs regarding first Agm Extension, final one and neither of them

17931 add Letter of Agm Extension PDFs

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-digital-credentials/src/entity_digital_credentials/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#18669
- Bumping the version numbers up for release 19.5b

bump version numbers for release 19.5b

---

legal-api/report-templates/template-parts/common/businessDetails.html

*Issue #:* /bcgov/entity#18108
Remove Special Resolution Type from header

18108 - Remove redundant Special Resolution Type from report

---

legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/version.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#18858
* cherry pick DBC commits from main for legal api that fix business loading issue
* https://github.com/bcgov/lear/pull/2342/files
* https://github.com/bcgov/lear/pull/2343/files 
* bump legal api version num

18858 firm loading issue dbc flag check

---

legal-api/src/legal_api/version.py
queue_services/entity-digital-credentials/src/entity_digital_credentials/version.py

*Issue #:* /bcgov/entity#18824

bump version numbers for release 19.6a

---

legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#18966

18966 Fix DBC allowed check properietor middle name issue

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#18970

18970 - bump version for release 19.6b

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/core/test_filing_ledger.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/resources/v2/test_business.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#18784
- updated allowable actions for amalgamation
- fix unit tests
- rename `amalgamation` to `amalgamationApplication`

18784 Update allowable actions for amalgamation

---

queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#18970

18970 - 2nd bump version number for 19.6b

---

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql

*Issue #:* /bcgov/entity#18007
* Update alternate_names/alternate_names_history population logic
* Update migration script such that SP natural person scenario is taken care of.  i.e. a SP natural person will not have entity_roles entry.  the SP will have an entity_type = 'person'.  Note that a lot of sql had to be written to merge the entity_role entry for the SP person with the original SP business record.
There are still a lot of little things that need to be tweaked and updated as I got deeper into this.  New tickets will be created to deal with any remaining outstanding work.
Before
After
Before
After
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear license (Apache …

18007 legal name migration script updates

---

legal-api/Makefile
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/src/legal_api/services/filings/validations/amalgamation_application.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py

*Issue #:* /bcgov/entity#18639

18639 amalgamation validation

---

legal-api/migrations/versions/5238dd8fb805_.py
legal-api/src/legal_api/models/__init__.py
legal-api/src/legal_api/models/amalgamating_business.py
legal-api/src/legal_api/models/amalgamation.py
legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/models/test_amalgamating_business.py
legal-api/tests/unit/models/test_amalgamation.py

*Issue #:* /bcgov/entity#18977
- Created Amalgamation and Amalgamating_Business Model updates
- Created relevant Enums
- Updated unit tests ( ongoing )

18977 Model updates for amalgamation and amalgamatiing_business

---

legal-api/tests/unit/services/filings/validations/test_correction_firms.py
legal-api/tests/unit/services/filings/validations/test_registration.py

*Issue #:* /bcgov/entity18954
Changed parameter name and added patcher

18954-fix-broken-tests

---

legal-api/migrations/versions/5238dd8fb805_.py
legal-api/src/legal_api/models/amalgamating_business.py
legal-api/tests/unit/models/test_amalgamating_business.py
legal-api/tests/unit/models/test_amalgamation.py

*Issue #:* /bcgov/entity#18804

18804 correcting data model

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#19006
Sprint release 19.7a

Sprint release 19.7a

---

queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py
queue_services/entity-filer/src/entity_filer/filing_processors/conversion.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py
queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
queue_services/entity-filer/src/entity_filer/utils/utils.py
queue_services/entity-filer/tests/conftest.py
queue_services/entity-filer/tests/unit/__init__.py
queue_services/entity-filer/tests/unit/worker/test_change_of_registration.py

*Issue #:* /bcgov/entity#18501

18501 Filer - change of registration updates

---

legal-api/devops/gcp/clouddeploy-targets.yaml

Update deployment configuration.

---

legal-api/src/legal_api/models/amalgamation.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/services/filings/validations/amalgamation_application.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py

*Issue #:* /bcgov/entity#18978

18978 amalgamatedInto in business response

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#19007
Sprint release 20.1a

190007 Sprint release 20.1a

---

legal-api/src/legal_api/services/filings/validations/amalgamation_application.py
legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py

*Issue #:* /bcgov/entity#19154
- check for duplicate TINGs
- check for at least 2 TINGs
- unit tests

19154 Update TING validation rules

---

legal-api/report-templates/template-parts/business-summary/amalgamations.html
legal-api/report-templates/template-parts/common/style.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#11550
Refer to Yui's comment
1. Solve the spacing issue
2. For a TING company have both amalgamated entities and amalgamated into session, we only keep the amalgamated into session

11550 - fix spacing and TING

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#19198
Bumped version numbers up for release 20.1b

bump version numbers up for release 20.1b

---

legal-api/migrations/versions/5238dd8fb805_.py
legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql

*Issue #:* /bcgov/entity#19013
- updated amalgamation alembic script
- updated database transfer script

19013 Update data migration scripts for amalgamation

---

legal-api/report-templates/template-parts/business-summary/amalgamations.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#19433

19433 amalgamation fix in business summary

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#19553

19553 Bumped version number for release 20.2a

---

legal-api/src/legal_api/models/__init__.py
legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/models/comment.py
legal-api/src/legal_api/models/dc_connection.py
legal-api/src/legal_api/models/dc_issued_business_user_credential.py
legal-api/src/legal_api/models/document.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/models/legal_entity.py
legal-api/src/legal_api/models/request_tracker.py
legal-api/tests/unit/models/test_amalgamating_business.py

*Issue #:* /bcgov/entity#19347
- update models based on #2418 
- some unit test updates

19347 Legal-api - update alternate name model + misc unit test updates

---

queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-MODERNIZED.html

*Issue #:* /bcgov/entity19142
An error was noted on the expiring soon letter. the 4th point on the Option 1 should read "4. Complete an application..."
it currently shows up as

Names letters: Error noted on Expiring Soon letter#19142

---

queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/tests/unit/test_tracker.py

*Issue #:* /bcgov/entity#18803

18803 Add amalgamation tracker

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_application.py

*Issue #:* /bcgov/entity#19043

19043 foreign_corp_num to foreign_identifier

---

legal-api/src/legal_api/resources/v2/business/business.py

*Issue #:* /bcgov/entity19453
- changed draft results to better correct applicationType in MBR 

19453 changed draft results for correct applicationType in MBR

---

legal-api/src/legal_api/resources/v2/business/business.py

*Issue #:* /bcgov/entity#19453

19453 fix key error
