bcgov/lear

coops-ui/Jenkinsfile, coops-ui/Jenkinsfile-DevToTest, coops-ui/Jenkinsfile-TestToProd, coops-ui/package.json
*Issue #:* bcgov/entity#381
Coops UI pipeline work:
- added jest tests to build pipeline
- added lint checking to build pipeline
- added test pipeline (move from dev to test)
- added prod pipeline (move from test to prod)
=> UI pipelines - jest and lint, plus test and prod

legal-api/pre-hook-update-db.sh
*Issue #:* n/a
comment out command line psql, as not in base image
left the psql check in there for future refernce
=> comment out command line psql, as not in base image

legal-api/src/legal_api/schemas/legal_filings.json
*Issue #:* bcgov/entity#385
Added the first cut of the JSONSchema for legal filings.
Contains definitions for address, person, director, filing_header, annual_report, and the filing schema'
=> adding first cut of legal_filings JSONSchema

legal-api/tests/microcks/legal-api.postman_collection.json
Signed-off-by: Lane <JAMLANE@BCGOV>
*Issue #:#467
I added a setup folder that fetches the legal schema and added validation tests to the two get requests. I believe some adjustment will be needed to get this running against the real APIs later, and if we move the schema files.
I also added some invalid request examples.
=> Added schema validation to GET requests

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* n/a
Content header set incorrectly on the examples for microcks, so it was removed.
=> fixed postman examples content length, by removing it

Makefile.template
*Issue #:* n/a
Added a template makefile to the root of the repo.
Changed the legal-api template so that the project directory is a variable.
=> made the project a variable in the Makefile

coops-ui/src/App.vue, coops-ui/src/components/ARSteps/Directors.vue, coops-ui/src/components/ARSteps/RegisteredOfficeAddress.vue, coops-ui/src/components/AnnualReport.vue, coops-ui/src/components/StdHeader.vue, coops-ui/src/views/Home.vue, coops-ui/tests/unit/Directors.spec.ts
*Issue #:* bcgov/entity#547
Added view UI functionality with jest tests; also added basic UI functionality of add and cease from prototype.
This code still includes hard-coded data, which will be removed once hooked up to lear, auth, and payment APIs correctly.
For testing - must have old/fake token in main.ts.
=> Added View Directors functionality plus basic UI for Add and Cease

legal-api/src/legal_api/services/__init__.py
*Issue #:* n/a
added plain __init__.py to the services module
=> make services a module

schemas/src/registry_schemas/schemas/directors.json
*Issue #:NA*
- added both appointment date and cessation date to director schema
- decision made to add these agreed upon by myself, thor and katie
- cessation date can be set to null
=> updated director schema to include appointment/cessation date

legal-api/Makefile
*Issue #:* n/a
- added new targets.
- setup no longer recreates the requirements.txt file
- build-req creates a new requirements.txt of a clean requirements install
=> added new targets. setup no longer recreates the requirements.txt file

coops-ui/package.json, coops-ui/public/config/configuration.json, coops-ui/public/schemas/person.json, coops-ui/src/main.ts, coops-ui/src/plugins/vuelidate.ts, coops-ui/src/router.ts, coops-ui/src/views/AnnualReport.vue
*Issue #:* https://github.com/bcgov/entity/issues/754
This is a Proof Of Concept of JSON Schema Validation using the vue-vuelidate-jsonschema package (which basically configures things for vuelidate).
Please review this PR and offer your opinion on whether / how we should use this to implement validation in the UI using the server-side object schemas ... add appropriate comments to the linked Zenhub ticket.
~~Do not merge this PR at this time... How we will proceed depends on what you guys think of this.~~
**Please accept this merge into a new bcgov branch so we can get back to it some time in the future.**
This PR:
- adds the necessary packages and loads them
- adds 'person' schema file locally into the coops-ui project (for now)
- loads the JSON schema file for …
=> POC for JSON schema validation in UI

coops-ui/public/config/configuration.json, coops-ui/src/App.vue, coops-ui/src/router.ts
*Issue #:* n/a
The issue was actually a mismatch between the auth_url config and the referrer URL from the auth app - one had slash, the other didn't. Changed it in dev config map to fix in dev, changed here also with addition bug fix in related error messages.
=> Fixed auth error - UI app not setting keycloak, bouncing back to auth every time

coops-ui/package.json, coops-ui/src/main.ts
*Issue #:* no ticket for this
- replaced deprecated @babel/polyfill package (see https://babeljs.io/docs/en/babel-polyfill)
- also bumped vue and vue-template-compiler versions to latest
- npm run build passes
- npm run test:unit passes
=> replaced deprecated @babel/polyfill package

coops-ui/package.json, coops-ui/public/config/configuration.json, coops-ui/src/router.ts
*Issue #:* n/a
In coordination with relationships team - removed listener/setter for keycloak token session storage, since the coops app and auth app will now be on same domain, so it will be set by auth app and be available automatically in session storage for coops app.
=> Change token storage

legal-api/tests/postman/legal-api.postman_collection.json, schemas/src/registry_schemas/schemas/business.json, schemas/tests/unit/schema_data.py, schemas/tests/unit/test_filings.py, schemas/tests/unit/test_registry_schema_utils.py
*Issue #:* /bcgov/entity#946
Added lastPreBobFilingTimestamp to schema and Legal API postman tests/examples, to support custom director appointment/cessation dates - specifically preventing conflicting Change of Directors filings.
Note - this is not a required field, so that existing code/examples don't all break. The only call we NEED this in, to support the Change of Directors filings, is the Business GET call.
=> Added lastPreBobFilingTimestamp to schema and Legal API postman tests/examples

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue
*Issue #:* /bcgov/entity#1015
Added actions list (empty) to get past schema validation failure.
This is WIP for the task - the very first step in the implementation, committed only to get past API validation failure based on not matching updated schema.
=> Added actions list (empty) to get past schema validation failure.

coops-ui/src/components/AnnualReport/Directors.vue
Fix for the uneven spacing of appointed/ceased dates in directors component
=> Fix - Appointed/Cease dates are spaced unevenly

legal-api/src/legal_api/reports/__init__.py
*Issue #:* /bcgov/entity#1012
*Description of changes:* Fixed a linter warning about catching all exceptions. No need to do so to return a 500, this is done automatically by the subsystem.
=> Fixed a linter warning - 500s are handled automatically (1012).

entity-filer/.envrc, entity-filer/k8s/templates/entity-filer-deploy.json, entity-filer/pay_filer.py, entity-filer/requirements/dev.txt, entity-filer/src/entity_filer/service_utils/exceptions.py, entity-filer/src/entity_filer/service_utils/service_logger.py, entity-filer/src/entity_filer/worker.py, entity-filer/tests/unit/__init__.py, legal-api/.envrc, legal-api/k8s/templates/legal-api-deploy.json
*Issue #:* /bcgov/entity#1038
- add sentry.io in to track msgs popped off the queue for errors to be managed manually.
- updated test data for actions[]
- updated legal-api to use the Sentry DSN
=> add sentry.io in to track erred queue messages

coops-ui/package.json
- changed the spec for a new (dev dependency) package from git+ssh to git+https
- this is because git+ssh works locally but not on the build server
=> changed package spec from git to https

coops-ui/src/App.vue, coops-ui/src/assets/styles/layout.styl
*Issue #:* Not Applicable
- use position:sticky instead of position:fixed to have browser automatically calculate and handle dynamic header height
- this is because the header may contain a banner (eg, payment processing not available)
- note that 'sticky' is not supported in IE11 so the header will scroll off the screen (which is not really a big deal)
=> added support for dynamic header height (per Jer)

entity-filer/requirements.txt, entity-filer/src/entity_filer/filing_processors/annual_report.py, entity-filer/src/entity_filer/worker.py, entity-filer/tests/integration/test_worker_queue.py, entity-filer/tests/unit/__init__.py, entity-filer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#1171
- last_ar_date column in the businesses table is now set to the 'annualReportDate' provided by the filing
- tests updated to reflect above + schema changes around annual report
=> updated filer for schema changes involving last_ar_date

legal-api/report-templates/annualReport.html, legal-api/report-templates/changeOfDirectors.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#1064
- added director and address info to AR PDF even when unchanged
- added "appointed" and "ceased" sections for directors
- added indicators of changed data ("new" label plus director previous name)
Also:
- bug fix - field name middleName -> middleInitial
NOT covered in this work: 
- "No AGM" filing. Business has not decided what to show in this case. Will be broken out to different ticket. 
- added, ceased director lists plus "new" labels in COD and COA PDFs - waiting on business decision re. how similar or different from AR filing. Will be completed in different ticket.
=> added full director and address info to AR PDF

legal-api/report-templates/annualReport.html, legal-api/report-templates/changeOfAddress.html, legal-api/report-templates/changeOfDirectors.html
*Issue #:* /bcgov/entity#1276
fixed bug - missing certified name in all PDFs - was due to schema change and this fix was missed in other fixes.
=> fixed bug - missing certified name in all PDFs

coops-ui/src/components/AnnualReport/Certify.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/Certify.spec.ts
*Issue #:* /bcgov/entity#1266
*Description of Certify changes:*
- Removed the shadow property fields to simplify the component.
- All the watchers could be removed once above simplification done.
- Added a property for the `currentDate`, so that (1) the component isn't tied to VueX, and (2) the parent component isn't required to have a specific named variable in the store for the current date.
- Added a `valid` event so the parent component knows if the form is complete or not. Will be returned on create so that the parent knows if the properties are valid or not.
- Added unit tests.
*Description of AnnualReport changes:*
- Passing in `currentDate` as a property.
- Added a `certifyFormValid` variable - there shouldn't be any need to store any of these in the store, but leaving the others …
=> Simplify the Certify component and add tests (#1266)

coops-ui/src/main.ts
*Issue #:* /bcgov/entity1345
The subject library import was removed in a previous ticket as it not directly needed for this project, however it is required for a SBC Common Component. This commit restores the library import.
=> imported Vue2Filters library needed for SbcFeeSummary component

coops-ui/src/components/AnnualReport/ARComplete.vue
*Issue #:* N/A
A mixin declaration was missing from the ARComplete component. This did not create an error because this component was not used. This change adds in the missing mixin declaration.
=> added missing mixin declaration

coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#1381
This code change disables all 3 save buttons (on all 3 filing pages) when any of them are in progress. As well, when any save function is already in progress then another save cannot be initiated.
=> prevent double-saving

legal-api/src/legal_api/services/filings/validations/annual_report.py, legal-api/tests/unit/services/filings/validations/annual_report/test_valid_agm_date.py, legal-api/tests/unit/services/filings/validations/annual_report/test_validate_ar_year.py, legal-api/tests/unit/services/filings/validations/annual_report/test_validation.py, legal-api/tests/unit/services/filings/validations/test_validation.py
- legal-api was not letting a user file an AR with an AGM before the 'go-live-date'
- changed to validate based on their last filing (done by checking the last_ledger_timestamp)
=> Validation fix

coops-ui/src/components/Dashboard/TodoList.vue
*Issue #:* /bcgov/entity#1289
For pending payments, allow expansion - shown on (i) click. For draft, disable because menu was causing the expansion, which looked wrong.
=> bug fix - only disable to-do list line expansion for drafts

coops-ui/.env, coops-ui/.env.production, coops-ui/openshift/Caddyfile, coops-ui/openshift/templates/coops-ui-bc.tools.json, coops-ui/openshift/templates/coops-ui-dc.dev.json, coops-ui/openshift/templates/coops-ui-dc.prod.json, coops-ui/openshift/templates/coops-ui-dc.test.json, coops-ui/src/utils/config-helper.ts, coops-ui/vue.config.js
https://github.com/bcgov/entity/issues/1349
1. Public path Vue changes
Used a process.env file so that the public path is not hardcoded vue.config.js 
2. Static assets which are read manually [ie config files etc] need to be read from the same context root. Or else it will cause inconsistencies
3. corrected erroneous extenstion of vue.config.ts to vue.config.js 
4. Openshift changes
For caddy to serve in a context root , the built bundle has to be in a folder with the name of the context root. Changed openshift configs for this.Also caddy rules has to be changed to support context root …
=> deployment of coops application in context root

coops-ui/package.json, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue
*Issue #:* /bcgov/entity#1191
- added schema rules to Registered Office Address to require region=BC and country=CA
- updated sbc-common-components version to include latest changes
=> implemented additional Registered Office Address validation rules

oracle/Jenkinsfile-startup
*Issue #:* /bcgov/entity#n/a
- oracle-forapi pod was restarting with bad sequence number which was causing duplicate ids for new events/directors/addresses
- updated startup oracle pipeline to set the sequences above current max values
=> Oracle pipeline update

schemas/src/registry_schemas/example_data/__init__.py, schemas/src/registry_schemas/example_data/schema_data.py, schemas/src/registry_schemas/schemas/address.json, schemas/tests/unit/test_addresses.py
*Issue #:* /bcgov/entity#1445
Changed addressRegion to allow null values, for the case where region (province) doesn't apply to a country, ie: any country not Canada, USA, and a few others.
**This PR is pointing at story branch address-validation.**
=> Changed addressRegion to allow null values; added more address tests.

coops-ui/src/components/AnnualReport/Directors.vue
*Issue #:* /bcgov/entity#1450
bug fix - director list not loaded correctly when draft loaded - only when no director changes saved in draft.
=> bug fix - director list not loaded correctly when draft loaded

coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue
*Issue #:* /bcgov/entity#1032
Modified the sameaddress method to exclude address type while comparing the addresses
=> Bug fix #1032 - Clicking 'Same as Delivery Address' should not add filing fee

coops-ui/src/registerServiceWorker.ts, coops-ui/src/service-worker.js, coops-ui/vue.config.js
*Issue #:* /bcgov/entity#1225
Created custom service worker
Updated the register service worker to show the confirmation pop up and post the message to the service worker. Added call back to force reload the window once user confirms to update the app.
Updated the vue config to point to custom service worker
Note : This commit is to test whether the confirmation popup is displayed when a new version of the app is available. May need a few iterations to get this working 
=> PWA first commit

coops-ui/src/registerServiceWorker.ts
*Issue #:* /bcgov/entity#1225
Changed the content of the confirmation window
=> Changing the confirm window content

coops-ui/.env, coops-ui/.env.production, coops-ui/public/config/configuration.json, coops-ui/public/config/local-configuration.json, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/utils/config-helper.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#1572
- deleted config for AUTH_URL (this can also be done in OCP config maps -- I think it's obsolete now)
- added VUE_APP_AUTH_URL key to env files
- updated config helper to store URLs accordingly
- updated components that use URLs
- updated unit tests to used more complete config
=> replaced AUTH_URL config with env key

coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
I forgot to rename an env variable in the unit tests, causing them to fail to get the env variable and causing 8 tests to fail. This PR fixes that.
=> fixed typos in unit tests

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/views/Dashboard.vue, coops-ui/tests/unit/Dashboard.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#1117
Reload dashboard when we return too quickly from completed filing.
This covers several scenarios, especially around free/unpaid filings that do not redirect to payment system.
The steps to reproduce and (rough) acceptance criteria - as described solution, not formal AC - are in the ticket.
=> Reload dashboard when we return too quickly from completed filing.

entity-filer/src/entity_filer/service.py, entity-filer/src/entity_filer/worker.py
*Issue #:* n/a
Do not catch error, just log it and allow it to trickle up. When that happens, the message is automatically added back to the queue without need for code (which was causing queue overload).
**NOTE: already running in dev from my branch; when this gets merged, the build config needs to be changed back to lear/master instead of katiemcgoff/branch.** 
=> fix entity filer bug - overloading queue

coops-ui/package.json
This is so everyone can use the latest sbc-common-components (this change was already done in 'release-2.1.0' branch.
=> updated dependency to latest sbc-common-components

coops-ui/package.json, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/components/Dashboard/AddressListSm.vue, coops-ui/src/components/Dashboard/DirectorListSm.vue, coops-ui/src/mixins/countries-provinces-mixin.ts, coops-ui/src/mixins/index.ts, schemas/src/registry_schemas/example_data/schema_data.py, schemas/src/registry_schemas/schemas/address.json, schemas/tests/unit/test_addresses.py
**I have tested locally and this seems to work correctly using the latest sbc-common-components package, as designed.**
*Issue #:* /bcgov/entity#1191, /bcgov/entity#1192, /bcgov/entity#1497
- merging issue 1192 into feature branch
- merging issue 1191 into feature branch
- Changed addressRegion to allow null values; added more address tests.
- fixed mixin usage
- updated package dependency
=> Address validation

coops-ui/package.json, coops-ui/vue.config.js
*Issue #:* /bcgov/entity#1689
A package used by sbc-common-components was not being transpiled (to ES5) and IE11 did not recognize some of the new syntax.
This package was added to coops-ui (as it could be used there in the future and it's only a dev dependency) and Vue was configured to always transpile it. This solves the problem.
=> explicitly added package and forced it to be transpiled

coops-ui/src/App.vue, coops-ui/tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#1750
The stored Entity Founding date was changed from a date to a date-time string, so that it is in the correct format when filing an AR/COD/COA.
=> stored Entity Founding date-time instead of just date

coops-ui/src/registerServiceWorker.ts
*Issue #:* /bcgov/entity#1775
This PR adds a null check for objects to prevent an error in IE11. The service worker/PWA code does not work for IE11 anyway so this doesn't break anything.
=> added code safety check for IE11

coops-ui/package.json
- the sbc-common-component icon issue has been resolved, so coops-ui can now use the latest version
- I verified the changes in sbc-common-components since the previous version we were using (18) and they looks OK locally
- note that /bcgov/entity#1673 will now be testable (I will update the ticket accordingly)
=> updated sbc-common-components dependency

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/mixins/date-mixin.ts, coops-ui/src/store/getters.ts, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#1818, /bcgov/entity#1405
Changes to use local timezone datetime for filing_date and completion_date rather than utc 
Changes to correct the date time in reports
Changes to pass time to receipt
=> Bugfix - Filings completed after 4pm show as the next day, Report has wrong Datetime

colin-api/colin_api/models/business.py, lear-db/test_data/load_coop_2019.py
*Issue #:* /bcgov/entity#1886
Original version assumed AR filing existed but not true for recently-incorporated entities.
This has already been run in DEV (local colin api, running loader pointed to dev postgres).
=> loader - include entities without AR filings.

legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/tests/unit/api/test_business_tasks.py
*Issue #:* /bcgov/entity#1915
bug fix - when no filings exist, use founding year to calculate owed ARs.
=> bug fix - when no filings exist, use founding year to calculate owed ARs.

legal-api/report-templates/template-parts/directors.html
- removed indentation that is the likely cause of a server error when fetching a PDF
=> fixed indent in Directors PDF template

coops-ui/src/components/AnnualReport/Directors.vue
*Issue #:* /bcgov/entity#1824
Allow spaces in name (such as "H. Mary") but do not allow only spaces (" ").
=> UI - allow spaces in director names, but do not allow empty spaces only

coops-ui/tests/unit/Directors.spec.ts
- a line of code had extra spaces, causing a lint error; now fixed
=> fixed a lint error

lear-db/test_data/add_offices.py
Assign office.business_id in one-time script for office creation. Otherwise it's null in office table.
@peter-freshworks please validate - I discovered this by running this script in e2e environment and saw column was all nulls. Whereas in dev the column was filled in. I've made this change and run the script over e2e again and got the results I think should be there.
=> assign office.business_id in one-time script for office creation

coops-ui/src/components/common/SummaryDirectors.vue
* Updated filtering logic on directors list to validate the `actions` property before filtering by it. 
* Should correctly display a list of directors in the Bcomps Annual Report directors summary list.
=> Directors Summary Filtering Update

coops-ui/src/components/StandaloneDirectorChange/CODDate.vue, coops-ui/tests/unit/CODDate.spec.ts
Changing the logic to look at the last AR date and cod date only
Updated tests
=> Changing the logic to look at the last AR date and cod date only

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/resources/business/business_tasks.py
*Issue #:* /bcgov/entity#2071
Paid filings were being returned in the task list as a to-do item. Moved to the get business filings endpoint
=> Paid filings should be returned in filing history, not in task list

Jenkinsfiles/oracle-dev-refresh.groovy, Jenkinsfiles/oracle-forapi-refresh.groovy
- oracle refresh pipelines for dev env
- these will be in gluos-dev so as not to clutter the tools environment and are there to make it easier for devs to refresh the database
=> oracle-refresh pipelines for dev

colin-api/src/colin_api/__init__.py, colin-api/src/colin_api/config.py, colin-api/tests/unit/conf/test_configuration.py
- I think this will fix the issue of the colin-api not building in openshift
- most changes are for the pylint/flake8 errors in the config file (it was out of scope before)
=> fix for failure to run in openshift

queue_services/entity-pay/src/entity_pay/worker.py
*Issue #:* /bcgov/entity#1615
Removed functionality to add failed msg back to queue upon failure. It will end up in sentry anyway, that's enough - having it added back to the queue gets us no good functionality, just bad.
=> Removed functionality to add failed msg back to queue upon failure.

schemas/src/registry_schemas/schemas/voluntary_dissolution.json
- these are failing to come across because there's no info in colin on whether or not they still have liabilities so this flag is never being included in the json
- 1 bcorp pytest is failing from before
=> removed hasLiablities from required list in volunt. diss. schema

coops-ui/src/App.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/StandaloneDirectorChange/CODDate.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/App.spec.ts, coops-ui/tests/unit/CODDate.spec.ts, coops-ui/tests/unit/Directors.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts
*Issue #:* /bcgov/entity#2160, /bcgov/entity#2149
*Description of changes:* 
1. Priority one fixes for
Unable to save filing due to entity founding date not datetime
Error dialog not showing up for filing/ other errors (incorrect attach selectors)
2. Code refactoring
3. Test updates
=> P1 fixes for unable to save filing + error dialog not showing up

legal-api/tests/unit/api/test_business_filings.py, legal-api/tests/unit/api/test_business_tasks.py
*Issue #:* n/a
Mark two unit tests as integration with payment, so they can be skipped correctly.
=> Mark two unit tests as integration with payment, so they can be skipped

coops-ui/public/index.html, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/mixins/date-mixin.ts
*Issue #:* /bcgov/entity#2089
Changes to use a polyfill to get the timezone conversion working in IE11
=> Fix: Empty Filing History + Dashboard not loading after successful payment in IE11

coops-ui/jest.config.js, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/tests/unit/Directors.spec.ts
*Issue #:* /bcgov/entity#2257
- removed inter word spacing validation for director names
- forced sbc-common-components to be transformed in tests (ie, don't ignore it)
=> removed inter word spacing validation for director names

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/interfaces/address-interfaces.ts, coops-ui/src/interfaces/filingData-interfaces.ts, coops-ui/src/interfaces/form-interfaces.ts, coops-ui/tests/unit/Directors.spec.ts
*Issue #:* /bcgov/entity#2271
- only render 1 set of edit forms when editing a director
- fixed syntax for interfaces properties
- fixed unit tests
=> fixed director multiple forms issue

legal-api/src/legal_api/services/filings/validations/change_of_directors.py, legal-api/tests/unit/services/filings/validations/change_of_director/test_validation_basic.py
*Issue #:* /bcgov/entity#2278
- removed the address validation for Directors, that enforced their delivery address to BC
=> removed the address validation for Directors, that enforced their delivery address to BC

coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#2323
Todo list is broken for save as draft for a no agm filing 
Any AR filing for previous year blocks director changes for all future AR filings
Changes to the Todolist to look at the AnnualReportDate instead of AGM date to take care of the no agm scenario
Changes to pass the effective date for Annual Report like Standalone Director filing. The value of effective date will be AGM date for a normal filing / annual report date for a no AGM filing
=> Fixes for release 2.4

queue_services/entity-filer/src/entity_filer/filing_processors/annual_report.py, queue_services/entity-filer/tests/unit/test_worker.py
Filer fix to consider agm date as the last_ar_date of the business. For no agm scenarios last AR date will be the annualReportDate
=> Filer fix to set last AR date correctly

jobs/update-colin-filings/update_colin_filings.py
set colin event id to 0 for filings that tried and failed to be sent across to colin (prevents duplicates getting created)
=> duplicate fail safe for failed filings

coops-ui/src/mixins/resource-lookup-mixin.ts, coops-ui/src/resources/business-config.ts, coops-ui/tests/unit/Directors.spec.ts
*Issue #:* /bcgov/entity#1448
Enable Canadian resident and BC resident rules for Coop (originally thought to be out-of-scope for 1448)
=> enable majority directors rule for coops, fix majority calculation

coops-ui/package.json
*Issue #:* /bcgov/entity#2370
*Description of changes:* Changing common components version to 36. 37 is not stable and has multiple issues that causes build failure
=> Using sbc common version 36 as 37 is not stable and build is failing

coops-ui/package.json, coops-ui/src/components/common/OfficeAddresses.vue
*Issue #:* /bcgov/entity#2482
- Update sbc-common to version 37
- Using sbc common version 36 as 37 is not stable and build is failing
- Updating common components version to 40
- Added Jest flag to fix ts-jest problem
- Updated sbc-common-components to latest (41)
=> merge release 2.5.1 back into master

colin-api/src/colin_api/models/director.py, colin-api/src/colin_api/version.py, legal-api/src/legal_api/version.py, queue_services/entity-filer/src/entity_filer/version.py
- legal-api, colin-api, entity-filer version numbers updated to 2.5.2
- legal/colin updaters don't have version numbers
=> bumped versions

coops-ui/src/App.vue
*Issue #:* /bcgov/entity#2599
- on clicking Exit from "Dashboard Unavailable" dialog, redirect to Businesses page (instead of logging out)
=> changed Exit to redirect to Businesses page

coops-ui/package.json, coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/common/OfficeAddresses.vue, coops-ui/src/enums/filingCodes.ts, coops-ui/src/resources/business-config.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AGMDate.spec.ts, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/OfficeAddresses.spec.ts
*Issue #:* /bcgov/entity#2569
- redesigned and refactored/simplified AGMDate component
- updated testPathPattern for easier cli testing
- updated OfficeAddresses disabled prop to same as Directors component
- updated BCANN filing code (was previous TODO) and its usage
- used enums in business config JSON
- refactored AnnualReport page re: AGM Date props and events
- hid AnnualReport sections that are invalid when AGMDate is invalid
- updated Annual Report Date to Dec 31 (per discussion with Scott, Linda and Cameron W.)
=> changed AGM Date to have no default

coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/AGMDate.spec.ts
*Issue #:* /bcgov/entity#2569
- a "cleanup" commit was omitted from the initial PR and is now included here:
- better initialization of filing codes
- added unit test (+ cleanup)
- explicity set AGM Date to null because API doesn't handle empty string
=> fix for empty string in AGM Date

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/models/filing.py, legal-api/tests/unit/api/test_business_filings_internal.py
*Issue #:* /bcgov/entity#2638
exclude corrections from colin updater; this is a change in legal api in the internal filings GET that returns filings to be sent to COLIN.
=> exclude corrections from colin updater

.sonarcloud.properties
The deprecated directories have been excluded and scanning has been focused on the files that matter the most.
Adding more specific guidance in the sonarcloud properties file so that "red herring" issues are not clouding the feedback. More spcifically, I have excluded the 2 deprecated directories from the scanning scope.
=> Change to configuration to narrow down the scanning scope

.sonarcloud.properties
The paths do not seem to work properly, I want to bring it back to basics and meet the original goal, which was the elimination noise when scanning the deprecated code.
See above, commenting out the source and test locations, leaving only the exclusions.
=> Bring it back to basics but excluded the deprecated code

data-reset-tool/src/data_reset_tool/converter/JsonConverter.py, legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* n/a
Added comments and updated incorp postman tests.
NOTE 1 - when completing this today (Tuesday) they didn't pass *I think* because openshift is shifty.
NOTE 2 - comments cannot be deleted currently by the legal API (existing business rules) so that's not part of data loader. However that means when entities are reset, comments are orphaned. So dev db is going to be messy. Not functionally wrong, just messy.
=> Added comments and updated incorp postman tests.

colin-api/src/colin_api/resources/db.py, colin-api/tests/unit/api/test_directors.py
*Issue #:* /bcgov/entity#3025
COLIN itself does not have any issues with Unicode characters (I was able to locate many records with french characters for example), the issue is that the default encoding for cx_Oracle is ascii. Switching this to utf-8 seems to fix the issue for all operations. Lots of digging for a small fix
=> set default encoding for oracle connections to UTF-8

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/src/legal_api/resources/namerequest.py, legal-api/src/legal_api/services/__init__.py, legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/api/test_business_filings.py, legal-api/tests/unit/api/test_business_tasks.py, legal-api/tests/unit/api/test_name_requests.py
*Issue #:* /bcgov/entity#3102
- Implemented namex service for re-usable code when querying for NR data
- Updated name request proxy endpoint to use namex service
- Added function and logic to validate NR data
- Updated filings endpoint to return empty filings array when business not found
- Updated tasks endpoint to return empty tasks array when business not found
- Added in NR number check for tasks endpoint and return todo item if no draft filing exists
- Added in error handling when NR is invalid to return 403
- Added in a function for specifically creating a todo item for incorporating NR
- Added unit tests to cover the different NR data validations
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
=> 3102 - Incorporate NR todo item

legal-api/src/legal_api/resources/business/business_filings.py
Set the effective date as null if it is not present of if the value is null.  
Currently if the incorporation filing is saved as draft with a future effective date and after resuming if it is changed to immediately effective, the value of the effective date is not cleared from the db. This will result in the immediately effective filing to be treated as a future effective one
=> Effective date change

lear-db/test_data/process_for_parties_fix.md, legal-api/src/legal_api/models/party.py, legal-api/src/legal_api/models/party_role.py, legal-api/tests/unit/models/test_party_role.py, queue_services/entity-filer/requirements/dev.txt, queue_services/entity-filer/src/entity_filer/filing_processors/__init__.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#1891
- added changes for allowing multiple parties with the same exact name across different corps
- tests added to secure this
- added md file to explain the process for data fixing the parties that were possibly copied over incorrectly (as result of them having the exact same names) when the directors table was deleted
=> 1891 handle multiple names

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
The only business attribute that filer updates is the identifier. Some fields like legal name and legal type are empty and the value of the founding date is the default date at the time of initial business record creation
Changes to update business attributes
Open questions
The value of fiscal year end date and last ledger time stamp are also default values. If they have to be updated, what is the value?
=> Update the business record founding date , legal name and legal type

colin-api/src/colin_api/models/corp_party.py
*Issue #:* /bcgov/entity#2672
Had to remove reference to module not available in python 3.6
=> remove __future__ import

legal-api/migrations/versions/54a3fc54a2cf_.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#3536
- added payment_error_type column to filings to capture the the type of payment error used to query error details from pay-api
- added logic to return payment error type on the header so dashboard can fetch the error and display as needed
- added logic to clear out payment error type on successful payment
=> 3536 - BCOL Payment error messages

legal-api/src/legal_api/config.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/utils/legislation_datetime.py, legal-api/tests/unit/api/test_business_filings.py
*Issue #:* /bcgov/entity#3639
- added in legislation datetime utility with helper functions dealing with legislation timezone (future effective dating) to allow for COA to future effective to tomorrow midnight for the legislation timezone
- added in config for LEGISLATION_TIMEZONE (can be overridden through config map params, but I think we can just default to America/Vancouver)
- Fixed COA unit test
- Fixed Payment failed test (Due to BCOL error message changes)
=> 3639 - added in legislation datetime utility with helper functions dealing with legislation timezone (future effective dating)

legal-api/src/legal_api/models/registration_bootstrap.py, legal-api/src/legal_api/resources/business/business.py, legal-api/src/legal_api/services/bootstrap.py, legal-api/tests/unit/services/test_registraion_bootstrap_service.py
*Issue #:* /bcgov/entity#3779
- change corpType on affiliation to TMP, until we have lookups for all filing types
- add NR# to the name field, if an NR is provided
- add error handling for failed affiliations
=> changed corpType to TMP, placed NR# in name if present, updated error handling now that deletes are now available

legal-api/report-templates/template-parts/incorporation-application/completingParty.html, legal-api/report-templates/template-parts/incorporation-application/incorporator.html
… in reports for CP and incorporator
*Issue #:* N/A
Changed all delivery address references to mailing Address in incorporator and CP template parts
Fix to display org name under incorporator
=> Fix in reports

queue_services/entity-filer/src/entity_filer/filing_processors/__init__.py
*Issue #:* /bcgov/entity#4016
remove the word 'Address' in the address key if it exists. It comes from the front end into the filing JSON for formatting reasons, but it is not a valid address type. This is the simplest way to sanitise it.
=> strip out incorrect address type coming from front end

queue_services/entity-emailer/src/entity_emailer/email_templates/BC-BN.html, queue_services/entity-emailer/src/entity_emailer/email_templates/common/initiative-notice.html
*Issue #:* N/A
I added extra "whitespace paragraphs" to the MRAS initiative notice, as is done in the other email templates, to fix the issue of margins not working as expected in Outlook.
=> fixed paragraph whitespace for MRAS initiative notice

legal-api/src/legal_api/services/document_meta.py, legal-api/tests/unit/services/test_document_meta.py
*Issue #:* /bcgov/entity#4107
- if this is a temp registration, get legal type from data instead of Business record
- please ignore SonarCloud code duplication warning
- please ignore failing unit test "test_post_colin_filing" -- it wasn't touched in this PR
=> fixed IA legal type in document list

legal-api/report-templates/incorporationApplication.html
*Issue #:* /bcgov/entity#4104
- fixed classname used for Name Translation in IA/NOA output
- the broken unit test is not due to this code change
=> fixed Name Translations classname

legal-api/report-templates/noticeOfArticles.html, legal-api/report-templates/template-parts/common/style.html, legal-api/report-templates/template-parts/notice-of-articles/resolutionDates.html, legal-api/report-templates/template-parts/notice-of-articles/restrictions.html, legal-api/src/legal_api/models/share_series.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/services/business_details_version.py
*Issue #:* /bcgov/entity#4108
Modified versioned business service to include name translations, resolutions and restriction indicator
Added new template parts for the above
Added a cast to integer for share structure number of shares as the UI is currently passing it as string and "500">"1000" returns true
Minor formatting  fixes
=> Translations, Resolutions and Restriction Indicator in NOA

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#5126
OT* codes are no longer valid for Benefit Companies on the Payment side.
Updated the code to BCFDR for Benefit Company free filing
Updated tests
=> Fixing the free filing  fee code for Benefit company

legal-api/src/legal_api/resources/business/business_filings.py
We should not be looking at the business identifier prefix to identify the corp type in case the legal type is not
present in the business json. We should take that value from the business model.
=> Fix - Default value of corp type if legal type is not present in filing

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#4642
Currently if it is a correction filing it adds the fee for the sub filing types under it. If it is a correction it has a defined fee for each entity type and it should not consider the sub filing types.
=> Fix for corrections adding fee for sub filing type

legal-api/report-templates/template-parts/notice-of-articles/benefitCompanyStmt.html, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/services/business_details_version.py, legal-api/src/legal_api/services/document_meta.py, legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/services/test_document_meta.py
Fix for original certificate not retaining its old name
*Issue #:* /bcgov/entity#5284,/bcgov/entity#5310
Fix for following issues:
- Corrected certificate not present in the documents list for the scenarios
Named to Numbered Company correction
Name correction without an NR
- IA and correction documents not getting listed if there is a company type alteration
- Original certificate not retaining the old business name after correction
- Original label getting appended to the certificate even if there is no name correction
- Check for legal type around benefit company statement in NOA
- Added more tests
=> Multiple Fixes in document list generation for corrections

legal-api/src/legal_api/reports/report.py
The versioned business detail depends on the transaction id and is available only after a filing is complete. For a future effective
filing or immediately after the payment is done, transaction id will not be present in the filing and this causes issue while trying to download the report of a filing in paid status
=> Fix to use the versioned business info only if transaction id is present

queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py
*Issue #:* /bcgov/entity#4606
Fix for not sending the email to completing party for an IA correction
=> Fix for not sending the email to completing party for an IA correction

legal-api/report-templates/annualReport.html
*Issue #:* /bcgov/entity#6443
The AR output needs to use the "AR Filing Year" instead of the AR date, now that AGMs can be held in the year after.
=> fixed coop AR wrong filing year in output

legal-api/src/legal_api/services/filings/validations/alteration.py, legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/services/filings/validations/test_alteration.py
*Issue #:* /bcgov/entity#6902
* Updates `query_nr_number` method to return the response in json.
* Updates the validator to allow Bc company name changes. We will need these for Limited Companies coming into our system.
=> NR name change bug and validator update

legal-api/report-templates/template-parts/alteration-notice/businessTypeChange.html, legal-api/report-templates/template-parts/common/benefitCompanyStmt.html, legal-api/report-templates/template-parts/common/legalNameChange.html, legal-api/report-templates/template-parts/common/nameTranslation.html, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/services/business_details_version.py
*Issue #:* /bcgov/entity#7006
- Benefit company just appears when moving to Benefit Company
- Company Name Translation is showing NONE if nameTranslations is empty. If nameTranslations is not present, do not show section.
- In Change of Company Name just show Name Request Number when there is a value.
- Fix issue in Change of Business Type: When applying strong to text it was showing CairoFont, it is change to bold in span section.
- Fix issue in Notice of Articles template: Not showing benefit company statement and resolution Dates.
=> Changes in alteration notice:

legal-api/src/legal_api/services/filings/validations/common_validations.py, legal-api/tests/unit/services/filings/validations/alteration/__init__.py, legal-api/tests/unit/services/filings/validations/alteration/test_court_order.py
*Issue #:* /bcgov/entity#7038
- Fixed validator bug and added tests for the validator
=> 7038 - Saving an alteration as staff resulting in 500 error (court order related)

.github/workflows/filings-notebook-report-cd.yml, .github/workflows/future-effective-filings-cd.yml, .github/workflows/update-colin-filings-cd.yml, .github/workflows/update-legal-filings-cd.yml
Remove watch rollout step for the Jobs CD.
=> Remove watch rollout step for cronjob CD flows.

legal-api/report-templates/template-parts/common/nameTranslation.html, legal-api/src/legal_api/reports/report.py, legal-api/tests/unit/reports/templates/__init__.py, legal-api/tests/unit/reports/templates/test_name_translations.py
*Issue #:* /bcgov/entity#7006
- Fixed logic to display Name Translations in Alteration Notice
=> Fixed logic to display Name Translations in Alteration Notice

colin-api/requirements.txt, colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/event.py
* Addition of endpoint to retrieve all events specific to a business.  This was specifically created for the data loader so is able to retrieve the event associated with an incorporation application or conversion ledger
* Updated event `/event/<string:corp_type>/<string:event_id>` endpoint to support other corp types.  The way it was implemented previously did not really allow query events for any companies where the corp num did not have an alphabetical prefix
* `FILING_TYPES` in `colin-api/src/colin_api/models/filing.py` was updated to include type codes for Colin specific filing type codes.  This is used by data loader to determine the generic application filing type.  e.g. `incorporationApplication` or `conversion`
* Addition of …
=> 4711 colin api updates for data loader

legal-api/requirements.txt, legal-api/src/legal_api/constants.py, legal-api/src/legal_api/resources/business/business_filings.py
* Added `conversion` to `FILINGS` which is used by other lear components.  Specifically entity filer was updated to use `conversion`
* Updated filings save logic such that historical colin filings are not validated before saving
* Updated filings save logic such for colin filngs so that the filing is pushed to the entity filer queue in the following two scenarios:
* business has epoch lear filing and the currently colin filing being saved is after the epoch lear filing date
* business has no epoch lear filing 
* Updated flask-restx dependency conflict
=> 4711 legal api updates for data loader

legal-api/src/legal_api/models/filing.py
* Add `conversion` filing to FILINGS dictionary in `legal-api/src/legal_api/models/filing.py`
=> 4711 Add conversion filing to FILINGS dictionary in filing model

colin-api/requirements/dev.txt, colin-api/src/colin_api/models/filing.py, data-reset-tool/requirements/dev.txt, jobs/filings-notebook-report/requirements/dev.txt, jobs/future-effective-filings/requirements/dev.txt, jobs/update-colin-filings/requirements/dev.txt, jobs/update-legal-filings/requirements/dev.txt, lear-db/test_data/requirements/dev.txt, legal-api/src/legal_api/services/filings/validations/annual_report.py, queue_services/common/requirements/dev.txt, queue_services/entity-emailer/requirements/dev.txt, queue_services/entity-pay/requirements/dev.txt
- removed the prod.txt install within the dev.txt (causes make setup to install most current versions of everything instead of getting the versions from requirements.txt)
- added one liner to remove email from header if email is empty (was causing a validation error when filings were grabbed from colin-api and then posted to legal-api)
=> make setup fix for local and colin-api fix for null email

colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py
*Issue #:* /bcgov/entity#4391
* Updated Colin API such that completed registrar's notation, registrar's order and court order filings in Lear db not yet in Colin db can be pushed to Colin via Colin updater
=> 4391 Update colin api to support registrar's notation, registrar's order and court order filings

legal-api/src/legal_api/models/filing.py
*Issue #:* based on OPs efforts
set the colin & paper_only flags in the header, based on the Filing settings
=> paper and colin flags should be derived from the Filings entity, not submitted json

legal-api/src/legal_api/services/document_meta.py
*Issue #:* /bcgov/entity#7728
* Update `DocumentMetaService.get_documents` such that when filing dict contains no value for `availableOnPaperOnly` and `inColinOnly`, default value is `False`
=> 7728 fix GET filings endpoint error

legal-api/src/legal_api/models/filing.py
*Issue #:* hot-fix from OPS
- paper-only flag should be set from the Filing entity values
- current state sets the flags from the raw JSON, and it should be from the entity values.
=> paper-only flag should be set from the Filing entity values

legal-api/Makefile, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/utils/run_version.py
*Issue #:* ops hot-fixes
- always include flag availableOnPaperOnly,
- allow missing elements in __is_historical_colin_filing_,
- add back the hash to version header
=> ops hot fixes

legal-api/Makefile, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/utils/run_version.py
*Issue #:* ops
- always include flag availableOnPaperOnly,
- allow missing elements in __is_historical_colin_filing_, 
- add back the hash to version header
=> always include flag availableOnPaperOnly

legal-api/report-templates/template-parts/notice-of-articles/directors.html
*Issue #:* /bcgov/entity#7516
- Changed NOA report to display party.officer.middleInitial instead of party.officer.middleName
=> 7516 - Fixed NOA director's middle name

legal-api/migrations/versions/1fcdb213657d_add_order_details_column.py, legal-api/src/legal_api/models/filing.py, queue_services/entity-filer/src/entity_filer/filing_processors/court_order.py, queue_services/entity-filer/src/entity_filer/filing_processors/registrars_notation.py, queue_services/entity-filer/src/entity_filer/filing_processors/registrars_order.py, queue_services/entity-filer/tests/unit/filing_processors/test_court_order.py, queue_services/entity-filer/tests/unit/filing_processors/test_registrars_notation.py, queue_services/entity-filer/tests/unit/filing_processors/test_registrars_order.py
*Issue #:* /bcgov/entity#7677
*Description of changes:* 
* Add `order_details` column to `filings` table
* Added `order_details` to `filings` model
* Update entity filer for registrar's notation, registrar's order and court order filing such that orderDetails value is now saved to new `filings.order_details` column when filing is processed. 
* Removed code saving orderDetails value to `comment` table for the 3 filing types
* Update entity filer processor unit tests
sample payload of what is returned by GET `/api/v1/businesses/BC0870342/filings`
```
{
"filings": [
{
"filing": {
"business": {
"foundingDate": "2021-02-10T19:51:18.758421+00:00",
"identifier": "BC0870342",
"legalName": "1230084 B.C. LTD.",
"legalType": "BEN"
},
"courtOrder": {
"effectOfOrder": "planOfArrangement", …
```
=> 7677 Fix issue with orderDetails being added to comments table

colin-api/src/colin_api/exceptions/__init__.py, colin-api/src/colin_api/models/__init__.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/models/filing_type.py
Note: this PR was recreated from https://github.com/bcgov/lear/pull/1165 after the `main` branch was created for this repo.  For original review comments, please refer to the initial PR.
* Added support for NOALA filing type code for a GET on filings endpoint. This was preventing the legal updater job from pulling over this type of filing
* Added code to determine corp type of a business at the time of a NOALA filing
=> 4711 updates to get corp type for NOALA filing

colin-api/src/colin_api/version.py, legal-api/src/legal_api/version.py, queue_services/entity-filer/src/entity_filer/version.py
*Issue #:* /bcgov/entity#7537
* update legal-api, colin-api and entity-filer version number to 2.23.0
=> 7537 version number updates for release 2.23.0

colin-api/Dockerfile
* Fix issue where two oracle instant clients were being installed causing sqlplus to error out
=> Fix two oracle instant clients issue

colin-api/src/colin_api/models/filing.py
*Issue #:* /bcgov/entity#7338
* Update insert statement for event table such that event_timestmp is inserted with utc as opposed to pacific time(sysdate)
=> 7338 fix issue where event_timestmp was not being inserted as utc for event table

queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py, queue_services/entity-emailer/tracker/services/message_processing_service.py, tracker-db/tracker_db.sql
*Issue #:* /bcgov/entity#7882
* Update `message_id` field to 60 in `tracker_db.sql`.  Was already updated in alembic migration file but forgot to update `tracker_db.sql`
* Fix message context retrieval logic issues
* Include missed fields that were passed in create message function args but never used
=> 7882 duplicate message tracking bug fixes

queue_services/entity-emailer/tests/conftest.py, queue_services/entity-emailer/tests/unit/__init__.py, queue_services/entity-emailer/tests/unit/test_tracker.py
*Issue #:* /bcgov/entity#8036
* Added tests to verify message tracking works for following test scenarios:
* successfully track processed message
* does not try to re-process processed message
* successfully track failure when exception thrown
* failed message will succeed on retry if original error was a send email exception and email exception no longer thrown
* retry count is properly tracked
=> 8036 duplicate message tracking tests for entity emailer

legal-api/src/legal_api/services/filings/validations/alteration.py, legal-api/tests/unit/services/filings/validations/test_alteration.py
*Issue #:* /bcgov/entity#8984
* Added the Ben Conversion code to the allowable NR types for filing a conversion.
* Updated tests.
=> Lear Alteration Validators: Allow Ben Conversion Nr's

legal-api/requirements.txt
changed to use business-schema-2.15.4 which removes the mandatory AGM date
=> remove mandatory AGM date for AR

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* /bcgov/entity#8915
* Add postman tests to specifically test scenarios where dissolution statement type is required to confirm required and valid dissolution statement type validation is working
=> 8915 Update postman tests to test voluntary dissolution statement validation

legal-api/src/legal_api/core/filing.py
*Issue #:* /bcgov/entity#9762
* Update `_diff` function of Filing class to support returning diff block for correction filings with filing status of "PENDING_CORRECTION"
=> 9762 fix 500 error for fetching pending correction filings

queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY.html, queue_services/entity-emailer/tests/unit/email_processors/test_nr_notification.py, queue_services/entity-emailer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#9703
- modified the nr_before_Expiry email to include legal_name and expiration_date with specific format.
- Updated the test_nr_notification to include new fields.
=> #9703 Revise NR-BEFORE-EXPIRY email

queue_services/entity-emailer/src/entity_emailer/version.py
*Issue #:* /bcgov/entity#9603
* Bumped version num again for emailer to `2.30.0`. The last version bump was incorrect as I realized afterwards that the last lear release used `2.29.0` so updating version num to `2.28.0` would be wrong.
=> 9603 bumped emailer version num to correct version for name release 11.2

legal-api/src/legal_api/core/filing.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* /bcgov/entity#9638
* Verify payment status code before applying a receipt to the documents list to the ledger item. 
* This is to prevent documents or receipts displaying for documents that have not been completed within our system.
=> Verify Payment for Documents

legal-api/src/legal_api/core/meta/filing.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* /bcgov/entity#9924
- added the NOA to the documents list for changeOfDirectors
- limit that to BC & BEN types
- test that it shows for one of the types
- test that it doesn't show for CP business types.
=> add NOA to document list, for BC type corps filing a COD.

legal-api/src/legal_api/core/filing.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py
*Issue #:* /bcgov/entity#10145
* Use the display_name property for Submitter name when NOT redacted.
* Updated unit testing and User Factory method to take firstname and lastname.
=> Submitter Display Name

queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
This is a fix for the dissolution filer failing because it was trying to get business legal type from the filing submission json. 
- Got business legal type from object
=> 9016 - Fix for dissolution filer trying to get legal type from filing json

legal-api/migrations/versions/441a5e6cf682_.py, legal-api/src/legal_api/core/meta/filing.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
Removed special resolution from the co-op voluntary dissolution additional documents list as it is present in the legal filings in 
the filing metadata
Removed the custodial office from the old migration as it is giving an error while running the test. This entry was added in a 
new migration file today.
=> Fix for duplicate outputs

legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/version.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* /bcgov/entity#9286
* add rules and memorandum to Coop IA outputs in additional section
* updated tests
* bumped version num
=> 9286 hotfix for missing memorandum and rules docs in filing documents endpoint for Coop IAs

colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py, colin-api/src/colin_api/utils/__init__.py, colin-api/src/colin_api/version.py
*Issue #:* /bcgov/entity#8388
* Revert code that was originally intended to save to Oracle as UTC.  This turned out to be problematic for legacy systems.  Note: the code should be essentially the same as before.  Original commits that were reverted have been included as follows:
* https://github.com/bcgov/lear/commit/a9c878211cd95275629bc3cda11b2fe7dda91a14
* https://github.com/bcgov/lear/commit/592bfe4b7d723c13891dfecc133959ba58ee9ad9 
=> 8388 Revert code back to saving in pacific time to colin db and converting to UTC for GET calls

colin-api/src/colin_api/utils/__init__.py
*Issue #:* /bcgov/entity#8388
* Updated `convert_to_json_datetime`(pacific to utc conversion) function to be os timezone independent.  In its previous form this function would work locally if the timezone of the environment python was running in was pacific timezone.  In my case, it was and it would work locally.  The colin api pod timezone is set to UTC so this function did not work.  The code has now been updated to ensure to treat the incoming date as a naive date and add the pacific timezone and then convert to a utc datetime string. 
=> 8388 Fixed colin api to return datetimes in UTC

colin-api/src/colin_api/models/filing.py
*Issue #:* /bcgov/entity#10482
* Update `_insert_ledger_text` function to use filing effective date for `ledger_text_dts` field in `ledger_text` table in COLIN db
=> 10482 Update ledger text entries to use filing effective date

legal-api/scripts/manual_db_scripts/2022_jan_6_business_state_update.sql
*Issue #:* /bcgov/entity#10596
Note: as this is a manual script, it does not need to be pushed to test for the voluntary dissolution release to go forward.  
* Add sql script for updating business state.  
* New folder(`/legal_api/scripts/manual_db_scripts`) created to hold manual db scripts that should be run as one off and outside of alembic.
=> 10596 create manual sql update script for existing businesses where state is null

legal-api/src/legal_api/reports/business_document.py
The last AR and AGM date has time stamp of 00:00:00+00. So converting it to Pacific Time Zone will show the previous date. There is no need for converting this date to Pacific Time Zone. Only format needs to be changed
=> Issue fix : Last AR and  AGM date in business summary

legal-api/scripts/manual_db_scripts/2022_jan_31_add_ar_filing_year_to_meta_data.sql, legal-api/src/legal_api/core/meta/filing.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py, queue_services/entity-filer/src/entity_filer/filing_processors/annual_report.py
*Issue #:* /bcgov/entity#10801
* Update filer to include a new property in filing meta data for tracking annual report filing year
* Update legal api GET filing endpoint display logic for annual reports to use new filing meta data property for annual report filing year
* Fix broken legal api ledger AR test
* Manual sql script for updating COLIN and LEAR AR filings to have new annual report filing year property in filing meta data
=> 10801 Updates and datafix script for fixing AR filing history displaying wrong year

queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py, queue_services/entity-emailer/tests/unit/email_processors/test_nr_notification.py, queue_services/entity-emailer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#10311
Before Expiry email display UTC time, set it to actual time
=> 10311 before expiry set datetime correctly

legal-api/report-templates/incorporationApplication.html, legal-api/report-templates/template-parts/common/directors.html, legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/services/business_details_version.py, legal-api/src/legal_api/services/filings/validations/registration.py
*Issue #:* /bcgov/entity#8300
* Update to retrieve legal type from business version table when retrieving display name for ledger items
* Fix IA output header to fix bug where header would display as "Numbered Benefit Company" for LTD IA
* Fixed misc linting error for registration validation
* Fix issue with `common/directors.html` where directors in IA filing were not being displayed
=> 8300 incorrect legal type displayed in ledger and IA output fix

legal-api/src/legal_api/models/address.py, legal-api/tests/unit/models/test_address.py
The data returned by the addresses endpoint must have id. That id will have to be passed back to the API for an edit request.
=> id for addresses

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
*Issue #:* /bcgov/entity#11795
* Fix issue where draft correction was erroring out on no diff block for v2 filings endpoint
=> 11795 Fix issue retrieving draft correction filing via v2 endpoint

tests/data/common/auth_api_utils.ipynb, tests/data/misc/backfill_user_data.ipynb
*Issue #:* /bcgov/entity#11790
The notebook added in this PR for backfilling lear user data fixes a lot of instances where the lear user was missing first name and last name data.  This caused the ledger to fallback to displaying the username for the `filed by` value.
* Added notebook(`/tests/data/misc/backfill_user_data.ipynb`) for backfilling lear user data from auth
* Added `get_user_by_username` function to `auth_api_utils.ipynb`
=> 11790 Add jupyter notebook for backfilling lear user data from auth

data-tool/flows/common/event_filing_service.py, data-tool/flows/common/firm_filing_base_json.py, data-tool/flows/common/firm_filing_data_cleaning_utils.py, data-tool/flows/common/firm_filing_data_utils.py, data-tool/flows/common/firm_filing_json_factory.py, data-tool/flows/common/firm_queries.py, data-tool/flows/common/processing_status_service.py, data-tool/flows/common/query_utils.py, data-tool/flows/config.py, data-tool/flows/custom_filer/__init__.py, data-tool/flows/custom_filer/filer.py, data-tool/flows/custom_filer/filing_meta.py, data-tool/flows/custom_filer/filing_processors/__init__.py, data-tool/flows/custom_filer/filing_processors/filing_components/__init__.py, data-tool/flows/custom_filer/filing_processors/filing_components/aliases.py, data-tool/flows/custom_filer/filing_processors/filing_components/business_info.py, data-tool/flows/custom_filer/filing_processors/filing_components/business_profile.py, data-tool/flows/custom_filer/filing_processors/filing_components/filings.py, data-tool/flows/custom_filer/filing_processors/filing_components/name_request.py, data-tool/flows/custom_filer/filing_processors/filing_components/offices.py, data-tool/flows/custom_filer/filing_processors/filing_components/parties.py, data-tool/flows/custom_filer/filing_processors/filing_components/shares.py, data-tool/flows/custom_filer/filing_processors/registration.py, data-tool/flows/migrate_sp_gp_flow.py, data-tool/flows/tasks/task_utils.py
*Issue #:* /bcgov/entity#11771
* Create Prefect flow(`data-tool/flows/migrate_sg_gp_flow.py`) for data loading SP/GP registrations from COLIN into LEAR.  It has been structured to process other filings in the near future but for now the pipeline only supports registration filings.
At a high level, essentially the workflow does the following:
1. Query all filing events from COLIN postgres db prepared by Richard and David Roberts.  The events will be grouped by corp num.   
2. Clean data associated with each registration filing event sequentially for a given corp num.
3. Create filing json for corp and save filing to LEAR db.
4. Run customized registration filer processor so business is made operational.  An auth entity record is also created during this process. …
=> 11771 Create SP/GP ETL pipeline for processing registration filings

legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/resources/v2/business/business.py, legal-api/src/legal_api/resources/v2/business/business_tasks.py, legal-api/src/legal_api/services/__init__.py, legal-api/src/legal_api/services/compliance/__init__.py, legal-api/src/legal_api/services/compliance/compliance_checks/__init__.py, legal-api/src/legal_api/services/compliance/compliance_checks/compliance.py, legal-api/src/legal_api/services/compliance/compliance_checks/firms.py, legal-api/tests/unit/models/test_business.py, legal-api/tests/unit/resources/v2/test_business.py, legal-api/tests/unit/resources/v2/test_business_tasks.py, legal-api/tests/unit/services/compliance/compliance_checks/__init__.py, legal-api/tests/unit/services/compliance/compliance_checks/test_firms.py
*Issue #:* /bcgov/entity#11912
* Update GET business endpoint to return `complianceWarnings` list property
* Add compliance service to check compliance warnings for SP/GPs
* Update task endpoint to check for compliance warnings and if there are any, populate task list with only the conversion todo
=> 11912 Update GET business endpoint to support compliance warnings

legal-api/src/legal_api/resources/v2/business/business_tasks.py, legal-api/tests/unit/resources/v2/test_business_tasks.py
*Issue #:* /bcgov/entity#11912
* Updated task endpoint to in addition to returning conversion todo when required to also return all other todos.  Originally I tried to implement functionality of how the task endpoint works specific to SP/GPs as a part of the incomplete business info work in this ticket.  But given that it is not as simple as expected, we should groom another ticket to cover this work.
=> 11912 fix tasks endpoint issue not returning required tasks for SP/GPs

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
* Update create invoice logic to grab business mailing address from conversion filing json where available, otherwise query db for it.
=> Fix issue where conversion filing fails when no existing business mailing address

queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py
* Update `update_parties` function in change of registration processor to ignore FE party guids
=> Fix filer where UI party guids causes error to be thrown

legal-api/src/legal_api/core/meta/filing.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* [/bcgov/entity#12199](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12199)
- suppress `Notice of Articles` item for "Correction - Annual Report" in Recent Filing History, for all of the following conditions
- the filing type is `CP`
- the display name is `Correction - Annual Report`
- the document link is for `noticeOfArticles`
=> 12199 Update Doc List: Suppress output for Coop Annual Report Correction for all Coop records

queue_services/entity-filer/setup.cfg, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py, queue_services/entity-filer/src/entity_filer/filing_processors/registration.py, queue_services/entity-filer/tests/unit/filing_processors/test_registration.py
*Issue #:* /bcgov/entity#12845
* Added `pass_code` parameter to `update_affiliation` function in `AccountService` class.  This was needed to pass firm party(partner or proprietor) names as a pass code to the auth api affiliation endpoint
* Updated registration filer processor to use updated `update_affiliation` function in `AccountService` class to pass party name as pass code
* Added test for firm affiliation verification in registration processor 
=> 12845 Fix firm affiliation bug (part 2)

legal-api/src/legal_api/models/business.py, legal-api/tests/unit/models/test_business.py
*Issue #:* /bcgov/entity#12895
Add in   'associationType': self.association_type to business call. 
Example URL:
GET <lear dev>/api/v2/businesses/CP1002552
=> 12895 - Add in associationType for business call for Coop Association Type

legal-api/migrations/versions/8fef256bf5d7_add_middle_name_to_users.py, legal-api/src/legal_api/models/user.py, legal-api/tests/unit/models/test_user.py
*Issue #:* /bcgov/entity#13046
* Add middle name column to user table.  
Note that this is used to support middle name data being loaded from firm filing user data in COLIN.  Currently, new user entries via LEAR only make use of the first/last name fields.  It seems like middle names are entered via either the first or last name field at times.  It was decided in discussion with @rarmitag  not to add the middle name to one of these fields during the data loading process in order to be able to be able to definitively know what the middle name was for the filing user data ported over from COLIN.
* Update user model tests …
=> 13046 Add middle name column to user model to support COLIN firm filing user data

legal-api/src/legal_api/config.py, legal-api/wsgi.py
*Issue #:* n/a
- adding the config to allow postgres to use unix sockets.
- needed config change to allow for deployment to GCP
=> adding postgres config to allow the use of unix sockets

data-tool/flows/common/firm_filing_data_cleaning_utils.py, data-tool/flows/common/firm_queries.py, data-tool/flows/config.py
*Issue #:* /bcgov/entity#13168
* Update pipeline query to make registration related filings between march 15, 2004 and april 8, 2011 to be available electronically. 
* Add `AUTH_SVC_URL` to fix auth related issue
* Fix cleaning error where pipeline cannot handle invalid event timestamp for first firm filing record
=> 13168 Update sp/gp pipeline to set paper only flag to false for registration related filings meeting specific criteria

data-tool/flows/common/firm_filing_json_factory_service.py, data-tool/flows/common/firm_queries.py
*Issue #:* /bcgov/entity#13515
* Fixed bug in pipeline where parties data was being cleared for dissolution filings.  This caused loading errors for subsequent processing of filings for a SP/GP as previous filing party data could not be used to reconstruct the filing history. 
* Refactored to have specific function to populate completing party filing json
=> 13515 Fix FILE_FRCHG event/file type loading issue in SP/GP pipeline

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/resources/v1/business/business_filings.py, legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/tests/unit/core/test_filing.py
*Issue #:* /bcgov/entity#10911
- effective_date is now not overridden by payment date if the effective_date was before the effective date (every time due to date selector in front end)
- When there is NO AGM for an AR the effective_date is defaulted to December 31, of the AR year.
=> 10911 co-op filing AR, director effective dates fix

legal-api/src/legal_api/resources/v2/business/business.py, legal-api/src/legal_api/services/__init__.py, legal-api/src/legal_api/services/bootstrap.py
*Issue #:* n/a
Updated the account lookup for businesses, to return for a new role and for businesses not necessarily affiliated to the calling user.
This supports adding the **accountId** to a business struct, if request by a users with the correct roles
=> update account lookup to return accounts not affiliated with the current user

data-tool/flows/common/firm_filing_json_factory_service.py, data-tool/flows/common/firm_queries.py, data-tool/flows/common/lear_data_utils.py, data-tool/flows/custom_filer/filer.py, data-tool/flows/custom_filer/filing_processors/registration.py, data-tool/flows/migrate_sp_gp_flow.py, data-tool/flows/sp_gp_affiliation_flow.py
*Issue #:* /bcgov/entity#13784
* Update SP/GP pipeline to push contact info to auth when processing registrations
* Update affiliation pipeline to not push contact info to auth if corporation.admin_email has a value.  This is an assumption that the SP/GP pipeline should have pushed the contact info already.
* Fix a bug where a filing processed unsuccessfully would be stuck in PAID state.  PAID state is problematic as other jobs may pick it up such as the future effective date job.  Updated to use PENDING state instead.
* Add more debug logging and error handling states.
=> 13784 SP/GP pipeline update to push contact info to auth and misc updates

data-tool/flows/custom_filer/filing_processors/dissolution.py, legal-api/src/legal_api/models/business.py, legal-api/tests/unit/__init__.py, legal-api/tests/unit/models/test_business.py, queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py, queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py, queue_services/entity-filer/tests/utils.py
*Issue #:* /bcgov/entity#13834
* Update filer to add dissolution date to filing meta data
* Update filer test
* Update custom SP/GP pipeline filer to add dissolution date to filing meta data
* Update business endpoint to return dissolution date in same format as all other places.  i.e. only the date and not timestamp
* Update business json test
=> 13834 Add dissolution date to filing meta data

legal-api/report-templates/template-parts/common/businessDetails.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /
bcgov/entity#13036
bcgov/entity#13833
bcgov/entity#13774
- For change of registration  filings the registration date is set to the business founding date for dashboard outputs.
- Missing BN now displays Not available instead of None
- Middle initial has been added to previous name
=> 13036 13833 13774 Dashboard output fixes

legal-api/src/legal_api/services/bootstrap.py, queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
Experimental deploy to DEV
Send over extra information to make it possible to synchronize affiliations in Auth to point at one entity instead of two entities.
This allows STAFF to use a client's affiliated NR, to register a business and at the end of the process show the same information in both the client's and staff's business dashboards.
Thank you Lekshmi for these changes
=> Multiple affiliation fix 

data-tool/flows/common/affiliation_queries.py, data-tool/flows/common/event_filing_service.py, data-tool/flows/common/firm_filing_data_utils.py, data-tool/flows/common/firm_filing_json_factory_service.py, data-tool/flows/common/firm_queries.py, data-tool/flows/common/lear_data_utils.py
*Issue #:* /bcgov/entity#12918
* Updated SP/GP pipeline to support ADFIRM_NULL filing/event type.  This filing/event type maps to the change registration filing
* Misc update to SP/GP affiliation flow to not try to reprocess FAILED affiliations by default
=> 12918 SP/GP pipeline - add support for ADFIRM events with no filings

legal-api/requirements.txt, legal-api/src/legal_api/version.py
* Cherry picked commit to extend max length of party organization length by using latest schema version
* bumped legal api version num to 2.63.0a for patch release
=> Patch release commits

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/src/entity_filer/filing_processors/registration.py, queue_services/entity-filer/tests/unit/filing_processors/test_registration.py, queue_services/entity-filer/tests/unit/test_worker/test_incorporation.py
*Issue #:* /bcgov/entity#13938
* Update IA and registration filing processor to update bootstrap entity instead of re-creating affiliation and entity.  Note: this bypasses having to delete the existing bootstrap affiliation and entity which was causing a timing issue in some instances for the FE.
* Add & update IA & registration tests
=> 13938 Update IA and registration filing processor affiliation logic

legal-api/report-templates/template-parts/business-summary/parties.html, legal-api/report-templates/template-parts/change-of-registration/partner.html, legal-api/report-templates/template-parts/change-of-registration/proprietor.html, legal-api/report-templates/template-parts/common/businessDetails.html, legal-api/report-templates/template-parts/registration-statement/party.html, legal-api/report-templates/template-parts/registration/party.html
*Issue #:* /bcgov/entity#14071
- show BN15 once received from CRA
- using taxId instead of business.taxId to get the updated business number (business.taxId is coming from version table and the taxId is updated as part of separate transaction) except business summary
- party.tax_id is obsolete. removing from reports (we have a separate cleanup ticket to remove from schema and table)
=> 14071 do not show BN9 in reports

legal-api/requirements.txt, legal-api/src/legal_api/services/filings/validations/common_validations.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/__init__.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py
*Issue #:* /bcgov/entity#14120
* Add parties name validation to IA validation such that BENs and COOPs can only have first and middle name of max length 20
* Add tests for IA party names validation
=> 14120 Update party first and middle name validation for BEN & COOP IAs

legal-api/src/legal_api/services/filings/validations/correction.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/services/filings/validations/test_correction_firms.py
*Issue #:* /bcgov/entity#14182
* Add correction filing specific `validate_naics` function.  This function is a bit different from the generic one used across other filing types as it needs to avoid NAICS validation when the existing NAICS code and/or description have not changed.
* Added tests for correction NAICS validation
=> 14182 Fix NAICS validation issue for firm corrections

legal-api/src/legal_api/models/business.py
*Issue #:* /bcgov/entity#14190
* Add a mapping for legal types to numbered company legal  name suffixes.  This can be extended for other things related to a legal type in the future.  
For the purposes of #14190, this will be used to append the appropriate legal name suffix for numbered companies of legal type BC, BEN, CC and ULC when the IA is processed
=> 14190 Add mapping for numbered company legal name suffixes

queue_services/entity-filer/requirements.txt, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/conftest.py, queue_services/entity-filer/tests/unit/filing_processors/test_conversion.py, queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py, queue_services/entity-filer/tests/unit/test_worker/test_incorporation.py
*Issue #:* /bcgov/entity#14190
* Update to latest schema version
* Added court order processing to IA filing processor
* Added logic to ensure business identifier is retrieved from COLIN for new legal types
* Updated numbered company legal name logic to append legal name suffix using a new map provided in business model
* Update existing IA tests to support new legal types
* Update tests in `test_conversion.py` as they were breaking.  I think these can actually be removed as well as some other tests in `test_incorporation_filing.py` as they either related to syncing back to COLIN or it has to do with the dataloader which is no longer used.  This will need to be addressed in future tickets
* Fixed issue in `conftest.py` where tests only ran successfully every …
=> 14190 Update IA filer processor to support ULC, CCC and BC

colin-api/src/colin_api/models/business.py
*Issue #:* /bcgov/entity#14190
* Revert additions for ULC and CCC legal types in Colin API.  Initially added this thinking it was required for business identifier retrieval/generation for these legal types.  It turns out that "BC" is used for these legal types so these additions are not required.
=> 14190 Revert unneeded colin api change

legal-api/src/legal_api/core/meta/filing.py, legal-api/tests/conftest.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py
*Issue #:* /bcgov/entity#14254
* Update filings document endpoint to support new legal types for IA filing
* Update IA display name to return non-empty value for new legal types
* Update filing ledger and filing documents list tests
* Update `conftest.py` to fix problem where tests would fail every other run when running locally
=> 14254 Update document list and ledger display name for IAs to support ULC, CC and BC

legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#14277
=> 14277 Fix registration app output download issue when business.tax_id is null

legal-api/requirements.txt, legal-api/requirements/dev.txt, legal-api/src/legal_api/models/filing.py, legal-api/tests/unit/models/test_registration_bootstrap.py
*Issue #:* /bcgov/entity#14282
* Updated dependencies to support Prefect 2 which will be used for corps(BC/ULC/CCC) data migration pipeline
* Pinned down flake8 version as latest one results in linting errors
* Fixed broken tests
* Updated JSONB columns in filings model to use `sqlalchemy-json` to resolve issue where partial JSON field value updates weren't being persisted to the database after upgrading `SQLAlchemy` version in `requirements.txt`.  More details of the problem can be found here https://amercader.net/blog/beware-of-json-fields-in-sqlalchemy/
=> 14282 Update dependencies

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#14524
* Fix future effective date serialization error
* Add test to test COA for different entity types and to confirm future effective date exists for entity types that support FED
=> 14524 Fix future effective date serialization error

legal-api/migrations/versions/bddd732a9269_index_by_idp_guid.py, legal-api/src/legal_api/models/user.py, legal-api/tests/unit/models/test_user.py, legal-api/tests/unit/resources/v1/test_business_comments.py, legal-api/tests/unit/resources/v1/test_filing_comments.py, legal-api/tests/unit/resources/v2/test_business_comments.py, legal-api/tests/unit/resources/v2/test_filing_comments.py, legal-api/tests/unit/services/test_flags.py, legal-api/tests/unit/services/utils.py
bcgov/entity#14596
after keycloak migration to gold, sub from jwt token (i.e. keycloak guid) will be changed for users, as it is tied to a specific IDP instance, and idp guid should be used instead to uniquely identify users
=> use idp guid to uniquely identify users

queue_services/entity-bn/src/entity_bn/bn_processors/change_of_registration.py, queue_services/entity-bn/src/entity_bn/bn_processors/dissolution_or_put_back_on.py, queue_services/entity-bn/src/entity_bn/bn_processors/registration.py, queue_services/entity-bn/src/entity_bn/exceptions.py, queue_services/entity-bn/src/entity_bn/worker.py, queue_services/entity-bn/tests/unit/bn_processors/test_change_of_registration.py, queue_services/entity-bn/tests/unit/bn_processors/test_correction.py, queue_services/entity-bn/tests/unit/bn_processors/test_dissolution_or_put_back_on.py, queue_services/entity-bn/tests/unit/bn_processors/test_registration.py
*Issue #:* /bcgov/entity#14844
- introduced `BNRetryExceededException` to handle retry exceeded exception.
- skip messaging `BNRetryExceededException` to Sentry
=> 14844 remove sentry errors

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/v1/business/business_filings.py, legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py, legal-api/tests/unit/services/test_authorization.py
*Issue #:* /bcgov/entity#14978
* Add fee code and allowable filings support for restoration filings(full restoration & limited restoration)
Note: this PR is only for full restoration and limited restoration as still need to determine whether limited restoration extension/conversionFullRestoration will use restoration schema.  Subsequent PR will follow to address remaining two filings.
* Add and update tests
=> 14978 Add fee code and allowable filings support for restoration filings

queue_services/common/src/entity_queue_common/service_utils/service_logger.py
*Issue #:* /bcgov/entity15003
Set default common log level to `ERROR` for the following queue_services:
- entity-bn
- entity-emailer
- entity-filer
- entity-pay
Anyone with access to change the environment variables, can use the `LOG_LEVEL` environment variable to change the log level in containers as needed.  Admittedly, we don't have the flexibility to set the log level for `asyncio` separately from `aiohttp.access`.  Let me know if you see that as a problem.
=> 15003 set common LOG_LEVEL from environment var

queue_services/common/src/entity_queue_common/service_utils/service_logger.py
*Issue #:* /bcgov/entity15003
When LOG_LEVEL not provided, default to `ERROR` string not the integer `logging.ERROR`.
=> 15003 - default to 'ERROR' string not integer

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
* Update create invoice logic to pass filing id.  The pay api will use this to populate the `filingIdentifier` property in the payment queue message that it sends to the entity pay listener.  This will allow entity pay to not require the sleep/retry code it currently has in place as it tries to determine which filing to process by looking for the `filing.payment_id` instead of the `filing.id`.  
=> 15114 Update create invoice logic to pass filing id

queue_services/entity-pay/Makefile, queue_services/entity-pay/requirements.txt, queue_services/entity-pay/requirements/dev.txt, queue_services/entity-pay/setup.cfg, queue_services/entity-pay/src/entity_pay/worker.py, queue_services/entity-pay/tests/conftest.py, queue_services/entity-pay/tests/integration/test_worker_queue.py, queue_services/entity-pay/tests/integration/utils.py, queue_services/entity-pay/tests/unit/test_worker.py
NOTE: do not merge until pay api updates the queue message to populate the `filingIdentifier` field with the filing id.
* Update entity pay to use `filingIdentifier` and `corp_type_code` fields from incoming payment token. 
* Remove sleep/retry logic as using filing id should always be findable as opposed to the original implementation which used the payment id. 
* Add `is_processable_message` function to only look at relevant queue messages
* Add/update tests
* Update linting config and fix linting issues
=> 15114 Update entity pay to support payment queue message with filing id and corp type code fields

queue_services/entity-bn/src/entity_bn/bn_templates/create_program_account_request.xml
*Issue #:* bcgov-registries/ops-support/issues/2180
- include owner when businessNumber is unavailable
- Limit length of organizationName to 30
=> 2180 include owner when businessNumber is unavailable

jobs/filings-notebook-report/notebookreport.py
*Issue #:* /bcgov/entity 2247
All notebook reports (including Namex, LEAR, PAY notebook reports) were sent but didn't deliver to the receivers. The reason for this is that the contents in the email body were filter by the email server. Need to update codes to fix this issue.
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/gh/bcgov-registries/ops-support/2247
=> To fix all notebook reports Sent but not delivered Issue#2247

legal-api/src/legal_api/services/filings/validations/restoration.py, legal-api/tests/unit/services/filings/validations/test_restoration.py
*Issue #:* /bcgov/entity#15479
* Update restoration NR validation logic to not validate NR block when there is no `nrNumber` provided in filing json for a NR.  This follows the logic used for corrections.
* Added tests
=> 15479 Fix NR validation logic for restorations

legal-api/report-templates/template-parts/restoration-application/approvalType.html, legal-api/report-templates/template-parts/restoration-application/nameRequest.html, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/utils/legislation_datetime.py
*Issue #:* /bcgov/entity#14642
* Updated approval type wording
* Updated mapping of gazette published date and notice of app mailed date.   published date and notice of app mailed date should have been swapped.
* Updated text to support different legal types in NR block when NR number not provided.
* Fixed incorrect expiry date
=> 14642 Update restoration application outputs based on UXA feedback

legal-api/report-templates/template-parts/restoration-application/nameRequest.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#14642
* Update numbered legal name suffix to match what filer uses when creating a numbered corp
=> 14642 Update numbered legal name suffix used for restoration application outputs

legal-api/src/legal_api/services/filings/validations/restoration.py, legal-api/tests/unit/services/filings/validations/test_restoration.py
*Issue #:* /bcgov/entity#14672
* Update NR validation logic for restorations to not require a NR block for limited restoration extensions
* Add NR tests for limited restoration extensions and convert limited to full restorations
=> 14672 Update restoration validation logic

legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/reports/business_document.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* /bcgov/entity#15589
=> 15589 - Backend changes for SR memorandum update.

legal-api/report-templates/template-parts/restoration-application/approvalType.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#15958
* Fix restoration application output for extensions to display "Not Applicable" instead of "None" for the two dates when approval type = "Registrar"
* Remove bold style for two dates
=> 15958 Fix restoration application output bug

legal-api/src/legal_api/reports/business_document.py
*Issue #:* /bcgov/entity#14953
* Update to retrieve expiry date from `filing.meta_data` for business summary.  This is the same approach that was used for displaying expiry dates for restoration application
=> 14953 Fix business summary expiry date issue

legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/services/test_authorization.py
*Issue #:* /bcgov/entity#16049
* Updated to return administrative and voluntary dissolution in allowable actions for staff users
* Updated to return voluntary dissolution in allowable actions for general users
* Updated to block dissolution actions for staff/general users when there is missing required business info for a firm.  i.e. a conversion filing is req'd for the firm
=> 16049 Update allowable actions to allow dissolution filings for firms

queue_services/entity-filer/src/entity_filer/filing_processors/consent_continuation_out.py, queue_services/entity-filer/tests/unit/filing_processors/test_consent_continuation_out.py
*Issue #:* /bcgov/entity#15045
fix `consentcontinuationout` variable name as mixed case
=> 15045 Fix CCO Filer Outstandng Issue

legal-api/scripts/manual_db_scripts/2023_may_25_legal_name_updates.sql
*Issue #:* /bcgov/entity#15529
* part 1 of legal name migration script to migrate legal name data for firms to `alternate_names`/`alternate_names_version` tables.  This script will be updated as other data migration work for other tables is worked on.
* other misc updates in `legal_entities`/`legal_entities_version` table to ensure version history can be re-created
**Example of before/after migration script run for a GP with multiple operating name changes.**
_Before script run_
_After script run_
=> 15529 legal name data migration script - part 1

legal-api/src/legal_api/core/filing.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* /bcgov/entity#16121
- the only output document for continuation out for corps is receipt
- add unit tests
=> 16121 Legal API - List of Outputs - Continuation Out for Corporations

legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/filing.py
* Update logic for returning business response json such that logic for determining if corrections or court orders exist does not require pulling back all filings for a given business.  Added a static function to filings model to just perform a query that returns a scalar value.
=> Performance tweaks for retrieving business object

legal-api/scripts/manual_db_scripts/2023_may_25_legal_name_updates.sql
*Issue #:* /bcgov/entity#16201
This PR is mainly to get the legal name changes migration script updates merged into the `dev_legal_name_changes` branch for storage purposes at this point in time.
Some of the work in this migration script will need to be re-worked in the near future.  In particular, with us removing sqlcontinuuum, the versioning aspects of the script will need to be updated to use the new db versioning model.
As such, this PR does not need to be reviewed in detail.  Another PR in the future will have these same changes adapted for the new db versioning model.
* Added migration sql to existing legal name changes migration script to:
*  Migrate parties/parties_version entries to legal_entities/legal_entities_version or …
=> 16201 legal name changes migration script for party_roles & parties tables

legal-api/migrations/versions/004f7558063f_second.py, legal-api/migrations/versions/3d8eb786f4c2_add_coop_firm_sequence.py, legal-api/scripts/manual_db_scripts/legal_name_change/README.md, legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql, legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear_after.sql, legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear_before.sql, legal-api/src/legal_api/models/legal_entity.py
*Issue #:* /bcgov/entity#16202
* Added scripts to transfer data from old to new data model.  The new data model contains the new legal name changes as well as the new versioning approach. 
* Added readme file to provide instructions for migrating data to new model 
* misc alembic and model updates that were required to successfully apply the alembic scripts to a new empty LEAR database
**_Examples of what the data looks like for various tables after being migrated from old to new LEAR db._**
**legal_entities/legal_entities_history**
**addresses/addresses_history**
**share_classes/share_classes_history**
**party_roles/party_roles_history**
**parties/parties_history**
**Output from running migration scripts using current Dev db as source database:**
``` …
```
=> 16202 Add script for migrating data from old to new LEAR data model

queue_services/entity-emailer/q_cli.py
* Fix import order issue that was causing emailer `q_cli.py` to error out when called. 
=> Fix emailer q_cli

queue_services/entity-emailer/src/entity_emailer/config.py, queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py, queue_services/entity-emailer/src/entity_emailer/worker.py, queue_services/entity-emailer/tests/unit/test_tracker.py
*Issue #:* /bcgov/entity#16730
-  Add a way to dynamically configure number of retries for emailer. It need to add a new variable `MSG_RETRY_NUM` at `.env`. Note that the default number of retries is 5.
- Update unit test
=> 16730 Dynamically configure number of email resending

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/bcregistry-libraries.txt, queue_services/entity-filer/src/entity_filer/filing_processors/correction.py, queue_services/entity-filer/tests/unit/test_worker/test_correction_conversion.py
*Issue #:* /bcgov/entity#16858
The conversion local correction will need to move to "PENDING_CORRECTION" status as well
=> 16858 Set Correction Filing Status as PENDING_CORRECTION

legal-api/scripts/manual_db_scripts/legal_name_change/README.md, legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql, legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql, legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear_after.sql, legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear_before.sql
*Issue #:* /bcgov/entity#16901
* Updated scripts to add/drop constraints instead of disabling/enabling triggers.  Google Cloud SQL databases do not allow disabling of triggers easily.  
* Updated README such that `transfer_to_near_lear_after.sql` is run as last step.
* Changed ordering of table transfers in `transfer_to_new_lear.sql` to reduce adding/removal of constraints.
* Added additional tables to sequence updates as well as updated sequence updating logic to handle edge case.
Note that due to there being orphaned data in dev/test/prod databases, not all dropped constraints could be added back in the `transfer_to_new_lear_after.sql` script.  This issue will go away once the cleanup orphaned data script is created and applied via the work in #16902.  
As an …
=> 16901 Update db migration scripts to work with GCP loads

data-tool/flows/custom_filer/filing_processors/correction.py, legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/services/document_meta.py, legal-api/tests/unit/models/test_filing.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py, legal-api/tests/unit/services/test_document_meta.py, python/common/business-registry-model/src/business_model/models/filing.py, python/common/business-registry-model/tests/models/test_filing.py, queue_services/entity-filer/src/entity_filer/filing_processors/correction.py, queue_services/entity-filer/tests/unit/test_worker/test_worker.py
*Issue #:* /bcgov/entity#17162
- Added a comment to `parent_filing_id` column in filings model to indicate that this should no longer be used for correction filings.
- Added comments for all references to `parent_filing` indicating that corrections should no longer use this and it should be removed in the future.
=> 17162 Add warnings in code to flag obsolete corrections code

queue_services/entity-emailer/devops/vaults.json, queue_services/entity-emailer/src/entity_emailer/config.py, queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY.html, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-EXPIRED.html
*Issue #:* [/bcgov/entity/17214](https://github.com/bcgov/entity/issues/17214)
*Description of changes:* update letter contents based on https://preview.uxpin.com/86ca5ddbe4d40318d3395577c17d4a692946fd27#/pages/163300702/simulate/no-panels
=> Sre emails

legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py, queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py, queue_services/entity-emailer/tests/unit/email_processors/test_correction_notification.py
*Issue #:* [/bcgov/entity17348](https://github.com/bcgov/entity/issues/17348)
=> 17348 - Change SR correction to be consistent with other correction filings

legal-api/poetry.lock, legal-api/src/legal_api/models/colin_update.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/models/legal_entity.py, legal-api/src/legal_api/resources/v2/business/__init__.py, legal-api/src/legal_api/resources/v2/business/business_filings/__init__.py, legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/src/legal_api/resources/v2/business/internal_services.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py, legal-api/tests/unit/resources/v2/test_business_filings/test_internal.py
*Issue #:* /bcgov/entity#17330
* Moved existing v1 internal endpoints to v2.  The internal endpoints are still needed by BE jobs like update legal filings, update colin filings and future effective date jobs.
* Moved internal endpoint tests from v1 to v2
* Fixed misc broken tests
Internal endpoint testing results:
=> 17330 Add internal endpoints to v2

legal-api/requirements.txt, legal-api/src/legal_api/services/filings/validations/correction.py, legal-api/tests/unit/services/filings/validations/test_correction_special_resolution.py
*Issue #:* /bcgov/entity#16978
- Updated to include validation for special resolution corrections.
- Added tests to ensure:
- if no parties list is provided, validation fails
- if parties is an empty list, validation fails
- if only completing party is included in parties list, validation fails indicating at least 3 directors are req'd
- if less than 3 directors is included in parties list, validation fails
=> 16978 Added extra validation to special resolution correction

colin-api/src/colin_api/__init__.py, colin-api/src/colin_api/errorhandlers.py, colin-api/src/colin_api/resources/__init__.py
*Issue #:* /bcgov/entity#17443
* Register error handlers directly against flask restx api object.  Registering against flask app resulted in errors not being picked up and a generic 500 internal server error would be returned for things like auth errors.
=> 17443 Update error handling to work properly for auth exceptions and other unhandled exceptions

jobs/sftp-icbc-report/requirements.txt, jobs/sftp-nuans-report/requirements.txt
*Issue #:* /bcgov/entity: 17739
Both sftp-icbc-report and sftp-nuans-report were broken after Pimento patched last weekend. Fixed the broken 
=> sftp-icbc-report and sftp-nuans-report broken on PROD#17739

jobs/update-legal-filings/update_legal_filings.py
*Issue #:* /bcgov/entity#17447
* Remove most of the logging that was added/used to determine why calls to colin api with auth turned on was not working.  Issue turned out the  image pull policies in the cronjob.yaml files in update-colin-filings and update-colin-legal filings job were not set to "always".
=> 17447 Remove unnecessary logging

colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/version.py
*Issue #:* /bcgov/entity#15978
=> colin-api: good standing bug fix

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql, legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql
*Issue #:* /bcgov/entity#18139
* Updated temp tables in `legal_name_updates.sql` to not use `CREATE TEMP`
* Updated `transfer_to_new_lear.sql` to use fewer threads for specific tables 
=> 18139 Small tweaks to legal name conversion scripts for larger datasets

legal-api/requirements.txt, legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/services/test_authorization.py
*Issue #:* /bcgov/entity#18026
-  Added Allowable Change item for filing type = `agmLocationChange`
- Applicable only to company types - BC Ltd., BEN, ULC, CCC
- Filing is not allowed when one or more of following is true for business
- Business is in "Not in Good Standing" state
- Business is frozen
- Business has a pending or draft filing
- Created Unit Tests
Note: The unit tests are currently blocked by tickets in progress.
=> 18026 Add allowable actions for AGM location change

legal-api/src/legal_api/resources/v2/business/business_directors.py, legal-api/tests/unit/resources/v2/test_business_director.py
*Issue #:* /bcgov/entity#17340
Revert remove mailingAddress for directors for CP.
=> 17340 - Revert remove mailingAddress for directors for CP.

legal-api/src/legal_api/services/filings/validations/alteration.py
Add in BECV, I believe this was new by Eve to fix the data for an alteration NR.
https://github.com/bcgov/entity/issues/18286
=> 18286 - Add in BECV - NR for Benefit to Limited Name Change is not working

queue_services/entity-emailer/src/entity_emailer/config.py, queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-COLIN.html, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-MODERNIZED.html, queue_services/entity-emailer/tests/unit/email_processors/test_nr_notification.py, queue_services/entity-emailer/tests/unit/test_worker.py
*Issue #:* https://github.com/bcgov/entity/issues/17214
*Description of changes:* Most recent uxpin design splits email contents into 3 groups: modernized/colin/neither(paper form workflow). Need to provide users with different instructions for 'expiring soon' NRs depending on which type of legal entity NR is for (i.e., which group it is in)
=> 17214 -add 3 versions of expiry email: modernized, colin, neither

legal-api/gunicorn_config.py, legal-api/gunicorn_server.py
*Issue #:* /bcgov/entity#18284
* Add pre-fork server hook to gunicorn config such that loading of each worker process is staggered by 5 seconds.  This works around a traction api token retrieval issue where back to back token retrievals with less than 2 seconds produces invalid tokens.
=> 18284 Add pre-fork server hook to gunicorn config

legal-api/report-templates/letterOfAgmExtension.html, legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py, legal-api/tests/unit/services/test_authorization.py
*Issue #:* /bcgov/entity#18370
- Created initial template file for "Letter of AGM Extension" 
- Changed filing display name to "Request for AGM Extension"
**NOTE: implementation and logic of the letter to be implemented by the agm extension outputs ticket bcgov/entity#17931**
=> 18370 Fix list of outputs AGM extension

queue_services/entity-emailer/src/entity_emailer/config.py, queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-SO.html, queue_services/entity-emailer/src/entity_emailer/version.py
*Issue #18240 https://github.com/bcgov/entity/issues/18240
Updating/adding nr expiry letters for societies
=> 18240_Expiring_Emails

legal-api/src/legal_api/decorators.py
Cherry pick 401/500 fix(#18578) into release-2.94.0 branch
=> fix: traction auth decorator (#2308)

legal-api/src/legal_api/decorators.py, legal-api/src/legal_api/models/__init__.py, legal-api/src/legal_api/models/dc_connection.py, legal-api/src/legal_api/models/dc_issued_business_user_credential.py, legal-api/src/legal_api/models/dc_revocation_reason.py, legal-api/src/legal_api/resources/v2/business/business_digital_credentials.py, legal-api/src/legal_api/services/digital_credentials.py
*Issue #:* /bcgov/entity#18474
* Will only try to delete a record in Traction if it exists (prevents 404 and subsequent 500 errors from Traction)
* Adds connection state enums (following DRY pattern)
* Adds ability to vary revocation reason
* Adds helper class to be re-used with queueing service in #2299 
* Uses walrus operator for code legibility
=> fix: 404 errors from Traction when revoking or replacing a credential

queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-COLIN.html, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-MODERNIZED.html, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-SO.html, queue_services/entity-emailer/src/entity_emailer/version.py
*Issue : #2306  https://github.com/bcgov/entity/issues/18240
updated condition
=> 18240-Expiring-Soon-Emails

queue_services/entity-emailer/src/entity_emailer/email_processors/nr_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-COLIN.html, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-MODERNIZED.html, queue_services/entity-emailer/src/entity_emailer/email_templates/NR-BEFORE-EXPIRY-SO.html
*Issue #:* /bcgov/entity#18240
- Moving the Names team commit to the release branch that Sev created
=> 18240 - Fixed Expiring Soon Emails

legal-api/src/legal_api/decorators.py, legal-api/src/legal_api/resources/v2/business/business_digital_credentials.py, legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/resources/v2/test_business_digital_credentials.py, legal-api/tests/unit/services/test_authorization.py, legal-api/tests/unit/services/test_digital_credentials.py
*Issue #:* /bcgov/entity#18688
* adds a feature flag and decorator to check that business has access to digital credentials
=> feat: digital credentials decorator

legal-api/report-templates/template-parts/correction/rulesMemorandum.html, legal-api/src/legal_api/core/filing_helper.py, legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/services/filings/validations/correction.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py, queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/special_resolution_helper.py, queue_services/entity-emailer/src/entity_emailer/email_templates/CP-SR-CRCTN-COMPLETED.html, queue_services/entity-emailer/tests/unit/__init__.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/rules_and_memorandum.py, queue_services/entity-filer/tests/unit/test_worker/test_correction_special_resolution.py
*Issue #:* [/bcgov/entity18495](https://github.com/bcgov/entity/issues/18495)
=> 18495 - Add Memorandum Update to COOP Correction - Update Filer, Legal-API, Emailer

legal-api/src/legal_api/core/filing_helper.py, queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/CP-SR-CRCTN-COMPLETED.html, queue_services/entity-emailer/tests/unit/email_processors/test_correction_notification.py
*Issue #:* [/bcgov/entity18495](https://github.com/bcgov/entity/issues/18495)
=> 18495 - Add Missing Memorandum PDF to Emailer

legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/services/test_authorization.py
*Issue #:* /bcgov/entity#18784
* Add PAID status to allowable actions blocker check for FED pending dissolution filings
* Update allowable actions config for amalgamation to explicitly pass in dissolution sub-type.  If this was't passed in, the underlying db query filters dissolutions out entirely
* Update unit tests to include dissolution sub-type and PAID status
* Created `FilingTypesCompact` in core filing to reduce code duplication that was being flagged by sonarcloud
* Updated `ALLOWABLE_FILINGS` to be returned in a function to access `FilingTypesCompact`
=> 18784 Include PAID status in allowable actions blocker check for FED pending dissolution filings

legal-api/Makefile
currently linting/tests are failing in gtihub actions due to makefie  failing to find requirements.txt in relative path
=> fix absolute path for requirement.txt in makefile

legal-api/report-templates/amalgamationApplication.html, legal-api/report-templates/certificateOfAmalgamation.html, legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* /bcgov/entity#18801
- Add list of documents
=> 18801 - add list of documents for amalgamation

legal-api/src/legal_api/core/filing.py, legal-api/tests/unit/core/test_filing_ledger.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py
*Issue #:* /bcgov/entity#18490
=> 18490 Add displayLedger flag

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/bcregistry-libraries.txt, queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_application.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/test_worker/test_amalgamation_application.py
*Issue #:* /bcgov/entity#18804
=> 18804 Filer - Regular Amalgamations

legal-api/src/legal_api/resources/v2/business/business.py, legal-api/src/legal_api/services/__init__.py, legal-api/src/legal_api/services/authz.py, legal-api/src/legal_api/services/filings/validations/amalgamation_application.py, legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py
*Issue #:* /bcgov/entity#19374 and /bcgov/entity#19375
=> 19374 & 19375 amalgamation validaton fixes

legal-api/report-templates/businessSummary.html, legal-api/report-templates/template-parts/business-summary/amalgamating.html, legal-api/report-templates/template-parts/business-summary/amalgamations.html, legal-api/report-templates/template-parts/business-summary/stateTransition.html, legal-api/src/legal_api/reports/business_document.py
*Issue #:* /bcgov/entity#11550
- modify TED Business Summary PDF
- modify TING Business Summary PDF
=> 11550 - AmalgamaTING and TED Business Summary PDF

queue_services/entity-emailer/requirements.txt, queue_services/entity-emailer/src/entity_emailer/email_processors/amalgamation_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/AMALGA-COMPLETED.html, queue_services/entity-emailer/src/entity_emailer/email_templates/AMALGA-PAID.html, queue_services/entity-emailer/src/entity_emailer/version.py, queue_services/entity-emailer/src/entity_emailer/worker.py, queue_services/entity-emailer/tests/unit/__init__.py, queue_services/entity-emailer/tests/unit/email_processors/test_amalgamation_notification.py
*Issue #:* /bcgov/entity#18803
=> 18803 Add amalgamation email

legal-api/src/legal_api/reports/business_document.py
*Issue #:* /bcgov/entity#11550
Back to Yui's comment, remove "Amalgamating Corporations Information" section, only keep "Amalgamated Into" section for a business that is previously TED and then TING now
=> 11550 - remove amalgamating information section for TING

legal-api/migrations/versions/004f7558063f_second.py, legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
*Issue #:* /bcgov/entity#19346
* Addition of following columns to alternate_names/alternate_names_history tables
* business_start_date
* dissolution_date
* state
* state_filing_id
* admin_freeze
* last_modified
* Addition of required FKs and indexes to  alternate_names/alternate_names_history tables
*  Add alternate_name_id column to following tables and corresponding FK entry
* comments
* request_tracker
* filings
* dc_connections
* dc_issued_business_user_credentials
* documents/document_versions
* Misc cleanup of temp functions + extensions created by migrations scripts
=> 19346 Update alternate_names and other tables + misc script updates

legal-api/src/legal_api/resources/v2/business/business.py, legal-api/tests/unit/resources/v2/test_business.py
*Issue #:* /bcgov/entity#19453
- added legalName field to draft_results to link with auth-api
=> 19453 added legalName field to draft_results to link with auth-api

legal-api/migrations/versions/004f7558063f_second.py, legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
*Issue #:* /bcgov/entity#19346
* Update scripts to populate new `alternate_names` fields
* Update scripts to re-link various records to `alternate_names` record for SP scenarios
* Update scripts to remove SP records in LE table that are no longer required
* Added `colin_entity_id` to `alternates_names` in alembic script to support SP DBA scenario where firm owner is not in LEAR
Note that versioning entries still needs some work.  Will be taking care of that in another ticket
=> 19346 Update migration script to populate new alternate_name fields + misc script updates

legal-api/src/legal_api/version.py
*Issue #:* /bcgov/entity#19193
Currently, the meta endpoint for the GCP endpoint returns the following: 
We're hoping that after this PR is merged, the CD will automatically run and the meta endpoint will return 2.100.0 for the legal-api version
=> 19193 - Bumped legal api version to test GCP CD

legal-api/src/legal_api/resources/v2/business/business.py
*Issue #:* /bcgov/entity#19816
- Updated POST /search endpoint to work with alternate names.
- For the POST /businesses endpoint:
- It does not appear to use `LegalEntity` or `AlternateName` specific code (and neither does the `RegistrationBootstrapService` which is used in this endpoint), so no updates were made. 
- When testing it seems to work fine up until the `auth_url` POSTs in [`create_affiliation`](https://github.com/bcgov/lear/blob/feature-legal-name/legal-api/src/legal_api/services/bootstrap.py#L137). It probably fails here because I do not have an accountId and access token combo that work together for the auth requests. It should be fine anyway since that is the last step before saving the filing (which is already updated).
**Tests**
POST …
=> 19826 Update remaining business endpoints to work with alternate name

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
*Issue #:* /bcgov/entity#19685
- If owner of SP DBA does not match a LEAR business, a colin entity is now created and the DBA is owned by the colin entity
- If a non-person partner entry for a GP does not match a LEAR business, a colin entity is now created and the entity role correctly references the colin entity id.
- Verified changes (below). Please let me know if I'm missing something.
=> Updated migration script to fix unmatched firm owner data

legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/resources/v1/business/business_filings.py, queue_services/entity-emailer/requirements.txt, queue_services/entity-emailer/requirements/bcregistry-libraries.txt, queue_services/entity-emailer/src/entity_emailer/email_processors/amalgamation_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/AMALGA-PAID.html, queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-information.html, queue_services/entity-emailer/tests/unit/__init__.py, queue_services/entity-emailer/tests/unit/email_processors/test_amalgamation_notification.py
*Issue #:* /bcgov/entity#19904
=> 19904 email updates for amalgamation application

legal-api/migrations/versions/5238dd8fb805_.py, legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql, legal-api/src/legal_api/models/amalgamating_business.py, legal-api/src/legal_api/models/amalgamation.py
*Issue #:* /bcgov/entity#19934
- change `foreign_corp_num` column name to `foreign_identifier` in `amalgamating_businesses` table
- change `amalgamating_business` table name to `amalgamating_businesses` and `amalgamation` to `amalgamations` and corresponding columns in those two tables
- update `transfer_to_new_lear.sql`
For now `amalgamations` table looks like 
`amalgamating_businesses` table looks like 
=> 19934 - bring in latest amalgamation table changes

queue_services/entity-filer/src/entity_filer/filing_processors/put_back_on.py, queue_services/entity-filer/tests/unit/filing_processors/test_put_back_on.py
*Issue #:* /bcgov/entity#15285
Post deployment script to update existing business with state_filing_id:
```
with business_with_pbo as (
select f.business_id from public.filings f
join public.businesses b on b.id = f.business_id
where f.filing_type='putBackOn' and b.state = 'ACTIVE' and b.state_filing_id is null
),
last_pbo_filing as (
select f.business_id, f.id, f.filing_type, rank() over (partition by f.business_id order by f.filing_date desc, f.effective_date desc) as r
from public.filings f 
where f.business_id in (select business_id from business_with_pbo) and f.filing_type='putBackOn'
)
update public.businesses b set state_filing_id = f.id
from public.filings f
where f.id in (select id from last_pbo_filing where r = 1) and f.business_id = b.id;
```
By …
=> 15285 update state filing id in putbackon

legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/services/test_authorization.py
*Issue #:* /bcgov/entity#19865
Disallow restorations for businesses in pending amalgamation
=> 19865-disallow-ting-restorations

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
*Issue #:* /bcgov/entity#19429
- populate SP proprietor addresses & email for SP DBA LEAR & SP DBA COLIN
- link `offices/offices_history` to alternate names through `althernate_name_id`
- link custodial addresses in `addresses/addresses_history` to alternate names through `alternate_name_id` , for compatibility with old method (please refer to `addresses.legal_entity_id`)
- update TO-DOs for future reference
1. No changes to populate SP addresses & email to `alternate_names_history` in this PR, this complex scenario will be carefully considered in bcgov/entity#19349
2. Here is the explanation for different scenarios of SP proprietors' addresses
- SP individual: use LE person address fields 
- SP DBA LEAR & SP DBA COLIN: use alternate name address fields
By …
=> 19429 update migration scripts to populate SP addresses and other related stuff

legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/models/test_alternate_name.py, legal-api/tests/unit/models/test_legal_entity.py
*Issue #:* /bcgov/entity#20129
* Update `AlternateName.OPERATING` references to use `AlternateName.DBA`
=> 20129 fix broken alternate name related tests

legal-api/src/legal_api/models/business_common.py, legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/tests/conftest.py, legal-api/tests/unit/__init__.py, legal-api/tests/unit/resources/v2/test_business.py, legal-api/tests/unit/resources/v2/test_business_address.py, legal-api/tests/unit/resources/v2/test_business_director.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py, legal-api/tests/unit/resources/v2/test_business_filings/test_internal.py, legal-api/tests/unit/resources/v2/test_business_resolutions.py, legal-api/tests/unit/resources/v2/test_business_share_classes.py, legal-api/tests/unit/resources/v2/test_business_tasks.py
*Issue #:* /bcgov/entity#20121
- Update conftest to work with flask-sqlalchemy 3.x
- A couple small fixes to some of the unit tests
- This update improves the unit test success:
```
Latest test run on feature-legal-name == 382 failed, 1466 passed, 44 skipped in 303.10s (0:05:03)
Current test run in this PR: =========== 182 failed, 1666 passed, 44 skipped in 308.61s (0:05:08)
```
- There's still failing unit tests but from a cursory look the failing tests are due to different issues unrelated to improper transaction rollbacks. 
In the legal name feature branch, we upgraded the `flask-sqlalchemy` package from 2.5.1 to ^3.0.3. Part of this upgrade means moving from SqlAlchemy 1.x to SqlAlchemy 2.x (confirmed in …
=> 20121 Fix db data not being reset properly between test runs

legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/resources/v2/business/business_parties.py, legal-api/tests/unit/reports/test_report.py
*Issue #:* /bcgov/entity#19942
- Fix broken unit tests for report folder
- 60/60 unit tests pass
=> 19942 Fix broken unit tests (report folder)

legal-api/src/legal_api/models/legal_entity.py
*Issue #:* /bcgov/entity#20119
* Fix issue with generating alternate name json for GP when start date is null
=> 20119 fix alternate name json issues when business start date is null

legal-api/src/legal_api/services/authz.py
*Issue #:* /bcgov/entity#19451
- Fixed small issue in the authz after the sync with main
=> 19451 Fixed small issue in authz after sync with main

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
*Issue #:* /bcgov/entity#20166
- Updated legal_name_updates.sql to populate entity_type for alternate_names and alternate_names_history tables
- Verified data migration script populates entity_type in alternate name tables
=> 20166 populated entity type for data migration update - alternate names

legal-api/src/legal_api/models/filing.py, python/common/business-registry-model/src/business_model/models/filing.py, queue_services/entity-filer/poetry.lock, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py
*Issue #:* /bcgov/entity#20327
- fix issues related to `find_by_id()` to make sure only number can pass in
- update status listener of filing data model so that the status of filing can be updated automatically after filing is processed by filer
=> 20327 Fix error occurred when testing filer on GCP for registration - part 2

legal-api/src/legal_api/models/alternate_name.py, legal-api/src/legal_api/models/legal_entity.py, legal-api/src/legal_api/resources/v2/internal_services.py, legal-api/tests/unit/models/test_legal_entity.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py, python/common/business-registry-model/src/business_model/models/alternate_name.py, python/common/business-registry-model/src/business_model/models/legal_entity.py, python/common/business-registry-model/tests/models/test_legal_entity.py
*Issue #:* /bcgov/entity#20148
- Removed `operatingName` from everywhere because we're using `name` now.
Verification/Testing:
=> 20148 remove operating name

legal-api/src/legal_api/services/business_service.py
* Updated business_service class functions for returning a business to work for scenario where GP is owner of a SP.  Previously, I believe we had to do some hacky logic when `alternate_name.entity_type` wasn't an actual column in the table.  Don't think we need this anymore.
=> Fix issue where none was being returned for DBAs where owner is GP

legal-api/src/legal_api/models/business_common.py, legal-api/src/legal_api/models/colin_entity.py, legal-api/src/legal_api/reports/business_document.py, legal-api/src/legal_api/services/business_details_version.py
*Issue #:* /bcgov/entity#20359
- updated business summary to use alternate name
- adjusted functions to handle other alternate name updates
*Examples:*
*Local:*
*OCP Dev:*
[FM1000001.Summary.-.2024-04-06.pdf](https://github.com/bcgov/lear/files/14924417/FM1000001.Summary.-.2024-04-06.pdf)
- partner information issue here
*Local:*
*OCP Dev:*
- partner information issue here
*Local:*
*OCP Dev:*
=> 20359  -business summary updates

python/common/business-registry-model/src/business_model/models/address.py, queue_services/entity-filer/poetry.lock, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/alternate_name.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/legal_entity_info.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/offices.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py, queue_services/entity-filer/src/entity_filer/filing_processors/registration.py, queue_services/entity-filer/src/entity_filer/resources/worker.py, queue_services/entity-filer/src/entity_filer/services/bootstrap.py, queue_services/entity-filer/src/entity_filer/services/business_service.py, queue_services/entity-filer/src/entity_filer/services/naics.py, queue_services/entity-filer/tests/unit/__init__.py, queue_services/entity-filer/tests/unit/worker/test_change_of_registration.py
*Issue #:* /bcgov/entity#20328
- Update change of registration filing processor to work with alternate name changes
- Update relevant unit tests
- Set `entity_type` values for registration filing processor since `alternate_names.entity_type` was introduced into db
- Temporarily copy `NaicsService` and `RegistrationBootstrapService` from legal-api (also `BusinessService` in previous PR). The files should be removed once filer can refer to common module
- Misc fixes & updates
=> 20328 Filer - Update change of registration filing processor to work with alternate name changes

queue_services/entity-bn/q_cli.py, queue_services/entity-bn/setup.py, queue_services/entity-bn/src/entity_bn/bn_processors/change_of_registration.py, queue_services/entity-bn/src/entity_bn/bn_processors/registration.py, queue_services/entity-bn/tests/unit/__init__.py, queue_services/entity-bn/tests/unit/bn_processors/test_change_of_registration.py, queue_services/entity-bn/tests/unit/bn_processors/test_registration.py
*Issue #:* /bcgov/entity#20775
- the output legal name is sorted and only shows first 2 names
- unit tests for registration
- unit tests for change of registration
=> 20775 - fix sorted and first 2 legal name outputs for registration and change of registration

legal-api/flags.json, legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/reports/business_document.py, legal-api/src/legal_api/reports/report.py, legal-api/tests/unit/models/test_business.py
*Issue #:* /bcgov/entity#20777
- Add `business_legal_name` hybrid property in business model to return correct legal name for SP/GPs when `enable-legal-name-fix` feature flag is on. Note that `legal_name` is frequently used in the outputs as business name so I use another name to prevent incorrect use.
- Fix some potential issues in the outputs where `legalName` in `business.json()` is used
*Some testing examples when flag is on*
- SP Individual - FM1028594
- SP DBA - FM1054864
- GP (2 partners) - FM1044962
- GP (>2 partners)
- Non firm - BC1218875
=> 20777 - Update logic for legalName field in business response

legal-api/src/legal_api/models/business.py
*Issue #:* /bcgov/entity#20777
- Bug fix
*Local testing result*
GP(2 partners without cessation date) - FM1000001
GP(>2 parners without cessation date) - FM1000013
=> 20777 - Filter out party when cessation date is not null

legal-api/flags.json, legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/resources/v1/test_name_requests.py, legal-api/tests/unit/resources/v2/test_name_requests.py, legal-api/tests/unit/services/filings/validations/test_alteration.py
*Issue #:* /bcgov/entity#21202
**Note: this feature flag is only intended to disable NR check in the sandbox.**
* Integrate `disable-nr-check` feature flag with namex service's `nr_validate` function.  Always returns that NR is valid when flag is on.
* Fix broken tests
* Add tests to test valid NR is always returned when flag is on
=> 21202 Integrate disable-nr-check feature flag with NR validate code

legal-api/report-templates/bcAnnualReport.html, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/resources/v1/business/business_filings.py
*Issue #:* /bcgov/entity#21020
- Fixed incorrect AR year in the outputs. A similar issue was fixed previously for co-ops https://github.com/bcgov/lear/pull/1105
Before:
After:
=> 21020 Fix wrong AR year is being displayed in the annual report output

legal-api/src/legal_api/services/filings/validations/alteration.py, legal-api/src/legal_api/services/filings/validations/common_validations.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/resources/v1/test_name_requests.py, legal-api/tests/unit/resources/v2/test_name_requests.py
*Issue #:* /bcgov/entity#21202
* Update to return with no NR validation errors for all top level functions that validate NRs when NR check flag is off
* Update get_approved_name in namex service to return an approved or conditionally approved name regardless of NR's state when NR check flag is off.  This is called separately in some places in code base.
* Update/add tests
=> 21202 Add additional checks to disable NR related functionality when disable-nr-check flag is on

legal-api/src/legal_api/models/business.py, legal-api/tests/unit/models/test_business.py
*Issue #:* /bcgov/entity#21123
- Add in_dissolution property to business model
- checks that a business belongs to a batches entry where status is not COMPLETED
- checks that a business has a batch_processing entry that matches on business_id and status is not COMPLETED or WITHDRAWN
- Add unit tests for the logic added above
=> 21123 add in dissolution property to business model

legal-api/src/legal_api/reports/business_document.py
*Issue #:* /bcgov/entity#21414
- Updated business json endpoint to return correct legal name when flag `enable-legal-name-fix` is on
*Testing results in local env*
- Firm - FM1019177
1. flag on
2. flag off
- Non-firm - BC1218875
1. flag on
2. flag off
- Verified that PDF versions are unchanged
=> 21414 - Update business summary json endpoint to return correct legal name

legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/services/test_authorization.py
*Issue #:* /bcgov/entity#21124
- Update allowable actions to block following filings types if business is in dissolution. This [PR](https://github.com/bcgov/lear/pull/2481/files) is a good reference
- Voluntary dissolution
- Alteration
- Amalgamation
-  Use new in_dissolution property in business model to help in determining if a business is in the process of being dissolved
-  Add/update unit tests as appropriate
-  Update [allowable actions spreadsheet](https://docs.google.com/spreadsheets/d/1sxsZ7vuODtD_ftjR27qLvgYErWDB-msvzGucjvBRQXQ/edit#gid=0) to include new rules
=> 21124 Legal API - update allowable actions

legal-api/src/legal_api/models/business.py, legal-api/tests/unit/models/test_business.py
*Issue #:* /bcgov/entity#21262
Moved the ~warnings array~ inDissolution to slim json
Currently, in Auth Web, the search endpoint for all the businesses returns the slim json:
So, as of right now, there's no way of actually knowing that the business is the process of being dissolved (D1 state for example).
Now that the inDissolution is in the slim json, I will be able to use it in AUTH WEB. And In doing so, I can actually add the alert when inDissolution is true.
=> 21262 Added inDissolution to slim json

legal-api/src/legal_api/services/involuntary_dissolution.py, legal-api/tests/unit/services/test_involuntary_dissolution.py
*Issue #:* /bcgov/entity#21455
- Add a criterion to exclude frozen businesses by checking _Business.admin_freeze_ is not True
- Update unit tests, expecting business eligibility returns false when the business is admin frozen
- Passed all unit tests in _test_involuntary_dissolution.py_ including the updated one
=> 21455 add criterion to exclude frozen businesses from being selected to involuntary dissolution

legal-api/src/legal_api/services/involuntary_dissolution.py, legal-api/tests/unit/services/test_involuntary_dissolution.py
*Issue #:* /bcgov/entity#21279
* Update `_get_businesses_eligible_query` to pull back additional info to regarding why a business is eligible for dissolution - overdue ARs or transition filing
* Add `EligibilityDetails` dataclass
* Update `check_business_eligibility` to return `elgibility` and `eligibility_details`.  This will be used by the warnings check for involuntary dissolutions to pass back specific codes as to why a business is not in good standing.
=> 21279 Update to include more details about why business eligible for dissolution

legal-api/src/legal_api/models/configuration.py, legal-api/src/legal_api/resources/v2/admin/configuration.py, legal-api/tests/unit/resources/v2/test_configuration.py
*Issue #:* /bcgov/entity#21442
- Add filter query param to GET /configurations endpoint to retrieve configuration items by name
=> 21442 Legal API - Add filter to configurations endpoint

legal-api/setup.py
- Add `requirements-nats.txt` as optional dependency
Note that using `pip install <legal-api path>/legal-api` just installs partial dependencies excluding supports for NATS.
To install all dependencies for legal-api, use `pip install <legal-api path>/legal-api[nats]` instead.
=> Small tweak on legal-api setup.py to add NATS requirements as optional

jobs/involuntary-dissolutions/involuntary_dissolutions.py, jobs/involuntary-dissolutions/requirements.txt, jobs/involuntary-dissolutions/requirements/prod.txt, jobs/involuntary-dissolutions/tests/unit/test_involuntary_dissolutions.py, jobs/involuntary-dissolutions/tests/unit/test_job.py, legal-api/src/legal_api/services/involuntary_dissolution.py
*Issue #:* /bcgov/entity#21331
- Implemented stage 2 for dissolutions job
- Misc updates
=> 21331 Dissolutions Job - Implement stage 2

queue_services/entity-filer/src/entity_filer/worker.py
*Issue #:* n/a
add back in temp identifier that was pulled in gcp event for testing
=> fix: add in temp identifier to gcp event call

.github/workflows/legal-api-ci.yml
*Issue #:* /bcgov/entity#21696
This is a tiny PR. As part of the ticket.
Add token to legal-api-ci, need to merge and test with legal api CI action before doing other changes
=> 21696-Fix broken code coverage uploads in all CI pipelines - Try out add token

jobs/involuntary-dissolutions/config.py, jobs/involuntary-dissolutions/involuntary_dissolutions.py, jobs/involuntary-dissolutions/tests/unit/__init__.py, jobs/involuntary-dissolutions/tests/unit/test_involuntary_dissolutions.py
- Updated stage 1 & stage 2 processes for dissolutions job.
Now `batch_processing.trigger_date` is set in stage 1, and stage 2 & 3 can use this to check whether the business can be processed.
- Fix unit tests
=> 21475 Dissolutions job - Update stage 1 & stage 2 processes

queue_services/entity-filer/src/entity_filer/worker.py
=> Update filer to publish generic events in format that pay understands

colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py, colin-api/tests/postman/colin-api.postman_collection.json, colin-api/tests/unit/api/test_future_effective_filings.py
https://app.zenhub.com/workspaces/annual-report-filing-for-corporations-661483a4f4f833001637ec44/issues/zh/26
Modified the filing endpoint to return the future effective filings
Added tests
=> Get future effective filings in Colin

legal-api/migrations/versions/01b28a2bb730_furnishings.py, legal-api/src/legal_api/models/__init__.py, legal-api/src/legal_api/models/address.py, legal-api/src/legal_api/models/batch.py, legal-api/src/legal_api/models/furnishing.py, legal-api/tests/unit/models/test_furnishing.py
*Issue #:* /bcgov/entity#21737
- Added alembic script to create furnishings table
- Added data model for furnishing
- Misc updates for others
*db after upgrading*
=> 21737 - Create alembic script & model for furnishings table

legal-api/src/legal_api/models/business.py, legal-api/tests/unit/models/test_business.py
*Issue #:* /bcgov/entity#21476
Implemented the logic to include transition filing logic used in involuntary dissolution eligibility check in `business.good_standing`.
(`enable_involuntary_dissolution` feature flag)
The main logic is same as the `_has_no_transition_filed_after_restoration()` method in involuntary dissolution. 
Differences are: 
- instead of checking with a given Business, this implementation checks with itself.
- instead of returning a SQLAlchemy clause, this implementation returns a boolean value, implemented using `.scalar()` after the query.
Also added unit tests to check 4 situations:
- New established business
- In limited restoration, not expired, no need for transition 
- Transition filed and completed
- Transition not filed 
By submitting …
=> 21476 update good standing logic to include transition filing criteria

.github/workflows/entity-filer-ci.yml, queue_services/entity-filer/Makefile, queue_services/entity-filer/flags.json, queue_services/entity-filer/requirements.txt, queue_services/entity-filer/src/entity_filer/config.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_address.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/integration/test_publish_event.py, queue_services/entity-filer/tests/unit/__init__.py, queue_services/entity-filer/tests/unit/filing_processors/test_change_of_address.py
- Added feature flag to filer
- Updated COA filing processor to delay business in dissolution
- Fixed linting
=> 21475 Filer - Update Change of Address filing processor to delay dissolution

jobs/email-reminder/requirements.txt
*Issue #:* /bcgov/entity#21571
Added nest_asyncio to email reminder job requirements
I debugged locally, this error is fixed now
=> 21571 Added nest_asyncio to email reminder job requirements

jobs/email-reminder/requirements.txt
*Issue #:* /bcgov/entity#21971
- Fixed the email reminder job
The protobuf downgrade is for this:
=> 21971 - Fixed Email Reminder Job

queue_services/entity-filer/src/entity_filer/filing_processors/change_of_address.py, queue_services/entity-filer/tests/unit/filing_processors/test_change_of_address.py
- Fix wrong calculation for target dissolution date
=> 21475 Filer - Fix target dissolution date calculation

legal-api/devops/vaults.json, legal-api/requirements.txt, legal-api/requirements/prod.txt, legal-api/src/legal_api/config.py, legal-api/src/legal_api/resources/v2/__init__.py, legal-api/src/legal_api/resources/v2/mras.py, legal-api/src/legal_api/services/__init__.py, legal-api/src/legal_api/services/mras_service.py, legal-api/tests/unit/resources/v2/test_mras.py, legal-api/tests/unit/services/test_mras_service.py
*Issue #:* /bcgov/entity#22012
- Implemented endpoint to proxy MRAS get jurisdictions call
```shell
GET <legal-api-base-url>/api/v2/mras/<identifier>
{
"jurisdictions": [
{
"id": "SK",
"name": "Saskatchewan",
"nameFr": "Saskatchewan",
"redirectUrl": ...,
"targetProfileId": ...
},
{
"id": "AB",
"name": "Alberta",
"nameFr": "Alberta",
"redirectUrl": ...,
"targetProfileId": ...
}
]
}
```
- Added a service class to handle MRAS calls
- Updated config.py
- Updated vaults.json
*Local testings*
- Business has EP registrations
- Business doesn't have EP registrations
=> 22012 Legal API - implement endpoint to proxy MRAS get jurisdictions call

jobs/involuntary-dissolutions/involuntary_dissolutions.py, legal-api/src/legal_api/utils/datetime.py, legal-api/tests/unit/utils/test_datetime.py
*Issue #:* /bcgov/entity#21953
- Part of the tech design for the stage 1 letter flow for the furnishings job includes checking how many business days have elapsed since the furnishings email has been sent. 
- I could not find any existing method of adding business days to a date in the project, so I created a util function in the custom `datetime` object that handles this logic.
- The logic for `add_business_days` is fairly simple and only handles weekends. Holidays are not covered under this implementation.
- This should be merged before #2816 
=> 21953 Create datetime method to add business days to a date

legal-api/src/legal_api/models/review.py, legal-api/src/legal_api/resources/v2/admin/__init__.py, legal-api/src/legal_api/resources/v2/admin/reviews.py, legal-api/tests/unit/resources/v2/test_reviews.py
*Issue #:* /bcgov/entity#21929
- "get reviews" endpoint
- support pagination (added logic to handle limit and page)
- add unit tests
=> 21929 - get reviews endpoint

jobs/furnishings/Makefile, jobs/furnishings/requirements.txt, jobs/furnishings/src/furnishings/stage_processors/stage_one.py
*Issue #:* /bcgov/entity#21953
* Handles scenario where an auth call to retrieve email info may return a 404.  This shouldn't really happen but for imported BC companies data, there may be entries that haven't been created in auth which leads to auth returning a 404.  For now, we will log this as an error and just return `None` for the contact email so the furnishings job can continue running
=> 21953 Fix issue when auth returns 404 for GET <auth_url>/entities/{identifier} endpoint

colin-api/src/colin_api/models/__init__.py, colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/corp_involved.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/models/reset.py, colin-api/src/colin_api/resources/business.py, colin-api/src/colin_api/resources/filing.py, colin-api/src/colin_api/resources/reset.py, jobs/update-colin-filings/requirements.txt, jobs/update-colin-filings/requirements/prod.txt, jobs/update-legal-filings/update_legal_filings.py
*Issue #:* /bcgov/entity#19794
=> 19794 colin sync for amalgamationApplication

queue_services/entity-emailer/src/entity_emailer/email_processors/involuntary_dissolution_stage_1_notification.py, queue_services/entity-emailer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#21760
- Update the `processed_date` and `last_modified`
- In a failure scenario, update the `notes` field with `Failure to send email`
=> 21760 Additional furnishing record updates

colin-api/src/colin_api/resources/business.py, jobs/update-colin-filings/update_colin_filings.py
*Issue #:* /bcgov/entity#19794
=> 19794 fixes

legal-api/report-templates/noticeOfDissolutionCommencement.html, legal-api/src/legal_api/reports/report_v2.py
*Issue #:* /bcgov/entity#22235
- Updated to make sure there's a space in postal code
- Updated to use double space between region and postal code as per design
*Testing*
- Before
- After
=> 22235 - Legal API - Small tweak on address format for dissolution AR letter

queue_services/entity-emailer/q_cli.py, queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py, queue_services/entity-emailer/src/entity_emailer/email_processors/involuntary_dissolution_stage_1_notification.py, queue_services/entity-emailer/tests/unit/email_processors/test_involuntary_dissolution_stage_1_notification.py, queue_services/entity-emailer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#22368
- To get coloured version of letter as email attachment
- Update `q_cli.py` so that it can inject queue message for furnishings job
- Fix http response processing described in bcgov/entity#22435
*Testing*
Note that my local testing is based on v2 of legal-api, and the email file can be downloaded at MailHog.
- overdue AR without EP registration
- overdue AR with EP registration
=> 22368 Emailer - Add letter attachment to stage 1 AR email

jobs/update-colin-filings/devops/vaults.json
*Issue #:* /bcgov/entity#21699
* Revert sentry config for update-colin-filings job back to entity vault.   Will test this in dev first before updating other BE services
=> 21699 Revert update-colin-filing job to use entity vault's sentry config

jobs/involuntary-dissolutions/involuntary_dissolutions.py, legal-api/requirements.txt, legal-api/src/legal_api/config.py, legal-api/src/legal_api/services/warnings/business/business_checks/involuntary_dissolution.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/services/warnings/business/business_checks/test_involuntary_dissolution.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_address.py, queue_services/entity-filer/tests/unit/__init__.py, queue_services/entity-filer/tests/unit/filing_processors/test_change_of_address.py
*Issue #:* /bcgov/entity#22432
- update `targetDissolutionDate` in dissolution warnings
- update unit tests
- **Question: need to update vaults.json or not?**
*Notes for this update*
(from Dylan) We are just wanting to make sure we never display something stupid like a date in the past. 😄 
=> 22432 - Legal API - update dissolution warnings targetDissolutionDate

legal-api/src/legal_api/config.py
* Attempt to fix sentry_dsn config issue where null value is populated in OCP secrets when sentry_dsn is populated with empty string in 1pass.  We need to initialize sentry with empty string in this case.
If this works, will update for all other BE services
=> Attempt to fix sentry_dsn issue for legal api

colin-api/src/colin_api/config.py, jobs/email-reminder/config.py, jobs/furnishings/src/furnishings/config.py, jobs/future-effective-filings/config.py, jobs/involuntary-dissolutions/config.py, jobs/update-colin-filings/config.py, jobs/update-legal-filings/config.py, queue_services/business-pay/src/business_pay/config.py, queue_services/entity-bn/src/entity_bn/config.py, queue_services/entity-digital-credentials/src/entity_digital_credentials/config.py, queue_services/entity-emailer/src/entity_emailer/config.py, queue_services/entity-filer/src/entity_filer/config.py, queue_services/entity-pay/src/entity_pay/config.py
* Fix sentry_dsn config issue where null value is populated in OCP secrets when sentry_dsn is populated with empty string in 1pass. We need to initialize sentry with empty string in this case.
=> Fix sentry issue where sentry_dsn null string value should be converted to empty string

docs/oas/business.yaml
*Issue #:* /bcgov/entity#22115
- New PR for incorporation application api spec
- Created new pr with addressed comments
=> incorporation application changes for api spec

queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py, queue_services/entity-emailer/src/entity_emailer/email_processors/agm_extension_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/agm_location_change_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/amalgamation_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/change_of_registration_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/consent_continuation_out_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/continuation_in_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/dissolution_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/registration_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/restoration_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/special_resolution_helper.py, queue_services/entity-emailer/tests/unit/email_processors/test_correction_notification.py, queue_services/entity-emailer/tests/unit/email_processors/test_cp_special_resolution_notification.py, queue_services/entity-emailer/tests/unit/email_processors/test_restoration_notification.py
*Issue #:* /bcgov/entity#22431
=> 22431 update to use v2 of legal api

docs/business.yaml
*Issue #:* /bcgov/entity#22708
- Updated wording for GET /businesses/{identifier}/filings endpoint to reflect the new change.
- Checked typos and format.
**Note:**
Based on the discussions with Dylan, the previously uncertain descriptions for the fields have been updated as follows:
- **legalFilings**: "This field identifies filings that corporations are required to submit under the BC Corporations Act."
- **displayName**: "This field represents the name to be displayed for the ledger item associated with the filing record."
**Updated Result:**
=> 22708 - Update wording for GET /businesses/{identifier}/filings

colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py, legal-api/src/legal_api/resources/v2/business/colin_sync.py
*Issue #:* /bcgov/entity#21954
- No updates for update-colin-filings job
- Updated colin-api to support adding events for involuntary dissolutions
- Updated legal-api to populate batch_processing.meta_data into filing json returned for COLIN related services
Note that similar with administrative dissolution, no filing will be created for involuntary dissolution. It just creates events and changes the state of the companies.
=> 21954 - Sync involuntary dissolutions back to COLIN

docs/business.yaml
*Issue #:* /bcgov/entity#22717
- Adjusted the business overall description
- Adjusted the description for multiple endpoints
_Note:_
Regarding the "No Methods" comment, as per discussion with Dylan, we will leave it as what it is right now. Since all the schemas used for filing are used in the Filing schema, and the the Filing schema is the one directly used in related endpoints. Also cannot remove "No methods use this type." since it's an Apigee setting.
Test Apigee instance: https://storied-landing-429920-d2-apispecs.apigee.io/docs/apispecstest/1/overview
=> 22717-adjust wordings based on the feedback doc and discussion

legal-api/report-templates/template-parts/common/businessDetails.html, legal-api/src/legal_api/resources/v1/business/business_filings.py, legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/src/legal_api/utils/legislation_datetime.py, legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
*Issue #:* bcgov/entity#22586
- removed time workaround from businessDetails.html
- assigned new effective data for COA filing (2 places)
- added method for tomorrow 12:01 AM
- updated unit tests (3 places)
=> 22586 Fixed COA effective time bug

jobs/furnishings/src/furnishings/stage_processors/post_processor.py, jobs/furnishings/src/furnishings/stage_processors/stage_one.py, jobs/furnishings/src/furnishings/stage_processors/stage_three.py, jobs/furnishings/src/furnishings/stage_processors/stage_two.py, jobs/furnishings/src/furnishings/worker.py
*Issue #:* /bcgov/entity#22203
- Added more debug logging for furnishings job
- We can add more stuff as we go further with involuntary dissolutions.
Please let me know if you would like anything extra added.
=> 22203 - Added furnishings logging

queue_services/entity-emailer/src/entity_emailer/email_processors/involuntary_dissolution_stage_1_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/INVOL-DIS-STAGE-1.html, queue_services/entity-emailer/tests/unit/email_processors/test_involuntary_dissolution_stage_1_notification.py
*Issue #:* /bcgov/entity#22496
- Update email templates for Xpro and correct some content for BC companies
- Update to support different attachment (assuming the other work for it is done and the endpoint to get Xpro document is unchanged)
The testing result can be found at MailHog for A0883551 (I created this and it can be also found in dev. However, auth-api and UI don't fully support this type of business)
*Unit Test*
The related tests are passed. And the other broken tests will be fixed in another work.
=> 22496 Emailer - stage 1 overdue ARs notification (EP flow)

jobs/furnishings/src/furnishings/stage_processors/post_processor.py, jobs/furnishings/src/furnishings/stage_processors/stage_three.py, jobs/furnishings/src/furnishings/stage_processors/stage_two.py, jobs/furnishings/src/furnishings/worker.py, jobs/furnishings/tests/unit/stage_processors/test_post_processor.py, jobs/furnishings/tests/unit/stage_processors/test_stage_three.py
*Issue #:* /bcgov/entity#22323
- Added logic to generate XML for stage 3 (excluding EPs)
**Test 1: Run furnishings job on stage 1 and stage 2 batch_processing entries**
1. Starting with these stage 1 and stage 2 batch_processing entries:
2. Running the furnishings job (with all `cronstrings = * * * * *`) results in below. We expect to see:
- `furnishing_type == MAIL or EMAIL` for stage 1 batch_processings
- `furnishing_type == GAZETTE` for stage 2 batch_processings
- 2 different furnishing_groups
- An `xml_payload` entry with the stage 2 batch_processing businesses with "Intent to Dissolve (B.C.)"
---
**Test 2: Run furnishings job on stage 2 and stage 3 batch_processing entries**
1. Using the same batch_processings from test 1, change the `trigger_date` to before …
=> 22323 Furnishings job - Add logic to generate XML for stage 3

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/services/filings/validations/correction.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/AR-REMINDER.html, queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-information.html, queue_services/entity-filer/src/entity_filer/filing_processors/correction.py, queue_services/entity-filer/tests/unit/test_worker/test_worker.py
*Issue #:* /bcgov/entity#22353
=> 22353 correction of C, CBEN, CCC, CUL

queue_services/entity-emailer/src/entity_emailer/email_processors/involuntary_dissolution_stage_1_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/INVOL-DIS-STAGE-1.html
*Issue #:* /bcgov/entity#22657
- Fixed the involuntary dissolution job stage 1 email output
Tested, new email output:
You can see the email in Mailhog as well.
The formatting now is correct: X, Y, and Z. Also, Quebec is not shown anymore. ONLY NWPTA jurisdictions.
=> 22657 - Fixed stage 1 dissolution job email

jobs/furnishings/src/furnishings/stage_processors/post_processor.py, jobs/furnishings/src/furnishings/stage_processors/stage_three.py, jobs/furnishings/tests/unit/stage_processors/test_post_processor.py
*Issue #:* /bcgov/entity#22325
- Added logic to generate XML for stage 3 EPs
1. Starting with the following batch processing entries (3 D3 EPs, 2 D2 EPs, 3 D3 BCs, 2 D2 BCs):
2. Running the furnishings job results in the following furnishings entries:
3. And the final xml payload, including all 4 dissolution categories.
```xml
<public_notice>
<volume></volume>
<date></date>
<filing_desc title="Intent to Dissolve (B.C.)" id="">
<category>INTENT TO DISSOLVE</category>
<subcategory>B.C.</subcategory>
<corp_class>BC Company(s)</corp_class>
<description>The Registrar of Companies hereby gives notice that the following companies may, at any time after the expiration of one month from the date of publication of this notice, unless cause is shown to the …
```
=> 22325 Furnishings Job - Add EP logic to generate XML for stage 3

queue_services/entity-emailer/src/entity_emailer/email_processors/continuation_in_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-APPROVED.html, queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-CHANGE_REQUESTED.html, queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-REJECTED.html, queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-RESUBMITTED.html, queue_services/entity-emailer/src/entity_emailer/worker.py, queue_services/entity-emailer/tests/unit/email_processors/test_continuation_in_notification.py
*Issue #:* bcgov/entity#22363
- added attachment for RESUBMITTED continuation in
- added subjects for other statuses/options
- created APPROVED email template
- created CHANGE_REQUESTED email template
- created REJECTED email template
- created RESUBMITTED email template
- added latest_review_comment template variable
- updated Rejected template
=> 22363 Continuation in email templates

legal-api/src/legal_api/models/review.py
*Issue #:* /bcgov/entity#22011
Issue: Results not returned if selected same date as start and end date for date submitted filter (e.g. Aug 22 - Aug 22)
Fixed filtering issue for same date range by checking start and end of the day (date is `datetime` field)
=> 22011 - fix date range filtering issue

jobs/furnishings/src/furnishings-templates/gazette-notice.xml, jobs/furnishings/src/furnishings/stage_processors/post_processor.py
*Issue #:* /bcgov/entity#22889
- Added the time in the Dissolutions section in the XML Payloads
How I tested my change:
1. Went to DB and picked an entry in the batch_processing table that was in stage 1: 
2. Changed the trigger date to before today and ran the dissolutions job:
This moved it to stage 2.
3. Ran the furnishings job. This created an intent to dissolve furnishings entry with an XML payload that resembles the same:
4. Changed the trigger date again to before today and ran the dissolutions job again, this moved it to `DISSOLUTION`:
5. Ran the furnishings job again, this moved it to `CORP_DISSOLVED` and created an XML payload of DISSOLUTION:
Now, if you look at the text node, you can see the processed time in 12 hour PM/AM format.
By submitting this …
=> 22889 - Added time to dissolutions in XML payloads

jobs/involuntary-dissolutions/involuntary_dissolutions.py, jobs/involuntary-dissolutions/tests/unit/test_involuntary_dissolutions.py
*Issue #:* /bcgov/entity#22207
Updated the dissolution job to check furnishing data as required. Won't move to next step if furnishing entry hasn't completed.
How I tested:
Here, we have a business in first stage + a status of processing
Run furnishings job, get the email furnishing entry, set the status as QUEUED:
Now, since the status is QUEUED not PROCESSED, if we run the dissolutions job again, this'll set the status to ERROR as we're checking now if the furnishing entry has completed.
Logger:
Here, we have a business in second stage + a status of processing
Run furnishings job, get the gazette furnishing entry, set the status as QUEUED:
Now, since the status is QUEUED not PROCESSED, if we run the dissolutions job again, this'll set the status to ERROR as …
=> 22207 - update dissolution job to check furnishing data

legal-api/report-templates/dissolutionCover.html, legal-api/report-templates/template-parts/common/v2/styleMail.html, legal-api/src/legal_api/reports/report_v2.py, legal-api/src/legal_api/resources/v2/business/business_furnishings/furnishing_documents.py, legal-api/src/legal_api/services/__init__.py, legal-api/src/legal_api/services/furnishing_documents_service.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/resources/v2/test_business_furnishings/test_furnishing_documents.py, legal-api/tests/unit/services/test_furnishing_documents_service.py
*Issue #:* /bcgov/entity#22502
Note that this is the second PR of batch letter work. All the changes in this PR are only for legal-api. More changes in furnishings job will be in the following PR.
- create a service class for furnishing documents generation
- modify the `GET {{legal-api-base-url}}/businesses/:identifier/furnishings/:furnishing_id/document` endpoint to use service class
- add dissolution cover letter template
- modify `ReportV2` to support cover letter generation
- fix the bug in  bcgov/entity#22530
- add and update unit tests
- cover letter (with dummy data)
- merged batch letter with cover
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the lear …
=> 22502 - legal api - update to use service class for furnishing documents generation

queue_services/entity-emailer/q_cli.py, queue_services/entity-emailer/src/entity_emailer/email_processors/bn_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/mras_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-info.html, queue_services/entity-emailer/src/entity_emailer/worker.py, queue_services/entity-emailer/tests/unit/__init__.py, queue_services/entity-emailer/tests/unit/email_processors/test_bn_notification.py, queue_services/entity-emailer/tests/unit/email_processors/test_mras_notification.py
*Issue #:* /bcgov/entity#21515
- MRAS & BN emails for continuation in and amalgamation
- add unit tests
Some other unit tests are failing but the ones I added are running locally:
=> 21515 - MRAS & BN emails for continuation in and amalgamation

queue_services/entity-emailer/tests/unit/__init__.py, queue_services/entity-emailer/tests/unit/email_processors/test_change_of_registration_notification.py, queue_services/entity-emailer/tests/unit/email_processors/test_correction_notification.py, queue_services/entity-emailer/tests/unit/email_processors/test_dissolution_notification.py
*Issue #:* /bcgov/entity#22367
- Fix entity emailer unit tests relating to legal name.
=> 22367 Emailer - Fix emailer unit tests

colin-api/src/colin_api/models/filing.py
*Issue #:* https://app.zenhub.com/workspaces/names-team-board-new-655554cbddd49510027dad2e/issues/gh/bcgov/business-ar/318
When a Business AR filing is received from the new system, the corporation is looked up using `find_by_identifier`, which creates a founding_date based on the `recognition_date` (converted from Pacific Time to UTC).
https://github.com/bcgov/lear/blob/main/colin-api/src/colin_api/models/business.py#L327
When `_get_last_ar_filed_date` is called, it uses this founding_date by extracting the month and day. The issue was that the founding_date was not being converted back to Pacific Time. As a result, filings for businesses with a `recognition_date` after 5 PM local time were always showing a `last_ar_filed_date` one day ahead.
This PR fixes this …
=> fix: corrected get last ar filed date method

legal-api/Makefile
*Issue #:* /bcgov/entity#23354
This issue is mentioned in #3010. Trying to provide a temporary solution for it since `too-many-positional-arguments` is only available after version 3.3.0 and directly disabling it globally or locally will make pylint 3.2.x throw errors.
- make legal-api linting work for both pylint 3.2.x and pylint 3.3.x
=> Legal API Linting Fix

legal-api/requirements.txt, legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/src/legal_api/services/filings/validations/notice_of_withdrawal.py, legal-api/src/legal_api/services/filings/validations/validation.py, legal-api/tests/unit/services/filings/validations/test_notice_of_withdrawal.py
*Issue #:* /bcgov/entity#23349
- Added validation for Notice of Withdrawal filings, checking:
- the to be withdrawn filing exist
- it has a FED
- its status is PAID
- Added unit tests testing withdraw a filing from an existing business, as discussed, excluding the new business scenario.
- Updated the Registry Schema version number
*Testing Results:*
- All unit tests passed
- Linting Cleared
- Made a filing draft call in local environment (when testing, I commented out the authorization part to avoid the jwt staff check when running locally)
- Draft
- Validate
=> 23349 - validation notice of withdrawal

legal-api/migrations/versions/83a110e10979_add_batch_processing_id_to_colin_event_.py, legal-api/src/legal_api/models/colin_event_id.py, legal-api/tests/unit/models/test_colin_event_id.py
*Issue #:* /bcgov/entity#23539
=> 23539 add batch_processing to colin_event_ids table

jobs/furnishings/src/furnishings/stage_processors/stage_one.py, jobs/furnishings/tests/unit/stage_processors/test_stage_one.py
*Issue #:* /bcgov/entity#23608
- Fixed bugs related to the incorrect processed date, status, and notes population.
- Updated corresponding unit tests.
=> 23608 - Update furnishing entries transferred to bc mail+

jobs/furnishings/flags.json, jobs/involuntary-dissolutions/flags.json, jobs/involuntary-dissolutions/involuntary_dissolutions.py, jobs/involuntary-dissolutions/tests/unit/test_involuntary_dissolutions.py
*Issue #:* /bcgov/entity#23697
- Added the `disable-dissolution-sftp-bcmail` feature flag option in `flags.json`
- Updated the logic for furnishing entries check when moving from stage 1 to stage 2 of involuntary dissolution
- check furnishing entries - 2 scenarios
1. if email processed, and mail processed (after 5 business days still not in good standing)
2. only has a mail entry, and it's processed
- Updated the check to support SFTP function FF
**Action**: Trying to move a business from stage 1 to stage 2 of involuntary dissolution
**Scenario 1** - ERROR and not moving to stage 2
_when this business has an email entry and haven't sent out a mail _
**Scenario 2** - SUCCESS moving to stage 2
_when this business has an email entry and after 5 business days still …
=> 23697 - fix stage1 to stage2 dissolution transition bug

legal-api/src/legal_api/version.py, queue_services/entity-bn/src/entity_bn/version.py
*Issue #:* /bcgov/entity#23845
- Legal API v2.130.0
- Entity-bn v2.129.0
- Furnishing jobs ( no version )
- Dissolution jobs ( no version )
- Business-pay ( no version )
[Release Report 
](https://app.zenhub.com/workspaces/entities---david-65af11a89e89f5043c2911f6/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvMTA1Mzgw)
[Github release](https://github.com/bcgov/lear/releases/edit/untagged-f33b7bef3d18e5741e2e)
=> 23845 - Bumped version numbers up for release 23.2a

docs/business.yaml, legal-api/src/legal_api/models/review.py, legal-api/src/legal_api/resources/v2/admin/reviews.py
*Issue #:* /bcgov/entity#23563
Removed unneeded properties like FED from filter and sort
=> 23563 - update review endpoint

legal-api/src/legal_api/services/filings/validations/continuation_in.py, legal-api/tests/unit/services/filings/validations/test_continuation_in.py
*Issue #:* /bcgov/entity#24073
=> Fix 24073 - validate date and handle time offset

colin-api/src/colin_api/models/address.py, colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/corp_party.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/business.py, colin-api/src/colin_api/resources/filing.py, jobs/update-colin-filings/update_colin_filings.py, jobs/update-legal-filings/update_legal_filings.py, legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/v1/business/business_filings.py, legal-api/src/legal_api/resources/v2/business/colin_sync.py, legal-api/tests/unit/models/test_filing.py, legal-api/tests/unit/resources/v1/test_business_filings/test_internal.py, legal-api/tests/unit/resources/v2/test_colin_sync.py
*Issue #:* /bcgov/entity#24153
- Fixed `ORA-01830: date format picture ends before converting entire input string` (COD filing_date)
- Fixed `'NoneType' object has no attribute 'upper'`
- Handled optional fields 
- `update-colin-filings` changed logic of fetching filings with offset instead of paginate (to avoid calculation)
- `update_legal_filings` removed sync of CORPS from colin -> lear (this is not accepted anymore). Still have logic for COOP's, seems like it may be in use. Not in a position to work on COOP's
=> 24153 fixes in colin sync

data-tool/scripts/README_COLIN_Corps_Extract.md, data-tool/scripts/misc_extract_corps_queries.sql, data-tool/scripts/transfer_cprd_corps.sql
*Issue #:* /bcgov/entity#24164
- Update extract script
- resolve errors (mainly 2)
- incompatible type between boolean and numeric
- NULL byte (0x00)
- add disable/enable-trigger snippets
- Update `README_COLIN_Corps_Extract.md`
- dbschema version = 9.4.3
- transfer legacy dev db data to local extract db
- execution time:  14m40s
- results shown as follows
screenshot 1: outputs of dbschemacli
screenshot 2: results of db query
=> 24164 Update legacy database extract script

legal-api/src/legal_api/models/filing.py, legal-api/tests/unit/core/test_filing.py
*Issue #:* /bcgov/entity#24131
- Allow more company types to have effective date before payment date
=> 24131 - Fix Director Change Output

queue_services/entity-emailer/src/entity_emailer/email_processors/dissolution_notification.py
*Issue #:* /bcgov/entity#24318
- The root cause of consistently not getting `Voluntary Dissolution Application.pdf` attachment is due to passing the wrong document_type to legal_api's GET document endpoint (supposed to be `dissolution` but was `voluntaryDissolution`
**Note:** This PR is to solve the consistently missing `Voluntary Dissolution Application.pdf` attachment in the email issue.
The intermittently missing one PDF issue is still under investigation. _So, after this PR, the ticket will still be open until all issues are resolved._
**Log on DEV - Before:**
```log
2024-11-13 18:24:31,380 - legal_api - INFO in report:report.py:94 - _get_report: Sending report request - Filing: 151945, Type: voluntaryDissolution
2024-11-13 18:24:37,749 - legal_api - ERROR in …
```
=> 24318 - fix missing voluntary dissolution pdf in email attachment

colin-api/flags.json, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/services/flags.py
*Issue #:* /bcgov/entity#24295
Freeze all corporations when synchronizing to COLIN
=> 24295 - Freeze all corporations when synchronizing to COLIN

queue_services/entity-emailer/src/entity_emailer/email_processors/amalgamation_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/continuation_in_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-COMPLETED.html, queue_services/entity-emailer/src/entity_emailer/worker.py
*Issue #:* /bcgov/entity#24361
**For missing the `receipt.pdf` in the first email (continuation application received):**
- Found the root cause for not getting the receipt when the filing status is PAID due to a wrong data type in the payload when running emailer in local environment. To fix this, reformatted the payload to meet the requirement
```
📒 - Payload to get receipt: json:
corpName: None,
filingDateTime: November 13, 2024 at 6:11 pm Pacific time,
effectiveDateTime: ,
filingIdentifier: 152418,
businessNumber: 
continuation_in_notification.py:99-_get_pdfs:📒 - Response: {"type": "INVALID_REQUEST", "title": "Invalid Request", "detail": "Invalid Request", "invalidParams": ["None is not of type 'string'"]}
```
**For missing the `continuation application.pdf` …
=> 24361 - fix missing pdf continuation application

legal-api/flags.json, legal-api/src/legal_api/models/amalgamating_business.py, legal-api/src/legal_api/models/amalgamation.py, legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/db.py, legal-api/src/legal_api/resources/v2/business/colin_sync.py, legal-api/src/legal_api/services/business_details_version.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/models/test_business.py, legal-api/tests/unit/models/test_filing.py, legal-api/tests/unit/reports/test_report.py, python/common/sql-versioning/sql_versioning/versioning.py
*Issue #:* /bcgov/entity#22943
*Issue #:* /bcgov/entity#22942
Update the models and VersionedBusinessDetailsService to use the new DB versioning.
- ***Get the Versioning DB***
Old: `amalgamating_businesses_version = version_class(AmalgamatingBusiness)`
New: `amalgamating_businesses_version = VersioningProxy.version_class(db.session(), AmalgamatingBusiness)`
- ***Get the transaction in the Test***
Old: `uow = versioning_manager.unit_of_work(session).  transaction = uow.create_transaction(session)`
New: `transaction_id = VersioningProxy.get_transaction_id(session())`
=> 22943 update models to use new db_versioning

legal-api/src/legal_api/resources/v1/nr_type_map.py, legal-api/src/legal_api/services/filings/validations/alteration.py, legal-api/tests/unit/resources/v1/test_nr_type_map.py, legal-api/tests/unit/services/filings/validations/test_alteration.py
*Issue #:* bcgov/entity#24549
- added missing accepted request types
- added comments
- updated an error message
- moved request types together in mapping array
- added some missing types
- fixed and expanded unit tests
=> 24549 Added missing NR request types

docs/business.yaml
*Issue #:* /bcgov/entity###  No ticket number for this
As per discussion with Leo and Dave, made a quick update to add information about set relevant fields to `null` in certain scenarios, so that API users would be able to put correct value for the fields.
=> Add details for parValue and maxNumberOfShares fields

data-tool/flows/common/auth_service.py, data-tool/flows/corps_tombstone_flow.py, data-tool/flows/tombstone/tombstone_queries.py
*Issue #:* /bcgov/entity#24477
* Added `update_auth` task in `migrate_tombstone` task .  This new task contains logic that supports entity creation and affiliation in auth.  `UPDATE_ENTITY`, `AFFILIATE_ENTITY` and `AFFILIATE_ENTITY_ACCOUNT_ID`  config i values can be used to test the added auth logic.  
* Added `auth_service.py`.  This was added as the tombstone pipeline wasn't updated to support LEAR version of sqlalchemy like `migrate_corps_flow.py`.  As such, it causes issues with importing legal api dependencies.  This is ok for now as we mainly use raw sql and don't have much need for direct sqlachemy model access so far.  But we may need to revisit this later and refactor to support legal api models if it becomes any issue in downstream work.
**Testing …
=> 24477 Add auth logic for creating and affiliating entities to tombstone pipeline

jobs/furnishings/flags.json, jobs/furnishings/requirements.txt, jobs/furnishings/src/furnishings/config.py, jobs/furnishings/src/furnishings/worker.py, jobs/furnishings/tests/unit/__init__.py, legal-api/flags.json
*Issue #:* /bcgov/entity#22952
1. Replaced the code to initialize and use the new db versioning
2. Updated configuration to support feature flags
3. Added flags.json file
4. Updated requirements.txt with necessary dependencies
5. Switch the versioning Proxy
- Flag is on
- Flag is off
6. Unit Test
- legal: True, furnishings: True
- legal: True, furnishings: False
- legal: False, furnishings: True
- legal: False, furnishings: False
=> 22952 update furnishing job use versioning proxy

legal-api/flags.json, queue_services/entity-bn/flags.json, queue_services/entity-emailer/flags.json
*Issue #:* /bcgov/entity#22954
1. Investigated the job's functionality:
- Job only handles API calls from legal-api and queue messages
- No direct DB operations
- No legal-api package usage
2. Conclusions:
- No changes needed in db versioning setup
- Remove the future-effective-filings flag in legal-api's flags.json
3. Verification steps:
- Tested legal-api with feature flags ON & OFF
- Verified future-effective-filings job functionality
- Confirmed queue message processing works correctly in local environment
- All unit tests passed successfully
ScreenShots:
* Legal-API OFF
- Job works successfully in local environment
* Legal-API ON
1.  Created a Future Effective Filing (Change of Address) - Filing ID: 151265
2. Verified filing exists in local DB
3. Updated …
=> 22954 - Verify future-effective-filings job to use new db versioning

jobs/update-legal-filings/requirements.txt, legal-api/flags.json, queue_services/entity-bn/flags.json, queue_services/entity-emailer/flags.json
*Issue #:* /bcgov/entity#22956
update-legal-filings-job doesn't directly operate in lear db, instead, it's calling legal-api and colin-api endpoints. And there isn't any existing code initialize a db instance in this job. As per discussion I have removed FF for update-legal-filings in multiple flags.json files.
Keep the local lear-db's colin_last_update table remain the same for 3 runs in different scenarios.
In summary, there is no behaviour differences between these 3 scenarios:
1. Not using new db versioning
2. Using new db versioning and FF on
3. Using new db versioning and FF off
1. get max colin event_id from lear-db `{{url}}/api/v2/businesses/internal/filings/colin_id`
2. Pick an event_ids greater than the max id returned -- `105911836`
3. Get business …
=> 22956 - Verify update legal filings job to use new db versioning

legal-api/report-templates/template-parts/common/businessDetails.html
*Issue #:* /bcgov/entity#24629
Below are some examples  based on status:
IA (Status - Completed):
IA (Status - Paid/Pending, not future effective):
Change of Address (Status - Completed):
Change of Address  (Status - Paid/Pending):
=> 24629 - update logic to show effective date

legal-api/src/legal_api/services/business_details_version.py
*Issue #:* /bcgov/entity#24481
=> 24481 - Fix versioned business issue for loading placeholder state filing

jobs/furnishings/flags.json, legal-api/flags.json, legal-api/src/legal_api/models/resolution.py, legal-api/src/legal_api/resources/v2/business/colin_sync.py, queue_services/entity-bn/flags.json, queue_services/entity-emailer/flags.json
*Issue #:* /bcgov/entity#22955
1. Investigated the job's functionality:
- Job only handles API calls from legal-api and colin-api
- No direct DB operations
- No legal-api and db versioning package usage
2. Conclusions:
- No changes needed in db versioning setup
- Remove the update-colin-filings flag in legal-api's flags.json
3. Findings of db versioning relationship issue:
- Found versioned objects (BusinessVersion) missing relationship attributes (`Resolutions`)
- Root cause:       
- Our db versioning only copies table columns but misses the relationship mappings
- When versioning is enabled, `BusinessVersion` lacks the `resolutions` relationship that exists in the original Business model
- Solutions:
- Added direct Resolution query to replace relationship …
=> 22955 - Verify update-colin-filings job to use new db versioning

data-tool/flows/common/auth_service.py, data-tool/flows/common/corp_processing_queue_service.py, data-tool/flows/corps_tombstone_flow.py, data-tool/flows/tombstone/tombstone_queries.py, data-tool/scripts/colin_corps_extract_postgres_ddl
*Issue #:* /bcgov/entity#24478
* Add `claimed_at` and `flow_run_id` fields to `corp_processing` table
* Add `CorpProcessingQueueService`.  This differs a bit from what we had done previously for firms and old corps pipeline.  The underlying `corp_processing` table is still fully intact but this service has been re-implemented to handle parallel flows.  In particular a concept of reserving corps for a given flow run and claiming a batch of reserved corps has been introduced.  It hasn't been fully implemented but enough to handle the general flow of loading a tombstone corp from start to finish.  Error handling corp processing status updates still needs to be handled.  This work will take place in the future.  The batch logic in tombstone flow is also still a bit …
=> 24478 Add corp processing logic to tombstone pipeline

legal-api/flags.json, queue_services/entity-filer/flags.json, queue_services/entity-filer/requirements.txt, queue_services/entity-filer/src/entity_filer/config.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/__init__.py
*Issue #:* /bcgov/entity#22945
- Updated filer to use new db versioning
_Note: the 2 failed tests are because I did not have my NATS server running, but the rest of the tests pass._
Running the filer and legal api with FFs off results in a business_version with id=58116 and transaction_id=1077830
Running the filer and legal api with FFs on results in a business_version with id=58116 and transaction_id=1077831. The different transaction ids between test runs are because I used the same db instance and manually adjusted the test data, so it grabbed the next transaction_id in the sequence. However, we can see the new versioning working correctly here.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
=> 22945 Filer - Updated to use new db versioning

queue_services/business-pay/src/business_pay/resources/pay_filer.py
*Issue #:* /bcgov/entity#24826
- Disable publishing to emailer to avoid too many NATS error messages in GCP logs
=> 24826 - Disable publishing to emailer when sandbox FF is on

queue_services/entity-filer/src/entity_filer/version.py
*Issue #:* /bcgov/entity#24764
* Updated the version number of entity_filier for 23.5b release
=> 24764 - Bump version up for 23.5b release

queue_services/entity-filer/src/entity_filer/resources/worker.py
- Found an issue that the message is pushed back to filer infinitely in retention duration, even after the retry policy and dead letter topic are configured in GCP. This PR is trying to solve this issue.
- Let me know if you have any better thoughts ⭐ 
=> 24830-5 Tweak status code to avoid infinite retries before message is expired

legal-api/src/legal_api/services/authz.py
*Issue #:* /bcgov/entity#24952
Updated the logic for allowable actions to enable update Notice of Withdrawal draft. This change is only within scope for regular/existing businesses. The support of allowable actions for temporary business will be done in https://github.com/bcgov/entity/issues/24987
- Can file NoW and NoW draft
- But cannot update the draft using `PUT` method with endpoint `/api/v2/businesses/:identifier/filings/:filing_id?draft=true`
Able to update NoW draft using the endpoint and method mentioned above.
- Create a Draft
- Update this Draft
- Allowable Actions: there is no NoW or NoW draft, NoW filing is allowed
- Allowable Action: after a NoW draft is created, NoW filing is not allowed anymore
- Try to create the **second** draft when there is …
=> 24952 - Fix not allow to update NoW draft issue

docs/business.yaml, legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
*Issue #:* /bcgov/entity#22169
**Adding items listed below to the api specs**
- Notice of Withdrawal Schema
- Sample request
- Sample responses
**Specs Render Screenshots:**
- Overview
- Sample Request
- Sample Request with Options
- Sample Response - successful
- Sample Response - 400
- Sample Response - 401
- Sample Response - 404
=> 22169 - api specs notice of withdrawal

legal-api/src/legal_api/models/business.py, legal-api/tests/unit/models/test_business.py, queue_services/entity-filer/src/entity_filer/worker.py
*Issue #:* /bcgov/entity#24195
- Will create a post deployment script to update existing data in DB
=> 24195 updating last_modified with filing completion_date

queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/bcregistry-libraries.txt, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py, queue_services/entity-filer/src/entity_filer/filing_processors/put_back_off.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/filing_processors/test_annual_report.py, queue_services/entity-filer/tests/unit/filing_processors/test_put_back_off.py
*Issue #:* /bcgov/entity#25040
- Added put back off filing processor to handle expired limited restoration filings
- Implemented unit tests for put back off filing processor
=> 25040 - Filer put back off

legal-api/src/legal_api/services/bootstrap.py, queue_services/entity-filer/filer_service.py, queue_services/entity-filer/src/entity_filer/filing_processors/admin_freeze.py, queue_services/entity-filer/src/entity_filer/filing_processors/annual_report.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_name.py, queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py, queue_services/entity-filer/src/entity_filer/filing_processors/put_back_on.py, queue_services/entity-filer/src/entity_filer/filing_processors/special_resolution.py, queue_services/entity-filer/src/entity_filer/resources/worker.py, queue_services/entity-filer/src/entity_filer/services/gcp_auth.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/test_worker/test_incorporation.py
*Issue #:* /bcgov/entity#25023
=> 25023 Add more loggings for affiliation call and others

legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/v2/business/business.py, legal-api/src/legal_api/services/filings/validations/restoration.py, legal-api/src/legal_api/services/warnings/business/business_checks/firms.py, legal-api/tests/unit/models/test_filing.py, legal-api/tests/unit/services/filings/validations/test_restoration.py
*Issue #:* /bcgov/entity#24195
=> 24195 tweaks on filing queries

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#25159
This is a small change to avoid fill `temp_reg` field when we create a Notice of Withdrawal filing for a T business ([discussion link](https://teams.microsoft.com/l/message/19:cc93369433d341e7b5aa42b5ff78f7e0@thread.tacv2/1736275096889?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=00bd6377-9feb-44be-bbc8-19c3752a67b2&parentMessageId=1736270467592&teamName=External%3A%20SBC%20REG%20Modernization&channelName=Entities%20-%20Olga&createdTime=1736275096889))
File a NoW for a T business
After change, the `temp_reg` field is not filled when filing NoW for a T business:
=> 25159 - Update NoW filing not Saving temp_reg for T business

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#24820
- Embed NoW in the withdrawn bootstrap filing if the filing status = WITHDRAWN
1. Boostrap FE IA Status = PAID:
NoW is not embedded:
2. Boostrap FE IA Status = WITHDRAWN:
NoW is now embedded:
=> 24820 - Return embedded NoW filing for withdrawn bootstrap filing

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py
*Issue #:* /bcgov/entity#25387
- Add "WITHDRAWN" status to allowable statuses for filing history ledger fetched for regular businesses
Withdrawn Filing Status = WITHDRAWN
=> 25387-Add Filings with Withdrawn Status to Ledger

docs/business.yaml, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* /bcgov/entity#24772
- Update with hasTakenEffect and partOfPoa properties (see schema updates: https://github.com/bcgov/business-schemas/pull/172)
=> 24772-Update API Specs and Unit Test Mocks

colin-api/devops/vaults.json, colin-api/src/colin_api/config.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py, colin-api/src/colin_api/services/account.py, colin-api/src/colin_api/services/legal.py
*Issue #:* /bcgov/entity#25446
freeze a business if it exists only in LEAR
Branched off from https://github.com/bcgov/lear/tree/release-2.136.0 (Sev created this yesterday)
- add service to call legal-api business endpoint
- add logic to freeze a business only if found in LEAR
BC Limited company created in in DEV:
https://dev.business-dashboard.bcregistry.gov.bc.ca/BC0887528/?accountid=3040
Record in CDEV after COLIN sync was complete:
=> 25446 - add check for lear businesses before freezing corps

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/models/filing.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#25328
- Add special case for NoW when getting a filing for a temp business
- Update requirements for NoW Schema changes (https://github.com/bcgov/business-schemas/releases/tag/2.18.33)
Post new NoW DRAFT:
- withdrawn filing id = 156853
- notice of withdrawal id = 156943
Get NoW DRAFT (156943):
Update and Save NoW DRAFT:
Params:
Body (updating certifiedBy field):
Response:
Get NoW DRAFT to confirm update was saved:
=> 25328 - Support Update and Save NoW Draft for Bootstrap Filing

legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
*Issue #:* /bcgov/entity#24988 /bcgov/entity#25418
[Receipt.pdf](https://github.com/user-attachments/files/18528329/Receipt.pdf)
[Notice_of_Withdrawal.pdf](https://github.com/user-attachments/files/18528340/Notice_of_Withdrawal.pdf)
Outputs
[IA outputs.pdf](https://github.com/user-attachments/files/18579444/IA.outputs.pdf)
[Receipt-161949.pdf](https://github.com/user-attachments/files/18579447/Receipt-161949.pdf)
=> 24988 now documents temp business

legal-api/src/legal_api/version.py
*Issue #:* N/A
- bumped up the Legal API version before deployment to Test (only Legal API has changed since the last deployment)
=> Bumped Legal API version to 2.138.0

data-tool/flows/corps_tombstone_flow.py, data-tool/flows/tombstone/tombstone_base_data.py, data-tool/flows/tombstone/tombstone_queries.py, data-tool/flows/tombstone/tombstone_utils.py, legal-api/report-templates/template-parts/common/businessDetails.html, legal-api/src/legal_api/models/comment.py, legal-api/tests/unit/models/test_comments.py
*Issue #:* /bcgov/entity#25419
*Side Issue #:* /bcgov/entity#25508  /bcgov/entity#25504
- Load users for comments
- Load staff comments at business level
- Load staff comments at filing level
- Two types
- general filing comment
- filing comment coming with conversion ledger
- Note that conversion ledger may have two types of filing comments at the same time
- Some fix in legal-api for this work
- Update TODOs
_Testing_
The following businesses are loaded in dev and affiliated to account `3446`, but some are not properly displayed due to legal-api error. Since conversion ledger work is in progress, I used name `Conversion Ledger` as placholder for this filing and make this category display in UI when I loaded data into dev.
```python
BC0000921  # multiple …
```
=> 25419 - Tombstone - support staff comments

queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/test_worker/test_correction_bcia.py
*Issue #:* /bcgov/entity#25393
A little bit of background for this change.
We worked on a Jupyter Notebook to run Corrections for BEN statements. This will be a system file Correction filing with No Fee. This just adds a correction statement as Comment. We need to suppress any emails generated for such Corrections filing.
=> 25393 - Suppress emails for system file BEN Corrections Statement

legal-api/src/legal_api/core/filing.py, legal-api/tests/unit/core/test_filing_ledger.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings_ledger.py
*Issue #:* /bcgov/entity#25578 
- Add withdrawalPending property to commonLedgerItems
=> 25578 - Expose WithdrawalPending Property in CommonLedgerItems for FE 

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#25641 
- Previously we were only embedding the NoW once the bootstrap filing was processed and `status == WITHDRAWN`, now we also want to display the NoW when boostrap filing is pending and waiting to be processed (i.e. `withdrawal_pending == True`)
- Updated the conditions to also embed a NoW when `withdrawal_pending == True`  
- Updated unit tests
`withdrawal_pending == True` 
`withdrawal_pending == False` but `status == WITHDRAWN`
=> 25641 - Update NoW Embedding Conditions

queue_services/entity-filer/src/entity_filer/filing_processors/notice_of_withdrawal.py, queue_services/entity-filer/tests/unit/filing_processors/test_notice_of_withdrawal.py, queue_services/entity-filer/tests/unit/test_worker/test_worker.py
=> 23352 update fe filing meta

data-tool/flows/corps_tombstone_flow.py, data-tool/flows/tombstone/tombstone_base_data.py, data-tool/flows/tombstone/tombstone_mappings.py, data-tool/flows/tombstone/tombstone_queries.py, data-tool/flows/tombstone/tombstone_utils.py, legal-api/migrations/versions/d0b10576924c_alter_amalgamation_type_enum.py, legal-api/src/legal_api/models/amalgamation.py, legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/models/jurisdiction.py, legal-api/src/legal_api/reports/business_document.py, legal-api/tests/unit/models/test_amalgamation.py
*Issue #:* /bcgov/entity#24593
- Support conversion in pipeline
- exclude liquidation, involuntary dissolution, continuation out related events
- add TODOs in the code
- Update legal-api to display conversion state changes in summary
- Alter `amalgamation_type` in db & data model to add `unknown` enum
- Misc updates for pipeline and legal-api
_Testing_
The following businesses are loaded in dev and affiliated to account `3446`, but some business summaries are not properly displayed before the changes are merged.
```python
BC0019921
BC0383434
BC0073657
BC0690494  # cannot load into dev due to amalgamation type error
C0318245
C0158429
BC0640661
``` 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
=> 24593 Tombstone pipeline - implement conversion (exclude liquidation, invol dissolution, cont out)

data-tool/.corps.env.sample, data-tool/flows/batch_delete_flow.py, data-tool/flows/config.py, data-tool/flows/corps_tombstone_flow.py, data-tool/flows/tombstone/tombstone_base_data.py, data-tool/flows/tombstone/tombstone_mappings.py, data-tool/flows/tombstone/tombstone_queries.py, data-tool/flows/tombstone/tombstone_utils.py, legal-api/src/legal_api/reports/business_document.py, legal-api/src/legal_api/services/warnings/business/business_checks/involuntary_dissolution.py
*Issue #:* /bcgov/entity#25678 /bcgov/entity#25672
- Add in-dissolution information in tombstone data set
- Updates for conversion involuntary dissolution
- Update delete script
- Misc fix
Testing
The following businesses are loaded in dev and affiliated to account `3446` (add this account into involuntary dissolution filter so that things work, but the legal-api is buggy somewhere)
```python
BC0588870 # by SYSD1
BC0546050 # by DISD1 (delay of dissolution 1)
BC0550140 # by DISD2 (delay of dissolution 2)
BC0670410 # by ADCORP
BC0600187 # by FILE (change of address)
BC0585930 # by SYSD2
BC0703023 # by DISD1 (delay of dissolution 1)
BC0576833 # by DISD2 (delay of dissolution 2)
BC0927679 # by ADCORP
BC0546311 # by FILE (change of address)
```
```python
BC0617448 # …
```
=> 25678 Tombstone - Updates for involuntary dissolution

legal-api/src/legal_api/models/filing.py
*Issue #:* /bcgov/entity#25863
- Add status WITHDRAWN to the incomplete filing check, fix the Allowable actions bug
=> 25863 - Enable Allowable actions after a successful NoW filing

legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/office.py, python/common/sql-versioning/sql_versioning/versioning.py, python/common/sql-versioning/tests/__init__.py, python/common/sql-versioning/tests/test_versioning.py, queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_shares.py
*Issue #:* /bcgov/entity#24628
This fix ended up needing 3 things:
1. In order to use `<parent>.remove(<child>)` and have the child be deleted from the table, the relationship needs `cascade='delete-orphan'`. This is already the case for resolutions, but I added it to the versioning tests as well.
2. For whatever reason, the parent side of the relationship also needs `backref=<parent>`, otherwise we always get `operation_type=0` (created). This however results in the child version entries that were removed getting `operation_type=1` (updated).
3. In order to properly assign `operation_type=2` on cascade deleted orphans I needed to add some custom logic to versioning.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> 24628 Get remove() function working for db versioned relationships

legal-api/src/legal_api/resources/v2/business/colin_sync.py
*Issue #:* /bcgov/entity#24628
In Colin Sync, update to use a work around to fix the issue when trying to get amalgamation filings sync to colin.
**Before -- when running `update-colin-filings` job**
Log from the job:
Corresponding log from legal-api:
**After change:**
Local Run = Local db + Local legal-api + Local update-colin-filing job + DEV colin-api
=> 24628 - update a work around to get resolution versioning data

legal-api/report-templates/template-parts/common/businessDetails.html
*Issue #:* /bcgov/entity#26028
- For NoW for temp business output, Show blank recognition date/time, because the application was withdrawn
- For IA/Amagl/ContIn output, Show blank recognition date/time, when the time not come to pass
=> 26028 - Show blank recognition date/time if the application was withdrawn/not come to pass

data-tool/flows/tombstone/tombstone_mappings.py, data-tool/flows/tombstone/tombstone_utils.py
*Issue #:* /bcgov/entity#24691
- Updates for expired restoration
- Remap `CO_PO`, `AM_PO` to put back on
- Remap `CO_PF`, `AM_PF` to put back off
Note that legal-api changes of summary for put back off need to wait until release branch merges back to main.
_Testing_
- expired restoration
```python
BC0484448 # RESTL
BC0763194 # RESXL
```
- put back on/off
```python
BC1150455 # CO_PO
BC0296354 # CO_PF
```
=> 24691 - Updates for expired restoration & remap put back on/off

legal-api/src/legal_api/core/meta/filing.py
*Issue #:* /bcgov/entity#25940
- The bug is: file a NoW for a Voluntary Dissolution -> the Filing History is empty
- Cause: there is a key error when read filing.meta_data[dissolution]
- Fixed: add a check 
=> 25940 - Fix the Filing History Bug after withdraw a VD

legal-api/src/legal_api/models/db.py, python/common/sql-versioning/sql_versioning/utils.py, python/common/sql-versioning/sql_versioning/versioning.py
*Issue #:* /bcgov/entity#23001 
- Reduce DB Versioning Debugging Logs to Minimal
- Only keep showing the current db-versioning type (new / old) to help us quickly identify whether FF switching works or not)
**For a same API call:**
**Before**
**After**
=> 23001 - Reduce DB Versioning Debugging Logs to Minimal

queue_services/entity-bn/src/entity_bn/version.py, queue_services/entity-digital-credentials/src/entity_digital_credentials/version.py
*Issue #:* /bcgov/entity#25779
- entity-bn v2.142.0
- entity-digital-credentials v2.142.0
- Other component versions already bumped during release branch merge https://github.com/bcgov/lear/pull/3251
=> Bump db versioning component versions to 2.143.0

data-tool/flows/tombstone/tombstone_queries.py, data-tool/flows/tombstone/tombstone_utils.py, data-tool/scripts/colin_corps_extract_postgres_ddl, data-tool/scripts/transfer_cprd_corps.sql
*Issue #:* /bcgov/entity#25870
- Update extract to include payment info
- Update extract for Q* type to merge them into BC (revert [previous changes](https://github.com/bcgov/lear/pull/3177))
- Update user info formatting for filing submitter and business comment staff (There's one exception of filing comment where staff is BCOMPS and we haven't looked into it. But no bad impact in this work)
_Testing_
```python
BC0642190 # null, anon
BC0935488 # bcol, anon, staff
BC1283244 # reg
BC1235881
BC0820915
BC0503592
BC0672944
BC0000921
``` …
=> 25870 Tombstone - Extract updates & filing submitter and staff user info updates

.github/workflows/legal-api-ci.yml
*Description:*
This is a test to resolve this error:
It is related to the recent update of the GitHub runner for this script -- Ubuntu-24.04 (instead of previous 20.04).
=> 26204 try setup-python v5

legal-api/src/legal_api/models/db.py, python/common/sql-versioning/sql_versioning/__init__.py
*Issue #:* /bcgov/entity#26262
- Removed the remaining `debug` in `__all__`
- Change logging to only print out when a service initialized, and when switching versioning
**Screenshots after change:**
Legal-API:
Emailer:
Filer:
**Local Linting and Testing Results**
Since we currently have some issues in the legal-api CI, here are screenshots for local linting and testings resutls
=> 26262 - Minimize DB Versioning Logging

legal-api/report-templates/template-parts/business-summary/stateTransition.html, legal-api/src/legal_api/reports/business_document.py
*Issue #:* /bcgov/entity#26269
- As requested, show expiry date instead of effective date with no time stamp
=> 26269 - Show expiry date instead of effective date

jobs/email-reminder/email_reminder.py, jobs/furnishings/src/furnishings/worker.py, jobs/involuntary-dissolutions/involuntary_dissolutions.py, queue_services/entity-bn/src/entity_bn/worker.py, queue_services/entity-digital-credentials/src/entity_digital_credentials/worker.py, queue_services/entity-emailer/src/entity_emailer/worker.py, queue_services/entity-filer/src/entity_filer/worker.py
*Issue #:* /bcgov/entity#26262
Try to solve the issue of not seeing db-versioning loggings suppose to be printed out when a service starts
- change importing level from `legal_api` to `legal_api.models.db` for importing `init_db` in BE components
=> 26262 - change init_db importing approach

legal-api/src/legal_api/models/db.py
*Issue #:* /bcgov/entity#26262
change logging approach to use `logger.info` to see if we'll be able to see loggings, and `logger.error` when not able to determine versioning type.
Known issue: won't be able to see it in Emailer, since the LOG_Level has been set to ERROR
When switching db versioning:
=> 26262 - change logging approach

legal-api/report-templates/template-parts/business-summary/stateTransition.html, legal-api/src/legal_api/reports/business_document.py, legal-api/src/legal_api/utils/legislation_datetime.py
*Issue #:* /bcgov/entity#26298 
- As requested, display the effective date as the day after the expiry date (i.e. if expiry date is February 20, 2025, then the effective date should be February 21, 2025)
=> 26298 - Display Historical Date instead of Effective Date

legal-api/flags.json, legal-api/src/legal_api/resources/v2/business/business_documents.py
*Issue #:* /bcgov/entity#26321
- Added `enable-business-summary-for-migrated-corps` FF
- Added logic to hide/show business summary for tombstone corps based on FF
Flag ON (show summary)
Flag OFF (hide summary)
=> 26321 Hide business summary for tombstone corps

legal-api/src/legal_api/services/bootstrap.py
*Issue #:* /bcgov/entity#25831
Try to fix the Auth Get Call by adding the `headers` parameter keyword
=> 25831 - fix get call bug

data-tool/flows/common/corp_processing_queue_service.py, data-tool/flows/corps_tombstone_flow.py, data-tool/flows/tombstone/tombstone_base_data.py, data-tool/flows/tombstone/tombstone_mappings.py, data-tool/flows/tombstone/tombstone_queries.py, data-tool/flows/tombstone/tombstone_utils.py
*Issue #:* /bcgov/entity#26143 /bcgov/entity#26323
- Add `SKIPPED_EVENT_FILE_TYPES` list for types that we don't need to migrate
- Add `NO_FILING_EVENT_FILE_TYPES` list for types that we don't map to filings but we bring data over
- Add unsupported event_file_type info for each corp
- Update statistic info
_Testing_
1. Local
2. Dev
```python
BC1252541  # SYST event
BC0943825  # FILE_TILMA
BC1517634  # FILE_COGS1
BC1267803  # FILE_NOAPL
C1089184   # FILE_LIQUR
```
=> 26143 & 26323 Tombstone - allow skipped event_file types & partial processed_status

legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/core/meta/filing.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py, legal-api/tests/unit/resources/v2/test_business.py, legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py, legal-api/tests/unit/services/test_authorization.py
*Issue #:* /bcgov/entity#26487
- Add Record of Amalgamate Out Filing Type, support Save and update draft
- Add Allowable action item for Amalgamate Out, restricted to staff only
- Add checks to prevent filing when:
Business is "Not in Good Standing"
Business has a pending or draft filing
=> 26487 - Support save amalgamation out draft

colin-api/src/colin_api/models/filing.py
*Issue #:* bcgov/business-ar/issues/544
1. Fixed an issue in the _get_last_ar_filed_date method to properly handle February 29th dates when the filing year is not a leap year. The changes include:
2. Added logic to detect when a founding date is February 29th (leap day)
Implemented standard leap year calculation to determine if the filing year is a leap year:
- A year is a leap year if divisible by 4
- Except if divisible by 100, unless also divisible by 400
3. When the founding date is February 29th but the filing year is not a leap year, the code now returns February 28th instead
This prevents generating invalid dates like "2025-02-29" which would cause errors
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> fix: Handle February 29 leap year edge case

legal-api/flags.json, legal-api/src/legal_api/config.py, legal-api/src/legal_api/resources/v2/business/business.py, legal-api/tests/unit/resources/v2/test_business.py
*Issue #:* /bcgov/entity#22143
Add auth check for business endpoint v2. Public account with new 'view' role should not access full business information. (the slim version data is still available for public)
=> 22143 - Add auth check for legal-api business endpoint v2

data-tool/flows/tombstone/tombstone_queries.py
*Issue #:* /bcgov/entity#26950
* Update parties query in tombstone pipeline to include ceased parties data
**Test notes:**
Have loaded some early adopters corps into dev with this update so we can compare the same corps in test:
'BC1507445','BC1507435','BC1292656','BC1249698','BC1196188'
In particular, I did some testing with BC1196188 as it tested the scenario where an AR was referencing a ceased director.  You can observe that the filing json for the AR is different in dev & test.  The corp in dev correctly files the AR with the ceased director.
filing json for AR
=> 26950 Update tombstone pipeline to included ceased party data

data-tool/flows/tombstone/tombstone_utils.py
*Issue #:* /bcgov/entity#27011
* Update to pipeline to include grouping by cessation date.  Without this, if there is an active and ceased party(officer or director) that both matches against the current group by criteria(full name + role), the pipeline maps to the same party in LEAR.  This causes an issues as the address may not be the same
Loaded problem corp into test and compared with prod - BC1249698.  Note that I mostly checked all the early adopter corps to see if parties were still loading correctly.  seemed like the parties were still loaded correctly
=> 27011 Fix director address mismatch issue

data-tool/flows/tombstone/tombstone_queries.py
*Issue #:* /bcgov/entity#27043
- Updated offices_held query to include data for ceased officers.
I used BC0006247 from the prod extract for testing. Running the tombstone pipeline before implementing this update resulted in 2 entries in `offices_held`
Running the tombstone pipeline after implementing this update resulted in 3 entries. The new entry is the ceased officer entry.
=> 27043 Tombstone pipeline - Update offices_held query to include data for ceased officers

legal-api/src/legal_api/services/bootstrap.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/filing_processors/test_registration.py, queue_services/entity-filer/tests/unit/test_worker/test_incorporation.py
*Issue #:* /bcgov/entity#27091
Remove sandbox environment override code as we now have a standalone sandbox auth API. 
Changes include:
1. Remove Environment-Override header in `get_account_by_affiliated_identifier` & `create_affiliation` method
2. Remove FFs import and parameter
3. Clean up unused flags-related code
=> 27091 - Remove sandbox environment override code

queue_services/entity-filer/scripts/sandbox.sql
*Issue #:* /bcgov/entity#26431
- Update sandbox.sql to include the auth db sql required to determine the correct business identifier sequence nums to be used in LEAR db.  The previous script worked the first time but subsequent LEAR db syncs to sandbox would result in collisions with auth db.
Example of auth db portion of script.  The next_sequence_number value would be used in the LEAR portion of the script for the corresponding business identifier sequences.
=> 26431 Update post LEAR db sandbox sync sql script

python/common/sql-versioning-alt/src/sql_versioning/versioning.py, python/common/sql-versioning-alt/tests/__init__.py, python/common/sql-versioning-alt/tests/test_versioning.py, python/common/sql-versioning/sql_versioning/versioning.py, python/common/sql-versioning/tests/__init__.py, python/common/sql-versioning/tests/test_versioning.py
*Issue #:* /bcgov/entity#27078
- Fix relationships orphans not getting deleted when cascade="delete, delete-orphan" is set
*Analysis:*
- Cascade delete on an orphaned record removes the non versioned records without issue. It properly creates the version record for the orphaned record. It does not however create the version record for cascade deleted records. 
```
parent.remove(child)
```
- This could be because SQLAlchemy emits a DELETE command for the child to grandchild relationship, but the grandchild object does not actually get added to session.delete or session.dirty. In order to resolve this we need to manually add the grandchild object to session.deleted before it is flushed.
_Testing:_
- Verified that all tables created correctly for
``` …
```
=> 27078 Versioning - Cascade delete relationship orphans

legal-api/report-templates/letterOfConsent.html, legal-api/report-templates/letterOfConsentAmalgamationOut.html
*Issue #:* /bcgov/entity#27144
- Update the output tittle to say "Consent Letter" when open the pdf in the tab (for both CCO and CAO)
=> 27144 - Update Output Title for CCO and CAO Consent Letter

colin-api/src/colin_api/models/filing.py, jobs/correction-ben-statement/add_corrections.ipynb
*Issue #:* /bcgov/entity#27376
Based on recent discussions with business it was requested to have NOA for BEN correction statements. (NOA is still suppressed for Correction on the ledger/empty correction)
To enable it, removed `"commentOnly": True` from BEN correction statement job payload and added a check for `correctionBenStatement` to sync this back to COLIN
Test in DEV: https://dev.business-dashboard.bcregistry.gov.bc.ca/BC0887853?accountid=3040
=> Include NOA for BEN correction statements

colin-api/src/colin_api/models/filing.py
*Issue #:* /bcgov/entity#27375
Removed comment for Dissolution sync
I looked in the code and looks like this is an issue only for Voluntary Dissolution. Involuntary and Administrative dissolutions update corp state and make it historical.
=> 27375 - Remove comment for Dissolution sync

legal-api/src/legal_api/__init__.py
*Issue #:* /bcgov/entity#27492
- add missing `Access-Control-Allow-Origin` header to Auth Error Handler 
- remove unused redirect import from `flask`
=> 27492 - Add Custom Auth Handler with Missing Header

legal-api/report-templates/template-parts/common/correctedOnCertificate.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#27199
- Use the current registrar's info instead of the original registrar's info for corrections
Before changes:
After:
=> 27199 - Use current registrar info for corrections

queue_services/business-filer/Dockerfile, queue_services/business-filer/Makefile
*Issue #:* /bcgov/entity#26307
- removed dangling \ in Makefile
- updated Dockerfile for ENV default to "production"
=> fix: dockerfile change default env to "production"

data-tool/flows/batch_delete_flow.py, data-tool/flows/tombstone/tombstone_queries.py, data-tool/flows/tombstone/tombstone_utils.py
*Issue #:* /bcgov/entity#26973
**Note that the logic updates are excluding officer for now until further notice**
- Update logic to bring over ceased parties for
- director
- liquidator
- receiver
- custodian
- Update logic to get appointment date
- Misc updates
_Testing_
The following businesses are loaded in dev and affiliated to account `3446` (most businesses are affiliated except BC1249698 and BC0878472)
```python
BC0000621
BC1249698  # person with the same was appointed at different period of time
BC0018656  # person with the same was appointed as both director and officer
BC0752755
BC0318959  # liquidator updated by filings, ceased liquidator
BC0835125 # 2 receivers with the same name and colin keeps both of them
BC0231750
BC0043660 # ceased receiver …
```
=> 26973 Tombstone - add ceased parties

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
*Issue #:* /bcgov/entity#27621
- Fix the error by omitting the contactInfo when the mailing_address is none
=> 27621 - Fix Error filing COA

legal-api/src/legal_api/errorhandlers.py
*Issue #:* /bcgov/entity#27641
- Improved error handling for 500 errors, focusing on scenarios most frequently encountered by API users (as discussed on Discourse) and in our internal tests.
- Most uncaught errors we found that return a 500 error are:
`KeyError`: when required keys are missing/invalid in the filing json.
`AttributeError`: when fields have unexpected types or structures.
`TypeError`: due to invalid value types in the database or submitted payload.
So, for each error type we found, we improved the return message and status code to help give API users more useful information.
**Local Testing Results**:
`KeyError` issue:
- when required fields are invalid: (given an invalid field in the URL: …
=> 27641 - Improve 500 error response

legal-api/flags.json, legal-api/src/legal_api/models/party_role.py, legal-api/src/legal_api/services/business_details_version.py, legal-api/tests/unit/models/test_party_role.py, python/common/business-registry-model/src/business_model/models/party_role.py, python/common/business-registry-model/tests/models/test_party_role.py
*Issue #:* /bcgov/entity#28413
- Update both legal-api and business-registry-model
- Hide unsupported roles ~~based on FF~~
~~**I've turned the flag on for dev/test/prod.**~~
_Testing_
- default view 1
- query officer
- query receiver
- default view 2
- query liquidator
- query liquidator with end date
=> 28413 Legal API - Hide unsupported party roles based on FF

queue_services/business-pay/src/business_pay/resources/pay_filer.py
*Issue #:* /bcgov/entity#28618
Set the filing.payment_completion_date to the datetime of the payment CloudEvent, if missing use now()
=> fix(business-filer): set payment_completion_date to the datetime of the payment CloudEvent

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/services/filings/validations/alteration.py, legal-api/src/legal_api/services/filings/validations/amalgamation_application.py, legal-api/src/legal_api/services/filings/validations/common_validations.py, legal-api/src/legal_api/services/filings/validations/continuation_in.py, legal-api/src/legal_api/services/filings/validations/correction.py, legal-api/src/legal_api/services/filings/validations/dissolution.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_alteration.py, legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py, legal-api/tests/unit/services/filings/validations/test_continuation_in.py, legal-api/tests/unit/services/filings/validations/test_correction_ia.py, legal-api/tests/unit/services/filings/validations/test_dissolution.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_registration.py
*Issue #:* /bcgov/entity#28460
For this PR, we primarily added and updated BE validations for the corps type business to ensure validation consistency with FE in the sandbox.
* Added backend validation to ensure corps-type companies cannot have share series when hasRightsOrRestrictions is false.
* Aligned with FE logic. The UI prevents users from adding series if the share class does not have rights or restrictions.
* Added validations for parties' delivery addresses in multiple filing types to match FE behavior, including:
1. IA Corps
2. Amalgamation Application(Regular type) Corps 
3. Continuation In Corps 
* Added backend validations for parties, custodial office, and email fields in voluntary dissolution filings.
* These fields are required on the FE but were …
=> 28460 - Add Backend validations for FE/BE mismatch in sandbox

data-tool/flows/batch_delete_flow.py, data-tool/flows/common/init_utils.py, data-tool/flows/corps_tombstone_flow.py, data-tool/flows/corps_verify_flow.py, data-tool/requirements.txt, data-tool/requirements/prefect.txt
*Issue #:* /bcgov/entity#29109
* Update to use prefect 3.4.6
* Add `cache_policy=NO_CACHE` param + value to prefect task decorators.  Without this, errors are thrown each time a prefect task is called.
=> 29109 Update to prefect 3.4.6

legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#28628
- Fix the bug that sometimes can't download the Letter of AGM Extension
- The issue is with the "expireDateCurrExt" (Expiry date for current extension) property in meta data.
=> 28628 - Fix-Bug-Download-Letter-of-AGM-Extension

data-tool/backup_extract_tables.sh, data-tool/restore_extract.sh, data-tool/scripts/colin_corps_extract_postgres_ddl
*Issue #:* /bcgov/entity#29204
* Misc updates to COLIN extract ddl as migration tables ordering was incorrect and ddl failed to create initial skeleton tables
* Add shell script(`backup_extract_tables.sh`) to back up data for specific extract tables
* corp_processing
* colin_tracking
* mig_group
* mig_batch
* mig_corp_batch
* corps_with_third_party
* Add shell script(`restore_extract.sh`) to restore data for specific extract tables.  Note: there are some TODOs in this script as there is some future work to maybe integrate the extract transfer script into this this script.
**Example run details:**
=> 29204 Add scripts for backing up and restoring specific COLIN extract tables

legal-api/src/legal_api/services/search_service.py
*Issue #:* /bcgov/entity#
Hotfix for search endpoint
- updated early return if no filings being searched.
limit is always being set by default so would be always search filters, no identifiers then return early
=> Hotfix for Search

data-tool/restore_extract.sh
*Issue #:* /bcgov/entity#29204
- Add logic to empty data in tables that will be restored with data dump(e.g. `keep_2025-07-11.dump`) generated from `backup_extract.sh`
- Update sequence logic so it properly updates sequences that use nextval pattern as opposed to serial/identity method in postgres
=> 29204 Tweaks to restore extract script

docs/business.yaml
*Issue #:* /bcgov/entity#29516
Add `effectiveDate` to AR payload, update specs and postman collection
Ref: Discourse link of original API user question https://discourse.onebc.ca/t/annual-report-date/545/3
=> 29516 - add effective date to AR filing payload

legal-api/src/legal_api/services/business/validations/validator.py, legal-api/tests/unit/services/business/validations/test_validator.py
*Issue #:* /bcgov/entity#29785
- update validator to allow BCBCA types
- add tests for the new business types and document combinations
=> feat(api): allow all the BCBCA types to retrieve these documents

legal-api/src/legal_api/resources/v2/business/business_documents.py, legal-api/src/legal_api/services/business/validations/validator.py, legal-api/tests/unit/resources/v2/test_business_documents.py
*Issue #:* /bcgov/entity#27028 
- Also check correction filings for any resolutions when retrieving COOP Docs and Info
- Refactored logic into helpers due to `too-many-locals` lint warning 
=> 27028 - Update Logic to Retrieve COOP Docs and Info from Correction

legal-api/src/legal_api/resources/v2/business/business_documents.py
*Issue #:* /bcgov/entity#27078 
- Caught while testing in Dev, `includedInResolution `and `includedInResolutionDate `flags should be set regardless of whether the doc exists
Ex: 
=> 27078 - Fix IncludedInResolution flags

queue_services/business-bn/src/business_bn/bn_processors/registration.py
*Issue #:* /bcgov/entity#29929
Account service is throwing an issue on get_bearer_token when the business-bn processes it. This is because it is importing the service incorrectly, fixed the import
=> Fix error on business incorporation

legal-api/src/legal_api/services/digital_credentials_rules.py, legal-api/src/legal_api/services/digital_credentials_utils.py, legal-api/tests/unit/services/test_digital_credentials_helpers_and_utils.py, legal-api/tests/unit/services/test_digital_credentials_rules.py
*Issue #:* /bcgov/entity#28990
See details in linked ticket. Minor tweak so app context name (instead of `root`) shows up in a couple files. Remove unneeded log assert in unit tests that isn't done anywhere else (coverage and business rules covered in tests).
=> 28990: Tweak log context

.gitignore, data-tool/flows/tombstone/tombstone_utils.py
*Issue #:* /bcgov/entity#30276
Before:
After:
The submitter_roles is now set to staff if the filing was done as staff in COLIN
=> 30276 - Set submitter_roles to staff if filing was done by staff

colin-api/src/colin_api/models/filing.py
*Issue #:* /bcgov/entity#29946
Update the process for restoration to NOT sync comment (ledger text)
=> 29946 - do not sync COA text/comment for restoration

data-tool/scripts/data-fixes/backfill_cutoff_filing_id.sql
*Issue #:* /bcgov/entity#30319
- Created the SQL script file
- The file has two parts:
- Main query that actually populates the backfill_cutoff_filing_id
- Queries for verification purposes
Before running the main SQL query:
SQL Query Run:
After running the main SQL query:
For filing 3285951, it's correct:
I also checked for all the others, they're also correct! 👍 
Now, I just need to run this query on dev and test before I add reviewers.
=> 30319 - Implemented SQL queries to populate backfill cutoff filing id

legal-api/src/legal_api/services/digital_credentials_helpers.py, legal-api/tests/unit/services/test_digital_credentials_helpers_and_utils.py
*Issue #:* /bcgov/entity#30628
Use the timezone helper so the correct date ends up in the string sent in the credential offer if the biz is registered after the time cutoff. Add unit test for the function that determines date.
=> DBC: adjust credential offer founding date to handle timezone

data-tool/scripts/data-fixes/backfill_cutoff_filing_id.sql
*Issue #:* /bcgov/entity#30319
All versioning records for matching businesses should have the end_transaction_id populated. Removed the IS NULL check.
=> 30319 - Fix to updating backfill_cutoff_filing_id in version table

legal-api/src/legal_api/services/filings/validations/agm_location_change.py, legal-api/src/legal_api/services/filings/validations/alteration.py, legal-api/src/legal_api/services/filings/validations/amalgamation_application.py, legal-api/src/legal_api/services/filings/validations/common_validations.py, legal-api/src/legal_api/services/filings/validations/continuation_in.py, legal-api/src/legal_api/services/filings/validations/dissolution.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/src/legal_api/services/filings/validations/restoration.py, legal-api/src/legal_api/services/filings/validations/validation.py, legal-api/src/legal_api/services/utils.py, legal-api/tests/unit/services/filings/validations/test_agm_location_change.py, legal-api/tests/unit/services/filings/validations/test_alteration.py, legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py, legal-api/tests/unit/services/filings/validations/test_common_validations.py, legal-api/tests/unit/services/filings/validations/test_continuation_in.py, legal-api/tests/unit/services/filings/validations/test_dissolution.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_restoration.py
*Issue #:* /bcgov/entity#30385 
- Add whitespace validation for **Agm Location Change** `reason `field
- Add whitespace validation for **Voluntary Dissolution** custodian of records -> `organizationName` field and `email` field
- Add whitespace validation for `certifiedBy ` field for **all filings**
- Add whitespace validation for `nameTranslation `field for **IA, Amalgamation, Cont. In, Alteration, Correction**
- Update existing `validate_series `and `validate_shares` method to include whitespace validation for share class name and share series name
- Update existing `validate_party_name` method to include whitespace validation for parties -> officer ->` firstName`, `middleName`/`middleInitial` and `lastName` + add 30 char limit for `lastName` field
- Add/update …
=> 30385 - Add Whitespace Validation

docs/business.yaml
*Issue #:* bcgov/entity#30654
- add officers info to spec
=> 30654 - officers spec
