docs/docs/.vuepress/config.js
=> added the "base" tag to the config as were not the primary repo for bcgov

docs/docs/.vuepress/config.js, docs/docs/guide/testing/annual-report-test-plan.md, docs/docs/guide/testing/quality-plan.md
Initial commit of some testing documents. I will review these with the team in the sprint review.
=> Added Quality plan and AR test plan to Guide section

docs/docs/guide/testing/quality-plan.md
Added more steps to the pre-release checklist in the Quality Plan.
Thor, let me know if you would prefer to have me upload these docs directly, rather than using pull requests.
=> Added more steps to the pre-release checklist

coops-ui/src/App.vue, coops-ui/src/assets/styles/base.styl, coops-ui/src/assets/styles/layout.styl, coops-ui/src/assets/styles/theme.styl, coops-ui/src/components/Tombstone.vue, coops-ui/src/views/Home.vue
Ticket 231
Adding initial markup/styling for Tombstone component.
=> [231] Add Tombstone UI Component

coops-ui/Jenkinsfile, coops-ui/openshift/Readme.md, coops-ui/openshift/templates/coops-ui-bc.tools.json, coops-ui/openshift/templates/coops-ui-dc.dev.json, coops-ui/openshift/templates/coops-ui-dc.prod.json, coops-ui/openshift/templates/coops-ui-dc.test.json, coops-ui/openshift/templates/coops-ui-inter-bc.tools.json, coops-ui/openshift/templates/coops-ui-service.devtestprod.json
=> 231 tombstone

coops-ui/Jenkinsfile
=> final (for now) pipeline changes for coops ui build pipeline

oracle/Dockerfile, oracle/ReadMe.md, oracle/bin/configDB2.sh, oracle/bin/configDBora2.sh, oracle/bin/dockerInit2.sh, oracle/bin/setupDB2.sh, oracle/bin/shutDB2.sh, oracle/bin/sleep, oracle/bin/startupDB2.sh, oracle/bin/uid_entrypoint, oracle/bin/untarDB2.sh, oracle/openshift/oracleDeploymentConfig.yaml
*Issue #:bcgov/entity#164*
- files needed for building/pushing the oracle image running in dev
=> 164 oracle pod

coops-ui/Jenkinsfile
*Issue #:* bcgov/entity#381
UI pipeline - added visual confirmation for confirmation when no changes.
=> UI pipeline - added visual confirmation for confirmation when no changes.

coops-ui/Jenkinsfile, coops-ui/Jenkinsfile-DevToTest, coops-ui/Jenkinsfile-TestToProd
*Issue #:* bcgov/entity#381
UI pipeline - tagging previous image
=> UI pipeline - tagging previous image

legal-api/manage.py, legal-api/pre-hook-update-db.sh, legal-api/pre_hook_create_database.py, legal-api/src/legal_api/__init__.py, legal-api/src/legal_api/resources/__init__.py, legal-api/src/legal_api/resources/ops.py, legal-api/tests/unit/api/test_ops.py, legal-api/wsgi.py
*Issue #:* n/a
Update legal-api for blueprints and db deployments
=> Update legal-api for blueprints and db deployments

legal-api/pre-hook-update-db.sh
*Issue #:* n/a
testing via pulls from the repo, missed a closing quote.
=> ack, fixed typo, testing from the repo pull

legal-api/tests/microcks/colin-api.postman_collection.json
*Issue #:* bcgov/entity#386
added first cut of colin api mock data - for microcks in postman format
=> added first cut of colin api mock data - for microcks in postman format

legal-api/tests/microcks/legal-api.postman_collection.json
*Issue #:* n/a
Adding the postman collection for the legal api, that can be used by microcks
=> mocks of the legal api

docs/docs/guide/testing/quality-plan.md
*Issue #:*
rogue-no ticket
Updated quality plan to include the normal flow of tickets through the new QA pipelines. To be used as a talking point between teams during sprint planning, backlog grooming and the next demo.
=> Updated quality plan to include ZenHub ticket flow for QA tasks.

coops-ui/src/store.ts
=> hardcoded aryear to 2018 for demo

coops-ui/public/index.html
=> changed keycloak location

legal-api/tests/microcks/colin-api.postman_collection.json, legal-api/tests/microcks/legal-api.postman_collection.json
*Issue #:* n/a
Adding postman exports to support microcks
=> adding postman exports for microcks

schemas/LICENSE, schemas/MANIFEST.in, schemas/Makefile, schemas/examples/annual_report.json, schemas/examples/curl_examples, schemas/requirements.txt, schemas/requirements/dev.txt, schemas/requirements/prod.txt, schemas/scripts/verify_license_headers.sh, schemas/setup.cfg, schemas/setup.py, schemas/src/registry_schemas/__init__.py, schemas/src/registry_schemas/schemas/business.json, schemas/src/registry_schemas/schemas/legal_filings.json, schemas/src/registry_schemas/utils.py, schemas/tests/unit/__init__.py, schemas/tests/unit/test_registry_schemas.py, schemas/tests/unit/test_validate_registry_schemas.py
*Issue #:* n/a
moved the JSONSchemas from the sub-projects and created as an installable library
=> moved registry schemas out of project, created as a library

coops-ui/public/config/configuration.json, coops-ui/src/main.ts, coops-ui/src/views/Home.vue
=> Switched to configuration for API URL.

colin-api/Jenkinsfiles/build.groovy, colin-api/openshift/colin-api-build-pipeline.param, colin-api/openshift/templates/colin-api-build-base.json, colin-api/openshift/templates/colin-api-build.json, colin-api/openshift/templates/colin-api-deploy.json, colin-api/openshift/templates/colin-api-pipeline.json, colin-api/requirements/testing.txt, colin-api/tests/__init__.py, colin-api/tests/unit/api/test_meta.py, colin-api/tests/unit/conf/test_version.py, colin-api/tests/utilities/decorators.py
*Issue #:* bcgov/entity#481
Colin API - scripts for builds, deployment, and pipeline.
Also prep for running pytests in pod, but no implementation.
=> 481 colin api openshift

coops-ui/package.json, coops-ui/src/axios-auth.ts, coops-ui/src/components/ARSteps/AGMDate.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/main.ts, coops-ui/src/store.ts, coops-ui/src/views/Home.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/EntityInfo.spec.ts, coops-ui/validators.ts
*Issue #:bcgov/entity#473*
- AR + entity info plumbing finished (payment integration + login from other team not covered)
- AR + entity call mocks currently
- entity values need to be looked at (hardcoded status + businessNum because they werent in the 
mock)
- payment calls a mock but no error checking except for the call succeeding
- jest tests added for ar + entity (axios reconfigured for stubs + better use going forward)
- vuelidate working and implemented around agm date
=> 473 ar ui development

coops-ui/public/index.html, coops-ui/src/App.vue, coops-ui/src/axios-auth.ts, coops-ui/src/components/EntityInfo.vue, coops-ui/src/components/StdHeader.vue, coops-ui/src/main.ts, coops-ui/src/router.ts, coops-ui/src/store.ts, coops-ui/src/views/Home.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/EntityInfo.spec.ts, coops-ui/vue.config.ts
*Issue #:bcgov/entity#531*
- added redirect and listener for login if user has no token
- took out keycloak (token will be verified in backend) and manually parse token
- added in .env with URLs (added vue.config to use this)
=> integrated login properly with our ui

coops-ui/jest.config.js, coops-ui/public/config/configuration.js, coops-ui/public/config/configuration.json, coops-ui/src/main.ts, coops-ui/src/router.ts, coops-ui/src/views/Home.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/EntityInfo.spec.ts
*Issue #:bcgov/entity#531*
- changed the way URLs are set 
=> changed URL vars to work with openshift environment

coops-ui/src/main.ts
=> Fixed redirect url

coops-ui/public/config/configuration.js, coops-ui/src/main.ts
=> config edit

coops-ui/public/config/configuration.js, coops-ui/src/main.ts, coops-ui/src/router.ts, coops-ui/src/views/Home.vue
=> config debug for openshift1

coops-ui/public/config/configuration.js, coops-ui/src/main.ts, coops-ui/src/router.ts, coops-ui/src/views/Home.vue
=> hardcoded urls in configuration

coops-ui/public/config/configuration.js
=> fixed auth url

coops-ui/public/config/configuration.js, coops-ui/public/config/configuration.json, coops-ui/src/main.ts, coops-ui/src/router.ts, coops-ui/src/views/Home.vue
=> fixed url issue

coops-ui/package.json
*Issue #:bcgov/entity#284*
- version change on payment component
=> updated version of payment component

colin-api/tests/postman/colin_api_local.postman_collection.json, colin-api/tests/postman/colin_api_local.postman_environment.json
=> added rough postman tests for local development

coops-prototype/package.json, coops-prototype/src/components/ARFilingDates.vue, coops-prototype/src/components/StdHeader.vue, coops-prototype/src/router.ts, coops-prototype/src/views/AnnualReport.vue, coops-prototype/src/views/Payment.vue
=> Updating Prototype

colin-api/Jenkinsfiles/build.groovy
=> added waits to builds in jenkins file

colin-api/Jenkinsfiles/build.groovy
=> Colin pipelines

schemas/src/registry_schemas/schemas/change_of_address.json, schemas/src/registry_schemas/schemas/filing.json, schemas/tests/unit/test_filings.py
*Issue #:n/a*
- added certifiedBy and email to change_of_address 
- converted some missed fields from snake case to camel case
=> updated for address change

coops-prototype/src/assets/styles/base.styl, coops-prototype/src/assets/styles/layout.styl, coops-prototype/src/assets/styles/overrides.styl, coops-prototype/src/components/ARFilingDates.vue, coops-prototype/src/components/EntityInfo.vue, coops-prototype/src/components/StdHeader.vue, coops-prototype/src/router.ts, coops-prototype/src/views/AnnualReport.vue, coops-prototype/src/views/DashboardSuccess.vue, coops-prototype/src/views/Payment.vue, coops-prototype/src/views/PaymentCart.vue, coops-prototype/src/views/PaymentInfo.vue
Continued prototype development
=> Adding Prototype Dashboards

coops-prototype/src/assets/styles/base.styl, coops-prototype/src/assets/styles/layout.styl, coops-prototype/src/assets/styles/overrides.styl, coops-prototype/src/components/ARFilingDates.vue, coops-prototype/src/components/EntityInfo.vue, coops-prototype/src/views/AnnualReport.vue, coops-prototype/src/views/Dashboard.vue, coops-prototype/src/views/DashboardSuccess.vue
=> Prototype Updates

colin-api/colin_api/exceptions/__init__.py, colin-api/colin_api/models/business.py, colin-api/colin_api/models/filing.py, colin-api/colin_api/resources/filing.py, colin-api/colin_api/utils/__init__.py, colin-api/tests/postman/lear_colin_api.postman_collection.json, colin-api/tests/unit/api/test_business.py, colin-api/tests/unit/api/test_coa.py, colin-api/tests/unit/api/test_ops.py
*Issue #:bcgov/entity#437*
- added in change of address to colin api
- refactored api to handle different filings (right now just coa and ar) and for schema changes
- added pytests + postman tests
=> 437 reg off addr colin api

schemas/src/registry_schemas/schemas/filing.json
*Issue #:* n/a
added paymentToken to the filing header.
=> added paymentToken to filing header

coops-prototype/src/assets/styles/base.styl, coops-prototype/src/components/ARFilingDates.vue, coops-prototype/src/components/FeeSummary.vue, coops-prototype/src/router.ts, coops-prototype/src/views/AnnualReportAlt.vue, coops-prototype/src/views/Dashboard.vue, coops-prototype/src/views/DashboardSuccess.vue
=> Adding Alternative Director Interface

coops-prototype/src/views/AnnualReport.vue, coops-prototype/src/views/AnnualReportAlt.vue, coops-prototype/src/views/AnnualReportStep1.vue, coops-prototype/src/views/AnnualReportStep2.vue
=> Updating Prototype Text

coops-ui/jest.config.js, coops-ui/public/config/configuration.json, coops-ui/public/index.html, coops-ui/src/App.vue, coops-ui/src/components/ARSteps/RegisteredOfficeAddress.vue, coops-ui/src/components/AnnualReport.vue, coops-ui/src/router.ts, coops-ui/src/store.ts, coops-ui/src/views/Home.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/ChangeOfAddress.spec.ts
*Issue #:bcgov/entity#572*
- canada post api integration (needs new key - was using my free trial and it expired)
- added more reg off stuff per schema + rule changes
- tests added
=> 572 reg office addr ui

schemas/src/registry_schemas/schemas/address.json, schemas/src/registry_schemas/schemas/change_of_directors.json, schemas/src/registry_schemas/schemas/directors.json, schemas/src/registry_schemas/schemas/filing.json, schemas/tests/unit/schema_data.py, schemas/tests/unit/test_filings.py
*Issue #:* bcgov/entity#545
Created complete schema for directors - view/snapshot and change of directors filing.
Field size limits of 30 on director name strings match colin.
=> 545 directors schema

schemas/tests/unit/test_filings.py
=> fixed schema test data for max string sizes

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* bcgov/entity#663-postman
- updated postman examples
- added bdd test stack
- added some example tests
=> 663 filing id postman

coops-prototype/src/components/StdHeader.vue
Updating header component with the markup / styling for the sign out button.
=> Adding Sign Out Button

legal-api/Makefile, legal-api/requirements.txt, legal-api/requirements/prod.txt, legal-api/requirements/repo-libraries.txt, legal-api/src/legal_api/__init__.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business.py, legal-api/tests/unit/api/test_business_filings.py, legal-api/tests/unit/api/test_oas.py, legal-api/tests/unit/models/test_filing.py
*Issue #:*  bcgov/entity#663
added the filing_id to the repose for any creates made via the API.
=> 663 filing id api

coops-prototype/src/views/AnnualReport.vue, coops-prototype/src/views/AnnualReportAlt.vue, coops-prototype/src/views/PaymentCart.vue
=> Updating Content for Prototype

colin-api/colin_api/exceptions/__init__.py, colin-api/colin_api/models/__init__.py, colin-api/colin_api/models/address.py, colin-api/colin_api/models/director.py, colin-api/colin_api/models/filing.py, colin-api/colin_api/models/office.py, colin-api/colin_api/resources/__init__.py, colin-api/colin_api/resources/directors.py, colin-api/colin_api/resources/filing.py, colin-api/colin_api/resources/office.py, colin-api/tests/postman/lear_colin_api.postman_collection.json, colin-api/tests/unit/api/test_directors.py, colin-api/tests/unit/api/test_registered_office.py
*Issue #:bcgov/entity#544*
- added in get call for change of directors filing (this will get 404's until data around director start/end event ids is fixed)
- added in get call for current directors
- reorganized api to make more sense structurally for getting filings vs getting individual pieces of filings
- tests added (all pass for postman + pytest)
=> 544 directors view colin api

legal-api/MANIFEST.in, legal-api/requirements.txt, legal-api/src/legal_api/__init__.py, legal-api/src/legal_api/config.py, legal-api/tests/unit/conf/test_configuration.py
*Issue #:* bcgov/entity#679
Moved config.py within the package, so that the library can be installed and used for a common model.
=> moved some files to make the library fully installable.

docs/docs/post/example.md, docs/docs/post/incident_00_template.md
*Issue #:* bcgov/entity#705
Added a postmortem template and example.
=> 705 added postmortem template

coops-ui/package.json
=> change to package.json - couldn't build in openshift

coops-ui/package.json, coops-ui/src/components/ARSteps/Directors.vue
=> fixed minor layout change in directors list

legal-api/pre_hook_create_database.py
*Issue #:* n/a
corrected path to the config module in pre_hook_create_database.py
=> corrected path to config in the pre_hook_create_database.py

coops-ui/src/components/ARSteps/AGMDate.vue, coops-ui/src/components/ARSteps/ARComplete.vue, coops-ui/src/components/ARSteps/Directors.vue, coops-ui/src/components/ARSteps/RegisteredOfficeAddress.vue, coops-ui/src/components/AnnualReport.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/components/StdHeader.vue, coops-ui/src/store.ts, coops-ui/src/validators.ts, coops-ui/src/views/Home.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/ChangeOfAddress.spec.ts, coops-ui/tests/unit/Directors.spec.ts
*Issue #:* https://github.com/bcgov/entity/issues/745
- updated AGM Date component per prototype (but with validation and "no AGM" option)
- updated unit tests affected by new initial AGM Date
- initialized AGM Date in Home component (for future re-entry)
- moved 'validated' logic to Annual Report parent component (instead of AGM Date child component)
- improved some code
- renamed some variables
- updated some console log text
- misc cleanup
- also removed tab stop from entity status v-chip
=> updated AGM Date component + cleanup

coops-ui/src/axios-auth.ts
*Description of changes:* Changes to inject the authorization header  using axios request interceptor. 
=> Change to inject the Authorization Header using axios request interceptor

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* entity/bcgov#797-r1
Updated 1 example to the new CP number.
=> updated 1 example to the new CP identifier

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* bcgov/entity#797-r2
updated postman examples for the 3 CPs (CP0002098, CP0002103, CP0002106)
=> updated postman examples for the 3 CPs (CP0002098, CP0002103, CP0002106)

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* bcgov/entity#797-r3
added address and AGM/AR dates to examples
=> added address and AGR?AR dates to examples

legal-api/tests/postman/legal-api.postman_collection.json, schemas/tests/unit/test_filings.py
*Issue #:* bcgov/entity#742
Added mock data for directors (get and filing post) with dates.
Also added tests for schema change - appointment and cessation date.
=> Added mock data for directors (get and filing post) with dates.

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* n/a
- Corrected some the example data.
=> corrected some of the example data

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* n/a
altered collection name, to legal_api
=> altered collection name, to legal_api

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* n/a
- Added status to the business.
- Changed one director example that was not working.
=> added status and corrected one example

coops-ui/public/config/configuration.json, coops-ui/src/App.vue, coops-ui/src/assets/styles/base.styl, coops-ui/src/axios-auth.ts, coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/components/Dashboard/AddressListSm.vue, coops-ui/src/components/Dashboard/DirectorListSm.vue, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/FilingHistoryTable.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/store/actions.ts, coops-ui/src/store/state.ts, coops-ui/src/validators.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/Dashboard.vue
*Issue #:* https://github.com/bcgov/entity/issues/778
~~This feature (778) is still WIP until the unit tests are updated.~~ <<< this is task https://github.com/bcgov/entity/issues/779
*Note:* Managing new/draft ARs are separate tasks (https://github.com/bcgov/entity/issues/791 and https://github.com/bcgov/entity/issues/793).
- misc cleanup from previous commits
- new Dashboard sub-components (including aside)
- get addresses from API
- get directors from API (WIP until API is ready)
- created Todo List based on Last AGM Date
- created Filings List from API response
- fixed AR Year (number vs string) and sub-component init
- updated styles
- misc cleanup
- this PR also refers to the latest mock API version (74)
- this PR also disables the Bearer auth header so …
=> final updates to Dashboard per prototype

coops-ui/Jenkinsfile, coops-ui/package.json, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/tests/unit/Directors.spec.ts
*Issue #:* /bcgov/entity#730
Integrated BaseAddress component into Directors listing.
=> 730 integrate address component

coops-ui/src/main.ts
*Issue #:* /bcgov/entity#589
Removed hardcoded login token which overrides corp num.
=> removed hardcoded token from main.ts

coops-ui/Jenkinsfile, coops-ui/package.json, coops-ui/public/config/configuration.json
=> updated version to try to break cache

coops-ui/public/config/configuration.json, coops-ui/src/axios-auth.ts, coops-ui/src/router.ts
*Issue #:* bcgov/entity#589
Updated token processing to get from new json response, rather than old simple data.
Also updated config to remove (sort of) PAY_URL - not used as far as I can tell but not ready to commit to that yet.
=> UI - Fixed keycloak token - parse from json rather than straight text

coops-ui/Jenkinsfile
=> rolled back to silent unit tests

colin-api/colin_api/exceptions/__init__.py, colin-api/colin_api/models/address.py, colin-api/colin_api/models/business.py, colin-api/colin_api/models/director.py, colin-api/colin_api/models/filing.py, colin-api/colin_api/models/office.py, colin-api/colin_api/resources/filing.py, colin-api/tests/postman/colin-api.postman_collection.json, colin-api/tests/unit/api/test_ar.py, colin-api/tests/unit/api/test_directors.py, colin-api/tests/unit/api/test_registered_office.py
*Issue #:* /bcgov/entity#822
- see ticket linked above for details
=> 822 colin-api appoint directors, handle multiple filings

coops-ui/Jenkinsfile, coops-ui/package.json, coops-ui/tests/unit/AnnualReport.spec.ts
*Issue #:* n/a
Fixed failing AR test.
Changed jenkins to handle negative failure response from jest tests.
Changed unit test param to be correct catch-all (from star to dot) to remove error from jest run.
=> Fixed failing ar test

coops-ui/package.json, coops-ui/public/config/configuration.json, coops-ui/src/App.vue, coops-ui/src/router.ts, coops-ui/src/views/AnnualReport.vue
*Issue #:* /bcgov/entity#886
Integrated sbc common components for sign out functionality + common header and footer
Added more items to the session storage for the common components
Passing pay url as props to the sbc fee component
Changes to construct redirect url irrespective of whether '/' is present in the config
=> Integration with sbc common

.gitignore, colin-api/requirements.txt, colin-api/requirements/dev.txt, jobs/update-colin-filings/config.py, jobs/update-colin-filings/openshift/cron-update-legal-filings.yaml, jobs/update-colin-filings/requirements/dev.txt, jobs/update-colin-filings/requirements/prod.txt, jobs/update-colin-filings/run.sh, jobs/update-colin-filings/update_colin_filings.py, jobs/update-colin-filings/utils/__init__.py, jobs/update-colin-filings/utils/logging.py, jobs/update-legal-filings/update_legal_filings.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/postman/legal-api.postman_collection.json, legal-api/tests/unit/models/__init__.py, schemas/src/registry_schemas/schemas/filing.json
=> 641 legal to colin job

legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#887
- added the missing jwt to the invoice creation request
=> added jwt token and removed other status settings.

entity-filer/app.py
*Issue #:* /bcgov/entity919a
- added app.py to leverage the OS s2i framework.
=> added app.py for s2i framework

entity-filer/Jenkinsfiles/build.groovy
*Issue #:* /bcgov/entity#919b
- migrateTo Kial's new jenkins template
=> move to kials new jenkines template

coops-ui/src/components/AnnualReport/Directors.vue
=> added ID on form field to assist QA

legal-api/tests/postman/legal-api.postman_collection.json, schemas/src/registry_schemas/schemas/filing.json, schemas/src/registry_schemas/schemas/task.json, schemas/src/registry_schemas/schemas/todo.json, schemas/tests/unit/schema_data.py, schemas/tests/unit/test_filings.py, schemas/tests/unit/test_task.py, schemas/tests/unit/test_todo.py
*Issue #:* /bcgov/entity/845
- added 'status' to filing header
- added 'required' to filing
- created task and todo schemas
- created task and todo unit tests
- updated schema_data.py
- updated Postman collection with new EP mock
- updated annual report name in sample headers (re: merge)
- fixed unit tests broken by filing name change (re: merge)
=> schemas, unit tests and mock data for /tasks endpoint

coops-ui/openshift/Readme.md, coops-ui/openshift/templates/coops-ui-dc.dev.json, coops-ui/openshift/templates/coops-ui-dc.prod.json, coops-ui/openshift/templates/coops-ui-dc.test.json, coops-ui/src/views/AnnualReport.vue
*Issue #:* n/a
Updated AR filing header name from annual_report to annualReport + unrelated openshift template changes
=> Updated AR filing header name from annual_report to annualReport

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* /bcgov/entity845
- re-exported postman json as v2.1
=> re-exported postman json as v2.1

coops-ui/package.json, coops-ui/src/assets/styles/base.styl, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/EntityInfo.vue
*Issue #:* /bcgov/entity950
NB - this needs to be rebased once #174 is merged
- added Past Filings message
- also cleaned up some styles
- also hid v-chip if status is null
- also toggled text when expansion panel is open/closed
=> added Past Filings message

legal-api/src/legal_api/resources/business/business.py
*Issue #:* /bcgov/entity#589
*Description of changes:* Changes to avoid cors error for business endpoint
=> Fix for business endpoint CORS error

coops-ui/src/router.ts
=> Fixed lint error

coops-ui/package.json, coops-ui/public/config/configuration.json, coops-ui/public/index.html, coops-ui/src/router.ts
*Issue #:* /bcgov/entity/971
- Updated to latest BaseAddress component, which integrates with Canada Post AddressComplete.
- Moved index.html script to main.ts to remove duplicated request and processing.
- Cleaned up duplicated processing of request response in main.ts.
- Fixed some TypeScript warnings in main.ts.
- Also hard coded the AddressComplete CSS and JS to fix browser warnings (#931).
=> 971 address complete

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* /bcgov/entity906
*Description of changes:* fixed get-filing-by-id for CP0002098
=> fixed get-filing-by-id for CP0002098

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* /bcgov/entity906
*Description of changes:* changed filing_id to 4
=> changed filing_id to 4 (in mock collection)

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* /bcgov/entity906
*Description of changes:* fixed mismatched legal name in postman json
=> fixed mismatched legal name in postman json

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* /bcgov/entity#943
- fixed paths for health/ready calls
- deleted echo request (doesn't exist in api)
- fixed auth url (was inconsistent in collection)
=> legal postman fixes

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/__init__.py, legal-api/src/legal_api/resources/business/business.py, legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/tests/unit/api/test_business_tasks.py
*Issue #:* /bcgov/entity#927
Added a new endpoint to retrieve tasks for dashboard
Added tests for the new endpoint
=> Legal API tasks endpoint

coops-ui/package.json, coops-ui/src/App.vue
*Issue #:* /bcgov/entity/980
*Description of changes:* replaced broken sbc-layout with sbc-header and sbc-footer
=> replaced broken sbc-layout with sbc-header and sbc-footer

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/Dashboard.vue, coops-ui/tests/unit/EntityInfo.spec.ts
*Issue #:* /bcgov/entity#981
- fixed lint error
- fixed unit test re: change for no status
- added Save and Save & Resume Later buttons
- changed mounted() to created() to load data
- added FILED AND PAID to filing history
- update style of View Documents links
-  added tel and mailto links to contact info
=> misc fixes

coops-ui/public/config/configuration.json, coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/store/getters.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/AnnualReport.spec.ts
*Issue #:* /bcgov/entity906
- fixed lint error
- fixed unit test re: change for no status
- added Save and Save & Resume Later buttons
- changed mounted() to created() to load data
- added Save & File tooltip
- added FILED AND PAID to filing history
- updated style of View Documents links
- temporary styling fix until common components are fixed (per Jer)
- added tel and mailto links to contact info
- implemented resume AR filing
- updated AR sub-components accordingly
- implemented resume error dialog
- updated Payment Incomplete message
- changed AR status TODO to NEW
=> implemented Resume AR Filing

legal-api/src/legal_api/resources/business/business_address.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/src/legal_api/services/authz.py, legal-api/tests/unit/api/test_business_address.py, legal-api/tests/unit/api/test_business_filings.py
*Issue #:* /bcgov/entity#589
Corrected Legal API addresses endpoint to return data in sync with the mocks
Modified tests of addresses endpoint
Modified the authorization wrapper to do a case insensitive comparison for the username
Modified filings endpoint to return only completed filings
Modified the tasks endpoint to move order and enabled at the root of task object
=> Corrected the legal api addresses endpoint

coops-ui/package.json, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/RegisteredOfficeAddress.spec.ts
*Issue #:* /bcgov/entity#982
- used prop and watch to pass draft addresses to component
- conditionally set 'current' addresses
- used emitter to update addresses in parent
- added validation when loading draft data
- implemented PUT for draft filings
=> resume a Change Address filing

coops-ui/src/axios-auth.ts
=> added keycloak token to all axios calls

Jenkinsfiles/run-pytests.groovy, colin-api/Jenkinsfiles/build.groovy, colin-api/Jenkinsfiles/deploy-test.groovy, legal-api/Jenkinsfiles/deploy-test.groovy
- changed pytest pipeline to call ora pipeline properly (changed from previous merge)
- changed the legal/colin pipelines to call pytest pipeline properly due to above
- added deploy to test jenkinsfile for legal
- updated deploy-test jenkinsfile for colin due to pytest pipeline changes
=> pipeline fixes

legal-api/k8s/legal-api-deploy.test.param
*Issue #:* /bcgov/entity#945a
- deployment parameter file for legal_api in test
=> add deployment params for legal_api test setup

coops-ui/package.json
*Issue #:* /bcgov/entity#661
*Description of changes:* Bumped to latest common components
=> Bumped front end to latest common components (#661)

entity-filer/Jenkinsfiles/build.groovy, entity-filer/src/entity_filer/filing_processors/annual_report.py, entity-filer/src/entity_filer/filing_processors/change_of_address.py, entity-filer/src/entity_filer/worker.py, entity-filer/tests/unit/__init__.py, entity-filer/tests/unit/test_worker.py, legal-api/src/legal_api/models/filing.py
*Issue #:* /bcgov/entity#825
- added processor in filer for change of address
- updated legal model for filings to properly update status
=> filer processor for change of address added

coops-ui/public/config/configuration.json, coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/RegisteredOfficeAddress.spec.ts
*Issue #:* /bcgov/entity#982
This is the remainder of the work for the subject ticket. (The first part was PR #194 and was previously merged to allow others to work with the updated code.)
- deleted obsolete getters
- updated POST and PUT
- added http status codes package
- updated API URL in config
- hid vs disabled Save and Save & Resume buttons
=> resume a change address filing (+ more Resume AR work)

coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/AnnualReport.spec.ts
*Issue #:* /bcgov/entity#793
- implemented Save and Save & Resume Later
This PR builds upon #207, so THAT PR must be merged first, and then THIS PR can be rebased to get rid of the extra commits. THIS PR has only 1 commit.
=> implemented Save and Save & Resume Later

entity-filer/src/entity_filer/filing_processors/change_of_directors.py, entity-filer/src/entity_filer/worker.py, entity-filer/tests/unit/__init__.py, entity-filer/tests/unit/test_worker.py, legal-api/src/legal_api/resources/business/business_directors.py
*Issue #:* /bcgov/entity#826
- updated entity filer to apply director changes to db from a successful change of directors filing
=> filing processor for directors created with tests

coops-ui/openshift/Readme.md, coops-ui/openshift/templates/coops-ui-dc.dev.json, coops-ui/openshift/templates/coops-ui-dc.prod.json, coops-ui/openshift/templates/coops-ui-dc.test.json, coops-ui/src/views/AnnualReport.vue
*Issue #:* /bcgov/entity#894
Updated deployment templates for renamed config maps + unrelated lint fix
=> Updated deployment templates for renamed config maps + unrelated lint fix

coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/validators.ts, coops-ui/tests/unit/AGMDate.spec.ts
*Issue #:* /bcgov/entity#996
- added unit test to check for subject issue
- changed tests from nextTick() to async-await
- fixed date comparison bugs
=> AGM day issue

coops-ui/src/App.vue, coops-ui/src/DateUtils.ts, coops-ui/src/components/AnnualReport/Certify.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/router.ts, coops-ui/src/store/actions.ts, coops-ui/src/store/getters.ts, coops-ui/src/store/mutations.ts, coops-ui/src/store/state.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/Dashboard.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/Dashboard.spec.ts, coops-ui/tests/unit/Directors.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts
*Issue #:* /bcgov/entity#946
Completed standalone filings:
- date restrictions on Director dates based on previous filing
- standalone Office Address filing
*Note* there is a LOT of duplication of code now between the three filings (AR, Directors, Office Addresses) but that is a problem for another day.
=> Standalone filings

coops-ui/Jenkinsfile, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/tests/unit/AnnualReport.spec.ts
=> lint fixes; removed jest tests from pipeline

coops-ui/src/DateUtils.ts
=> bug fix in date conversion

legal-api/tests/postman/legal-api.postman_collection.json, schemas/src/registry_schemas/schemas/address.json, schemas/src/registry_schemas/schemas/change_of_address.json, schemas/src/registry_schemas/schemas/change_of_directors.json, schemas/src/registry_schemas/schemas/directors.json, schemas/tests/unit/test_filings.py, schemas/tests/unit/test_task.py, schemas/tests/unit/test_todo.py
*Issue #:* /bcgov/entity#1004
schema - added actions and prev officer name to directors; actions to addresses
=> schema - added actions and prev officer name to directors; actions to addresses

legal-api/report-templates/OTADD.html, legal-api/report-templates/OTANN.html, legal-api/report-templates/OTCDR.html, legal-api/src/legal_api/config.py, legal-api/src/legal_api/reports/__init__.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/reports/report_otann.py, legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#948
*Description of changes:* Added PDF retrieval for filings. Far from complete, but I will open other tickets for outstanding work.
=> First commit of the reports api but far from complete (#948)

jobs/update-colin-filings/requirements.txt, jobs/update-colin-filings/requirements/prod.txt, jobs/update-colin-filings/update_colin_filings.py
=> added req file

jobs/update-legal-filings/update_legal_filings.py
*Issue #:* /bcgov/entity#1013
- updated msging
=> updated msging in legal-updater

jobs/update-legal-filings/openshift/cron-update-legal-filings.yml, jobs/update-legal-filings/run.sh
=> 1013 job starts

legal-api/src/legal_api/resources/business/business_filings.py
=> improved internal filing msging

colin-api/colin_api/models/filing.py, colin-api/tests/postman/colin-api.postman_collection.json
*Issue #:* /bcgov/entity#998
- added in functionality for editing a director while ceasing
=> updated tests + api for editing a director and ceasing them

coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#1019
Changes to save standalone director as  draft and resume those changes
=> Save and Resume standalone addresses

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue
*Issue #:* /bcgov/entity#1019
Address changes to be in sync with the schemas for both standalone and annual report director sections
=> Fixes to standalone directors

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
Changed default type of actions to array
=> Fix- Default values of properties

coops-ui/src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#949
Added PDF presentation from dashboard for filing history.
=> Added PDF presentation from dashboard for filing history.

coops-ui/package.json, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/tests/unit/Directors.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts
*Issue #:* /bcgov/entity#1015
Added actions to director and office address components, for all filings - list of actions used in COLIN api and reports.
Also:
- hid/commented out director change functionality removed from MVP release
- fixed unrelated StandaloneDirectorsFiling failing tests
- added previous name fields for COLIN api to use when updating record
- not currently used, since director name change is not supported in MVP
=> Added actions to director and office address components, for all filings

legal-api/k8s/templates/legal-api-deploy.json, legal-api/requirements.txt, legal-api/src/legal_api/config.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_tasks.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/models/test_filing.py
*Issue #:* /bcgov/entity#1036
- added tests for filing additions
- added filter for go-live-date
- added go-live-date to deployment config and configmap
=> 1036 filter off legacy filings

coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/EntityInfo.vue
*Issue #:* /bcgov/entity#1010
Changes to consider the last ledger timestamp for min value of AGM date
=> Changes to consider the last ledger timestamp for AGM date

coops-ui/package.json, coops-ui/public/config/configuration.json, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/router.ts, coops-ui/src/routes.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/mockRouter.ts
*Issue #:* /bcgov/entity#1039
- implemented Receipt PDF download
- disabled buttons and show spinner while downloading
- fixed download filename for IE
- misc cleanup
- updated local PAY_API_URL
- moved routes out of router declaration
- changed id param to string
- deleted obsolete transition
- added loading animation to AR buttons
- added test helper package
- added mock router function
- rewrote 'routing' unit tests
- added dialog for download errors
=> implemented Receipt PDF download + unit test fixes

jobs/update-colin-filings/openshift/cron-update-colin-filings.yml, jobs/update-colin-filings/update_colin_filings.py, jobs/update-legal-filings/openshift/cron-update-legal-filings.yml, jobs/update-legal-filings/update_legal_filings.py
=> cronjob yml update + sentry update for jobs

coops-ui/public/config/configuration.json, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/tests/unit/AnnualReport.spec.ts
*Issue #:* /bcgov/entity#1039
- fixed breaking change to PAY_API_URL
=> fixed breaking change to PAY_API_URL

legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/tests/unit/api/test_business_tasks.py
=> added errored filings to return in tasks

legal-api/k8s/templates/legal-api-deploy.json
*Issue #:* /bcgov/entity#1048
updated deployment config for NATS vars
=> updated deployment config

entity-filer/src/entity_filer/filing_processors/__init__.py, entity-filer/src/entity_filer/filing_processors/change_of_address.py, entity-filer/src/entity_filer/filing_processors/change_of_directors.py, entity-filer/tests/unit/__init__.py
=> update address instead of adding a new one

legal-api/report-templates/annualReport.html
*Issue #:* /bcgov/entity#1045
- implemented Annual Report PDF page numbering using the CSS page-margin at-rule approach
=> implemented AR PDF page numbering

coops-ui/src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#1054
- fixed incorrect id for fetching receipt
=> fixed incorrect id for fetching receipt

coops-ui/src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#1052
- added corp num to front of document names
=> added corp num to front of document names

coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/tests/unit/Dashboard.spec.ts
*Issue #:* /bcgov/entity#1051
- added error status to blocking state
=> added error status to blocking state

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue
*Issue #:* /bcgov/entity#758
- expand filing after return from payment
=> expand filing after return from payment

coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts
*Issue #:* /bcgov/entity#1050
- disabled buttons when busy
- added loading indicators when busy
- added missing checks for filing id
- fixed incorrect routes
=> disabled buttons after clicking

coops-ui/src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#758
- fixed missing filing id to highlight (which was deleted by another PR)
=> fixed missing filing id to highlight

coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#1057
bug fix - upon filing save-and-stay, save only one draft instead of multiple.
=> bug fix - upon filing save-and-stay, save only one draft instead of multiple

coops-ui/src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#1055
- updated PDF download code to work with FF
=> updated PDF download to work with FF

coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/views/AnnualReport.vue
*Issue #:* /bcgov/entity#1064
include address and director filings in AR, even when no changes.
=> include address and director filings in AR, even when no changes.

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings.py
Add required JWT to GET on businesses/filings
=> added required jwt to GET business filings

entity-filer/src/entity_filer/filing_processors/__init__.py, entity-filer/src/entity_filer/filing_processors/change_of_address.py, entity-filer/src/entity_filer/filing_processors/change_of_directors.py, entity-filer/tests/unit/__init__.py, entity-filer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#1049
- updated directors processor in entity filer to use actions in json
- tests updated to reflect changes
=> 1049 director update

entity-filer/src/entity_filer/filing_processors/__init__.py, entity-filer/src/entity_filer/filing_processors/change_of_directors.py, entity-filer/tests/unit/__init__.py
*Issue #:* /bcgov/entity#1049
- .upper was failing on empty value 
=> empty title, first/last/middle name fix

coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/views/AnnualReport.vue
*Issue #:* /bcgov/entity#1064
This rolls back a change that is causing pricing issues; we have a better long-term fix in mind but this must roll back for MVP launch.
=> Revert "include address and director filings in AR, even when no changes. (#271)"

coops-ui/package.json
=> bump front-end version number

colin-api/Jenkinsfiles/deploy-prod.groovy, entity-filer/Jenkinsfiles/deploy-prod.groovy, entity-filer/Jenkinsfiles/deploy-test.groovy, jobs/update-colin-filings/Jenkinsfiles/tag-prod.groovy, jobs/update-legal-filings/Jenkinsfiles/tag-prod.groovy, legal-api/Jenkinsfiles/deploy-prod.groovy
*Issue #:* /bcgov/entity#1078
- see ticket for which services
=> jenkinsfiles for remaining pipelines

entity-filer/src/entity_filer/version.py, legal-api/src/legal_api/version.py
*Issue #:* n/a
bump versions to 1.0.0 for release
=> version bump

coops-ui/src/App.vue, coops-ui/src/axios-auth.ts, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/main.ts, coops-ui/src/router.ts, coops-ui/src/util/config-helper.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#855
-changed synchronous XMLHttpRequest() to axios.get()
-used promise to load Vue after fetching config
-added helper to fetch config
-saved config in session storage
-related updates and cleanup
=> replaced deprecated XMLHttpRequest

coops-ui/src/components/ConfirmDialog.vue, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/main.ts, coops-ui/src/plugins/vuetify.ts, coops-ui/src/router.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts
*Issue #:* /bcgov/entity#893
- created async Confirm Dialog component
- updated spacing in dialogs
- moved vuetify plugin to main.ts
- added 'scroll to top' on route changes
- added beforeUnload handler to AR and standalone views
- added beforeRouteLeave handler to AR and standalone views
- added basic code to track changes
- updated some if-else blocks (cleanup)
- removed some obsolete code (cleanup)
- fixed unit tests (broken by different PR)
=> implemented Unsaved Changes confirmations

coops-ui/src/App.vue, coops-ui/src/assets/styles/base.styl, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/components/Dashboard/AddressListSm.vue, coops-ui/src/components/Dashboard/DirectorListSm.vue, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/main.ts, coops-ui/src/store/actions.ts, coops-ui/src/store/getters.ts, coops-ui/src/store/mutations.ts, coops-ui/src/store/state.ts, coops-ui/src/util/config-helper.ts, coops-ui/src/views/Dashboard.vue, coops-ui/tests/unit/AGMDate.spec.ts, coops-ui/tests/unit/AddressListSm.spec.ts, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/App.spec.ts, coops-ui/tests/unit/Dashboard.spec.ts, coops-ui/tests/unit/DirectorListSm.spec.ts, coops-ui/tests/unit/Directors.spec.ts, coops-ui/tests/unit/EntityInfo.spec.ts, coops-ui/tests/unit/FilingHistoryList.spec.ts, coops-ui/tests/unit/RegisteredOfficeAddress.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#913
- added Dashboard Unavailable dialog
- moved GETs and related code from sub-components to App
- added error handling/retry
- added data objects to store
- added error handling in main
- converted a few components to TS
- fixed misc code
- moved Dashboard loading panel to App
- updated and expanded unit tests
Note that I noticed some missing unit tests in TodoList, but instead of adding them in this ticket, I entered new ticket /bcgov/entity#1145.
=> centralized data loading and implemented dashboard unavailable/reload

coops-ui/src/views/Dashboard.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/Dashboard.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts
*Issue #:* /bcgov/entity#1173
- pass id=0 on new COA/COD
- route back home if no route param 'id'
- added Dashboard unit tests
- bit of cleanup
=> fix duplicate COA/COD drafts

coops-ui/src/components/AnnualReport/Certify.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#1093
- refactored the component into TypeScript
- deleted some superfluous divs in templates
=> modernized Certify component

coops-ui/src/components/AnnualReport/PaymentErrorDialog.vue, coops-ui/src/components/AnnualReport/ResumeErrorDialog.vue, coops-ui/src/components/AnnualReport/SaveErrorDialog.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* Not Applicable
- moved error dialogs to own components
- updated AR, COD, COA accordingly
=> refactored AR dialogs

coops-ui/src/components/Dashboard/FilingHistoryList.vue
*Issues #:* /bcgov/entity#1259
- updated phone number
=> updated phone number

coops-ui/public/config/configuration.json, coops-ui/public/config/local-configuration.json, coops-ui/src/App.vue
*Issues #:* /bcgov/entity#1272
- updated incorrect local config for Auth Api URL
- updated code that uses config accordingly
=> update auth api url

legal-api/src/legal_api/services/filings/validations/annual_report.py, legal-api/tests/unit/api/test_business_filings.py, legal-api/tests/unit/models/__init__.py
*Issue #:* n/a
validate ar date by last_ar_date before resorting to founding_date
=> validate ar date by last_ar_date before resorting to founding_date

legal-api/src/legal_api/services/authz.py
=> logging to see auth_url used

colin-api/Jenkinsfiles/deploy-test.groovy, coops-prototype/Jenkinsfile, coops-ui/Jenkinsfile, coops-ui/Jenkinsfile-DevToTest, entity-filer/Jenkinsfiles/build.groovy, entity-filer/Jenkinsfiles/deploy-test.groovy, jobs/update-colin-filings/Jenkinsfiles/build.groovy, jobs/update-legal-filings/Jenkinsfiles/build.groovy, legal-api/Jenkinsfiles/build.groovy, legal-api/Jenkinsfiles/deploy-test.groovy
*Issue #:* n/a
Changed my jenkins username in all pipelines (-edit to -admin)
=> Changed my jenkins username in all pipelines (-edit to -admin)

colin-api/colin_api/models/filing.py, colin-api/tests/unit/api/test_ar.py, colin-api/tests/unit/api/test_business.py
*Issue #:* /bcgov/entity#1126
- see linked ticket for details
=> set filing user id in oracle when creating a filing

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings.py
*Issue #:* /bcgov/entity#1359
- see linked ticket for details
=> director free name/address change implemented in legal-api

legal-api/requirements.txt, legal-api/src/legal_api/resources/business/business_filings.py
- hotfix for create invoice issue
- increased timeout to 20 secs (temporary fix)
=> increased create invoice socket timeout

colin-api/colin_api/version.py, coops-ui/package.json, entity-filer/src/entity_filer/version.py, legal-api/src/legal_api/version.py, schemas/src/registry_schemas/version.py
=> Bumped versions to 2.0.0 for new release.

coops-ui/src/App.vue, coops-ui/src/components/AnnualReport/DeleteErrorDialog.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/store/actions.ts, coops-ui/src/store/mutations.ts, coops-ui/src/store/state.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#1289
Added Delete Draft functionality to UI.
=> Added Delete Draft functionality to UI

lear-db/test_data/load_coop_2019.py
*Issue #:* /bcgov/entity#n/a
- fix for e2e env
- last ar date populated with last agm date if it is null (only happens with dev data)
=> data-loader fix for dev data issues

legal-api/requirements.txt, legal-api/requirements/prod.txt, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings.py
*Issue #:* /bcgov/entity#1361
- see linked ticket
- updated to new filing code that sumesh created for pay-api
- package attrs causes pytests not to run if version is not < 19.2 so I added this into prod.txt
=> updated free fee filing code + package dependency

legal-api/src/legal_api/services/authz.py
*Issue #:* /bcgov/entity#n/a
- added public user to role validation (used for staff and bc services card users)
=> added public_user to role validation

coops-ui/src/router.ts
I removed a couple of console.log messages that are no longer helpful for debugging.
=> removed redirect/auth console logging

coops-ui/src/components/AnnualReport/Directors.vue
*Issue #:* /bcgov/entity#1465
- saved delivery instructions for new director
- deleted unused properties
=> BUGFIX: saved delivery instructions for new director

coops-ui/openshift/Caddyfile, coops-ui/package.json, coops-ui/public/config/configuration.json, coops-ui/src/App.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#1349
In addition to the changes made in PR #364, a few more things needed to be updated for the app to redirect correctly due to the public URL change:
- changed AUTH_URL re: bcregistry.ca
- fixing wrong path in Caddyfile
- fixed 'return URL' + updated unit tests
- passed origin to sbc header for brand link (for future use)
- updated sbc-common-component dependency (v1.1.14) <<< v1.1 is special v1 branch that does not contain BaseAddress changes
=> changes for public URL

coops-ui/package.json
*Issue #:* /bcgov/entity#1349
Updated sbc-common-component dependency to pick up header fix.
=> updated sbc-common-component dependency for header fix

coops-ui/tests/unit/AddressListSm.spec.ts, coops-ui/tests/unit/Certify.spec.ts, coops-ui/tests/unit/Dashboard.spec.ts, coops-ui/tests/unit/Directors.spec.ts, coops-ui/tests/unit/EntityInfo.spec.ts, coops-ui/tests/unit/RegisteredOfficeAddress.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #963:* /bcgov/entity###
Updated Unit Tests for the following..
* RegisteredOfficeAddress.spec
* AddressListSm.spec
* Certify.spec
* Dashboard.spec
* Directors.spec
* EntityInfo.spec
* ToDoList.spec ( Was WIP - 75% )
=> Updated Unit Testing for Vuetify 2.0

coops-ui/public/config/configuration.json, coops-ui/public/config/local-configuration.json, coops-ui/public/index.html, coops-ui/src/assets/styles/base.scss, coops-ui/src/components/EntityInfo.vue
Some minor cleanup and linting fixes, plus an updated AddressComplete key.
=> minor cleanup and linting + updated AC key

coops-ui/tests/unit/AnnualReport.spec.ts
Some code was indented incorrectly, causing a linting error. That has now been fixed.
=> lint indentation fix

coops-ui/public/index.html, coops-ui/src/assets/styles/base.scss, coops-ui/src/assets/styles/overrides.scss, coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/AnnualReport/BCorp/ARDate.vue, coops-ui/src/components/AnnualReport/Certify.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue
- reverted font upgrade
- fixed v-chip faded color
- fixed v-alert background
=> reverted font upgrade + misc fixes

coops-ui/src/assets/styles/base.scss, coops-ui/src/assets/styles/overrides.scss, coops-ui/src/components/ConfirmDialog.vue, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue
- override for button letter spacing
- fixed v-card padding (eg, in v-dialogs)
- set some v-dialog text to black
- fixed list-item line height
- removed expansion panel wrap padding
- fixed document-list padding
=> layout fixes

schemas/src/registry_schemas/example_data/__init__.py, schemas/src/registry_schemas/example_data/schema_data.py, schemas/src/registry_schemas/schemas/business.json, schemas/src/registry_schemas/schemas/change_of_name.json, schemas/src/registry_schemas/schemas/filing.json, schemas/src/registry_schemas/schemas/special_resolution.json, schemas/src/registry_schemas/schemas/stub_filing.json, schemas/src/registry_schemas/schemas/voluntary_dissolution.json, schemas/tests/unit/schema_data.py, schemas/tests/unit/test_filings.py
*Issue #:* /bcgov/entity#1246
Added all remaining filings with SR, Vol. Diss., and CON flushed out, others stubbed.
This PR is into a story branch but could safely be merged into master if necessary - it does not change existing filings schemas, just adds to them. @thorwolpert feel free to adjust as needed.
=> Added all remaining filings with SR, Vol. Diss., and CON flushed out, others stubbed.

coops-ui/src/components/AnnualReport/Directors.vue
=> fixed directors v-chip styling

coops-ui/package.json
*Issue #:* N/A
This internal version change is to line up the code with the GitHub release number.
=> changed version to 2.1.0

legal-api/tests/unit/api/test_business_filings.py, legal-api/tests/unit/services/test_queue_publish.py
*Issue #:* n/a
Added two missing decorators on pytests.
=> added two missing decorators on pytests

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts
*Issue #:* /bcgov/entity#1357 & /bcgov/entity#1363
Director name change and address change - free filings - in UI.
=> 1357 director name change & 1363 director address change

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, legal-api/requirements/prod.txt, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings.py
*Issue #:* /bcgov/entity#1164 (free director name chg STORY) and /bcgov/entity#1165 (free director address chg STORY)
Free filings for director name change and address change. 
=> 1164 director name change & 1165 director address change

coops-ui/src/service-worker.js
=> Fix for method does not exist

coops-ui/package.json, coops-ui/src/components/Dashboard/DirectorListSm.vue, coops-ui/src/mixins/address-mixin.ts, coops-ui/src/mixins/index.ts, coops-ui/tests/unit/DirectorListSm.spec.ts
*Issue #:* /bcgov/entity  #1387  & #1417
* Updated dashboard UI to accordion style for Directors.
* Implemented mailing address to directors for Bcorps.
* Refactored method of importing Mixins.
* Created a Mixin for address utility.
* Updated unit tests.
* Regression testing.
Sometimes the issue linking is off, so i've included links to the tickets & designs..
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/1417
https://app.zenhub.com/workspaces/entity-5bf2f2164b5806bc2bf60531/issues/bcgov/entity/1387
Designs: https://projects.invisionapp.com/share/38U4FN3WA2B#/screens/384879517 …
=> Dashboard UI Change for Directors

coops-ui/src/service-worker.js
PWA is not supported in IE11. Adding a check that will fix the app breaking in IE11
=> Fixing the issue in IE11

coops-ui/public/config/configuration.json, coops-ui/public/config/local-configuration.json, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/router.ts, coops-ui/src/utils/config-helper.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#1572
The Auth URL was changed from an absolute URL to a relative URL, and code that uses it was updated to prepend the 'origin' accordingly.
=> HOTFIX: changed absolute Auth URL path to relative path (config maps also need to be updated)

coops-ui/src/router.ts
*Issue #:* /bcgov/entity#1572
I forgot to update a file.
=> fixed router redirect code

schemas/src/registry_schemas/example_data/schema_data.py, schemas/src/registry_schemas/schemas/voluntary_dissolution.json
*Issue #:* n/a
Addition to schema - no new ticket, just a missed value from the original schema work.
=> added hasLiabilities field to Voluntary Dissolution schema.

entity-filer/src/entity_filer/service.py, entity-filer/src/entity_filer/service_utils/__init__.py, entity-filer/src/entity_filer/service_utils/exceptions.py, entity-filer/src/entity_filer/worker.py
*Issue #:* /bcgov/entity#1560
CURRENTLY RUNNING IN DEV
In entity filer, if filing cannot be found (because payment ID hasn't been assigned yet) try again up to 5 times, then add the message back to the queue to be processed again.
~~The original ticket says to wait 200 ms but the code does not wait, it just tries again. So far this has been sufficient.~~
=> Fix queue problem

colin-api/colin_api/models/director.py, entity-filer/src/entity_filer/filing_processors/change_of_directors.py
*Issue #:* /bcgov/entity1413
Add mailing address to COLIN director model 
=> add mailing address to director (COLIN-API side)

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/tests/unit/Directors.spec.ts
*Issue #:* /bcgov/entity#1593
- bug fixed where resuming a standalone directors filing and editing an untouched director caused an error (this was due to the original directors list being empty)
- test added that renders the directors component with a 'draft' filing and tests that the original directors are populated
=> bug fixed and secured with test

legal-api/report-templates/changeOfName.html, legal-api/report-templates/specialResolution.html, legal-api/report-templates/template-parts/dissolution.html, legal-api/report-templates/template-parts/legalNameChange.html, legal-api/report-templates/template-parts/resolution.html, legal-api/report-templates/voluntaryDissolution.html, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/services/filings/utils.py, legal-api/src/legal_api/services/filings/validations/change_of_name.py, legal-api/src/legal_api/services/filings/validations/special_resolution.py, legal-api/src/legal_api/services/filings/validations/validation.py, legal-api/src/legal_api/services/filings/validations/voluntary_dissolution.py
=> Post-bob filing changes

coops-ui/src/App.vue, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/EntityInfo.vue, coops-ui/src/views/Dashboard.vue, coops-ui/tests/unit/TodoList.spec.ts
Issue #: /bcgov/entity#1599
Description of changes:
- fixed layout issue in Todo List (changed from columns to subtitle)
- fixed contact info layout bug (issue with hidden blocks)
- fix for incorrect prop values
- fix for expansion panel opening when it shouldn't
- fix for processing retry not completing on error
- fix for unit tests
=> Fix Layout Issue in Todo List

coops-ui/src/components/AnnualReport/Certify.vue, coops-ui/src/components/AnnualReport/DeleteErrorDialog.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/PaymentErrorDialog.vue, coops-ui/src/components/AnnualReport/ResumeErrorDialog.vue, coops-ui/src/components/AnnualReport/SaveErrorDialog.vue, coops-ui/src/components/Dashboard/AccountAuthorizationDialog.vue, coops-ui/src/components/Dashboard/DashboardUnavailableDialog.vue, coops-ui/src/components/Dashboard/DeleteErrorDialog.vue, coops-ui/src/components/Dashboard/DownloadErrorDialog.vue, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/ErrorContact.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#1606
- extracted Download Error Dialog into new component
- standardized dialog widths (30, 45, 60)
- updated contact info and layout
- created error contact component
=> updated contact email and phone numbers

coops-ui/package.json
- updated sbc-common-components dependency to pick up their latest changes (not including address validation); it's now v2.0.11
=> updated sbc-common-components dependency

coops-ui/package.json
=> Update sbc-common-components version from 1.0.11 to 1.0.12

coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#1589
- updated the title, text and buttons of the filings' "cancel" dialogs to flow better (UX)
=> updated 'cancel' dialogs

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/tests/unit/Dashboard.spec.ts
*Issue #:* /bcgov/entity#1436
FilingListHistory changes to display post-bob filings
Refactoring the code to have a common parameterized method  to load reports
=> UI changes - post-bob filings

coops-ui/src/components/Dashboard/AddressListSm.vue, coops-ui/src/components/Dashboard/DirectorListSm.vue, coops-ui/tests/unit/Dashboard.spec.ts
=> fix syntax error from merge (probably) + lint fix

colin-api/colin_api/models/__init__.py, colin-api/colin_api/models/director.py, colin-api/colin_api/models/entity_name.py, colin-api/colin_api/models/filing.py, colin-api/colin_api/models/office.py, colin-api/colin_api/resources/event.py, colin-api/colin_api/resources/filing.py, colin-api/tests/postman/colin-api.postman_collection.json, colin-api/tests/unit/api/test_change_of_name.py, colin-api/tests/unit/api/test_special_resolution.py, colin-api/tests/unit/api/test_voluntary_dissolution.py
=> vd, con, sr filings added to colin-api

coops-ui/package.json, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/RegisteredOfficeAddress.vue, coops-ui/src/components/Common/SummaryDirectors.vue
**Note that PR https://github.com/bcgov/sbc-common-components/pull/75 must be merged first (since THIS PR depends on the new package version).**
*Issue #:* /bcgov/entity#1658
- deleted some obsolete code
- replaced some "v-on" with shorthand
- replaced some "v-bind" with shorthand
- renamed some incorrectly named methods
- cleaned up some code layout
- updated package dependency version
=> cleanup related to BaseAddress

coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts
*Issue #:* /bcgov/entity#1559
Code changes to prevent saving duplicate drafts / filings
Added a test/ Fixed a few failing tests
=> Bugfix  #1559 - duplicate drafts

coops-ui/src/components/AnnualReport/Directors.vue
*Issue #:* /bcgov/entity#1652
reverted directors Add/Edit form layout
=> reverted directors Add/Edit form layout

coops-ui/src/components/Dashboard/DirectorListSm.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts
*Issue #:* /bcgov/entity#1611 
Updated the entityType code passed into Payment to be implemented dynamically based on current clients entityType.
Updated - Annual Report Filing, Standalone Directors, Standalone Address Change.
Updated unit testing.
=> #1611 Directors Filing EntityType Payment Code

schemas/src/registry_schemas/schemas/business.json
*Issue #:* /bcgov/entity1610
Remove Co-op hardcoding for schema validation on business identifiers
=> Change validation on business identifiers to be less strict

coops-ui/src/components/Dashboard/FilingHistoryList.vue
=> Bug fix #1485 - Receipts showing incorrect coop name

colin-api/Jenkinsfiles/build.groovy, colin-api/Jenkinsfiles/deploy-test.groovy, entity-filer/Jenkinsfiles/build.groovy, entity-filer/Jenkinsfiles/deploy-test.groovy, jobs/update-colin-filings/Jenkinsfiles/build.groovy, jobs/update-legal-filings/Jenkinsfiles/build.groovy, legal-api/Jenkinsfiles/build.groovy, legal-api/Jenkinsfiles/deploy-test.groovy
=> Added Severin to pipeline permissions.

.gitignore
=> added a backup extension from a text editor I use (editplus)

schemas/src/registry_schemas/example_data/__init__.py, schemas/src/registry_schemas/example_data/schema_data.py, schemas/tests/unit/test_filings.py
=> fixed schema tests after merge

queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/repo-libraries.txt, queue_services/entity-pay/requirements.txt, queue_services/entity-pay/requirements/repo-libraries.txt
=> filer requirements fixes

coops-ui/src/App.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts
*Issue #:* /bcgov/entity#1652
Added back column layout of New Director form.
=> fixed column layout of New Director form.

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts, coops-ui/tests/unit/SummaryDirectors.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#1567
- redirect to Pay URL only if filing needs to be paid
- added new status to Todo List
- created new unit tests
- removed obsolete return value
- misc cleanup + lint fixes
- fixed a font size issue ('i' looked like 'l')
=> redirect to Pay URL only if filing needs to be paid

coops-ui/package.json
As we are deploying another build to Prod, I updated the minor version number accordingly. (We are still in Release 2.)
=> updated version to 2.2.0

legal-api/src/legal_api/models/filing.py
Code change to pick the lastest AR based on the filing_date rather than filing_id.
=> Bug fix - Task list does not pick the latest AR based on the filing date

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/tests/unit/api/test_business_tasks.py, legal-api/tests/unit/models/__init__.py
- fixes todolist bug
- tests updated to follow schema
=> todo list fix

legal-api/src/legal_api/resources/business/business_directors.py, legal-api/tests/unit/api/test_business_director.py
*Issue #:* /bcgov/entity1839
Remove 404 being thrown if director list is empty. Empty list is valid
=> remove error if director list is empty

coops-ui/src/components/AnnualReport/Directors.vue
=> default checkmark to unchecked for same-address on directors

coops-ui/src/mixins/date-mixin.ts
=> Changing date parsing logic to ignore microseconds and timezone offset

lear-db/test_data/add_offices.py, lear-db/test_data/load_coop_2019.py
*Issue #:* /bcgov/entity#1876
Once the story branch is merged, and deployed, coops will need to be updated to have an office association. New coops will need one created on initial load from colin. 
=> add script to fix coops after offices deployed

coops-ui/src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#1870
- fixed typo
=> fixed typo

coops-ui/public/index.html, coops-ui/src/App.vue, coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/main.ts, coops-ui/src/router.ts, coops-ui/src/utils/config-helper.ts, coops-ui/src/views/Dashboard.vue
*Issue #:* /bcgov/entity#1651
- redirect before app starts when no KC token
- deleted obsolete REDIRECTED functionality
- added missing conditions for dashboard loading transition
- added check for env variables
- some cleanup
- defer AddressComplete JS to execute it after app loads (to improve app loading performance)
=> improved app loading behaviour

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/Dashboard/DirectorListSm.vue, coops-ui/tests/unit/Directors.spec.ts
*Issue #:* /bcgov/entity#1914
* Fixed Directors filing submission where the coops directors would contain an empty mailing address.
* Updated unit testing.
=> #1914 Remove Coops Directors Mailing Address

legal-api/report-templates/template-parts/directors.html, legal-api/src/legal_api/reports/report.py
*Issue #:* None.
- fixed a bug found during testing of filings imported from Colin
=> only show Appointed and Ceased directors if filing did not come from Colin

queue_services/entity-filer/requirements/prod.txt, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py, queue_services/entity-filer/src/entity_filer/version.py, queue_services/entity-filer/src/entity_filer/worker.py
=> Entity filer fix for processing colin change of directors

legal-api/report-templates/template-parts/directors.html
- fixed incorrectly nested "if"s
- fixed keyword error
=> more report fixes

queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py
Fix to handle a reappointed director in colin
=> Fix to handle a reappointed director in colin

queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py
=> Fixing condition check

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/tests/unit/FilingHistoryList.spec.ts
*Issue #:* n/a
UI - Filing History - pad filing date with zeroes. This matches original design and was just lost during timezone conversions.
=> UI - Filing History - pad filing date with zeroes

coops-ui/tests/unit/FilingHistoryList.spec.ts
=> non-functional lint fix

queue_services/entity-pay/src/entity_pay/worker.py
*Issue #:* /bcgov/entity#1955
entity-pay - added timezone to payment_completion_date
=> entity-pay - added timezone to payment_completion_date

coops-ui/src/components/AnnualReport/Directors.vue
=> UI - allow spaces in director names, but do not allow empty spaces only

coops-ui/src/App.vue, coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/store/actions.ts, coops-ui/src/store/mutations.ts, coops-ui/src/store/state.ts, coops-ui/tests/unit/AGMDate.spec.ts, legal-api/src/legal_api/models/director.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py
*Issue #:* Misc.
These are fixes to fix functionality currently broken in the current build (in Dev):
- AGM Date UI changes to consider only the last annual report date
- Bug fixes in the director component
- Disabling director component if a standalone director filing exists after the AGM  date
- Changes in the director component to consider appointment date
- Unit test fixes
=> AGM date and Director component fixes

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/FilingHistoryList.spec.ts, legal-api/report-templates/annualReport.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#1975
UI changes for No AGM
Report fixes for No AGM
=> No AGM UI and report changes

coops-ui/package.json, coops-ui/src/App.vue
*Issue #:* /bcgov/entity#1997
- removed filings sorting
- updated UI version to 2.3.0
=> removed filings sorting

legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#1998
Set effective date in db column from json value (effects post-bob colin filings)
=> Set effective date in db column from json value (post-bob colin filings)

coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/AnnualReport.spec.ts
=> Fix to ignore the last preload filing date 

colin-api/colin_api/models/filing.py, colin-api/colin_api/resources/event.py, queue_services/entity-filer/src/entity_filer/version.py
- updated version number for filer
=> version change for filer

coops-ui/src/components/Dashboard/TodoList.vue
=> Changing agm date reference to annual report date

coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/StandaloneDirectorChange/CODDate.vue, coops-ui/src/mixins/date-mixin.ts, coops-ui/src/validators.ts, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/tests/unit/ARDate.spec.ts, coops-ui/tests/unit/CODDate.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, legal-api/report-templates/changeOfDirectors.html, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/reports/report.py
**I accidentally closed @leksmall's original PR (#522) so this is the replacement PR.**
*Issue #:* /bcgov/entity#1579, /bcgov/entity#1582
New date component for Standalone Director Change Date
Report changes to consider effective date
Unit test for the new date component
=> UI and Report changes - Custom date for standalone director change

coops-ui/src/components/AnnualReport/Certify.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/tests/unit/Certify.spec.ts, coops-ui/tests/unit/Directors.spec.ts, coops-ui/tests/unit/EntityInfo.spec.ts, coops-ui/tests/unit/SummaryCertify.spec.ts, coops-ui/tests/unit/SummaryDirectors.spec.ts
*Issue #:* /bcgov/entity#1706
- added rules to validate extra whitespace in Directors component
- added unit tests to verify Directors input values
- added "trim" to some v-models
- removed extra whitespace in Certify component
- fixed boolean errors in Certify component
- updated Certify unit tests re: above
- cleaned up misc unit tests
=> fixed blank space bug for directors names

legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/office.py, legal-api/src/legal_api/services/filings/validations/change_of_address.py, legal-api/tests/__init__.py, legal-api/tests/pytest_marks.py, legal-api/tests/unit/api/test_business_address.py, legal-api/tests/unit/api/test_business_filings.py, legal-api/tests/unit/api/test_business_filings_internal.py, legal-api/tests/unit/api/test_business_filings_reports/test_business_filings_reports.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/models/test_business.py
- fixed existing flake8 errors.
- fixed existing failing tests.
=> fixed linting and test errors

legal-api/src/legal_api/models/filing.py, legal-api/tests/unit/models/test_filing.py
*Issue #:* /bcgov/entity#1997
- set default order_by for get_filings_by_status to submission & effective date
=> set default order_by for get_filings_by_status to submission & effective date

coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/views/AnnualReport.vue
Component hiding in AR for if a later standalone change exists
=> Fix to save and resume noAGM

queue_services/entity-filer/requirements.txt
=> changed requirements to release branch

jobs/update-legal-filings/update_legal_filings.py
- this ensures failed filings from colin don't get forgotten/buried after multiple runs of the legal-updater 
- it also makes sure future filings from the same coop aren't applied before the failed ones are resolved
=> saves first failed id instead of last successful id

coops-ui/src/views/Dashboard.vue, coops-ui/tests/unit/Dashboard.spec.ts
- enums were recently renamed (all caps) but some code was not updated, causing errors; now fixed
=> fixed missing enum renames

colin-api/colin_api/models/filing.py
=> fixed effective date for cod/coa that happened with an ar

coops-ui/tests/unit/Directors.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
=> Test fixes

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/AnnualReport/PaymentErrorDialog.vue, coops-ui/src/components/AnnualReport/ResumeErrorDialog.vue, coops-ui/src/components/AnnualReport/SaveErrorDialog.vue, coops-ui/src/components/ConfirmDialog.vue, coops-ui/src/components/Dashboard/AccountAuthorizationDialog.vue, coops-ui/src/components/Dashboard/CoaWarningDialog.vue, coops-ui/src/components/Dashboard/DashboardUnavailableDialog.vue, coops-ui/src/components/Dashboard/DeleteErrorDialog.vue, coops-ui/src/components/Dashboard/DownloadErrorDialog.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/Dashboard.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/tests/unit/Dashboard.spec.ts, coops-ui/tests/unit/SaveErrorDialog.spec.ts
*Issue #:* /bcgov/entity#1733
- hid contact info for staff in dialogs
- updated some dialog text per wireframes
- changed Okay buttons to OK (per Scott)
- aligned dialog buttons consistently
- made all dialogs persistent (must click button to close)
- made Save Error dialog narrower (per Scott)
- added IDs to dialogs
- fixed missing enum rename
- changed Dashboard responsive breakpoint to medium (per Scott) (no change to main views/pages)
=> updated dialogs (no contact info for staff, cleanup)

schemas/src/registry_schemas/example_data/schema_data.py, schemas/src/registry_schemas/schemas/annual_report.json, schemas/tests/unit/test_annual_report.py, schemas/tests/unit/test_filings.py
*Issue #:* /bcgov/entity#2014
change JSONSchema to validate against the new office/address structure. Removed duplicate tests
=> 2014 update ar schema

legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/tests/unit/api/test_business_tasks.py
*Issue #:* /bcgov/entity#2044
Task list not taking pending filings into account for B-Comp. Fix the todo-list constructor method to account for pending/draft filings for non CO-OP entities as well.
=> fix for bug 2044

legal-api/src/legal_api/services/filings/validations/change_of_directors.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py
*Issue #:* /bcgov/entity#1913
Add empty object check for (optional) mailing address in change of director
=> check not only for a mailing address, but also that it is not empty

coops-ui/src/components/common/OfficeAddresses.vue, coops-ui/src/components/common/SummaryCertify.vue, coops-ui/src/components/common/SummaryDirectors.vue, coops-ui/src/components/common/SummaryStaffPayment.vue, coops-ui/src/components/common/index.ts
*Issue #:* /bcgov/entity#2053
- changed folder name (that git did not detect originally)
=> Fixing dev - Changing the folder name

coops-ui/src/components/AnnualReport/BCorp/ARDate.vue, coops-ui/src/components/Common/SummaryDirectors.vue, coops-ui/src/components/Common/SummaryOfficeAddresses.vue, coops-ui/src/components/Common/index.ts, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/enums/filingCodes.ts, coops-ui/src/enums/index.ts, coops-ui/src/interfaces/filingData-interfaces.ts, coops-ui/src/interfaces/index.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/Dashboard.spec.ts, coops-ui/tests/unit/SummaryOfficeAddresses.spec.ts, schemas/src/registry_schemas/schemas/annual_report.json
Issue #: /bcgov/entity#1424 & /bcgov/entity#1425
Description of changes:
* Refactored the Annual Report component to support a BCOMPs filing while keeping the COOPs filing unchanged.
* Created a new Address Summary Component to display summarized, un-editable address data.
* Updated Unit Testing for Annual Report
* New Unit Testing for the summaryOfficeAddresses component.
* Designs for reference : 
https://invis.io/MHTDPV2Z4GS
=> AR Refactor / Bcomps

legal-api/migrations/versions/441a5e6cf682_.py, legal-api/migrations/versions/94c2a694d51f_.py, legal-api/tests/unit/api/test_business_tasks.py
=> change the order of alembic migrations

coops-ui/tests/unit/SummaryOfficeAddresses.spec.ts
=> Fixing incorrect reference in test

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/common/SummaryDirectors.vue, coops-ui/src/components/common/SummaryOfficeAddresses.vue, coops-ui/src/mixins/common-mixin.ts, coops-ui/src/store/actions.ts, coops-ui/src/store/getters.ts, coops-ui/src/store/state.ts, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/Directors.spec.ts, coops-ui/tests/unit/FilingHistoryList.spec.ts, coops-ui/tests/unit/SummaryDirectors.spec.ts
*Issue #:* /bcgov/entity#2053
- fixed unit tests
- misc cleanup
- added types to store actions, getters and state
=> release 2.3.0 merge cleanup

coops-ui/src/components/common/SummaryDirectors.vue, coops-ui/src/interfaces/director-interfaces.ts
*Issue #:* /bcgov/entity#2049
- changed component to watch its prop
- reverted 'includes' to 'indexOf'
- enforced model usage
- misc cleanup
=> updated Summary Directors component

queue_services/entity-filer/src/entity_filer/filing_processors/annual_report.py
=> Merge clean up: Removing incorrect import in entity filer 

legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#2078
Annual Report and Change of Address Report fixes
=> Annual Report and Change of Address Report fixes

jobs/future-effective-filings/openshift/cron-file-future-effective.yml
=> initial commit

jobs/future-effective-filings/config.py, jobs/future-effective-filings/openshift/cron-file-future-effective.yml
=> Env variables future effective cron

queue_services/entity-filer/k8s/entity-filer-deploy.dev.param, queue_services/entity-filer/k8s/templates/entity-filer-deploy.json, queue_services/entity-filer/src/entity_filer/config.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/integration/test_publish_event.py
*Issue #:* /bcgov/entity#1623
- fixed some pre-existing lint errors
- added a new queue subject and publish a summary of the legal-filings to it.
=> 1623 publish filer changes to queue

coops-ui/package.json, coops-ui/public/config/configuration.json, coops-ui/src/main.ts, coops-ui/src/services/token-services.ts, coops-ui/src/utils/config-helper.ts, coops-ui/vue.config.js
*Issue #:* /bcgov/entity#2077
- copied token service locally (for now - will use sbc-common-components version later)
- added KC JSON URL to config
- check for all necessary tokens on app start
- initialized token service to periodically refresh kc token
- fixed font preload href
=> integrated kc refresh service (local copy for now)

coops-ui/src/services/token-services.ts
*Issue #:* /bcgov/entity#2077
- fixed typo in local library
=> fixed typo in local library

colin-api/tests/postman/colin-api-local.postman_environment.json
*Issue #:* n/a
added env for colin postman tests running locally
=> added env for colin postman tests running locally

jobs/future-effective-filings/file_future_effective.py
*Issue #:* /bcgov/entity#2161
remove event_loop.run_forever()
=> Cron job remains subscribed to queue after running

Jenkinsfiles/oracle-dev-refresh.groovy, Jenkinsfiles/oracle-forapi-refresh.groovy
=> fixed error in pipelines

jobs/future-effective-filings/openshift/cron-file-future-effective.yml
*Issue #:* n/a
future effective filings - changed cron to no concurrent
=> future effective filings - changed cron to no concurrent

coops-ui/src/components/Dashboard/TodoList.vue
While investigating design options with Scott, we found that the Todo List buttons had excessive whitespace around them (compared with deployed code in Test and Prod). This PR fixes that.
=> fixed excessive whitespace around buttons

colin-api/tests/README.md
*Issue #:* /bcgov/entity#2121
Added readme for colin-api testing. Please review and let me know if this is enough detail, or if there is anything missing from what we talked about in our lunch and learn.
Including @peter-freshworks and @cameron-freshworks for your information since you weren't at the session. Please see if you can get set up and come to me (katie) if you need assistance or clarification.
=> readme for colin-api testing

coops-ui/src/App.vue, coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/StandaloneDirectorChange/CODDate.vue, coops-ui/tests/unit/App.spec.ts, coops-ui/tests/unit/CODDate.spec.ts, legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#2149, /bcgov/entity#2160
Fix for banner not in sync with date picker for coops
Fix for effective date not getting set from the input for bcomp
New requirement of setting date picker to business founding date if no filings exist for Bcomp or coops
Test updates.
=> Custom director change - date fixes

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/common/OfficeAddresses.vue, coops-ui/src/components/common/SummaryDirectors.vue, coops-ui/tests/unit/Directors.spec.ts
**NOTE: THIS PR NO LONGER DEPENDS ON LATEST SBC-COMMON-COMPONENTS.**
*Issue #:* /bcgov/entity#1921
- replaced duplicate ids with classnames in Directors component
- some simplification and cleanup
- updated some unit tests
=> cleanup related to BaseAddress usage

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* /bcgov/entity#1982 (COD effective dates), /bcgov/entity#2122 (cancel payment)
Added tests for COD effective date, cancel payment, dir list by date.
Also changed some test validation in COD and COA task list tests to make
more robust.
=> Added tests for COD effective date, cancel payment, dir list by date.

colin-api/Jenkinsfiles/deploy-test.groovy
=> colin-api test pipeline fix

coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/resources/business-config.ts, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts
*Issue #:* /bcgov/entity#1550
Small typos in certify component and todo-list
=> 1550 spelling errors

colin-api/src/colin_api/models/filing.py, jobs/update-colin-filings/update_colin_filings.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_tasks.py
- minor updates after looking through the tables with Bob
=> fixes implemented after testing with Bob

coops-ui/src/components/Dashboard/FilingHistoryList.vue
*Issue #:* /bcgov/entity#2274
Fixed bug 
=> Fixed bug - js error if filing json doesn't contain effectiveDate

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/components/EntityInfo.vue
*Issue #:* /bcgov/entity#1853, /bcgov/entity#2037, /bcgov/entity#1805
Added min-width to the list item so that the delete draft button is visible
=> Bugfix - IE11 - cannot delete draft

coops-ui/src/components/common/OfficeAddresses.vue
*Issue #:* /bcgov/entity#662
- fixed address layout (IE11, Edge)
=> fixed address layout (IE11, Edge)

coops-ui/src/assets/styles/base.scss, coops-ui/src/components/Dashboard/AddressListSm.vue, coops-ui/src/components/Dashboard/DirectorListSm.vue
*Issue #:* /bcgov/entity#2301
- fixed empty address lines (re: Firefox)
=> fixed empty address lines (re: Firefox)

legal-api/src/legal_api/services/filings/validations/change_of_directors.py, legal-api/tests/unit/services/filings/validations/change_of_director/test_validation_basic.py
*Issue #:* /bcgov/entity#2278
- removed validation of directors address that required it to be in BC
=> removed validation of directors address that required it to be in BC

coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/StandaloneDirectorsFiling.vue, coops-ui/src/views/StandaloneOfficeAddressFiling.vue
*Issue #:* /bcgov/entity#2239
- disabled Cancel button when busy saving or filing/paying
=> disabled Cancel button when busy

jobs/update-colin-filings/config.py, jobs/update-colin-filings/openshift/cron-update-colin-filings.yml
=> colin-updater config fix

coops-ui/public/index.html, coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/mixins/date-mixin.ts
*Issue #:* /bcgov/entity#2320
- deferred timezone polyfill script
- simplified date formatting
- used different locale for consistent date formatting
- reformatted dates for Jest if needed
=> fixed date format issue that broke Filing History in IE11

colin-api/src/colin_api/models/director.py, colin-api/tests/unit/api/test_ar.py, colin-api/tests/unit/api/test_directors.py, jobs/update-colin-filings/config.py, jobs/update-colin-filings/openshift/cron-update-colin-filings.yml, lear-db/test_data/data-loader.yml, lear-db/test_data/load_coop_2019.py
- added user id to data-loader so that source of historic filings gets set to COLIN
- added check in colin-api director change - if director doesn't exist it will fail 
=> 1147 colin updater

jobs/update-colin-filings/openshift/cron-update-colin-filings.yml, jobs/update-colin-filings/update_colin_filings.py
- updated yml: put concurrencyPolicy in properly
- updated success message to be a debug msg instead of an error msg
=> small updater fixes

jobs/update-colin-filings/update_colin_filings.py
=> put clean none method back in to resolve err

data-reset-tool/Jenkinsfiles/deploy-test.groovy, data-reset-tool/k8s/README.md, data-reset-tool/k8s/data-reset-tool-build-pipeline.param, data-reset-tool/k8s/data-reset-tool-deploy.dev.param, data-reset-tool/k8s/templates/data-reset-tool-build.json, data-reset-tool/k8s/templates/data-reset-tool-deploy.json, data-reset-tool/k8s/templates/data-reset-tool-pipeline.json, data-reset-tool/pre-hook-update-db.sh, data-reset-tool/src/data_reset_tool/converter/ExcelWriter.py
*Issue #:* /bcgov/entity#2262
Data reset tool deployed in openshift - build and pipeline, plus dev deployment.
This is currently build from my branch in Openshift if you want to see it in action.
ALSO INCLUDES a bug fix for adding director addresses.
=> 2262 data reset tool in Openshift

coops-ui/src/components/AnnualReport/Directors.vue, coops-ui/src/components/common/SummaryDirectors.vue
*Issue #:* /bcgov/entity#2286
- fixed v-chip display on 2 pages
- capitalized v-chip text on review page
- removed obsolete CSS properties
=> fixed v-chip layout

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/common/OfficeAddresses.vue, coops-ui/tests/unit/OfficeAddresses.spec.ts
*Issue #:* /bcgov/entity#2331
* Updated Filing history UI for future effective dates. 
https://user-images.githubusercontent.com/26335434/71854968-93bab000-3094-11ea-8b42-126229b19d82.PNG
* Fixed UI for Address component.
https://images.zenhubusercontent.com/5d49ce359547713e57d6cd4b/f8557ee5-b404-4ad1-a553-503eff0a94eb
* Fixed Some functionality for Records address when it is the same as Registered Address. 
* Updated Unit testing.
=> #2331 Updated Design of UI for FilingHistory List & Address Component

jobs/future-effective-filings/Jenkinsfiles/build.groovy, jobs/future-effective-filings/file_future_effective.py, jobs/future-effective-filings/openshift/cron-file-future-effective.yml, jobs/future-effective-filings/requirements/prod.txt
*Issue #:* /bcgov/entity#2161
After some troubleshooting and debugging, this seems to be fixed. Added libraries to requirements file
=> Fix for CRON job hang

.github/workflows/schema-pr.yml, .github/workflows/schema-publish.yml
*Issue #:* /bcgov/entity#2296a
- initial GH Actions for schema package
=> initial workflows for schema, to being testing on GH

schemas/src/registry_schemas/example_data/__init__.py, schemas/tests/unit/test_annual_report.py, schemas/tests/unit/test_filings.py
*Issue #:* n/a
- fix existing pylint and flake8 errors
- fix failing pytest
=> fixing others lint and pytest errors

coops-ui/src/components/Dashboard/FilingHistoryList.vue, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/src/views/Dashboard.vue
*Issue #:* /bcgov/entity#2377
- set missing id so logic drops through and doesn't cause infinite looping
- minor cleanup + added helpful comments for future development/debugging
=> fixed logic that caused looping

coops-ui/package.json, data-reset-tool/src/data_reset_tool/version.py, legal-api/src/legal_api/version.py, queue_services/entity-filer/src/entity_filer/version.py, queue_services/entity-pay/src/entity_pay/version.py, schemas/src/registry_schemas/version.py
*Issue #:* n/a
Bumped versions, no review needed.
=> bumped versions

coops-ui/src/components/common/OfficeAddresses.vue
=> Adding a check for record office as this is not present for coops

coops-ui/package.json, coops-ui/src/components/common/OfficeAddresses.vue, data-reset-tool/src/data_reset_tool/version.py, legal-api/src/legal_api/version.py, queue_services/entity-filer/src/entity_filer/version.py, queue_services/entity-pay/src/entity_pay/version.py, schemas/src/registry_schemas/version.py
*Issue #:* n/a
Merging release branch back into master.
=> Release 2.5.0

coops-ui/package.json
=> Updated sbc-common to version 37

queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/__init__.py, queue_services/entity-filer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#2410
- updated filer for lear model changes
=> updated filer for lear model changes

legal-api/src/legal_api/resources/business/business.py
*Issue #:* /bcgov/entity#1894
Added OPTIONS to Business endpoints 
=> options preflight header added to endpoints

jobs/filings-notebook-report/openshift/templates/filings-notebook-report-bc-template.json, jobs/filings-notebook-report/openshift/templates/filings-notebook-report-pipeline.json, jobs/filings-notebook-report/openshift/templates/filings-notebook-report-runtime-bc-template.json
Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>
Added Filings Stats to Jupyter Notebook Report
=> 651-Stats-for-Filings

coops-ui/package.json
=> Updating common components version to 40

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/src/legal_api/services/filings/validations/validation.py, legal-api/tests/unit/api/test_business_incorporation.py
=> Fixed flake8 and pylint errors (no functionality change).

coops-ui/jest.config.js, coops-ui/package.json
*Issue #:* /bcgov/entity#2370
- added Jest flag to fix ts-jest problem
- updated sbc-common-components to latest (41)
=> fixed unit test problem

colin-api/src/colin_api/models/address.py, colin-api/src/colin_api/models/director.py, colin-api/src/colin_api/models/entity_name.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/models/office.py, colin-api/src/colin_api/resources/directors.py, colin-api/src/colin_api/resources/filing.py, colin-api/src/colin_api/resources/office.py, colin-api/tests/unit/api/test_directors.py, jobs/update-colin-filings/update_colin_filings.py
=> pass connection through code to inc speed and fix bug

jobs/update-colin-filings/update_colin_filings.py, legal-api/src/legal_api/models/filing.py
=> quick add to skip filings

colin-api/src/colin_api/models/business.py
=> added reset fix

jobs/update-colin-filings/update_colin_filings.py
=> added skip to bcomps and test coops

legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/resources/business/business.py, legal-api/tests/postman/legal-api.postman_collection.json, legal-api/tests/unit/api/test_business_incorporation.py, legal-api/tests/unit/api/test_business_tasks.py
*Issue #:* /bcgov/entity#2138
Updated put/post for business endpoint (incorporation) for consistency with filing endpoints.
Changed unit and postman tests to match.
Fixed one unrelated unit test, breaking due to new year.
NOT linked to ticket yet because this is only step 1, does not complete ticket.
=> Updated put/post for business endpoint (incorporation) for consistency with filing endpoints.

colin-api/src/colin_api/models/director.py
=> Cherrypick

colin-api/src/colin_api/models/director.py
=> updated director method for bad data

colin-api/src/colin_api/models/address.py, colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/director.py, colin-api/src/colin_api/models/entity_name.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/models/office.py, colin-api/src/colin_api/resources/directors.py, colin-api/src/colin_api/resources/filing.py, colin-api/src/colin_api/resources/office.py, colin-api/src/colin_api/version.py, colin-api/tests/unit/api/test_directors.py, jobs/update-colin-filings/update_colin_filings.py, legal-api/setup.cfg, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/version.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py, queue_services/entity-filer/src/entity_filer/version.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/__init__.py, queue_services/entity-filer/tests/unit/test_worker.py
*Issue #:* 
| bcgov/entity#2410 | Syncing COLIN: update colin_event_id to be a cross reference table |
| bcgov/entity#2362 | Finish testing/start colin updater in prod |
| bcgov/entity#2354 | colin data resetter |
- see tickets for details
- summary: code to get syncing back to colin
=> Release 2.5.2 - colin updater and resetter + colin_event_ids cross-reference table

coops-ui/.env, coops-ui/.env.production, coops-ui/public/config/configuration.json, coops-ui/public/config/local-configuration.json, coops-ui/src/components/Dashboard/TodoList.vue, coops-ui/src/main.ts, coops-ui/src/utils/config-helper.ts, coops-ui/tests/unit/AnnualReport.spec.ts, coops-ui/tests/unit/StandaloneDirectorsFiling.spec.ts, coops-ui/tests/unit/StandaloneOfficeAddressFiling.spec.ts, coops-ui/tests/unit/TodoList.spec.ts
*Issue #:* /bcgov/entity#2433
- moved Auth Path to config params
- moved Signin Path to config params
- added Businesses URL to config params
- inform signin to return to businesses page
- added missing Vue2Filters init
**NOTE** The config maps need to be updated - see /bcgov/entity#2584
=> updated Return URL to Businesses Dashboard

colin-api/src/colin_api/models/director.py
*Issue #:* n/a - ops fix
Compare director names case-insensitive.
=> Compare director names case-insensitive.

.gitignore, coops-ui/package-lock.json, coops-ui/package.json
- updated version to 2.6.0
- checked in package-lock.json (NB: this ensures that the build server uses the same versions of packages that we developed with)
=> updated version + checked in package lock file

colin-api/requirements.txt, colin-api/requirements/repo-libraries.txt, colin-api/src/colin_api/models/director.py, data-reset-tool/requirements.txt, data-reset-tool/requirements/repo-libraries.txt, jobs/filings-notebook-report/requirements/prod.txt, jobs/update-colin-filings/requirements/prod.txt, jobs/update-legal-filings/requirements/prod.txt, lear-db/test_data/requirements.txt
=> Updated all requirements to point to new schemas location

lear-db/test_data/fix_missing_offices_json.py, lear-db/test_data/requirements.txt
*Issue #:* /bcgov/entity#2537
Added one-time script that was used for fixing older filings without offices.
=> Added one-time script that was used for fixing older filings without offices.

colin-api/src/colin_api/models/director.py, colin-api/src/colin_api/models/filing.py
*Issue #:* /bcgov/entity#2537
- fixes going in with colin-api
=> flake8 fix + ledger notation update

coops-ui/src/components/AnnualReport/AGMDate.vue, coops-ui/src/views/AnnualReport.vue, coops-ui/tests/unit/AGMDate.spec.ts, coops-ui/tests/unit/AnnualReport.spec.ts
*Issue #:* /bcgov/entity#2648
- updated Annual Report Date logic (see code comments for details)
=> updated Annual Report Date logic

schemas.deprecated/README.md
*Issue #:* n/a
Added note re. new schemas location.
=> Added note re. new schemas location.

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/models/comment.py, legal-api/src/legal_api/models/user.py, legal-api/tests/unit/api/test_filing_comments.py, legal-api/tests/unit/models/test_comments.py, legal-api/tests/unit/models/test_user.py
*Issue #:* /bcgov/entity#2613
Added submitter display name to comment json output.
=> Added submitter display name to comment json output.

README.md
=> Added SonarCloud badges

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/models/__init__.py, legal-api/src/legal_api/models/address.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/src/legal_api/services/filings/validations/validation.py, legal-api/tests/unit/api/test_business_incorporation.py
*Issue #:* /bcgov/entity#2138
Re-arranged legal API for incorporation.
Encapsulated some functionality for re-use in Business and Filing.
=> Re-arranged legal API for incorporation.

.sonarcloud.properties
Updating to the exact locations
Remove some of the test paths and refined the others as we are getting errors on the scanning.
=> Getting some errors on the test locations

.sonarcloud.properties
The layered structure of the directories in this repository poses some challenges when narrowing the paths for the sources.
Update the paths.
=> Update the source paths to make sure that all can be found

legal-api/migrations/env.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/src/legal_api/services/filings/validations/correction.py, legal-api/src/legal_api/services/filings/validations/validation.py, legal-api/src/legal_api/version.py, legal-api/tests/__init__.py, legal-api/tests/unit/api/test_business_tasks.py, legal-api/tests/unit/models/test_filing.py, legal-api/tests/unit/services/filings/validations/test_correction.py, queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/repo-libraries.txt, queue_services/entity-filer/requirements/temp.txt, queue_services/entity-filer/src/entity_filer/filing_processors/correction.py, queue_services/entity-filer/src/entity_filer/version.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/__init__.py, queue_services/entity-filer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#2637
Added correction filing processing to entity filer.
Includes two changes to legal api to support corrections in Entity Filer.
=> Added correction filing processing to entity filer.

support/notebooks/business-ops/bcr-business-ops-template.ipynb, support/notebooks/business-ops/bcr-business-setup.ipynb
*Issue #:* /bcgov/entity#2614
- added function to find latest correction filing
- added section to add new directors
=> updated template for correction filing type, and adding directors

support/notebooks/business-ops/bcr-business-ops-template.ipynb
*Issue #:* /bcgov/entity#2614
- commented out the TXN check
- added a check for PENDING_CORRECTION state
- added the Director model into the import
=> removed previous TXN check, added PENDING_STATE check and added import of Director model.

legal-api/tests/unit/api/test_filing_comments.py, legal-api/tests/unit/models/test_comments.py
*Issue #:* n/a
- changed tests to use freezegun and removed the system tiimezone setup so that it'll work on other setups
=> changed datetiime usage so that it works on other platforms

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings.py
*Issue #:* /bcgov/entity#2765
- fixed some returns to follow the {errors[{}]} pattern.
- added when a call to pay fails with a 400 (BAD_REQUEST) that the returned {code, message} are returned as an error block.
=> adding pass through of code & message when payment fails

legal-api/requirements.txt, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py
*Issue #:* /bcgov/entity#2673
* Updated Schema version dependency.
* Implemented Validators for Step 2 People and Roles data.
* Pytests for additional validators and properties.
=> #2673 legal api step2

legal-api/src/legal_api/services/filings/validations/validation.py, legal-api/tests/unit/api/test_business_tasks.py, legal-api/tests/unit/services/filings/validations/test_correction_coa.py
*Issue #:* /bcgov/entity#3017
- added validation for a COA correction
- added tests for the validation functionality
=> added validations for a COA correction

legal-api/src/legal_api/models/share_class.py, legal-api/src/legal_api/resources/business/__init__.py, legal-api/src/legal_api/resources/business/business_share_classes.py, legal-api/tests/unit/api/test_business_share_classes.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/models/test_share_class.py
*Issue #:* /bcgov/entity#3035
Added endpoints for share structure
Added unit tests
=> Endpoints for share structure

legal-api/requirements.txt, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py
*Issue #:* /bcgov/entity#3171
* Refactored validators and unit tests based on updated schema.
* Updated schema version in requirements.txt.
* Also involved a small update/pr to schemas repo to release the latest changes.
=> #3171 Refactor Step2 Validators

legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py
*Issue #:* /bcgov/entity#3035
*Description of changes:* Step 3 validator
=> Step 3 validator

jobs/update-legal-filings/update_legal_filings.py, lear-db/test_data/Makefile
=> tiny fix for manually bringing across a filing and makefile

legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/tests/unit/api/test_business_tasks.py
*Issue #:* /bcgov/entity#2932
Default to next anniversary year if no annual reports exist
=> bug fix for 2932

legal-api/src/legal_api/config.py, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#1940
Retrieve full country name for report display
=> 1940 country bug

legal-api/src/legal_api/resources/business/business_tasks.py
*Issue #:* /bcgov/entity#3102
- fixing a bug where empty tasks are returned for nr
=> 3102 - bugfix empty tasks list for nr

legal-api/src/legal_api/resources/business/business_tasks.py
*Issue #:* /bcgov/entity#3102
- NR bug fix to check for completed and paid filings
=> 3102 - bug fix to check for PAID/COMPLETED filings

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/requirements/prod.txt, legal-api/src/legal_api/__init__.py, legal-api/src/legal_api/models/__init__.py, legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/comment.py, legal-api/src/legal_api/models/db.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/models/user.py
*Issue #:* n/a
remove the marshmallow library and associated schemas that were not being used.
=> Remove marshmallow

legal-api/src/legal_api/resources/business/business.py, legal-api/tests/unit/api/test_business.py
*Issue #:* n/a
add that a JWT and read authorization is required for GET
=> add that a JWT and read authorization is required for GET

jobs/future-effective-filings/file_future_effective.py
*Issue #:* /bcgov/entity#2546
- fixes: queue msg format and debug success stmnt
- this will stop it from failing in the filer
=> fixed queue msg format and debug success stmnt

legal-api/tests/unit/models/test_party_role.py, queue_services/entity-filer/src/entity_filer/filing_processors/__init__.py
*Issue #:* /bcgov/entity#1891
- fixed bug (was parsing json incorrectly for middle initial)
- added 2 more checks to legal tests
=> added tests, fixed bug

tests/postman/lear-integration.postman_collection.json
*Issue #:* /bcgov/entity#3506
- Created file structure for integration tests (/tests/postman since it will span different components)
- Added postman collection with pre-request script that gets a staff token (script is based on pay-api collection script that does the same thing)
=> 3506 - integration tests collection with pre-request script for staff token

legal-api/src/legal_api/resources/business/business.py
*Issue #:* /bcgov/entity###N/A
- removed extra auth check to prevent looping from auth-api (code to be recommented in after affiliation moves to lear)
=> removed auth check on get businesses/id for relationships

legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#3527,  /bcgov/entity#3540
Changed the filing type code for Incorporation
Added the futureEffective flag to filing type for Incorporation
Removed the method of payment from the create invoice payload
=> Payment related changes for incorporation

legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/api/test_business_incorporation.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py
*Issue #:* /bcgov/entity#2131
* Implemented validators an effective date for future effective incorporation filings.
* Updated unit testing.
=> Implemented Future Effective Validators

colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py, colin-api/tests/unit/api/test_incorporation_application.py
*Issue #:* /bcgov/entity#2343
- update create_corp_name(), create_corp_state(), create_corp_jurisdication() parameterization code
- add get_corp_name() to filing model
- update add filing to populate legal name
- update unit test to assert corp name (legal name) and corp state
=> 2343 - corp_name fixes

legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#3639
- updated set effective date logic to take into account local time offset
=> 3639 - update set effective date logic to take into account local time offsets

colin-api/src/colin_api/version.py, legal-api/src/legal_api/version.py, queue_services/entity-filer/src/entity_filer/version.py
=> version updates

legal-api/k8s/secret.param, legal-api/k8s/templates/secret.json, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py
=> fixed bug added k8s for secres in legal

legal-api/k8s/secret.param, legal-api/k8s/templates/secret.json, queue_services/entity-filer/src/entity_filer/config.py, queue_services/entity-filer/src/entity_filer/filing_processors/change_of_directors.py, queue_services/entity-filer/tests/conftest.py
*Issue #:* bcgov/entity#3679
- release branch merge
- includes bug fix and secrets k8s files for legal
=> release 2.9 branch merge

colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/models/reset.py
*Issue #:* /bcgov/entity#3790
- fixed filing type codes for bcomp
- lead to small refactor for adding/getting filings
- added insert into bn_process table for bcomp incorps
- pytests now fail because bcomp filing_typ_cds don't exist in our dev oracle (updated for now in for-api but will be gone after it is reset)
=> updated filing for bcomp

jobs/update-legal-filings/update_legal_filings.py
*Issue #:* /bcgov/entity#3817
- updated one of our calls to legal that now needs an auth header after last release
=> fixed legal updater bug

jobs/update-legal-filings/update_legal_filings.py
=> update based off colin api change

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#3766
- add folio number to invoice payload
=> 3766 - add folio number to invoice payload

.github/workflows/entity-emailer-pr.yml, queue_services/common/src/entity_queue_common/service_utils/__init__.py, queue_services/common/src/entity_queue_common/service_utils/exceptions.py
*Issue #:* /bcgov/entity#3396
- needed to have next PR pass tests
=> dependencies for entity-emailer

legal-api/prism.sh, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/services/bootstrap.py, legal-api/tests/unit/api/test_business_filings/test_filing_incorporation.py, legal-api/tests/unit/services/test_registraion_bootstrap_service.py
*Issue #:* /bcgov/entity#3805
- delete filing
- delete affiliation
=> 3805 delete ia filing and temporary registration

legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/services/__init__.py, legal-api/src/legal_api/services/document_meta.py, legal-api/src/legal_api/utils/legislation_datetime.py, legal-api/tests/unit/services/test_document_meta.py
*Issue #:* /bcgov/entity#3598
- add documents meta to filings json
- add document meta service to generate array of documents
=> 3598-documents-list

jobs/update-legal-filings/Makefile, jobs/update-legal-filings/requirements.txt, jobs/update-legal-filings/requirements/bcregistry-libraries.txt, jobs/update-legal-filings/requirements/prod.txt, jobs/update-legal-filings/update_legal_filings.py, lear-db/test_data/parties_fix_release2.9.py, lear-db/test_data/requirements.txt
*Issue #:* /bcgov/entity#3817
- script made to fix parties after last release (was already run and will not need to be run again)
- legal-updater req updates and makefile (was done to run the updater locally against prod for an ops ticket)
=> 3817 sbc ops

queue_services/common/src/entity_queue_common/messages.py, queue_services/entity-pay/src/entity_pay/config.py, queue_services/entity-pay/src/entity_pay/worker.py, queue_services/entity-pay/tests/conftest.py, queue_services/entity-pay/tests/integration/test_worker_queue.py
=> Trigger email after payment

queue_services/entity-filer/requirements.txt
*Issue #:*none
downgraded to werkzeug==0.16.1
=> downgraded to werkzeug==0.16.1

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
*Issue #:* n/a
hack over the legalType of a missing NR body
to be removed asap
=> hack for bad ia

legal-api/report-templates/incorporationApplication.html, legal-api/report-templates/template-parts/incorporation-application/nameRequest.html
=> Changed the condition to distinguish btw named and numbered company

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/src/entity_filer/worker.py
*Issue #:* n/a
- added the CREATED http status codes
=> corrected return codes for affiliation call

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
*Issue #:* n/a
corrected logic issues 
=> logic error corrected, stumbled trying to be quick.

legal-api/src/legal_api/resources/business/business_filings.py
=> Cancel Payment for IA

queue_services/entity-emailer/k8s/templates/entity-emailer.dc.json
=> updated dc.json file

queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py
*Issue #:* /bcgov/entity#3810
- last template path fix
=> template path fix

queue_services/entity-pay/requirements/bcregistry-libraries.txt
*Issue #:* /bcgov/entity#3810
- schema version change
=> grab most recent schema

queue_services/entity-emailer/src/entity_emailer/email_templates/BC-MRAS.html, queue_services/entity-emailer/src/entity_emailer/email_templates/BC-filed-success.html, queue_services/entity-emailer/src/entity_emailer/email_templates/BC-registered-success.html, queue_services/entity-emailer/src/entity_emailer/email_templates/common/initiative-notice.html, queue_services/entity-emailer/src/entity_emailer/email_templates/common/style.html
*Issue #:* /bcgov/entity#3793
- updated HTML titles for all 3 templates
- fixed MRAS template text
- updated MRAS partners URLs
- updated list item style for Microsoft Outlook
- fix for link item spacing (for Outlook)
=> updated MRAS template and link URLs + misc

queue_services/common/src/entity_queue_common/messages.py, queue_services/common/src/entity_queue_common/service_utils/__init__.py, queue_services/entity-filer/src/entity_filer/config.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/test_worker/test_incorporation.py, queue_services/entity-pay/src/entity_pay/worker.py, queue_services/entity-pay/tests/integration/test_worker_queue.py, queue_services/entity-pay/tests/integration/utils.py
*Issue #:* /bcgov/entity#3795
- email trigger for completed incorp
- moved code being used by both filer and pay into common
=> incorp complete email trigger - moved stuff for pay/filer into common

queue_services/entity-filer/src/entity_filer/worker.py
*Issue #:* /bcgov/entity#3795
- fixed syntax issue
=> fixed async/await issue

queue_services/entity-emailer/src/entity_emailer/worker.py
*Issue #:* /bcgov/entity#3795
- updated error messaging
=> fixed unneeded error sending

queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-pay/src/entity_pay/worker.py
=> fixed publish email message

queue_services/entity-emailer/q_cli.py
=> fixed q_cli error

queue_services/entity-emailer/src/entity_emailer/email_processors/incorp_notification.py
=> fixed noa and certificate call

queue_services/entity-emailer/src/entity_emailer/email_processors/incorp_notification.py
=> fixed getting numbered company receipt

queue_services/entity-filer/src/entity_filer/worker.py
=> quick fix to publish event

queue_services/entity-filer/src/entity_filer/version.py, queue_services/entity-filer/src/entity_filer/worker.py
=> 3816 release 2.11

colin-api/src/colin_api/version.py, legal-api/src/legal_api/version.py
=> updated api versions

queue_services/entity-emailer/src/entity_emailer/email_processors/incorp_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/BC-filed-success.html, queue_services/entity-emailer/src/entity_emailer/email_templates/BC-registered-success.html
*Issue #:* /bcgov/entity#4090
- implemented different subjects for emails
- set reasonable fallback HTML titles
=> implemented different subjects in IA emails

colin-api/src/colin_api/models/address.py, colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/corp_party.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py, colin-api/tests/__init__.py, colin-api/tests/postman/colin-api.postman_collection.json, colin-api/tests/unit/api/test_incorporation_application.py, colin-api/tests/unit/api/test_share_structure.py, colin-api/tests/utilities/decorators.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
=> fixes suggested by DBAs

colin-api/src/colin_api/models/address.py, colin-api/src/colin_api/models/corp_party.py, colin-api/src/colin_api/models/filing.py
=> broke out next ids for coops

colin-api/tests/postman/colin-api.postman_collection.json
=> incorp postman fix for bn

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
=> filer fix on get_next_corp_num

legal-api/report-templates/template-parts/incorporation-application/directors.html
*Issue #:* /bcgov/entity#4164
- director mailing address section was incorrectly displaying delivery address
=> fixed incorrect director mailing address in outputs

jobs/future-effective-filings/file_future_effective.py
*Issue #:* N/A
After testing this in Dev, I confirm that the time comparison logic is correct.
=> updated comment

jobs/update-legal-filings/update_legal_filings.py
=> await email fix

jobs/update-legal-filings/update_legal_filings.py
=> removed unneeded await

jobs/update-legal-filings/update_legal_filings.py
=> added asyncio event loop for async

jobs/update-legal-filings/config.py, jobs/update-legal-filings/k8s/templates/cronjob.json, jobs/update-legal-filings/k8s/templates/job.json
=> adding queue params

jobs/update-legal-filings/config.py, jobs/update-legal-filings/update_legal_filings.py
=> Bn email trigger fix

jobs/update-legal-filings/requirements.txt, jobs/update-legal-filings/requirements/bcregistry-libraries.txt, jobs/update-legal-filings/update_legal_filings.py, legal-api/src/legal_api/services/queue.py
=> BN trigger changes

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/api/test_name_requests.py
*Issue #:* /bcgov/entity#3883
- added functions for updating a name request in namex service
- added logic to update to name request expiration date on a completed filing, if the effective date exceeds the name request expiration date, the expiration date is extended to the future effective date (plus one day to allow for time jobs to process)
- added an update nr test
=> handle future effective dating NR

jobs/filings-notebook-report/daily/incorpfilings.ipynb, jobs/filings-notebook-report/monthly/cooperative.ipynb, jobs/filings-notebook-report/monthly/coopfilings.ipynb, jobs/filings-notebook-report/notebookreport.py, jobs/filings-notebook-report/openshift/templates/cron-notebook-report.yml, jobs/filings-notebook-report/requirements/prod.txt
Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>
*Issue #:* /bcgov/entity 4188
Add report for BCOMP Incorporation.
=> 4188-Jupiter Report for BCOMP Incorporation

legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py
*Issue #:* /bcgov/entity#4155
- merged arrays instead of nesting them
- updated unit tests accordingly
=> fixed incorrect IA validation error response

legal-api/src/legal_api/resources/business/__init__.py, legal-api/src/legal_api/resources/business/business_aliases.py, legal-api/tests/unit/api/test_business_aliases.py, legal-api/tests/unit/models/__init__.py
*Issue #:* /bcgov/entity#4129
Added endpoints for aliases
Added tests
=> Endpoint changes for aliases

legal-api/report-templates/incorporationApplication.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#4104
- added name translation section to IA report template
- ~~computed list of translations for alteration filings~~ _future ticket_
- set list of translations for IA filings
=> added Name Translation to IA/NOA outputs

legal-api/src/legal_api/resources/business/__init__.py, legal-api/src/legal_api/resources/business/business_resolutions.py, legal-api/tests/unit/api/test_business_resolutions.py
*Issue #:* /bcgov/entity#4309
Added Endpoint for resolutions
Added tests
=> Endpoint for resolutions

legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#4104
- added handling in case "nameTranslations" object does not exist on this particular filing
=> Fix for incorporation application not getting downloaded

colin-api/requirements.txt
*Issue #:* /bcgov/entity#4169
- removed legal-api import
=> fixed reqs

legal-api/src/legal_api/services/document_meta.py, legal-api/tests/unit/services/test_document_meta.py
*Issue #:* /bcgov/entity#4107
- added functions to process correction and alteration filings (for future)
- added COA NOA conditionally
- added COD NOA conditionally
- added CON NOA conditionally (assume same as COA/COD)
- simplified formal parameters / added helper functions / cleanup
=> updated filing documents lists

queue_services/entity-filer/src/entity_filer/version.py
=> version for filer

colin-api/src/colin_api/utils/__init__.py, jobs/update-colin-filings/update_colin_filings.py
*Issue #:* /bcgov/entity#4194
- handles colin-updater old data problem
- handles different date timestamp strings in colin-api
=> handles bad data

jobs/update-colin-filings/update_colin_filings.py
=> fixed colin-updater for coops

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
=> changed get new corp num to post call

jobs/update-colin-filings/setup.cfg, jobs/update-colin-filings/update_colin_filings.py
*Issue #:* /bcgov/entity#4251
- small cleanup changes
=> small cleanup, put in while doing ops fix

queue_services/entity-filer/src/entity_filer/filing_processors/__init__.py
=> Fix for share series not getting saved in db

colin-api/src/colin_api/models/corp_party.py, colin-api/src/colin_api/models/filing.py, colin-api/tests/postman/colin-api.postman_collection.json, support/notebooks/business-ops/bcr-bcomp-alteration-template.ipynb, support/notebooks/business-ops/bcr-business-setup.ipynb, support/notebooks/business-ops/requirements.txt
*Issue #:* /bcgov/entity#4165
- notebook for manually processing an alteration filing
- colin-api changes for new schema alteration stuff
=> notebook built + colin-api changes for schema

colin-api/src/colin_api/version.py, legal-api/src/legal_api/version.py, queue_services/entity-filer/src/entity_filer/version.py
*Issue #:* /bcgov/entity#4427
- in prep for release 2.14.0
=> updated versions to 2.14.0

legal-api/report-templates/template-parts/common/style.html
*Issue #:* /bcgov/entity#4230
- moved business-details-container up a little to remove whitespace
=> fixed whitespace in output header

legal-api/src/legal_api/models/filing.py
*Issue #:* n/a
- added Alteration filing and ALTER pmnt code.
- alphabetized dict based on key filing name
=> adding ALTER payment code

colin-api/src/colin_api/models/filing.py
*Issue #:* /bcgov/entity#4130
Name Translation for IA
=> Name Translation for IA

colin-api/src/colin_api/models/corp_name.py, colin-api/tests/postman/colin-api.postman_collection.json
*Issue #:* /bcgov/entity#4420
Added the code to call a function to get the search name
Updated postman collection
=> Fix  for long corp name in colin

jobs/filings-notebook-report/daily/incorpfilings.ipynb
Signed-off-by: IDIR\schen <steven.chen@gov.bc.ca>
*Issue #:* /bcgov/lear/947-The Total Amount of Incorps to Date
*Description of changes: Added total amount of Incorporation Applications to date and Benefit Corporations to date to report
=> 947-The Total Amount of Incorps to Date

colin-api/Jenkinsfiles/deploy-test.groovy, colin-api/src/colin_api/models/office.py
*Issue #:* /bcgov/entity#4533
- updated office model to handle other office types (skips all except LQ, RC, RG)
- removed e2e prompts from deploy-test pipeline
=> fixed other office types issue and got rid of e2e pipeline for colin-api

colin-api/src/colin_api/models/corp_party.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py, colin-api/src/colin_api/version.py, colin-api/tests/postman/colin-api.postman_collection.json
*Issue #:* /bcgov/entity#4256
- see linked ticket for details
=> 4256 colin bc maintenance filings

colin-api/tests/postman/colin-api.postman_collection.json
*Issue #:* /bcgov/entity#4533
- tweaked pm collection while verifying colin-api for release 2.15
=> tweaked pm collection

colin-api/src/colin_api/models/corp_name.py, colin-api/src/colin_api/models/filing.py
=> Fix for multiple name translations failing in colin

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/version.py, legal-api/tests/unit/api/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#4494
* Added Conditionals and Fee Codes for BCOMP Maintenance Filings
* Updated Unit testing for Fee Codes
*Notes: *
* My exposure to the legal api has been limited, so please be critical and don't hesitate to mention any implications these changes or approach might have throughout. Thanks!
=> Added Bcomp Fee Codes and Tests

legal-api/report-templates/template-parts/bc-annual-report/legalObligations.html, legal-api/requirements/dev.txt, queue_services/entity-filer/requirements/dev.txt, queue_services/entity-filer/src/entity_filer/version.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-pay/requirements/dev.txt, queue_services/entity-pay/src/entity_pay/version.py, queue_services/entity-pay/src/entity_pay/worker.py, queue_services/entity-pay/tests/integration/test_worker_queue.py
*Issue #:* /bcgov/entity#4216
Moved publish to email queue outside IA check
Changed the trigger message to include the actual filing status
=> Email trigger for maintenance filings

queue_services/entity-filer/requirements/bcregistry-libraries.txt, queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/aliases.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/unit/filing_processors/test_aliases.py
*Issue #:* /bcgov/entity#2468
- added nameTranslations to Incorporation and Alteration filings
=> added nameTranslations to Incorporation and Alteration filings

queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_business_profile.py
*Issue #:* /bcgov/entity#4610
- added post_processing to the IA and Alteration
- added business profile update to the post_processing
- added PUT after failed POST if profile exists
=> 4610 added business_profile update to the IA & Alteration in the Filer

queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py, queue_services/entity-emailer/src/entity_emailer/worker.py, queue_services/entity-emailer/tests/unit/__init__.py, queue_services/entity-emailer/tests/unit/test_worker.py
*Issue #:* /bcgov/entity#4580
- fixes for emails being sent when not supposed to
=> skips sending emails to coops and annualReport completed

queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py
- changed naming for pdf attachments on maintenance filings
=> changed naming for pdf attachments on maintenance filings

legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py
*Issue #:* /bcgov/entity#4045
-added validation that names for classes and series must be unique.
=> 4045 added validation that names for classes and series must be unique.

queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py, queue_services/entity-emailer/src/entity_emailer/worker.py
- quick fix to stop sentry spamming
=> emailer ignores coop filings without sentry error

legal-api/src/legal_api/services/filings/validations/change_of_directors.py, legal-api/src/legal_api/utils/legislation_datetime.py, legal-api/tests/unit/services/filings/validations/change_of_director/test_validation_basic.py, legal-api/tests/unit/services/filings/validations/change_of_director/test_validation_effective_date.py
*Issue #:* /bcgov/entity#4311
- removed unused code (effective date is always present, so no need to check filing date)
- compared dates instead of datetimes
- expanded unit tests
=> fixed COD effective date logic

legal-api/src/legal_api/services/document_meta.py, legal-api/tests/unit/services/test_document_meta.py
=> Adding NOA to the list of docs for alteration

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py
*Issue #:* /bcgov/entity#4668
*Description of changes:
- altered incorporation to use the new share structure
=> 4668-altered incorporation to use the new share structure

queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py, queue_services/entity-emailer/src/entity_emailer/email_processors/mras_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-info.html
*Issue #:* /bcgov/entity#4658
- Show Incorporation Number as `Pending` if file_type is incorporationApplication and status is PAID
=> Show Incorporation Number as `Pending` if file_type is incorporationApplication and status is PAID #4658

legal-api/src/legal_api/services/business_details_version.py
*Issue #:* /bcgov/entity#4652
The free filings like director name change and director address change will not have any changes to the party role table. The loading of party relation from party role will result in the outdated record. The party and address version tables are now queried separately based on the composite primary key (id and transaction id)
=> Fix for director name and address change not getting reflected in NOA

legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/share_class.py, queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/bcregistry-libraries.txt, queue_services/entity-filer/requirements/prod.txt, queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/aliases.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/shares.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/__init__.py, queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_shares.py
*Issue #:* /bcgov/entity#4668
- created function to remove keys from dict type objects
- create common shareStructure processor
- change IA to use the new shareStructure processor
- change Alteration to use the new shareStructure processor
=> 4668 filer update ia alteration share structure

queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/BC-ALT-COMPLETED.html, queue_services/entity-emailer/src/entity_emailer/worker.py
*Issue #:* /bcgov/entity#4728
Added a new template for Alteration completed email
Added a condition to prevent email for alteration in PAID status
=> NOA email for alteration

queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
*Issue #:* /bcgov/entity#4662
- corrected URL used to set profile contact info
=> 4662 update profile email

legal-api/report-templates/template-parts/common/shareStructure.html
*Issue #:* /bcgov/entity#4527
- Par Value from share class instead of series
=> Par Value from share class instead of series

colin-api/src/colin_api/version.py, legal-api/src/legal_api/version.py, queue_services/entity-emailer/src/entity_emailer/version.py, queue_services/entity-filer/src/entity_filer/version.py
*Issue #:* /bcgov/entity#4673
- version update
=> updated versions for 2.16 release

jobs/update-colin-filings/run.sh
*Issue #:* /bcgov/entity#4673
colin-updater fix
=> fix colin-updater

jobs/update-colin-filings/k8s/templates/cronjob.json, jobs/update-colin-filings/k8s/templates/job.json
=> fixed templates

jobs/update-colin-filings/update_colin_filings.py
- fix for colin-updater around cods/coas
=> fix for colin-updater

legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/office.py, legal-api/src/legal_api/models/party.py, legal-api/src/legal_api/models/party_role.py, queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/bcregistry-libraries.txt, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/offices.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_offices.py, queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_parties.py
*Issue #:* /bcgov/entity#4518
New processor for parties and offices
Changes in IA to use the new processors ( IA will be used by  new application as well as correction)
=> Filer changes

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/src/legal_api/services/filings/validations/validation.py, legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/services/filings/validations/test_correction_ia.py
=> Validation for NR: Incorporation Application in Correction

Jenkinsfiles/oracle-reset-pipeline.groovy, colin-api/src/colin_api/models/corp_name.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/resources/filing.py, colin-api/tests/postman/colin-api.postman_collection.json, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings/test_internal.py
*Issue #:* /bcgov/entity#4605 and bcgov/entity#4592
- see tickets for check boxes
=> 4605 colin correction name change

queue_services/entity-filer/src/entity_filer/filing_processors/correction.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py, queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_name_request.py, queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
*Issue #:* /bcgov/entity#4601
Created new filing component for name request
Updated the business info filing component by moving some methods from IA processor
Modified the worker to consume the NR for an IA correction only if its a new NR
Added new tests
=> Filer Update - Name Request in correction

queue_services/entity-pay/src/entity_pay/config.py, queue_services/entity-pay/src/entity_pay/worker.py
=> prevent error spam in dev/test

legal-api/src/legal_api/models/address.py
=> Adding ondelete option for office_id foreign key

.github/workflows/data-reset-tool-cd.yml, .github/workflows/data-reset-tool-ci.yml, .github/workflows/entity-pay-cd.yml, .github/workflows/future-effective-filings-cd.yml, .github/workflows/future-effective-filings-ci.yml, .github/workflows/update-colin-filings-cd.yml, .github/workflows/update-colin-filings-ci.yml, .github/workflows/update-legal-filings-cd.yml, .github/workflows/update-legal-filings-ci.yml, data-reset-tool/k8s/templates/data-reset-tool-deploy.json, jobs/future-effective-filings/k8s/templates/cronjob.json, jobs/future-effective-filings/k8s/templates/job.json, jobs/update-colin-filings/k8s/templates/cronjob.json, jobs/update-colin-filings/k8s/templates/job.json, jobs/update-legal-filings/k8s/templates/cronjob.json, jobs/update-legal-filings/k8s/templates/job.json
*Issue #:* https://github.com/bcgov/entity/issues/3261
1. add ci/cd actions to jobs projects.
=> Add github actions to Jobs projects.

data-reset-tool/Dockerfile
=> Update docker file to handle python 3.8.

legal-api/src/legal_api/services/document_meta.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/services/filings/validations/test_correction_ia.py, legal-api/tests/unit/services/test_document_meta.py
*Issue #:* /bcgov/entity#4641
- updated document list for correction ia
=> 4641 updated document list for correction ia

legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/unit/services/filings/validations/test_correction_ia.py
=> 4604 bug fixed

legal-api/Makefile, legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/models/business.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/version.py, legal-api/tests/postman/legal-api.postman_collection.json, legal-api/tests/unit/api/test_business_director.py, legal-api/tests/unit/api/test_business_filings/test_filing_alteration.py, legal-api/tests/unit/api/test_business_filings/test_filing_incorporation.py, legal-api/tests/unit/api/test_business_filings/test_filings.py, legal-api/tests/unit/api/test_business_filings/test_internal.py, legal-api/tests/unit/api/test_business_tasks.py, legal-api/tests/unit/models/__init__.py, legal-api/tests/unit/services/filings/validations/test_incorporation_application.py, legal-api/tests/unit/services/test_document_meta.py
*Issue #:* /bcgov/entity#5006
- legal-api portion for this ticket (breaking it up so that it's smaller PR)
=> 5006 legal type change

legal-api/report-templates/certificateOfIncorporation.html, legal-api/report-templates/template-parts/common/correctedOnCertificate.html, legal-api/src/legal_api/reports/report.py
- Common template part for correction on
- Included in the certificateOfIncorporation in case of correction
=> 4643 common output template for corrected certificates

legal-api/src/legal_api/core/__init__.py, legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/services/filings/validations/incorporation_application.py, legal-api/tests/__init__.py, legal-api/tests/unit/core/__init__.py, legal-api/tests/unit/core/test_filing.py, legal-api/tests/unit/core/test_works.py, legal-api/tests/unit/services/filings/validations/test_correction_ia.py
*Issue #:* /bcgov/entity#4517
- added the correction check for effective dates
- refactored the validation for the corrected IA
- started the core definition for Filings
=> 4517 correction ia completing party

legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#5006
- bug fix
=> set correct legal type for bcomp filings

legal-api/src/legal_api/models/filing.py, legal-api/tests/unit/api/test_business_filings/test_filings.py
=> 4982 new alter fee code

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings/test_filings.py
Change to retrieve the legal type from filing json for IA
Updated the test
=> Fix for IA failing in dev

queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
=> fixed comparison

jobs/filings-notebook-report/daily/incorpfilings.ipynb, jobs/filings-notebook-report/openshift/templates/cron-notebook-report.yml
As request by Kaine, Ezeh Olisa was added to recipients list for daily report and monthly reports
Added Ezeh Olisa to recipients list to daily report and monthly reports
=> Added Ezeh Olisa to recipients list to daily report and monthly reports

legal-api/src/legal_api/services/business_details_version.py
*Issue #:* /bcgov/entity#5162, /bcgov/entity#5163
Added versioned query for offices
Changes to ignore deleted records
=> Bug fixes - NOA

colin-api/src/colin_api/version.py, queue_services/entity-emailer/src/entity_emailer/version.py, queue_services/entity-filer/src/entity_filer/version.py
=> updated versions for release

data-reset-tool/requirements.txt, data-reset-tool/requirements/bcregistry-libraries.txt, data-reset-tool/src/data_reset_tool/version.py
=> fixed for release

legal-api/report-templates/incorporationApplication.html, legal-api/report-templates/template-parts/common/correctedOnCertificate.html, legal-api/report-templates/template-parts/common/style.html, legal-api/report-templates/template-parts/incorporation-application/businessDetails.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#4639, /bcgov/entity#5088, /bcgov/entity#4643
Changes to support the IA of a correction (Everything other than the corrected chip label against corrected entries)
Removed the unused NOA code from IA template ( NOA uses its own template)
Changed the description of CP entity type in report.py
Fixed the incorrect date shown in the corrected certificate.
=> Changes to support correction for IA + Bug fix in certificate corrected date

queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/aliases.py, queue_services/entity-filer/tests/unit/filing_processors/test_aliases.py
=> 5236 fix for modified name translation in correction/alteration

legal-api/report-templates/template-parts/notice-of-articles/benefitCompanyStmt.html, legal-api/report-templates/template-parts/notice-of-articles/directors.html, legal-api/src/legal_api/services/business_details_version.py
*Issue #:* /bcgov/entity#5197, /bcgov/entity#5198
- fixed json to match schema
=> match structure of json and core json

legal-api/report-templates/template-parts/common/correctedOnCertificate.html, legal-api/src/legal_api/reports/report.py
*Issue #:* /bcgov/entity#4640
Changes to include the new registrar details below the 'Corrected on' block if the registrar at the time of correction is different from the registrar at the time of incorporation  
=> Corrected Certificate of Incorporation - Updates

legal-api/migrations/versions/738437025c05_add_payment_account.py, legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/models/filing.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/version.py, legal-api/tests/unit/api/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#5240a
- added paymentAccount for the account identifier of the payer.
=> added account identifier of payer.

.github/workflows/entity-emailer-ci.yml, .github/workflows/entity-filer-ci.yml, .github/workflows/entity-pay-ci.yml, .github/workflows/legal-api-ci.yml, .gitignore, codecov.yaml, legal-api/README.md, legal-api/requirements/dev.txt, legal-api/setup.cfg, queue_services/entity-emailer/README.md, queue_services/entity-emailer/requirements/dev.txt, queue_services/entity-emailer/setup.cfg, queue_services/entity-filer/README.md, queue_services/entity-filer/requirements/dev.txt, queue_services/entity-filer/setup.cfg, queue_services/entity-pay/README.md, queue_services/entity-pay/requirements/dev.txt, queue_services/entity-pay/setup.cfg
*Issue #:* https://github.com/bcgov/entity/issues/5241
1. Add codecov configuration yaml file;
2. Add pytest-cov library and "--cov" parameter into ptest command;
3. Add upload coverage report action into CI;
4. Add codecov badge in Readme;
Queue jobs codecov support will finish by this ticket https://github.com/bcgov/entity/issues/5293 
=> Added codecov support to legal API.

legal-api/src/legal_api/services/business_details_version.py
*Issue #:* /bcgov/entity#5355
- revise date format in header
=> Correct time does not appear for Detail after filing a correction

legal-api/.vscode/launch.json, legal-api/.vscode/settings.json, legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings/test_filings.py
*Issue #:* n/a
- fixed some filing tests
- carried through changes in storage
=> fixed filing tests

legal-api/src/legal_api/models/filing.py, queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/bcregistry-libraries.txt, queue_services/entity-filer/src/entity_filer/filing_processors/transition.py, queue_services/entity-filer/src/entity_filer/worker.py, queue_services/entity-filer/tests/unit/filing_processors/test_transition.py, queue_services/entity-filer/tests/unit/test_worker/test_transition.py
*Issue #:* /bcgov/entity#5240
Added a new processor for transition filing
Added tests
=> Filer - Transition filing

colin-api/src/colin_api/models/corp_name.py, colin-api/src/colin_api/models/corp_party.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/models/office.py, colin-api/src/colin_api/models/reset.py, colin-api/src/colin_api/models/shares.py, colin-api/src/colin_api/resources/parties.py, colin-api/src/colin_api/resources/share_struct.py, colin-api/src/colin_api/version.py, colin-api/tests/postman/colin-api.postman_collection.json, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/tests/unit/api/test_business_filings/test_internal.py, legal-api/tests/unit/models/__init__.py
*Issue #:* /bcgov/entity#5195
- see postman collection for correction tests (gives examples of what I've pictured for what will be coming based on schema)
- all tests pass over test (first call is reset on 3 CPs -- this is needed for tests to pass), all important bcomp tests must be run in order from the Incorporation folder (they set the env vars for the other ones) 
- cognitive complexity code smells to be addressed in future refactoring 
=> finally finished corrections :P

Jenkinsfiles/oracle-reset-pipeline.groovy
*Issue #:* /bcgov/entity#5309
- fixes reset pipeline for oracle pod
=> reset pipeline update

colin-api/src/colin_api/models/filing.py
*Issue #:* /bcgov/entity#5309
- fixed issue with ben ARs
=> fixed ben AR bug

colin-api/Dockerfile
*Issue #:* n/a
- updated base image
- added sqlplus
=> updated base image, added sqlplus

legal-api/src/legal_api/resources/business/business_filings.py
- temperory fix: skip versioning when there is no filing id
=> skip versioning when there is no filing id

queue_services/entity-filer/src/entity_filer/version.py
*Issue #:* /bcgov/entity#5408
- updated filer version to match release
=> version update for release

queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py, queue_services/entity-emailer/src/entity_emailer/email_templates/BC-CRCTN-IA-COMPLETED.html, queue_services/entity-emailer/src/entity_emailer/email_templates/BC-CRCTN-IA-PAID.html, queue_services/entity-emailer/tests/unit/__init__.py, queue_services/entity-emailer/tests/unit/email_processors/test_filing_notification.py
*Issue #:* /bcgov/entity#4606, /bcgov/entity#4607
Added new templates for IA correction (completed and paid)
Updated the processor to handle only the corrections for IA
Added tests
=> Notification - Correction

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/services/document_meta.py, legal-api/tests/unit/services/test_document_meta.py
*Issue #:* /bcgov/entity#5186
- Updated document list for transition application
PS: Validator is not included since discussion is pending
=> 5186 Updated document list for transition application

legal-api/src/legal_api/services/business_details_version.py
- setting completing party email from filing json
=> setting completing party email from filing json

legal-api/src/legal_api/services/business_details_version.py
=> Fix party version

data-reset-tool/src/data_reset_tool/blueprints/fixture.py
*Issue #:* /bcgov/entity#4936
- Fixed rewriting csv file by making into a single query
=> single query instead of multiple - party address

legal-api/tests/postman/legal-api.postman_collection.json
*Issue #:* /bcgov/entity#5186
Added postman tests for transition filing.
Note: I used the waiveFee option in the header so that we dont have to make the payment to complete the filing
=> Postman tests for transition application

legal-api/src/legal_api/services/filings/validations/incorporation_application.py
=> 5450 query new nr

queue_services/entity-emailer/src/entity_emailer/email_templates/BC-CRCTN-IA-PAID.html
Wording change in correction template
=> Wording change in the template

.github/workflows/colin-api-cd.yml, .github/workflows/data-reset-tool-cd.yml, .github/workflows/entity-emailer-cd.yml, .github/workflows/entity-filer-cd.yml, .github/workflows/entity-pay-cd.yml, .github/workflows/future-effective-filings-cd.yml, .github/workflows/legal-api-cd.yml, .github/workflows/update-colin-filings-cd.yml, .github/workflows/update-legal-filings-cd.yml, scripts/1pass.sh
*Issue #:* /bcgov/entity#5626
Update for deprecating set-env command of GHA.
=> Update for set environment variables issue of GHA.

legal-api/src/legal_api/core/utils.py
*Issue #:* n/a
- fixed issue as uncovered by Vysakh
Thanks!!
=> added missing call to diff_list in the recursive diff_dict call.

jobs/filings-notebook-report/notebookreport.py, jobs/filings-notebook-report/openshift/templates/cron-notebook-report.yml, jobs/filings-notebook-report/requirements/prod.txt
*Issue #:* /bcgov/entity/issues/5361
Updated legal type for Benefit Company from BC to BEN as database updated.
=> 5361 - Jupyter Notebook Report Legal Type Changed to BEN from BC

legal-api/src/legal_api/core/utils.py, legal-api/tests/unit/core/test_utils.py
*Issue #:* n/a
- fixed where deleted rows are missed
=> fix where deleted rows are missed.

colin-api/src/colin_api/models/filing.py
=> 5238 refactored add_filing to make it more generic

legal-api/src/legal_api/core/filing.py, legal-api/src/legal_api/core/utils.py, legal-api/tests/unit/core/test_filing_diff.py, legal-api/tests/unit/core/test_utils.py
*Issue #:* /bcgov/entity#5711
- changed diff to add item if list dict does not have an "id" key
=> changed diff on lists to add lists if the change lists do not have ids.

queue_services/entity-filer/requirements.txt, queue_services/entity-filer/requirements/bcregistry-libraries.txt, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/aliases.py, queue_services/entity-filer/tests/unit/filing_processors/test_aliases.py, queue_services/entity-filer/tests/unit/filing_processors/test_alteration.py, queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py, queue_services/entity-filer/tests/unit/filing_processors/test_transition.py, queue_services/entity-filer/tests/unit/test_worker/test_transition.py
*Issue #:* /bcgov/entity#5704
Updated the alias processor
Fixed the tests
=> Filer updates for name translation changes

legal-api/report-templates/template-parts/incorporation-application/benefitCompanyStmt.html, legal-api/report-templates/template-parts/notice-of-articles/benefitCompanyStmt.html, legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/src/legal_api/models/alias.py, legal-api/src/legal_api/reports/report.py, legal-api/src/legal_api/services/business_details_version.py, legal-api/tests/unit/api/test_business_aliases.py, legal-api/tests/unit/models/test_alias.py
*Issue #:* /bcgov/entity#5717
Updated Versioned service
Updated incorporation application reports template. Corrections template will need additional work
Updated the keyname from alias to name in name translations to be in sync with schema
Updated tests
=> Legal API changes - Name Translations

colin-api/setup.cfg, colin-api/src/colin_api/exceptions/__init__.py, colin-api/src/colin_api/models/business.py, colin-api/src/colin_api/models/corp_name.py, colin-api/src/colin_api/models/corp_party.py, colin-api/src/colin_api/models/filing.py, colin-api/src/colin_api/models/office.py, colin-api/src/colin_api/models/shares.py, colin-api/src/colin_api/resources/business.py, colin-api/src/colin_api/resources/filing.py, colin-api/src/colin_api/utils/__init__.py, colin-api/src/colin_api/version.py, colin-api/tests/postman/colin-api.postman_collection.json
=> 5238 colin api transition

legal-api/src/legal_api/models/filing.py, legal-api/tests/unit/api/test_business_filings/test_filings.py
*Issue #:* /bcgov/entity#5525
Updated fee codes for transition filing
Updated tests
=> Fee code for transition application

legal-api/tests/unit/reports/test_report.py, legal-api/tests/unit/services/filings/validations/test_change_of_name.py, legal-api/tests/unit/services/filings/validations/test_special_resolution.py, legal-api/tests/unit/services/filings/validations/test_voluntary_dissolution.py
*Issue #:* /bcgov/entity#5607
- ran out of time to add full coverage to these, but improved it as much as I could within the timebox
=> added test coverage

colin-api/src/colin_api/models/filing.py
=> Fix in comparison

colin-api/src/colin_api/models/filing.py, colin-api/tests/postman/colin-api.postman_collection.json
=> Fix in translation processing in correction

.github/workflows/filings-notebook-report-cd.yml, .github/workflows/filings-notebook-report-ci.yml, jobs/filings-notebook-report/Dockerfile, jobs/filings-notebook-report/README.md, jobs/filings-notebook-report/notebookreport.py, jobs/filings-notebook-report/openshift/templates/cron-notebook-report.yml, jobs/filings-notebook-report/requirements/prod.txt, jobs/filings-notebook-report/setup.cfg
*Description of changes: 
Added github Workflow for Filings Notebook Report
=> Add github Workflow for Filings Notebook Report (#1018)

jobs/filings-notebook-report/requirements.txt
*Issue #:* /bcgov/entity 1018
Put libraries in requirements.txt
=> 1068 - Add github Workflow for Filings Notebook Report

jobs/filings-notebook-report/notebookreport.py
*Issue #:* /bcgov/entity#1068-Add github Workflow for Filings Notebook Report 
Use /tmp/ to store temp file 
=> 1068-Add github Workflow for Filings Notebook Report 

queue_services/common/requirements.txt
remove version constraint from attrs
=> remove versioning from attrs

legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/resources/business/business_tasks.py, legal-api/tests/unit/api/test_business_tasks.py
*Issue #:* /bcgov/entity#5619
- changes FE is expecting for online banking
- wasn't able to test create invoice return before leaving (my idir creds are not working for paying in dev)
- this is the 1 line in business_filings
=> changes needed for FE for online banking

jobs/filings-notebook-report/Dockerfile, jobs/filings-notebook-report/Makefile, jobs/filings-notebook-report/daily/incorpfilings.ipynb, jobs/filings-notebook-report/monthly/cooperative.ipynb, jobs/filings-notebook-report/monthly/coopfilings.ipynb, jobs/filings-notebook-report/notebookreport.py, jobs/filings-notebook-report/openshift/templates/cron-notebook-report.yml, jobs/filings-notebook-report/requirements/prod.txt
*Issue #:* /bcgov/lear/issues/1091
Added 'Cameron Wulff' as required by Kaine Sparks
Fixed bug from test_job.py
Added /opt/app-root/data/ for temp files when program runs on docker
=> Incorporation Filing Daily Stats Notebook Report Update #1091

legal-api/setup.cfg, legal-api/src/legal_api/resources/business/business_filings.py, legal-api/src/legal_api/resources/business/business_tasks.py
*Issue #:* /bcgov/entity#5619
- updates based on what FE was expecting and bugs
=> 5619 online banking payment

legal-api/src/legal_api/resources/business/business_filings.py
*Issue #:* /bcgov/entity#5619
- added pay details to temp reg filings response
=> quick fix for temp reg payment details

colin-api/setup.cfg, colin-api/src/colin_api/models/filing.py
=> added paper only for coop incorps

legal-api/src/legal_api/version.py
*Issue #:* /bcgov/entity#5567
- changed version to 2.19.0 to match release
=> version update

queue_services/entity-filer/requirements.txt, queue_services/entity-filer/setup.cfg, queue_services/entity-filer/src/entity_filer/version.py
*Issue #:* /bcgov/entity#5870
- changed dpath req back (last req change broke the code)
=> fix for alterations in filer

queue_services/entity-filer/requirements/prod.txt
*Issue #:* /bcgov/entity#5870
- missed this in last PR
=> updated prod.txt

legal-api/src/legal_api/services/filings/validations/annual_report.py
=> 6308 max_date cannot be greater than todays date and min_date for BCOMP is next anniversary date

legal-api/src/legal_api/resources/business/__init__.py, legal-api/src/legal_api/resources/business/business_comments.py, legal-api/src/legal_api/services/comments/validations/comment.py, legal-api/src/legal_api/services/comments/validations/validation.py, legal-api/src/legal_api/version.py, legal-api/tests/unit/api/test_business_comments.py, legal-api/tests/unit/models/__init__.py, queue_services/entity-filer/src/entity_filer/version.py
=> 6256 Update staff comments

legal-api/requirements.txt, legal-api/requirements/bcregistry-libraries.txt, legal-api/tests/unit/api/test_business_comments.py
=> 6256 update business schema

legal-api/src/legal_api/services/namex.py, legal-api/tests/unit/api/test_name_requests.py
=> Date format change

queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py, queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py, queue_services/entity-filer/src/entity_filer/worker.py
=> 5109 consume NR for alteration

queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py, queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_business_profile.py
*Issue #:* /bcgov/entity#5365
*Description of changes:* add the contact phone number (already passed) to business profile
=> 5365 filer phone to bus profile

legal-api/src/legal_api/services/bootstrap.py, legal-api/tests/unit/services/test_registraion_bootstrap_service.py, queue_services/entity-filer/src/entity_filer/worker.py
*Issue #:* /bcgov/entity#5109
- I will be creating separate ticket to consume this function in entity-filer
=> 5109 update affiliated entity data

queue_services/entity-filer/src/entity_filer/worker.py
=> 5109 update legal name and type in entity
