legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#19691
Bumped version numbers up for release 20.2b

bump version numbers up for release 20.2b

---

legal-api/pyproject.toml
legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/reports/report.py
python/common/business-registry-model/src/business_model/models/alternate_name.py

* Updates to legal api to get it running

Update legal api to get it running

---

legal-api/migrations/versions/004f7558063f_second.py

*Issue #:* /bcgov/entity#19425
- Add `email`, `mailing_address_id`, `delivery_address_id` to `alternate_names` and `alternate_names_history` tables
- Add foreign keys for `alternate_names` and `alternate_names_history` tables
- Add `alternate_name_id` to `offices` and `offices_history` tables
- Add foreign key for `offices` and `offices_history` tables
- Add indexes for `offices` and `offices_history` tables
- Update `downgrade()`

19425 Add address fields to alternate name table db scripts

---

colin-api/requirements.txt

*Issue #:* /bcgov/entity#19405

19405 Add missed dependency

---

queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_application.py
queue_services/entity-filer/tests/unit/__init__.py
queue_services/entity-filer/tests/unit/test_worker/test_amalgamation_application.py

*Issue #:* /bcgov/entity#19649

19649 filer - short form amalgamation

---

queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_application.py
queue_services/entity-filer/tests/unit/test_worker/test_amalgamation_application.py

*Issue #:* /bcgov/entity#19649

19649 inherit legal name from primary or holding business

---

legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/services/bootstrap.py
legal-api/tests/unit/services/test_registraion_bootstrap_service.py

*Issue #:* /bcgov/entity#19058

19058 initial draft creation fix

---

legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/models/business_common.py
legal-api/src/legal_api/models/colin_entity.py
legal-api/src/legal_api/models/legal_entity.py
legal-api/tests/unit/models/test_legal_entity.py

*Issue #:* /bcgov/entity#19197
- update `legal_name` and `business_name` for `LegalEntity` and `AlternateName`
- update unit tests
- other small fixes

19197 Update legal_name and business_name properties

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#19787
bump up version for release 20.3a

19787 - bump up version for release 20.3a

---

legal-api/migrations/versions/004f7558063f_second.py
legal-api/src/legal_api/models/address.py
legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/models/office.py

*Issue #:* /bcgov/entity#19665
- Add `mailing_address_id`, `delivery_address_id` and `email` to alternate name model
- Add office address properties to alternate names model.
- Add `alternate_name_id` to offices model
-  Update alembic script to add alternate_name_id to addresses table and add FKs and indexes as appropriate
-  Add alternate_id to addresses model and add relationships as appropriate

19665 - update alternate name model

---

legal-api/report-templates/amalgamationApplication.html
legal-api/report-templates/certificateOfAmalgamation.html
legal-api/report-templates/template-parts/amalgamation/amalgamatingCorp.html
legal-api/report-templates/template-parts/amalgamation/approvalType.html

*Issue #:* /bcgov/entity#19521

19521 added output bugs fixes

---

legal-api/migrations/versions/004f7558063f_second.py
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/models/business_common.py
legal-api/src/legal_api/models/colin_entity.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/models/legal_entity.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/business_service.py
legal-api/src/legal_api/services/warnings/business/business_checks/business.py
legal-api/src/legal_api/services/warnings/business/business_checks/firms.py

*Issue #:* /bcgov/entity#19351
Notes: 
* linting will be fixed in subsequent PR
* POST /business and /search endpoints will be updated in another ticket
* Additional updates to GET business endpoint to work with alternate_names.  Follow up from [initial PR](https://github.com/bcgov/lear/pull/2446)
* Update alternate names model's `json` function to include other req'd fields
* Updates to `business_service` to make it cleaner
* Moved more properties and functions common to `AlternateNames` and `LegalEntities` into `BusinessCommon`
* Update allowable actions to support alternate names
* Update warnings service to support alternate names
* Minimal updates to filings model functions to support alternate_names.  @leodube-aot just a heads up I might have crossed over …

19351 update business endpoint to work with alternate_names

---

queue_services/entity-emailer/src/entity_emailer/email_templates/AMALGA-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/AMALGA-PAID.html

*Issue #:* /bcgov/entity#19702
Changed "Amalgamation Certificate" -> "Certificate of Amalgamation"

Fixed email content

---

legal-api/src/legal_api/resources/v2/business/business.py

*Issue #:* /bcgov/entity#19107
- Simple fix to make ATMP draft types have a similar legalName as TMP draft type filings. 

19107 changed draft legal name for ATMP draft types

---

legal-api/report-templates/template-parts/business-summary/amalgamating.html
legal-api/report-templates/template-parts/business-summary/amalgamations.html

*Issue #:* /bcgov/entity#19088
Updated the title for TING and TED companies.

19088-business-summary-updates

---

legal-api/report-templates/template-parts/business-summary/amalgamating.html
legal-api/report-templates/template-parts/business-summary/amalgamations.html

*Issue #:* /bcgov/entity#19088
Changes done per UX review

19088-updated-summary-outputs

---

legal-api/report-templates/amalgamationApplication.html
legal-api/report-templates/certificateOfAmalgamation.html
legal-api/report-templates/noticeOfArticles.html
legal-api/report-templates/template-parts/amalgamation/amalgamatingCorp.html
legal-api/report-templates/template-parts/amalgamation/amalgamationName.html
legal-api/report-templates/template-parts/amalgamation/effectiveDate.html
legal-api/report-templates/template-parts/common/certificateStyle.html
legal-api/report-templates/template-parts/incorporation-application/nameRequest.html
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/services/filings/validations/test_registration.py

*Issue #:* /bcgov/entity#19713

19713 short form amalgamation outputs

---

legal-api/poetry.lock
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/models/business_common.py
legal-api/src/legal_api/models/legal_entity.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/src/legal_api/services/business_details_version.py
legal-api/src/legal_api/services/business_service.py

*Issue #:* /bcgov/entity#19352
- Updated /filings related endpoints such that correct business info retrieved for SPs via alternate names.
[See spreadsheet](https://docs.google.com/spreadsheets/d/1AXKilTudj-Y1reWtY2NNHOPXsIYYgcNwoScprUnNhmU/edit?usp=drive_link)

19352 Update filings endpoints to work with alternate name

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#19781
Changed amalgamation ledger title

19781-amalgamation-ledger-title-update

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#19880

19880 - bump version for 20.3b release

---

legal-api/report-templates/certificateOfAmalgamation.html

*Issue #:* /bcgov/entity#19885
Changed the format of the date in the certificate of amalgamation

19885-incorrect-amalgamation-date-format

---

legal-api/src/legal_api/services/filings/validations/amalgamation_application.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/consent_continuation_out.py
legal-api/src/legal_api/services/filings/validations/continuation_out.py
legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py

*Issue #:* /bcgov/entity#19746

19746 additional validations in amalgamation filing

---

legal-api/src/legal_api/models/business_common.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/filings/validations/amalgamation_application.py

*Issue #:* /bcgov/entity#19387

fix import model issue

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#20034

20034 bump up version 2.106.0

---

legal-api/src/legal_api/models/amalgamating_business.py
legal-api/tests/unit/models/test_amalgamating_business.py
queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_application.py

*Issue #:* /bcgov/entity#19934
Catch up all previously `foreign_corp_num` so the legal api can running

19934 - catch all foreign_corp_num to foreign_identifier

---

legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/resources/v2/business/business_parties.py

*Issue #:* /bcgov/entity#19387
- FM1028594 - SP Individual
- FM1054864 - SP LEAR DBA
- FM1061225 - SP COLIN DBA

19387 update getting SP entity role

---

legal-api/src/legal_api/resources/v2/business/business_tasks.py

* Fixed issue where task endpoint was failing for SPs

Fix task endpoint bug

---

legal-api/src/legal_api/models/alternate_name.py

Fix address endpoint bug

---

legal-api/src/legal_api/models/document.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/resources/v2/business/business_documents.py
legal-api/src/legal_api/resources/v2/business/business_tasks.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/filings/validations/restoration.py
legal-api/tests/unit/models/test_filing.py

*Issue #:* /bcgov/entity#19931

19931 update missed model class alt_name

---

legal-api/src/legal_api/models/filing.py

*Issue #:* /bcgov/entity#19941

19941 - fix sql warning

---

legal-api/migrations/versions/004f7558063f_second.py
legal-api/src/legal_api/models/alternate_name.py

*Issue #:* /bcgov/entity#20115

20115 update alt_names table to support name translation

---

legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/business_details_version.py

*Issue #:* /bcgov/entity#20177

20177 amalgamation application output - get versioned data

---

legal-api/src/legal_api/config.py

*Issue #:* /bcgov/entity#20146
- Update payment URL

20146 - Fix 402 error for submitting filings

---

legal-api/src/legal_api/models/alternate_name.py

*Issue #:* /bcgov/entity#20208
`{{url}}/api/v2/businesses/FM1061225`

20208 fix business endpoint colin sp legal_name and state response

---

legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/models/business_common.py

*Issue #:* /bcgov/entity#20129
- FM1054864 - SP LEAR DBA
- FM1018902 - GP

update alt_name name_type

---

legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#20255

20255 bump up version 2.107.0

---

legal-api/src/legal_api/services/namex.py

*Issue #:* /bcgov/entity#20263
Small fix that might possible fix the 404 not found error on the nameRequests endpoint

20263 - Small fix to the requests endpoint

---

colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/filing.py

*Issue #:* /bcgov/entity#19895

19895 sync admin dissolution in colin-api

---

legal-api/src/legal_api/models/alternate_name.py
legal-api/src/legal_api/services/warnings/business/business_checks/firms.py

* Fix firm start date missing not being picked up in warnings check
* Fix wrong start date being returned in business response

Fix firm start date issues

---

legal-api/migrations/versions/5238dd8fb805_.py
legal-api/src/legal_api/models/amalgamating_business.py
legal-api/src/legal_api/models/amalgamation.py
legal-api/tests/unit/models/test_amalgamating_business.py
legal-api/tests/unit/models/test_amalgamation.py

*Issue #:* /bcgov/entity#20211
- add `amalgamating_businesses_version` and `amalgamations_version` tables

20211 - alembic script + model updates for amalgamation table additions & changes

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

*Issue #:* /bcgov/entity#20276
- Fixed change of registration error

fixed change of registration

---

queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py
queue_services/entity-filer/tests/unit/test_worker/test_amalgamation_application.py

*Issue #:* /bcgov/entity#20179

20179 admin dissolution - delete amalgamations and amalgamating_businesses data

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

*Issue #:* /bcgov/entity#20276
- Fixed the doing a PUT request for the change of registration.
- This should also hopefully fix all PUT requests for filings done for entries in the Alternate Names.

20276 Fixed change of registration PUT request

---

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql

*Issue #:* /bcgov/entity#20117

20117 Update migration scripts to store aliases in alternate names table

---

legal-api/report-templates/template-parts/alteration-notice/statement.html
legal-api/report-templates/template-parts/common/statement.html

*Issue #:* /bcgov/entity#16130
Removed the extra comma from statement

16130-removed-extra-comma

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#20372
Bumped version numbers up for entities release 20.5b

bump version numbers up for release 20.5b

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/services/filings/validations/annual_report/test_validate_ar_year.py

*Issue #:* /bcgov/entity#20378

20378 fix the ar min date calculation for leap year (feb 29th)

---

legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql

*Issue #:* /bcgov/entity#20212
- change `amalgamations_version` to `amalgamations_history` table as below
- change `amalgamating_businesses_version` to `amalgamating_businesses_history` table as below

20212 - amalgamation table change

---

docs/oas/business.yaml

*Issue #:* n/a
Initial OAS3, OpenApi specification

oas3 for business

---

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
legal-api/src/legal_api/models/legal_entity.py

* Reverted commented out amalgamations code now that latest db changes have been applied to GCP dev/test LEAR dbs
* Fixed incorrect alternate name table associations for non-SP businesses
* Misc space formatting

Reverted commented code for amalgamations and fixed incorrect alternate name table associations for non-SP businesses in data script

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/consent_continuation_out.py
queue_services/entity-filer/tests/unit/test_worker/test_consent_continuation_out.py

*Issue #:* /bcgov/entity#19392

19392 cco field details removed

---

queue_services/entity-filer/poetry.lock

*Issue #:* /bcgov/entity#19807
- Possible fix for the filer GCP CD

19807 Fixed Filer GCP CD

---

jobs/email-reminder/devops/gcp/clouddeploy-targets.yaml
jobs/future-effective-filings/devops/gcp/clouddeploy-targets.yaml
jobs/update-colin-filings/devops/gcp/clouddeploy-targets.yaml
jobs/update-legal-filings/devops/gcp/clouddeploy-targets.yaml
queue_services/entity-auth/devops/gcp/clouddeploy-targets.yaml
queue_services/entity-bn/devops/gcp/clouddeploy-targets.yaml
queue_services/entity-emailer/devops/gcp/clouddeploy-targets.yaml
queue_services/entity-filer/devops/gcp/clouddeploy-targets.yaml
queue_services/entity-pay/devops/gcp/clouddeploy-targets.yaml

Added service account parameter to deployment.

---

queue_services/entity-filer/src/entity_filer/config.py

*Issue #:* /bcgov/entity#19807

19807 small addition to filer config

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#20352

20352 update allowable actions for TING

---

queue_services/entity-filer/src/entity_filer/services/gcp_queue.py

*Issue #:* /bcgov/entity#19807
Fixed the GCP queue not establishing connection properly:

19807 possible fix for the CCP queue

---

queue_services/entity-filer/poetry.lock
queue_services/entity-filer/src/entity_filer/filing_processors/registration.py

*Issue #:* /bcgov/entity#20327
- Fix bugs that causes unit tests failed in previous PR #2543 

20327 - Fix failed unit tests

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/admin_freeze.py
queue_services/entity-filer/tests/unit/filing_processors/test_admin_freeze.py

*Issue #:* /bcgov/entity#20195

20195 remove details from admin freeze

---

.github/workflows/business-oas-ci.yml
docs/oas/business.yaml

Added Business OAS CI flow.

---

docs/business.yaml

*Issue #:* n/a
Adding OAS to the docs folder on the mainline.

adding OAS on the mainline

---

legal-api/requirements.txt
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

*Issue #:* /bcgov/entity#19918

19918 futureEffective property in payment call for amalgamation

---

legal-api/src/legal_api/resources/v2/business/business.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#19930
Added a condition to have a placeholder for empty 

Added placeholder for Amalgamating Business application

---

queue_services/entity-pay/__init__.py
queue_services/entity-pay/src/entity_pay/services/gcp_queue.py

*Issue #:* /bcgov/entity#19808
Small fix to gcp queue of entity pay

19808 Small fix to gcp queue of entity pay

---

queue_services/entity-filer/poetry.lock

*Issue #:* /bcgov/entity#20327

20327 - Update poetry dependency so that filer can refer to latest data models

---

docs/oas/business.yaml

*Issue #:* /bcgov/entity#20150
* Add `alternateNames` field to business schema
* Add `alternateNames` to business response example

20150 Update API spec to include alternateNames in business response

---

docs/oas/business.yaml

*Issue #:* /bcgov/entity#20150
* Fixed syntax errors
* Fixed field name typo

20150 Fixed syntax errors and field name typo for alternateNames in business response

---

docs/business.yaml

*Issue #:* /bcgov/entity#20150

20150 cherry pick legal name spec updates

---

legal-api/src/legal_api/resources/v2/business/business.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#19930
Updated the fallback to Numbered XXX Company for both draft filings where numbered option is selected or no option is chosen. 

Updated test cases, added comments for extra clarity.

---

jobs/email-reminder/services/gcp_queue.py
jobs/future-effective-filings/services/gcp_queue.py
jobs/update-legal-filings/services/gcp_queue.py
python/common/gcp-queue/gcp_queue/gcp_queue.py
queue_services/entity-auth/src/entity_auth/services/gcp_queue.py
queue_services/entity-bn/src/entity_bn/services/gcp_queue.py
queue_services/entity-emailer/src/entity_emailer/services/gcp_queue.py
queue_services/entity-filer/src/entity_filer/services/gcp_queue.py
queue_services/entity-pay/src/entity_pay/services/gcp_queue.py

*Issue #:* /bcgov/entity#19808
I can't believe I wasted almost 2 days on this 😁 
I fixed this for all the other queues as well since we might forget to do that later.
After this PR is merged, I'm going to proxy and test in GCP Dev.

19808 Fixed publishing to queue

---

legal-api/scripts/manual_db_scripts/legal_name_change/legal_name_updates.sql
legal-api/scripts/manual_db_scripts/legal_name_change/transfer_to_new_lear.sql
legal-api/scripts/orphaned_data_cleanup.sql

*Issue #:* /bcgov/entity19935
- Updated the generation of alternate names so it does not take into account whether there is a legal name change. 
- additional indexing on temp tables to resolve performance issues for PROD extract once we started loading in additional records by excluding name change check
- additional entity_type checks when updating legal_entities fix (causing data to be updated that shouldn't be)
- added edge case updates and clean up for SPs

19935 - migration script - alternate name updates

---

legal-api/report-templates/incorporationApplication.html
legal-api/report-templates/template-parts/incorporation-application/benefitCompanyStmt.html
legal-api/report-templates/template-parts/incorporation-application/nameRequest.html
legal-api/src/legal_api/models/entity_role.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/business_details_version.py

*Issue #:* /bcgov/entity#20363
IA for BEN
IA for CP
Alternation without name translation
Alternation with name translation

20363 - update IA and Alternation

---

python/common/business-registry-model/src/business_model/models/address.py

*Issue #:* /bcgov/entity#20328
- Sync common address data model with the latest one in legal-api

20328 Sync common address data model

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#20855

bump version numbers up for release 21.1a

---

queue_services/entity-emailer/devops/vaults.json
queue_services/entity-emailer/src/entity_emailer/config.py
queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py
queue_services/entity-emailer/src/entity_emailer/email_processors/amalgamation_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/registration_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_amalgamation_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_filing_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_registration_notification.py
queue_services/entity-emailer/tests/unit/test_worker.py

*Issue #:* /bcgov/entity#20608

20608 my business registry url for temp identifier (IA, Registration, Amalgamation)

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#20576

20576 no output when requesting with temp identifier and filing is in completed state

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/continuation_out.py
queue_services/entity-filer/tests/unit/filing_processors/test_continuation_out.py

*Issue #:* /bcgov/entity#29533
Removed detail for continuation out

20533-removed-detail-for-cont-out

---

docs/business.yaml

*Issue #:* /bcgov/entity#20942

20942 update alt_name definition api spec

---

queue_services/entity-bn/src/entity_bn/bn_processors/change_of_registration.py
queue_services/entity-bn/src/entity_bn/bn_processors/registration.py

*Issue #:* /bcgov/entity#20775

20775 - lower function aligned

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/test_business.py

*Issue #:* /bcgov/entity#20778
- Updated `json` function in business model to return `alternateNames` list when enable-legal-name-fix feature flag is on. 
- Get business endpoint returns `alternateNames`
- Added unit tests to verify alternate names are being returned correctly
**Businesses tested**
```
Using: GET <api_base_url>/api/v2/businesses/<identifier>
// COOP
"CP1002603",
"alternateNames": [ ]
// BEN - no DBAs, with translation
"BC0871269"
"alternateNames": [
{
"name": "IUIOUI",
"startDate": "2020-12-05",
"type": "TRANSLATION"
}
]
// BEN - multiple DBAs, with translation
"BC1230010"
"alternateNames": [
{
"name": "LOREM IPSUM",
"startDate": "2020-10-28",
"type": "TRANSLATION"
},
{
"entityType": "SP",
"identifier": "FM1032630",
"name": "FIX", …
```

20778 Update business get response to return alternate names list

---

docs/business.yaml

*Issue #:* /bcgov/entity#20993

20993 Structural errors in schema in the Legal API spec

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/agm_extension.py

*Issue #:* /bcgov/entity#20437
Removed intendedAgmDate from schema.
Updated Filer
No test updates necessary

Removed intendedAgmDate

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/test_business.py

*Issue #:* /bcgov/entity#20996 
Added alternateNames to slim json

20996 Added alternateNames to slim json

---

jobs/involuntary-dissolutions/flags.json
jobs/involuntary-dissolutions/involuntary_dissolutions.py

*Issue #:* /bcgov/entity#20992
- Add logic to run code when `enable-involuntary-dissolution` FF is on 

20992 - Create skeleton involuntary dissolutions job (Part2)

---

legal-api/report-templates/certificateOfNameChange.html
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#19926

19926 certificateOfNameCorrection

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#21141
bumped up version numbers for release 21.2a

bumped up version numbers for release 21.2a

---

legal-api/migrations/versions/8bd6dc383c96_add_no_dissolution_to_businesses.py
legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/models/test_business.py
legal-api/tests/unit/resources/v1/test_business.py
legal-api/tests/unit/resources/v2/test_business.py
legal-api/tests/unit/services/warnings/__init__.py

*Issue #:* /bcgov/entity#21089
- Create alembic script to add `no_dissolution` to `businesses` and `businesses_version` tables
- Add new column to data model
- Add new property to business json
- Fix unit tests that failed due to updates
*After applying new script to local db*
`businesses` table
`businesses_version` table

21089 - Legal API - Alembic script and model update to exclude businesses from dissolution

---

legal-api/src/legal_api/models/business.py

*Issue #:* /bcgov/entity#21089

21089 Temporarily comment out code that breaks dev

---

legal-api/src/legal_api/models/business.py

*Issue #:* /bcgov/entity#21089
- Add mapper entry
- Revert commented out code
*Works at local env*

21089 Add mapper entry of new column

---

legal-api/src/legal_api/models/configuration.py
legal-api/src/legal_api/resources/v2/__init__.py
legal-api/src/legal_api/resources/v2/configuration.py
legal-api/tests/unit/resources/v2/test_configuration.py

*Issue #:* /bcgov/entity#21025
`/api/v2/admin/configuration`

21025 configuration GET endpoint

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#21056
update version for release 21.2b

21056 - update version for release 21.2b

---

colin-api/requirements/prod.txt
colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/resources/business.py

*Issue #:* /bcgov/entity#21120

21120 new get business endpoint to access from UI

---

.github/workflows/business-pay-ocp-cd.yml
queue_services/business-pay/Makefile

*Issue #:* n/a
- inistial build of business pay in OCP

initial cd for business-pay in OCP

---

queue_services/business-pay/poetry.lock
queue_services/business-pay/pyproject.toml

*Issue #:* n/a
- update docker build

changing back to my repo

---

legal-api/devops/vaults.json

the location of SENTRY_DSN var moved

---

legal-api/src/legal_api/models/filing.py

*Issue #:* /bcgov/entity#21236

21236 exclude local filings from colin sync

---

colin-api/src/colin_api/resources/business.py

*Issue #:* /bcgov/entity#21120

21120 OPTIONS for cors

---

docs/business.yaml

* Updated to use `description` instead of title 
* Updated example dates
* Updated so all example values displayed correctly
* Other misc updates

Update legal api spec after reviewing legal name updates in stoplight

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#21321
The ticket number is cool "21321" haha

21321 Bumped up version numbers for release 21.3a

---

colin-api/src/colin_api/models/business.py

*Issue #:* /bcgov/entity#20936

20936 update to support "C" corp_num series

---

colin-api/devops/vaults.json
jobs/email-reminder/devops/vaults.json
jobs/furnishings/devops/vaults.json
jobs/future-effective-filings/devops/vaults.json
jobs/involuntary-dissolutions/devops/vaults.json
jobs/update-colin-filings/devops/vaults.json
jobs/update-legal-filings/devops/vaults.json
queue_services/business-pay/devops/vaults.json
queue_services/entity-emailer/devops/vaults.json
queue_services/entity-filer/devops/vaults.json
queue_services/entity-pay/devops/vaults.json

fix path to sentry dsn var

---

jobs/involuntary-dissolutions/config.py
jobs/involuntary-dissolutions/devops/vaults.json

*Issue #:* /bcgov/entity#21197

21197 add configuration dissolution jobs

---

legal-api/src/legal_api/services/involuntary_dissolution.py
legal-api/tests/unit/services/test_involuntary_dissolution.py

*Issue #:* /bcgov/entity#21091
- Remove Change of Address check
- Remove unit tests
*Testing result at local env(new)*

21091 Legal API - Remove one criterion for eligible count of involuntary dissolution service

---

legal-api/src/legal_api/services/involuntary_dissolution.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/services/test_involuntary_dissolution.py

*Issue #:* /bcgov/entity#21091
- change some `<some_enum>.value` to `<some_enum>`
- other misc updates

21091 Update enum usage for some db queries

---

legal-api/src/legal_api/version.py

Test legal api CD

---

queue_services/entity-emailer/src/entity_emailer/email_templates/REG-COMPLETED.html

*Issue #:* /bcgov/entity#21347
- Remove: “In addition, the following links can assist you:”
- Remove: “A message from the Minister of Citizens’ Services and the Minister of Jobs, Economic Recovery and Innovation”
- Remove the bullet from the beginning of the last line in the email and move that last sentence up to the end of the paragraph that begins with ‘Important:.. ‘.
- Test it by running emailer locally and see the rendered email page

21347 fix email output for sp/gp registration

---

queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#21260

21260 - Bumped version number of emailer up

---

queue_services/entity-emailer/src/entity_emailer/email_processors/agm_extension_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/agm_location_change_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/amalgamation_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/change_of_registration_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/consent_continuation_out_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/continuation_out_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/dissolution_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/filing_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/registration_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/restoration_notification.py
queue_services/entity-emailer/src/entity_emailer/email_processors/special_resolution_helper.py

*Issue #:* /bcgov/entity#21437
Fixed since the notification api library has changed and we expect a string now

21437 Fix emailer 400 error

---

legal-api/src/legal_api/services/involuntary_dissolution.py
legal-api/tests/unit/services/test_involuntary_dissolution.py

*Issue #:* /bcgov/entity#21207
- Add method to check if given business is eligible for dissolution (slightly refactor the service class)
- Add & Update unit tests
- Remove unused statement

21207 Legal API - implement functionality to check if given business is eligible for dissolution

---

legal-api/src/legal_api/services/involuntary_dissolution.py
legal-api/tests/unit/services/test_involuntary_dissolution.py

*Issue #:* /bcgov/entity#21473
- Add query condition to skip businesses which have restoration filed within 1 year
- Updated unit tests

21473 Legal API - Fix transition filed check for eligible dissolution businesses

---

legal-api/Makefile

* Updated makefile to use `requirements-nats.txt` so nats requirements are installed

Small tweak to Makefile for requirements-nats.txt

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#21189
- Removed all files related to affidavit and authorization in filing from minio 
- Added relevant unit testing

21189 delete drafts minio

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/requirements/prod.txt
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_application.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_name.py
queue_services/entity-filer/src/entity_filer/filing_processors/change_of_registration.py
queue_services/entity-filer/src/entity_filer/filing_processors/conversion.py
queue_services/entity-filer/src/entity_filer/filing_processors/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/filings.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py
queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
queue_services/entity-filer/src/entity_filer/filing_processors/restoration.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_business_profile.py
queue_services/entity-filer/tests/unit/filing_processors/test_admin_freeze.py
queue_services/entity-filer/tests/unit/filing_processors/test_registration.py
queue_services/entity-filer/tests/unit/test_worker/test_consent_continuation_out.py
queue_services/entity-filer/tests/unit/test_worker/test_correction_firms.py
queue_services/entity-filer/tests/unit/test_worker/test_incorporation.py
queue_services/entity-filer/tests/unit/test_worker/test_worker.py

*Issue #:* /bcgov/entity#19268

19268 filer refactoring

---

legal-api/src/legal_api/services/involuntary_dissolution.py

*Issue #:* /bcgov/entity#21279
* Update `check_business_eligibility` & `_get_businesses_eligible_query` to allow including businesses already in dissolution via a `exclude_in_dissolution` parameter.  This is required for warning scenario when returning the not in good standing warning type when the business is already in dissolution.

21279 Update eligibility query to allow including/excluding of businesses in dissolution in check

---

legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#21279

21279 fix broken test

---

queue_services/entity-bn/requirements.txt
queue_services/entity-bn/requirements/prod.txt
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-digital-credentials/requirements.txt
queue_services/entity-digital-credentials/requirements/prod.txt
queue_services/entity-digital-credentials/src/entity_digital_credentials/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#21260

21260 bumped up version numbers for release 21.3b

---

legal-api/setup.py

Remove nats requirements from setup.py

---

queue_services/entity-filer/src/entity_filer/filing_processors/continuation_in.py
queue_services/entity-filer/tests/unit/test_worker/test_continuation_in.py

*Issue #:* /bcgov/entity#20802

20802 additional filing meta data

---

legal-api/migrations/versions/3083d361616e_add_trigger_date_to_batch_processing.py
legal-api/src/legal_api/models/batch_processing.py

This is the first PR for the ticket. More changes will come in the subsequent PRs.
- Added alembic script
- Updated data model
*batch_processing table after the change*

21475 - Add trigger_date to batch_processing table

---

queue_services/entity-filer/Dockerfile

*Issue #:* n/a
- setting protocol bufs to python generation

setting protocol bufs to python generation

---

queue_services/entity-filer/.dockerignore
queue_services/entity-filer/Dockerfile
queue_services/entity-filer/Makefile

*Issue #:* n/a
- updated dockerfile for protobuf collisions

fix: updated dockerfile

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#20802
- new staticDocuments object with name and url
```
{
"documents": {
"certificate": "http://localhost:5000/api/v2/businesses/C9900731/filings/149329/documents/certificate",
"legalFilings": [
{
"continuationIn": "http://localhost:5000/api/v2/businesses/C9900731/filings/149329/documents/continuationIn"
}
],
"noticeOfArticles": "http://localhost:5000/api/v2/businesses/C9900731/filings/149329/documents/noticeOfArticles",
"receipt": "http://localhost:5000/api/v2/businesses/C9900731/filings/149329/documents/receipt",
"staticDocuments": [
{
"name": "Director Affidavit",
"url": "http://localhost:5000/api/v2/businesses/C9900731/filings/149329/documents/static/8c0c4a4f-41cf-4934-a27c-81fca942d05e.pdf"
},
{
"name": "BC0923795 Annual Report …
```

20802 static documents with file name

---

.github/workflows/legal-api-ci.yml

*Issue #:* /bcgov/entity#21696
Try to use codecov-action@v4 as discussed

21696-fixe-broken-code-coverage-uploads-try-v4

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#20949, /bcgov/entity/issues/21803

20949 fix for special resolution fee filing type code

---

.github/workflows/colin-api-ci.yml
.github/workflows/entity-bn-ci.yml
.github/workflows/entity-digital-credentials-ci.yml
.github/workflows/entity-emailer-ci.yml
.github/workflows/entity-filer-ci.yml
.github/workflows/entity-pay-ci.yml
.github/workflows/furnishings-ci.yml
.github/workflows/involuntary-dissolutions-ci.yml
codecov.yaml

*Issue #:* /bcgov/entity#21696
- Update Codecov version to use v4, and add token to them
- Add Codecov section for Furnishings Job CI and Involuntary Dissolutions Job CI
Fixed and verified for legal-api before, PRs:
Add token and using v4: https://github.com/bcgov/lear/pull/2759
Verify it works for legal-api: https://github.com/bcgov/lear/pull/2760
Will create another test PR with other CIs after this PR gets merged.

21696-fix broken code coverage uploads in CIs

---

colin-api/setup.cfg
colin-api/src/colin_api/__init__.py
colin-api/src/colin_api/exceptions/__init__.py
colin-api/src/colin_api/models/address.py
colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/models/corp_name.py
colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/models/office.py
colin-api/src/colin_api/models/reset.py
colin-api/src/colin_api/resources/business.py
colin-api/src/colin_api/resources/db.py
colin-api/src/colin_api/resources/event.py
colin-api/src/colin_api/resources/filing.py
colin-api/src/colin_api/resources/office.py
colin-api/src/colin_api/resources/ops.py
colin-api/src/colin_api/resources/parties.py
colin-api/src/colin_api/resources/share_struct.py
colin-api/src/colin_api/services/flags.py
colin-api/src/colin_api/utils/__init__.py
colin-api/src/colin_api/utils/logging.py

*Issue #:* /bcgov/entity#21747
- Additional: refactoring and lint fix

21747 sync incorporationApplication of BC, CC, ULC

---

legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/src/legal_api/reports/business_document.py
legal-api/tests/unit/resources/v2/test_business_documents.py

*Issue #:* /bcgov/entity#21485
* Updated company status
* Updated "Dissolution/Restoration Information" section
* Added unit tests

21485 Legal API - Update business summary

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/requirements/bcregistry-libraries.txt
queue_services/entity-emailer/src/entity_emailer/email_processors/continuation_in_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/business-information.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_continuation_in_notification.py

*Issue #:* /bcgov/entity#19271
- create email templates
- create email processor for continuation in
- add unit tests

19271 - continuation in email

---

legal-api/requirements-nats.txt
legal-api/requirements.txt

Move requests lib to requirements-nats.txt

---

legal-api/src/legal_api/resources/v1/business/business_filings.py
legal-api/src/legal_api/resources/v2/business/__init__.py
legal-api/src/legal_api/resources/v2/business/colin_sync.py
legal-api/tests/unit/resources/v2/test_colin_sync.py

*Issue #:* /bcgov/entity#19794

19794 colin sync v2 endpoint

---

legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#21485
- Fix Dissolution/Restoration Information bug

21485 update business summary fix bug

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#21571
- Bumped the version numbers up for release 21.4a

bump version numbers up for release 21.4a

---

queue_services/entity-filer/devops/vaults.json

- Added `launchdarkly` into vaults.json

21475 Filer - Add launchdarkly into vaults.json

---

jobs/email-reminder/email_reminder.py

*Issue #:* /bcgov/entity#21571

21571 - potential fix for email reminder job

---

legal-api/report-templates/certificateOfAmalgamation.html
legal-api/report-templates/certificateOfContinuation.html
legal-api/report-templates/certificateOfGoodStanding.html
legal-api/report-templates/certificateOfIncorporation.html
legal-api/report-templates/certificateOfRestoration.html
legal-api/report-templates/certificateOfStatus.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#19267

19267 certificate of continuation in

---

legal-api/src/legal_api/services/involuntary_dissolution.py

Temp fix for error on get business when in dissolution business has pending COA

---

legal-api/src/legal_api/services/involuntary_dissolution.py

Revert temp involuntary dissolution fix for eligibility check query

---

jobs/involuntary-dissolutions/config.py
jobs/involuntary-dissolutions/involuntary_dissolutions.py
jobs/involuntary-dissolutions/requirements/dev.txt
jobs/involuntary-dissolutions/setup.py
jobs/involuntary-dissolutions/tests/unit/__init__.py
jobs/involuntary-dissolutions/tests/unit/test_involuntary_dissolutions.py

*Issue #:* /bcgov/entity#21332
- Added logic to dissolutions job to move businesses to stage 3. For detailed logic, reference [tech design](https://community.inkdrop.app/note/a27b7a79c8cdf7db0ab19be10b4fc2e8/note:Ej0jewYQK#user-content-3-processing-actual-dissolution-of-businesses)

21332 Dissolutions Job - Implement stage 3

---

legal-api/report-templates/template-parts/continuation/foreignJurisdiction.html

*Issue #:* /bcgov/entity#21114
Updated Continuation In application template based on Andy's feedback. Increase column width (labels) for Previous Foreign Jurisdiction section

21114 - update output template

---

legal-api/src/legal_api/services/namex.py

Fix issue with namex returning different expiration date formats

---

legal-api/src/legal_api/errorhandlers.py
legal-api/src/legal_api/logging.conf

Fixes for unhandled exception logging

---

legal-api/src/legal_api/services/namex.py

* Cherry pick fix that has been pushed into prod as part of hotfix for legal api

Fix issue with namex returning different expiration date formats (#2795)

---

jobs/furnishings/src/furnishings/stage_processors/stage_one.py
jobs/involuntary-dissolutions/involuntary_dissolutions.py
queue_services/entity-filer/src/entity_filer/filing_processors/annual_report.py

*Issue #:* /bcgov/entity#21777

21777 update check_business_eiligibilty usage

---

legal-api/src/legal_api/services/involuntary_dissolution.py
legal-api/tests/unit/services/test_involuntary_dissolution.py

*Issue #:* /bcgov/entity#21506
- Added sorting logic to prioritize businesses by "transition filing not filed" criterion first, followed by the oldest restoration filing date in ascending order.
- Added and updated unit tests to verify the new sorting logic.

21506 Legal API - Prioritize businesses eligible for involuntary dissolution by transition filing

---

queue_services/business-pay/src/business_pay/services/__init__.py

*Issue #:* /bcgov/entity#22110
- Trying this fix out

22110 - Fixed receiving emails when filing is in PAID state

---

legal-api/report-templates/template-parts/business-summary/foreignJurisdiction.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#22155
- quick bug fix for business summary

22155 business summary quick bug fix

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/tests/unit/models/test_business.py

*Issue #:* /bcgov/entity#22033
- Optimized the get_alternate_names function
- Moved the alternateNames array back to big JSON (removed it from slim json)
- Only get it in the slim json in search endpoint for firms
- fixed unit test

22033 - Fixed performance of get alternate names + misc. changes

---

legal-api/requirements.txt
legal-api/requirements/prod.txt
legal-api/src/legal_api/__init__.py
legal-api/src/legal_api/config.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/services/authz.py
legal-api/tests/unit/services/test_authorization.py

*Issue #:* /bcgov/entity#22030

API - business allowable actions for comp auths

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#21995
bumped version numbers up for release 22.1a

21995 - bumped version numbers up for release 22.1a

---

queue_services/business-pay/src/business_pay/utils/__init__.py

*Issue #:* /bcgov/entity#21930

21930 adding init file

---

jobs/furnishings/src/furnishings/stage_processors/stage_one.py
jobs/furnishings/src/furnishings/stage_processors/stage_two.py
jobs/furnishings/src/furnishings/worker.py
jobs/furnishings/tests/unit/__init__.py
jobs/furnishings/tests/unit/stage_processors/test_stage_one.py
jobs/furnishings/tests/unit/stage_processors/test_stage_two.py

*Issue #:* /bcgov/entity#21951
- Implemented stage 2 of furnishings job (exclude SFTP to BC Laws)
*Local testing*

21951 Furnishings job - stage 2 (exclude SFTP to BC Laws)

---

colin-api/src/colin_api/models/reset.py

Add logic to delete MRAS_MESSAGE_OUTBOUND entries associated with an event for reset endpoint

---

.github/workflows/colin-api-ci.yml
.github/workflows/data-reset-tool-ci.yml
.github/workflows/entity-bn-ci.yml
.github/workflows/entity-digital-credentials-ci.yml
.github/workflows/entity-emailer-ci.yml
.github/workflows/entity-filer-ci.yml
.github/workflows/entity-pay-ci.yml
.github/workflows/filings-notebook-report-ci.yml
.github/workflows/furnishings-ci.yml
.github/workflows/future-effective-filings-ci.yml
.github/workflows/involuntary-dissolutions-ci.yml
.github/workflows/legal-api-ci.yml
.github/workflows/sftp-icbc-report-ci.yml
.github/workflows/sftp-nuans-report-ci.yml
.github/workflows/update-colin-filings-ci.yml
.github/workflows/update-legal-filings-ci.yml
legal-api/src/legal_api/models/amalgamation.py

*Issue #:* /bcgov/entity#22248
- Disabled codecov failure
Following in the footsteps of Travis here: https://github.com/bcgov/sbc-auth/pull/2806
It works!

22248 - Disable codecov failure

---

jobs/involuntary-dissolutions/involuntary_dissolutions.py

*Issue #:* /bcgov/entity#22080
Added more debug logging for involuntary dissolutions job

22080 - Added more debug logging for involuntary dissolutions job

---

jobs/involuntary-dissolutions/involuntary_dissolutions.py
legal-api/src/legal_api/models/address.py

*Issue #:* /bcgov/entity#21953
- Add `FURNISHING` address type and `find_by` method.
- Separated this PR from #2816 so that the CI will run correctly once this is merged.

21953 Update Address model for furnishings job

---

legal-api/src/legal_api/resources/v2/business/business.py

Fixed the slim business structure

---

legal-api/src/legal_api/resources/v2/business/business.py

*Issue #:* /bcgov/entity#22262
* Cherry pick hotfix for #22262

22262 Fixed the slim business structure (#2825)

---

.github/workflows/furnishings-ci.yml
jobs/furnishings/setup.py
jobs/furnishings/src/furnishings/config.py
jobs/furnishings/src/furnishings/stage_processors/stage_one.py
jobs/furnishings/tests/unit/__init__.py
jobs/furnishings/tests/unit/stage_processors/test_stage_one.py

*Issue #:* /bcgov/entity#21952
- Implemented stage 1 letter flow logic (excluding letter/pdf creation and SFTP to BCMail+)

21953 Furnishings job - Implement stage one letter flow

---

jobs/furnishings/devops/vaults.json

*Issue #:* /bcgov/entity#22272
- Added furnishings entry to vaults.json

22272 Furnishings job - Add furnishings entry to vaults.json

---

jobs/furnishings/src/furnishings/stage_processors/stage_one.py
jobs/furnishings/src/furnishings/stage_processors/stage_two.py
jobs/furnishings/tests/unit/__init__.py
jobs/furnishings/tests/unit/stage_processors/test_stage_one.py
jobs/furnishings/tests/unit/stage_processors/test_stage_two.py
legal-api/migrations/versions/feb206b2ce65_add_columns_to_furnishings.py
legal-api/src/legal_api/models/furnishing.py
legal-api/tests/unit/models/test_furnishing.py

*Issue #:* /bcgov/entity#22205
- Added alembic script
- Updated code model
- Updated furnishings job
- Updated unit tests
- Upgrade DB - `last_ar_date` and `business_name` in `furnishings` table
- Run furnishings job - stage 1&2 
- Unit tests - all pass when referring to updated code model (2024-07-15 updated)

22205 Legal API - Add additional columns to furnishings table

---

jobs/furnishings/devops/vaults.json

*Issue #:* /bcgov/entity#22272
- Updated vaults.json

22272 Furnishings Job - Update vaults.json

---

legal-api/src/legal_api/models/furnishing.py

*Issue #:* /bcgov/entity#21760

21760 add business relationship into furnishing model

---

legal-api/tests/unit/resources/v2/test_reviews.py

*Issue #:* /bcgov/entity#21985
- added test cases for the review endpoint. 

Review Endpoint Testing

---

jobs/furnishings/src/furnishings/stage_processors/stage_one.py

*Issue #:* /bcgov/entity#21953

21953 Fix issue when auth returns empty contacts list for GET <auth_url>/entities/{identifier} endpoint

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#22309
- Bumped the version numbers up for release 22.2a

22309 Bump version numbers up for release 22.2a

---

legal-api/src/legal_api/models/review_result.py
legal-api/src/legal_api/resources/v2/admin/reviews.py
legal-api/tests/unit/resources/v2/test_reviews.py

*Issue #:* /bcgov/entity#21985

21985 creationDate in isoformat

---

jobs/furnishings/src/furnishings/stage_processors/stage_one.py
jobs/furnishings/src/furnishings/stage_processors/stage_three.py
jobs/furnishings/src/furnishings/worker.py
jobs/furnishings/tests/unit/stage_processors/test_stage_one.py
jobs/furnishings/tests/unit/stage_processors/test_stage_three.py

*Issue #:* /bcgov/entity#21952
- Implemented [stage 3 of furnishings job tech design](https://community.inkdrop.app/a27b7a79c8cdf7db0ab19be10b4fc2e8/lr3hwYXNS#stage-3).

21952 Furnishings job - Implement stage three

---

jobs/update-colin-filings/update_colin_filings.py
jobs/update-legal-filings/update_legal_filings.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v1/business/business_filings.py
legal-api/src/legal_api/resources/v2/business/colin_sync.py
legal-api/tests/unit/models/test_filing.py
legal-api/tests/unit/resources/v2/test_colin_sync.py

*Issue #:* /bcgov/entity#19794

19794 pagination

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v2/admin/reviews.py
legal-api/tests/unit/resources/v2/test_reviews.py
queue_services/business-pay/src/business_pay/database/filings.py
queue_services/business-pay/src/business_pay/database/review.py
queue_services/business-pay/src/business_pay/resources/pay_filer.py

*Issue #:* /bcgov/entity#21931
- included a date fix in business-pay for review creation

21931 submit staff review

---

legal-api/src/legal_api/resources/v2/admin/reviews.py
legal-api/tests/unit/resources/v2/test_reviews.py

*Issue #:* /bcgov/entity#21931

21931 update validation

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/models/review_result.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/models/test_review_result.py

*Issue #:* /bcgov/entity#22354

22354 latestReviewComment

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* bcgov/entity#22237
- Updated some version numbers to 2.119.0

Updated some version numbers to 2.119.0

---

docs/business.yaml

*Issue #:* /bcgov/entity#22294
- Added Agm_extension schema to the schema section under components
- Added examples of request and response for AGM extension filing
- Deleted unused schema party - copy and Suggestion_item - copy to ensure successful import into the Swagger Editor for QA
**Request**
**Response**

22294 update agm extension spec

---

legal-api/migrations/versions/bb9f4ab856b1_remove_group_identifier_from_furnishings.py
legal-api/src/legal_api/models/furnishing.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/models/test_furnishing.py

*Issue #:* /bcgov/entity#22286

22286 update to use new furnishing groups approach

---

jobs/furnishings/src/furnishings/stage_processors/stage_one.py
jobs/furnishings/src/furnishings/stage_processors/stage_three.py
jobs/furnishings/src/furnishings/stage_processors/stage_two.py
jobs/furnishings/tests/unit/stage_processors/test_stage_one.py

*Issue #:* /bcgov/entity#22286
Check the legal_api udpates here - https://github.com/bcgov/lear/pull/2858

22286 Update job to use new furnishing groups approach

---

docs/business.yaml

*Issue #:* /bcgov/entity#22300
- Updated relevant schemas -- Annual_report, office
- Added request and response examples for annual report filing

22300-update annual report spec

---

docs/business.yaml

*Issue #:* /bcgov/entity#22211
Add amalgamation (regular and short form) API spec endpoints

22211 - add amalgamation spec

---

docs/business.yaml

*Issue #:* /bcgov/entity#22298
- updated relevant schemas (name_request, name_translation, court_order)
- add request and response examples for alterations

22298-update alterations specs

---

colin-api/devops/vaults.json
jobs/email-reminder/devops/vaults.json
jobs/furnishings/devops/vaults.json
jobs/future-effective-filings/devops/vaults.json
jobs/involuntary-dissolutions/devops/vaults.json
jobs/update-colin-filings/devops/vaults.json
jobs/update-legal-filings/devops/vaults.json
queue_services/business-pay/devops/vaults.json
queue_services/entity-emailer/devops/vaults.json
queue_services/entity-filer/devops/vaults.json
queue_services/entity-pay/devops/vaults.json

*Issue #:* /bcgov/entity#21699
- Reverted the changes made to sentry in vaults.json a while back

21699 - Reverted the sentry dsn change

---

.github/workflows/legal-oas-ci.yml

* Add OAS CI workflow for docs/business.yaml file so any updates to api spec are linted.

Add CI workflow for legal api specs

---

.github/workflows/legal-oas-ci.yml

- Add OAS CI workflow to `api-spec-updates` branch for docs/business.yaml file so any updates to api spec are linted.

add CI workflow for legal api specs to api-spec-updates branch

---

.github/workflows/legal-oas-ci.yml

- add permissions section 
Will create a test PR after this change merged.

Adjust OAS CI Permissions

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

*Issue #:* /bcgov/entity#21933

21933 fix business type issue for new business

---

docs/business.yaml

*Issue #:* /bcgov/entity#22212
please see: https://github.com/bcgov/lear/pull/2872

22212 - add continuation in spec

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#22222

22222  additional affiliation information

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#22624

22624 bump version nums

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v2/admin/reviews.py
legal-api/src/legal_api/resources/v2/business/colin_sync.py
legal-api/src/legal_api/resources/v2/internal_services.py
legal-api/tests/unit/resources/v2/test_colin_sync.py
legal-api/tests/unit/resources/v2/test_internal_services.py

*Issue #:* /bcgov/entity#21819

21819 internal endpoint for future effective job

---

docs/business.yaml

*Issue #:* /bcgov/entity#
As per the discussion with Dave and Dylan, we have updated the API Gateway authentication details to use the Business Registry API privileges.

Update API Specs authentication requirements info

---

jobs/future-effective-filings/config.py
jobs/future-effective-filings/file_future_effective.py
jobs/future-effective-filings/setup.cfg
jobs/update-colin-filings/requirements.txt
jobs/update-colin-filings/requirements/bcregistry-libraries.txt
jobs/update-colin-filings/requirements/prod.txt
jobs/update-colin-filings/update_colin_filings.py
jobs/update-legal-filings/update_legal_filings.py

*Issue #:* /bcgov/entity#21819

21819 update future effective job

---

jobs/future-effective-filings/k8s/templates/cronjob.yaml

*Issue #:* /bcgov/entity#21819

21819 update future effective template to include legal-api v2 url

---

legal-api/migrations/versions/a31cb1eb4b6b_add_filing_id_to_batch_processing.py
legal-api/src/legal_api/models/batch_processing.py

*Issue #:* /bcgov/entity#22370
Create migration and update batch_processing model at legal_api

22370 Add_filing_id to batch_processing

---

jobs/involuntary-dissolutions/involuntary_dissolutions.py
jobs/involuntary-dissolutions/tests/unit/test_involuntary_dissolutions.py

*Issue #:* /bcgov/entity#22370
Add the filing_id to batch_processing in stage_3_process at the job

22370 Add_filing_id_to_batch_processing_at_job

---

colin-api/src/colin_api/models/filing.py

*Issue #:* /bcgov/entity#22714

22714 freeze BEN entity and map correct filing type for all amalgamation application

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#22664
Release 22.4a - bump up version

Release 22.4a - bump up version

---

docs/business.yaml

*Issue #:* /bcgov/entity#22710
- Updated wording for POST /businesses/{identifier}/filings endpoint to reflect the new change.
- Checked typos and format.

22710 - Update wording for POST /businesses/{identifier}/filings

---

legal-api/migrations/versions/01dc3337e726_add_batch_processing_status.py
legal-api/src/legal_api/models/batch_processing.py

*Issue #:* /bcgov/entity#22204
- Created alembic script to update batch_processing enum
- Should be merged before #2903 

22204 - Created alembic script to update batch_processing enum

---

docs/business.yaml

*Issue #:* /bcgov/entity#22700
- Sorted filing request and response examples alphabetically for POST /businesses/{identifier}/filings.
**Before:**
**After:**

22700 - Sorted filing request and response examples alphabetically

---

docs/business.yaml

*Issue #:* /bcgov/entity#22713 and /bcgov/entity#22715
Update wordings

Update spec wordings

---

docs/business.yaml

*Issue #:* /bcgov/entity#22698
- removed the duplications in the enums
- adjusted the required item in the Filing schema to filing which is the one in Business Schemas
- adjusted filing_header schema to fit the updated filing schema
- adjusted examples didn't meet requirements in schemas
**Note**:
The remaining errors are among `amalgamation application` and `continuation in filing`, which are out of scope for this ticket. These errors will be fixed by Olga's team.
This ticket focuses on the filings and related items below:
- agm extension
- agm location change
- annual report
- alteration
- change of directors
- consent continuation out
- voluntary dissolution
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

22698 - fix linting issues related to 7 filings

---

jobs/involuntary-dissolutions/involuntary_dissolutions.py
jobs/involuntary-dissolutions/tests/unit/test_involuntary_dissolutions.py
legal-api/migrations/versions/01dc3337e726_add_batch_processing_status.py
queue_services/entity-filer/Makefile
queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_dissolution.py

*Issue #:* /bcgov/entity#22204
- Updated to support queued status
- Waiting for #2902 to merge before I can fully confirm this works and can mark as ready for review.

22204 Filer + Dissolutions Job - Updated to support queued status

---

docs/business.yaml

*Issue #:* /bcgov/entity#22718
Sort filing examples alphabetically

Sort examples alphabetically

---

colin-api/src/colin_api/models/__init__.py
colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/models/jurisdiction.py
colin-api/src/colin_api/resources/filing.py

*Issue #:* /bcgov/entity#21663

21663 continuation in filing sync

---

.github/workflows/entity-filer-ci.yml
.github/workflows/legal-api-ci.yml
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py
queue_services/entity-bn/src/entity_bn/worker.py

*Issue #:* /bcgov/entity#22371

22371 receipt and continuation in docs in intermediate states

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#22835
- Bumped version numbers up for release 22.4b

22835 - Bumped version numbers up for release 22.4b

---

docs/business.yaml

*Issue #:* /bcgov/entity##
As we discussed, we've removed and updated the filings not needed for the demo from the API spec overview.

Remove filings not needed for demo

---

queue_services/entity-emailer/src/entity_emailer/email_processors/__init__.py
queue_services/entity-emailer/src/entity_emailer/email_processors/continuation_in_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/16px.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/20px.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/24px.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/8px.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/continuation-application-details.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/style.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/whitespace-16px.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/whitespace-24px.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py

*Issue #:* bcgov/entity#22290
- added template parts to list and updated comments
- added foreign jurisdiction computation and included it in continuation in variables
- updated CONT-IN-PAID template to match UI designs
- added some "true" whitespace template parts and updated comments
- added template part for continuation application details
- added a class to style.html and update title message whitespace
- updated a comment for future
- added "- Pending" to continuation application attachment name

22290 Updated continuation "PAID" email

---

legal-api/src/legal_api/core/filing.py
legal-api/tests/unit/core/test_filing_ledger.py

*Issue #:* /bcgov/entity#22673
- Hid the involuntary dissolution ledger entry/item
- Added unit test
Example of postman calls:

22673 - Hide involuntary dissolution ledger item

---

queue_services/entity-bn/src/entity_bn/bn_processors/registration.py
queue_services/entity-bn/src/entity_bn/worker.py
queue_services/entity-bn/tests/unit/bn_processors/test_registration.py

*Issue #:* /bcgov/entity#22819

22819 publish an event to ENTITY_EVENT_SUBJECT while receiving BN15

---

colin-api/src/colin_api/models/filing.py
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py

*Issue #:* /bcgov/entity#19528

19528 colin sync map correct alteration filing type

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#22598

22598 Bumped version numbers up for release 22.5a

---

jobs/furnishings/src/furnishings/stage_processors/post_processor.py
jobs/furnishings/src/furnishings/stage_processors/stage_three.py
jobs/furnishings/src/furnishings/stage_processors/stage_two.py
jobs/furnishings/tests/unit/stage_processors/test_post_processor.py

*Issue #:* /bcgov/entity#22324
- Added logic to generate XML for stage 3 EPs
1. Starting with the following batch processing entries (2 D3 BCs, 3 D2 BCs, and 5 D2 EPs):
2. Running the furnishings job results in the following furnishings entries:
3. And the final xml payload, including 3 different categories.
```xml
<public_notice>
<volume></volume>
<date></date>
<filing_desc title="Intent to Dissolve (B.C.)" id="">
<category>INTENT TO DISSOLVE</category>
<subcategory>B.C.</subcategory>
<corp_class>BC Company(s)</corp_class>
<description>The Registrar of Companies hereby gives notice that the following companies may, at any time after the expiration of one month from the date of publication of this notice, unless cause is shown to the contrary, be …
```

22324 Furnishings Job - Add EP logic to generate XML for stage 2

---

legal-api/report-templates/noticeOfDissolutionCommencement.html
legal-api/src/legal_api/reports/report_v2.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/reports/test_report_v2.py

*Issue #:* /bcgov/entity#22495

22495 update furnishing document endpoint to support stage 1 transition letter

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#22711

22711 hot fix

---

legal-api/migrations/versions/7d486343384b_add_batch_custom_sequence.py

*Issue #:* /bcgov/entity#22502
- add a new sequence to generate custom identifier used for "Report Batch ID" in batch letter
- just small tweaks, the major changes will be in the following PRs (WIP)

22502 - add batch custom identifier sequence for batch letter generation

---

queue_services/entity-emailer/src/entity_emailer/email_processors/involuntary_dissolution_stage_1_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_involuntary_dissolution_stage_1_notification.py

*Issue #:* /bcgov/entity#22497

22497 Update stage 1 NO_TR  letter attachments

---

queue_services/entity-emailer/src/entity_emailer/email_processors/involuntary_dissolution_stage_1_notification.py
queue_services/entity-emailer/tests/unit/email_processors/test_involuntary_dissolution_stage_1_notification.py

*Issue #:* /bcgov/entity#22497

22497 update stage 1 no tr letter attachments

---

legal-api/src/legal_api/models/review.py

*Issue #:* /bcgov/entity#22011
fixed the typo/copy-paste issue. Now query is fixed

22011 - fix query to filter by completing party

---

legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/filings/validations/change_of_registration.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/dissolution.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/src/legal_api/services/warnings/business/business_checks/business.py
legal-api/tests/unit/services/filings/validations/test_alteration.py
legal-api/tests/unit/services/filings/validations/test_change_of_registration.py
legal-api/tests/unit/services/filings/validations/test_dissolution.py
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py

*Issue #:* /bcgov/entity#22372

22372 continuation in alteration

---

legal-api/src/legal_api/models/review.py
legal-api/src/legal_api/resources/v2/admin/reviews.py
legal-api/src/legal_api/utils/legislation_datetime.py

*Issue #:* /bcgov/entity#22011
implemented filter and sorting for future effective date (missed it out earlier)

22011 - implement filter and sorting for future effective date

---

queue_services/entity-bn/src/entity_bn/bn_processors/__init__.py
queue_services/entity-bn/src/entity_bn/bn_processors/registration.py

*Issue #:* /bcgov/entity#23060

23060 map operating name in cra request

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#23062
bumped version numbers up for release 22.5b

23062 - bumped version numbers up for release 22.5b

---

queue_services/entity-filer/flags.json
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py
queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#22931

22931 update consume nr api call

---

queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#23058
- version is now 2.125.0

Update Entity Filer version for release

---

queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#23058
- version is now 2.125.0

Update Entity Emailer version for release

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#23058
- version is now 2.125.0

Update Legal API version for release

---

legal-api/src/legal_api/resources/v2/business/colin_sync.py
queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_application.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/filings.py
queue_services/entity-filer/tests/unit/__init__.py
queue_services/entity-filer/tests/unit/test_worker/test_amalgamation_application.py

*Issue #:* /bcgov/entity#23094

23094 carry over resolution date for Horizontal & Vertical amalgamation

---

jobs/email-reminder/email_reminder.py

*Issue #:* /bcgov/entity#21034
Update email reminder job to support C companies

21034 - Update email reminder job to support C companies

---

queue_services/entity-filer/src/entity_filer/filing_processors/annual_report.py
queue_services/entity-filer/tests/unit/filing_processors/test_annual_report.py

*Issue #:* /bcgov/entity#22681

22681_remove_notes_ar_filer

---

colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/filing.py

*Issue #:* /bcgov/entity#21753

21753 consentContinuationOut colin sync

---

colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/version.py

*Issue #:* /bcgov/entity###245
Added admin freeze check for ar-reminder job

Admin Freeze check in colin#245

---

colin-api/src/colin_api/resources/filing.py

319_delete_ar_prompt

---

colin-api/src/colin_api/models/__init__.py
colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/models/cont_out.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/filing.py
legal-api/src/legal_api/resources/v2/business/colin_sync.py

*Issue #:* /bcgov/entity#21754

21754 continuationOut colin sync

---

jobs/furnishings/devops/vaults.json
jobs/furnishings/src/furnishings/config.py
jobs/furnishings/src/furnishings/stage_processors/post_processor.py
jobs/furnishings/tests/unit/stage_processors/test_post_processor.py

*Issue #:* /bcgov/entity#22499
- Updated to decode the sftp private key from base 64
- Updated vaults.json
- Confirmed it uploaded to local sftp correctly.

22499 Furnishings Job - Update private key decoding

---

colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/filing.py

*Issue #:* /bcgov/entity#21757
Additional
- event date = filing date (bcgov/entity#20747)
- last_ar_filed_dt = annualReportDate (bcgov/entity#20834)

21757 agmLocationChange filing sync

---

legal-api/report-templates/certificateOfRestoration.html

*Issue #:* /bcgov/entity#16382
Some examples:
Before:
After fix:
Before:
After fix:

16382 - add name to limited restoration certificate

---

queue_services/entity-emailer/src/entity_emailer/worker.py

*Issue #:* /bcgov/entity#23413

23413 put the email msg back on the queue if notify-api fails

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

- Bumped up version for release 22.7a

Bump up version for release 22.7a

---

legal-api/flags.json
legal-api/src/legal_api/services/bootstrap.py
legal-api/src/legal_api/services/involuntary_dissolution.py
legal-api/tests/unit/services/test_involuntary_dissolution.py

*Issue #:* /bcgov/entity#23034

23034 add feature flags filter for dissolution runs

---

colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/filing.py

*Issue #:* /bcgov/entity#21756

21756 agmExtension filing sync

---

legal-api/src/legal_api/config.py
legal-api/src/legal_api/services/__init__.py
legal-api/src/legal_api/services/colin.py
legal-api/src/legal_api/services/filings/validations/continuation_in.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
legal-api/tests/unit/services/filings/validations/test_continuation_in.py

*Issue #:* /bcgov/entity#21104
- Added validation check for EXPRO business making a call to Colin API

21104 - add business search validation

---

jobs/furnishings/src/furnishings/config.py
jobs/involuntary-dissolutions/config.py
jobs/involuntary-dissolutions/devops/vaults.json
queue_services/entity-emailer/src/entity_emailer/config.py

*Issue #:* /bcgov/entity#23034

23034 add the config

---

jobs/involuntary-dissolutions/devops/vaults.json
legal-api/Makefile

*Issue #:* /bcgov/entity#23222

23222 comment out 1pass udpate section by 20241001

---

legal-api/src/legal_api/services/bootstrap.py

*Issue #:* /bcgov/entity#23034

23034 debug config

---

queue_services/entity-bn/src/entity_bn/bn_processors/__init__.py
queue_services/entity-bn/tests/unit/__init__.py
queue_services/entity-bn/tests/unit/bn_processors/test_registration.py

*Issue #:* /bcgov/entity#23525

23525 autoescape special characters in xml

---

jobs/involuntary-dissolutions/involuntary_dissolutions.py
legal-api/src/legal_api/services/bootstrap.py
legal-api/src/legal_api/services/involuntary_dissolution.py

*Issue #:* /bcgov/entity#23034

23034 fix config issues

---

legal-api/report-templates/amalgamationApplication.html
legal-api/report-templates/template-parts/amalgamation/amalgamationName.html

*Issue #:* /bcgov/entity#22847
- Updated the Amalgamation Application Output template, to display the type of Amalgamation Application (regular, short-form horizontal, short-form vertical)
- Adjust the font of Name of Amalgamated Company

22847 - Amalgamation Application Output Display Type

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/services/involuntary_dissolution.py
legal-api/tests/unit/resources/v1/test_business_filings/test_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#23354
- add filing type
- add fee codes
- add filing status
- add tests
Let me know if I'm missing something

23354 - Misc updates for Notice of Withdrawal

---

legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#22849
- An amalgamation was done. In the Business Summary for a TED, updated the Company Status to "Amalgamated" 

22849 - Update Amalgamation Summary Status

---

legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#23255
- Updated `FILING_SUMMARY_DISPLAY_NAME` to fallback to a common name unless there is a specific name
_**C9900778:**_
_**FM1019711 (SP) Voluntary Dissolution:**_

23255 - Refactor dissolution business summary display name to support C companies

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-digital-credentials/src/entity_digital_credentials/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#23561
- bumped version numbers up for release 22.7b

23561 - Bumped version numbers up for release 22.7b

---

.github/workflows/entity-filer-ci.yml
colin-api/src/colin_api/models/business.py
colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/models/office.py
colin-api/src/colin_api/resources/filing.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/services/filings/validations/test_consent_continuation_out.py
queue_services/entity-filer/src/entity_filer/filing_processors/alteration.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py

*Issue #:* /bcgov/entity#21752

21752 restoration filing sync

---

legal-api/report-templates/template-parts/restoration-application/applicant.html

*Issue #:* /bcgov/entity#23343
- Updated restoration applicant template to show business name

23343 - update restoration applicant template

---

jobs/involuntary-dissolutions/involuntary_dissolutions.py
jobs/involuntary-dissolutions/tests/unit/test_involuntary_dissolutions.py

*Issue #:* /bcgov/entity#23627
After Stage_1:
```
{ 
'overdueARs': True,
'overdueTransition': False,
'stage_1_date': '2024-09-26 18:08:12.386019+00'
}
```
After Stage_2
```
{ 
'overdueARs': True,
'overdueTransition': False,
'stage_1_date': '2024-09-26 18:08:12.386019+00',
'stage_2_date': '2024-09-27 18:08:12.386019+00'
}
```
After Stage_3
```
{ 
'overdueARs': True,
'overdueTransition': False,
'stage_1_date': '2024-09-26 18:08:12.386019+00',
'stage_2_date': '2024-09-27 18:08:12.386019+00',
'stage_3_date': '2024-09-28 18:08:12.386019+00'
}
```

23627 add meta data track the stages date

---

jobs/email-reminder/requirements.txt
jobs/email-reminder/requirements/bcregistry-libraries.txt
jobs/furnishings/requirements/bcregistry-libraries.txt
jobs/involuntary-dissolutions/requirements.txt
jobs/involuntary-dissolutions/requirements/bcregistry-libraries.txt
jobs/update-legal-filings/requirements.txt
jobs/update-legal-filings/requirements/bcregistry-libraries.txt
legal-api/requirements/bcregistry-libraries.txt
queue_services/entity-bn/requirements.txt
queue_services/entity-bn/requirements/bcregistry-libraries.txt
queue_services/entity-digital-credentials/requirements/bcregistry-libraries.txt
queue_services/entity-emailer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt

*Issue #:* /bcgov/entity#22827
- Update requirement files, partially done in #3024 

22827 - Update requirement files to include sql-versioning

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/src/legal_api/resources/v2/business/business_tasks.py
legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/bootstrap.py
legal-api/src/legal_api/services/namex.py
legal-api/src/legal_api/services/warnings/warning.py
legal-api/src/legal_api/utils/util.py

*Issue #:* /bcgov/entity#23959

23959 add debug logging & print

---

queue_services/entity-emailer/src/entity_emailer/email_templates/BC-CRCTN-PAID.html

*Issue #:* /bcgov/entity#23982
update correction email wording

23982 - update correction email wording

---

legal-api/src/legal_api/services/filings/validations/continuation_in.py
legal-api/tests/unit/services/filings/validations/test_continuation_in.py

*Issue #:* /bcgov/entity#24073
- add Legal API validation for Expro foundingDate

24073 - Add the Validation for Founding Date

---

legal-api/src/legal_api/services/filings/validations/continuation_in.py
legal-api/tests/unit/services/filings/validations/test_continuation_in.py

*Issue #:* /bcgov/entity#24073
- Fix the bug due to different date format

Fix 24073 - fix founding date validation

---

legal-api/src/legal_api/services/filings/validations/continuation_in.py

*Issue #:* /bcgov/entity#24073

Fix 24073 - add a msg show the 2 dates

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-digital-credentials/src/entity_digital_credentials/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#23844
- Legal API v2.131.0
- Entity Bn v2.131.0
- Entity Digital Credentials v2.131.0
- Entity Emailer v2.131.0
- Entity Filer v2.131.0
- Email Reminder job (no version)
- Furnishings job (no version)
- Involuntary Dissolutions job (no version)
- Update Legal Filings job (no version)

23844 - Bump version numbers up for release 23.2b

---

data-tool/.corps.env.sample
data-tool/Makefile
data-tool/flows/batch_delete_flow.py
data-tool/flows/common/event_filing_service.py
data-tool/flows/common/filing_data_cleaning_utils.py
data-tool/flows/config.py
data-tool/flows/corps/event_filing_service.py
data-tool/flows/corps/filing_data_cleaning_utils.py

*Issue #:* /bcgov/entity#23744
- Create a script to delete migrated data
- Refer to doc delete_script in shared folder for tables included in this script

23744 Script to delete migrated data

---

jobs/update-colin-filings/update_colin_filings.py

*Issue #:* /bcgov/entity#24121

24121 additional log

---

legal-api/src/legal_api/resources/v2/business/colin_sync.py

*Issue #:* /bcgov/entity#24121

24121 exception handling for unexpected data

---

legal-api/src/legal_api/models/filing.py

*Issue #:* /bcgov/entity#24121

24121 change order of colin sync

---

legal-api/report-templates/template-parts/common/businessDetails.html

*Issue #:* /bcgov/entity#24013
- Ensure retrieved date value aligns with label
- Display recognition date
As per discussion with Jacqueline, the recognition date and time for a future effective IA should be the same as the FED. (https://github.com/bcgov/entity/issues/24013#issuecomment-2463315472)
**Before**
[FE_IA_output_before_2.pdf](https://github.com/user-attachments/files/17681813/FE_IA_output_before_2.pdf)
**After**
[FE_IA_output_after_2.pdf](https://github.com/user-attachments/files/17681819/FE_IA_output_after_2.pdf)

24013 - FE Incorporation Application Output Updates

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/models/review_result.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

*Issue #:* /bcgov/entity#24085

24085 alteration BC to ULC fee code

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py

*Issue #:* /bcgov/entity#23872
Put the business name instead of T number
[named.pdf](https://github.com/user-attachments/files/17683051/named.pdf)
[numbered.pdf](https://github.com/user-attachments/files/17683052/numbered.pdf)

23872 receipt outputs hide temp number

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#24321
When trying to reproduce the problem in the TEST env, I found a 503 error in one of the requests and wanted to see the problem by printing more logs.

24321 - Add debug logging info

---

colin-api/src/colin_api/models/shares.py

*Issue #:* /bcgov/entity#24390

24390 colin sync currency mapping for share structure

---

colin-api/src/colin_api/models/corp_party.py

*Issue #:* /bcgov/entity#24395, bcgov/entity#24396, bcgov/entity#24397

24395-24396-24397 party sync fixes

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#24408
- Legal API v2.133.0
- Entity Emailer v2.133.0
- Colin API v2.133.0
- Update Colin Filings Job (no version)

24408 Bump version numbers up for release 23.3b

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#24321
Clean up the help debug log after the investigation

24321 - Clean up the debugging info

---

queue_services/entity-emailer/src/entity_emailer/email_processors/continuation_in_notification.py
queue_services/entity-emailer/src/entity_emailer/worker.py

*Issue #:* /bcgov/entity#24361
- Clean up the debugging logger code after successfully filed a continuation-in in DEV, and got expected emails and attachments.
https://github.com/bcgov/entity/issues/24361#issuecomment-2480136457

24361 - Remove debugging logger code for 24361

---

data-tool/.corps.env.sample
data-tool/Makefile
data-tool/flows/batch_delete_flow.py
data-tool/flows/common/init_utils.py
data-tool/flows/config.py
data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_base_data.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py
data-tool/scripts/colin_corps_extract_postgres_ddl
data-tool/scripts/transfer_cprd_corps.sql

*Issue #:* /bcgov/entity#24051
- add tombstone pipeline (first cut)
- able to load corp snapshot (exclude filings) into db
- move common utils
- update extract scripts
- update makefile
Note that there are lots of TODOs in the code and they will be done in future work.
*local testing*
_This is a testing corp without sensitive info_

24051 Tombstone pipeline (first cut)

---

data-tool/flows/batch_delete_flow.py
data-tool/flows/config.py

*Issue #:* /bcgov/entity#24486
Miscellaneous updates for delete script, including
- to support deleting entity & affiliation via auth api
- to delete lear_tombstone filing
- to delete no versioning records
p.s. we should delete `colin_event_ids`, so keep it unchanged (already support it in previous work)

24486 - Update delete script

---

colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/models/filing.py

*Issue #:* /bcgov/entity#24548

24548 Incorporator should not be ceased

---

data-tool/flows/batch_delete_flow.py
data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_base_data.py
data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#24387
- update tombstone pipeline to
- load plcaholder filings
- load user info (and prevent duplicate user loaded into db)
- only support a few basic event_filing_type mapping now (will re-visit it in the future work)
Note that this is a rough update, is going on hold for a short time until bcgov/entity#24486 complete
*local testing*
_This is a testing corp without sensitive info_

24387 Tombstone pipeline - Load placeholder filings & user info

---

legal-api/src/legal_api/resources/v1/nr_type_map.py

*Issue #:* bcgov/entity#24549
- fixed code typo

24549 Fixed code typo

---

legal-api/flags.json
legal-api/report-templates/template-parts/common/statement.html
legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#24368
- Integrate enable-new-ben-statement feature flag 
- Update logic for displaying the BEN statement in NOAs
- Add default value for ff
Here is the NOA BEN Statement when _enable-new-ben-statement_ is **FALSE**:
and when _enable-new-ben-statement_ is **TRUE**:

24368 - Update BEN Statement in NOA

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py

*Issue #:* /bcgov/entity#24474

24474 bump version up for 23.5a release

---

legal-api/flags.json
legal-api/requirements.txt
queue_services/entity-bn/devops/vaults.json
queue_services/entity-bn/flags.json
queue_services/entity-bn/requirements.txt
queue_services/entity-bn/src/entity_bn/bn_processors/change_of_registration.py
queue_services/entity-bn/src/entity_bn/config.py
queue_services/entity-bn/src/entity_bn/worker.py

*Issue #:* /bcgov/entity#22947
1. Added LaunchDarkly configuration to read feature flags
2. Replaced the code to initialize and use the new db versioning
3. Updated configuration to support feature flags
4. Added flags.json file
5. Updated requirements.txt with necessary dependencies
Testing Done:
**Screenshot:**
_Flag status:_ 
* legal-api on & entity-bn on
_Unit Test:_
* legal-api on & entity-bn off
_Unit Test:_

22947 - Update entity-bn to use the new db versioning

---

legal-api/report-templates/template-parts/common/resolutionDates.html
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/resources/v2/business/colin_sync.py

*Issue #:* /bcgov/entity#24552
- Update the Resolution Section wording in NOA
- Update the Resolution Section wording and resolution date format in Alteration/Correction/Amalgamation/Transition outputs

24552 - Update Resolution Section in Outputs + NOA

---

data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#24481
- fix event filing mappings for all 3 types dissolutions
- populate more info into filing_json & meta_data so that UI is able to load
- misc changes
Note down some issues & pending work in shared workspace, mention them here again
- FED filing vs. non-FED filing
- NoW (may affect some complex filings, state filings)
- SYST events
- display name for each filing
_Testing_
The following businesses are loaded in dev and affiliated to account `3446`, and one business is for one event_filing_type
```
BC0472301
BC0649417
BC0808085
BC0803411
BC0756111
BC0511226
BC0833000
BC0343855
BC0149266
``` …

24481 Tombstone pipeline - Updates to support dissolution

---

jobs/email-reminder/config.py
jobs/email-reminder/email_reminder.py
jobs/email-reminder/flags.json
jobs/email-reminder/requirements.txt
jobs/furnishings/flags.json
legal-api/flags.json
queue_services/entity-bn/flags.json
queue_services/entity-emailer/flags.json

*Issue #:* /bcgov/entity#22953
- Updated requirements to use legal-api from feature branch before merged into main
- Updated requirements to make it compatible with updated legal-api package 
- Updated the job to use new db-versioning
- Updated feature flags values for `email-reminder-job` in other services to `True`
- Updated feature flags values for the components, their update/verification tickets have been moved to done
There is no impact using the new versioning.
- Create 2 identical local databases (e.g. lear-dev-1, lear-dev-2), restored data from a same dump from DEV, one for testing with new versioning, one for testing with the old one
- Run the job using new versioning with local db-1, and old versioning interacting with local db-2
- Track the same …

22953 verify email reminder job new db versioning

---

jobs/involuntary-dissolutions/config.py
jobs/involuntary-dissolutions/flags.json
jobs/involuntary-dissolutions/involuntary_dissolutions.py
jobs/involuntary-dissolutions/requirements.txt
legal-api/flags.json

*Issue #:* /bcgov/entity#22950
- Replaced the code to initialize and use the new db versioning
- Updated configuration to support feature flags
- Added flags.json file
- Updated requirements.txt with necessary dependencies
- Switch the versioning Proxy
*Test:*
1. The Flag is on:
- Proxy Check
- Unit Test
2. The Flag is off:
- Proxy Check
- Unit Test

22950 update dissolution jobs use new db versioning

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#24764
- Bumped version up for 23.5b release

24764 - Bump version up for 23.5b release

---

data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#24483 /bcgov/entity#24484
- update mappings
- alteration, correction, change of address, change of directors, dissolution, legacy other
- update pipeline to support restoration & correction
- populate updated business info as per filing type
- populate more info filing_json and meta_data as per filing
- update error handling
- update TODOs
- update example data in query
*Testing*
More businesses are loaded (old ones are re-loaded using updated script) in dev and affiliated to account `3446`

24483 & 24484 Tombstone pipeline - update restoration, correction, mappings

---

legal-api/flags.json
queue_services/entity-digital-credentials/flags.json
queue_services/entity-digital-credentials/requirements.txt
queue_services/entity-digital-credentials/src/entity_digital_credentials/config.py
queue_services/entity-digital-credentials/src/entity_digital_credentials/worker.py
queue_services/entity-digital-credentials/tests/unit/__init__.py

*Issue #:* /bcgov/entity#22949
- Replaced the code to initialize and use the new db versioning
- Updated configuration to support feature flags
- Added flags.json file
- Updated requirements.txt with necessary dependencies
- Switch the versioning Proxy
Unit Test
**1. Flag is ON:**
**- Proxy Check**
**- Unit Test**
**2. Flag is OFF:**
**- Proxy Check**
**- Unit Test**

22949 update digital credentials to use new versioning

---

legal-api/src/legal_api/reports/report.py
queue_services/entity-filer/src/entity_filer/filing_processors/put_back_on.py
queue_services/entity-filer/src/entity_filer/filing_processors/restoration.py
queue_services/entity-filer/tests/unit/filing_processors/test_put_back_on.py

*Issue #:* /bcgov/entity#24741

24741 cease custodian while filing putbackon

---

queue_services/entity-filer/flags.json
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py

*Issue #:* /bcgov/entity#24831

24831 FF namex api call in filer

---

queue_services/business-pay/flags.json
queue_services/business-pay/src/business_pay/__init__.py
queue_services/business-pay/src/business_pay/config.py
queue_services/business-pay/src/business_pay/resources/pay_filer.py
queue_services/business-pay/src/business_pay/services/__init__.py
queue_services/business-pay/src/business_pay/services/flags.py

*Issue #:* /bcgov/entity#24825
- Update config
- Update to publish Pub/Sub message to filer
- Comment out NATS message publishing to filer
Run [Pub/Sub emulator](https://cloud.google.com/pubsub/docs/emulator), and comment out the `verify_gcp_jwt()`
- Pub/Sub
- Feature Flag

24825 Business-Pay - update to send pub/sub message to filer

---

legal-api/flags.json
legal-api/src/legal_api/core/business.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/namex.py
scripts/sandbox.sql

*Issue #:* /bcgov/entity#24833

24833 sequence for corps and continue in (only available in sandbox now) - api changes

---

legal-api/report-templates/certificateOfRestoration.html

*Issue #:* /bcgov/entity#23405
- Added the new name for the fully restored case in the certificate of restoration template
Before:
After:
Before:
After:

23405 - Added the new name for the fully restored case

---

queue_services/business-pay/src/business_pay/config.py
queue_services/business-pay/src/business_pay/services/flags.py

*Issue #:* /bcgov/entity#24825
- `ENVIRONMENT` exists in config, so remove the duplicate one I added

24825 Config updates

---

queue_services/entity-filer/flags.json
queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_application.py
queue_services/entity-filer/src/entity_filer/filing_processors/continuation_in.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_info.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/name_request.py
queue_services/entity-filer/src/entity_filer/filing_processors/incorporation_filing.py
queue_services/entity-filer/src/entity_filer/filing_processors/registration.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_incorporation_filing.py
queue_services/entity-filer/tests/unit/filing_processors/test_registration.py

*Issue #:* /bcgov/entity#24833

24833 sequence for corps and continue in (only available in sandbox now) - filer change

---

legal-api/src/legal_api/__init__.py
legal-api/src/legal_api/services/filings/validations/common_validations.py

*Issue #:* /bcgov/entity#24917

24917 adding logs for debugging

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#23362
- Add new endpoint to fetch a FED filing given a filing ID

23362 Fetch Endpoint for FED Filings

---

legal-api/src/legal_api/__init__.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/src/legal_api/services/filings/validations/change_of_name.py

*Issue #:* /bcgov/entity#24955

24955 skip namex call for sandbox

---

queue_services/business-pay/src/business_pay/resources/pay_filer.py
queue_services/business-pay/src/business_pay/services/__init__.py

*Issue #:* /bcgov/entity#24826
- Update message format published to filer as per conversations in #3126 

24826 Update business-pay message format

---

queue_services/entity-filer/Makefile
queue_services/entity-filer/filer_service.py
queue_services/entity-filer/flags.json
queue_services/entity-filer/q_cli.py
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/setup.py
queue_services/entity-filer/src/entity_filer/resources/__init__.py
queue_services/entity-filer/src/entity_filer/resources/worker.py
queue_services/entity-filer/src/entity_filer/services/__init__.py
queue_services/entity-filer/src/entity_filer/services/gcp_auth.py
queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#24829
- Updated filer to be a GCP Pub/Sub queue listener
- Structured changes to affect to existing NATS code as minimally as possible in order to make merging into main easier.
- Used the `enable-sandbox` FF where necessary.
- Confirmed NATS and GCP queue listeners both work.
- Used involuntary dissolution DRAFT filings since they were easy to create a lot of using the dissolutions job.
- Ran [Pub/Sub emulator](https://cloud.google.com/pubsub/docs/emulator), and commented out the `verify_gcp_jwt()` block in the worker.
**Summary of below tests** 
**NATS Queue (FF off)**
- Processed using `python q_cli.py -f 152417`
**GCP Queue (FF on) - unwrapped payload**
- In `resources/worker`, changed `get_simple_cloud_event` parameter …

24829 Filer - Update to GCP Pub/Sub queue listener

---

queue_services/entity-filer/src/entity_filer/config.py
queue_services/entity-filer/src/entity_filer/worker.py

- Updates for sandbox deployement

24830 - Updates for filer sandbox deployement

---

queue_services/entity-filer/src/entity_filer/config.py

24830-2 Add configs for GCP JWT verification

---

queue_services/entity-filer/src/entity_filer/config.py

- Used wrong format for pg8000 in previous updates. Correct it in this pr.

24830-3 Update psycopg2 connection format

---

queue_services/entity-filer/requirements.txt

- Use legal-api of `feature-sandbox` branch as dependency 
(Hope it's the last tweak to make filer run...)

24830-4 Update filer dependency for sandbox

---

queue_services/business-pay/src/business_pay/services/flags.py

*Issue #:* /bcgov/entity#24828
- Fix an issue found during testing

24828 - fix flags service of business-pay sandbox

---

queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_registration.py
queue_services/entity-filer/tests/unit/test_worker/test_incorporation.py

*Issue #:* /bcgov/entity#25000
* Update create affiliation call to append `Environment-Override` header when in sandbox.  Note that get affiliation auth call is not used in LEAR code except for involuntary dissolutions filter.  This filter is dev/test specific functionality that is feature flagged so get affiliation call will never be called in sandbox or production
* Updates to never create/update contact info in sandbox
* Update to skip auth calls for filings that don't create a new business
* Update broken tests
Tested locally to check header appended for create affiliation call when IA is submitted and `enable_sandbox` FF is on.
```
POST {{filer-base-url}}
Content-Type: application/json
{
"message": {
"data": …
```

25000 Update affiliation related logic for sandbox

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

* firms are not creating an invoice properly so adding debug logging to see what payload is being passed to pay api and what pay api is returning

Add debug logging for create invoice call

---

queue_services/entity-filer/src/entity_filer/resources/worker.py

* Add traceback logging to debug registration filer issue in sandbox

Add debug traceback logging to filer

---

legal-api/src/legal_api/services/bootstrap.py

*Issue #:* /bcgov/entity#25065
- Update registrer_bootstrap code
Testing
- FF on
- FF off

25065 Update register_bootstrap to use sandbox FF

---

scripts/sandbox.sql

*Issue #:* /bcgov/entity#25058
* Update firm and coop sequences to start at 3000000 so it doesn't collide with prod businesses in auth db

25058 Update firm and coop business identifier sequence start for sandbox env

---

colin-api/src/colin_api/models/filing.py

*Issue #:* /bcgov/entity#24708

24708 inserting to event_insert table for ORGBOOK sync

---

queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py

*Issue #:* /bcgov/entity#25023

25023-2 Add traceback logging

---

legal-api/report-templates/correction.html
legal-api/report-templates/template-parts/common/style.html
legal-api/src/legal_api/version.py

*Issue #:* [/bcgov/entity/24946](https://github.com/bcgov/entity/issues/24946)
Show Details of Correction change on Register Correction Application pdf

Correction Details Added on Register Correction Application pdf

---

colin-api/src/colin_api/models/filing.py

*Issue #:* /bcgov/entity#25084

25084 Sync local correction to COLIN

---

data-tool/flows/batch_delete_flow.py
data-tool/flows/common/corp_processing_queue_service.py
data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_base_data.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py
data-tool/scripts/colin_corps_extract_postgres_ddl
data-tool/scripts/transfer_cprd_corps.sql
legal-api/src/legal_api/models/amalgamating_business.py
legal-api/src/legal_api/models/amalgamation.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#24479
- COLIN extract script updates
- Delete script updates
- Amalgamation support (❗❗❗Need discussion for the priorities of TED & TING loading)
- Legal-API adjustments for tombstone business (❗Need followups for summary output)
- Other misc changes
_Testing_
The following businesses are loaded in dev and affiliated to account 3446. Some current legal-api calls fail in dev. Have verified that the failed calls are able to go through using the updated legal-api in this pr. Will test it again once it's merged.
```
TED BC0812196 - TING BC0593394, 2Xpros
TED BC0870100 - TING BC0805986, BC0561086
TED BC0747392 - TING BC0543231, BC0358476
```
❗❗ Note that I also find some ~~bugs~~(fixed) and TODOs for the flow, but they are not related to this …

24479 - Tombstone pipeline - amalgamation & legal-api adjustment

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#25180
bumped version numbers up for release 24.1

bumped version numbers up for release 24.1

---

data-tool/flows/batch_delete_flow.py
data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#25252
- add subqueries to select TING, TED and others (manual approach)
- fix some data mapping for amalgamation
- raise exception if TED is migrated before its corp TINGs
- fix delete scripit

25252 - Manual approach to populate TING info

---

jobs/email-reminder/email_reminder.py

Update email-reminder job to use `enable-bc-ccc-ulc-email-reminder`

email reminder flag update

---

colin-api/devops/vaults.json
colin-api/src/colin_api/config.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/filing.py
colin-api/src/colin_api/services/account.py
colin-api/src/colin_api/services/legal.py
jobs/email-reminder/email_reminder.py

*Issue #:* /bcgov/entity#25446
Merging release-2.136.0 hotfix updates to main

Hotfix updates

---

legal-api/src/legal_api/services/filings/validations/notice_of_withdrawal.py
legal-api/tests/unit/services/filings/validations/test_notice_of_withdrawal.py

*Issue #:* /bcgov/entity#25412 
- Add validation for hasTakenEffect and partOfPoa
- Update/Add unit tests
hasTakenEffect and partOfPoa = True:

25412 - Update NoW Validation with hasTakenEffect and partOfPoa Properties

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#25345
Bumped up version for 24.2 (Version#2.137.0)

bump up version for 24.2

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#25405
https://dev.business-dashboard.bcregistry.gov.bc.ca/BC0871549

25405 fix_entity_description_filing_outputs

---

data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#24594
- Implemented conversion ledger in tombstone pipeline
_Testing:_
The following businesses are loaded in dev and affiliated to account 668.
```
BC0010385
BC0019921
```

24594 Tombstone pipeline - Implement conversion ledger

---

legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#25583 
- Add case for NoW when in COMPLETED status 
- Update unit test

25583 - Return Documents for NoW when Status is COMPLETED

---

queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/src/entity_emailer/email_processors/notice_of_withdrawal_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/NOW-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/style.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_notice_of_withdrawal_notification.py
queue_services/entity-emailer/tests/unit/test_tracker.py

*Issue #:* /bcgov/entity#23351
- Add NoW emailer
- Update tracker code for NoW
- Add NoW emailer unit tests
- Update tracker unit tests for NoW
**Setup**: Local Emailer, Local db, DEV report-API --> get emails in MailHog
**1.1 Email subject & 2 Attachments:**
**1.2 Email:**
**2.1 Email subject & 2 Attachments:**
**2.2 Email:**
**3.1 Email subject & 2 Attachments:**
**3.2 Email:**
**4.1 Email subject & 2 Attachments:**
**4.2 Email:**

23351 - Notice of Withdrawal Emailer

---

queue_services/business-pay/src/business_pay/resources/pay_filer.py

*Issue #:* /bcgov/entity#25500
* Add new corp type code "BUS"

25500 - Investigate delay issue

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#25783 
- Add condition for NoW filing 
- Add unit test

25783 - Add NoW case to Delete Filings Endpoint

---

jobs/correction-ben-statement/add_corrections.ipynb

*Issue #:* /bcgov/entity#25660
- Update date format in the statement for corrections filed with Jupyter Notebook
- fix text alignment as UI now allows line breaks

25660 - updates for date and statement

---

queue_services/entity-filer/src/entity_filer/filing_processors/notice_of_withdrawal.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_notice_of_withdrawal.py

23352 notice_of_withdrawal_filer

---

queue_services/entity-filer/src/entity_filer/filing_processors/notice_of_withdrawal.py
queue_services/entity-filer/tests/unit/filing_processors/test_notice_of_withdrawal.py

23352 fix_now_filer_meta_issue

---

legal-api/src/legal_api/models/filing.py
queue_services/entity-filer/tests/unit/filing_processors/test_notice_of_withdrawal.py

23352 update_filing_status_listen

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/filing_processors/notice_of_withdrawal.py
queue_services/entity-filer/src/entity_filer/version.py

23352 fix_withdawn_date_value

---

queue_services/entity-filer/src/entity_filer/worker.py

23352 fix_get_business_type

---

queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/test_worker/test_notice_of_withdrawal.py
queue_services/entity-filer/tests/unit/test_worker/test_worker.py

23352 update now filer email trigger

---

legal-api/src/legal_api/version.py

*Issue #:* bcgov/entity#25763
- updated version to 2.141.0

25763 Update version.py

---

queue_services/entity-filer/src/entity_filer/filing_processors/put_back_off.py
queue_services/entity-filer/tests/unit/filing_processors/test_put_back_off.py

*Issue #:* /bcgov/entity#25473
- Add reason and expiry date to filing_meta
- Update unit test

25473 - Add Short Reason for Limited Restoration Expiry

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#25897

25897 fix document download when filing is in PAID status

---

legal-api/report-templates/template-parts/amalgamation/amalgamationStmt.html

*Issue #:* /bcgov/entity#23979
- With/Without court approval

23979 - Update Amalgamation Output Wording

---

data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_base_data.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#24699 /bcgov/entity#24700
- Updates for `filing_date`, `completion_date`, `effective_date`
- Implement Notice of Withdrawal
~~- Need discussion for different COLIN/LEAR behaviours of withdrawn IA, amalgamation❗~~ DONE
_Testing_
```python
BC0920360 # lots of FED CoA + 2 FED alteration
BC1489667 # FED followed by NoW
```

24699 & 24700 Tombstone - distinguish FED and non-FED, implement Notice of Withdrawal

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#25975
- Add missing logic for submitter name in embedded NoW filing
Public view:
Staff view:

25975 - Fix Submitter Name for Embedded NoW Filing

---

data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py
data-tool/scripts/README_COLIN_Corps_Extract.md
data-tool/scripts/colin_corps_extract_postgres_ddl
data-tool/scripts/transfer_cprd_corps.sql

*Issue #:* /bcgov/entity#25797
- new data dump is available in GCP `pg_colin_mig_corps_prod_local_dump_20250220.zip`

25797 Tombstone pipeline include last_ar_reminder_year

---

queue_services/entity-emailer/src/entity_emailer/email_processors/notice_of_withdrawal_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/NOW-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/email_processors/test_notice_of_withdrawal_notification.py

*Issue #:* /bcgov/entity#25843
- Update label wordings
- Remove ‘Date and Time of Filing’ label and value
- Show company name for temp business as well
- Show company name in email subject for temp business as well

25843 - Update NoW email template

---

data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_utils.py
data-tool/scripts/colin_corps_extract_postgres_ddl

*Issue #:* /bcgov/entity#26013
* Add indexes to source db ddl to speed up migration
* Add workpool deployment configs to be used for true parallel flow runs.  Different workpool per major scenario(TINGs, TEDS, all other corps)
* Add concurrent task runner config for workpool based runs
* Fixed single quote error encountered when building filing meta data json

26013 tweaks from prelim corps dry run

---

jobs/email-reminder/requirements.txt
jobs/email-reminder/requirements/bcregistry-libraries.txt
jobs/furnishings/requirements.txt
jobs/furnishings/requirements/bcregistry-libraries.txt
jobs/involuntary-dissolutions/requirements.txt
jobs/involuntary-dissolutions/requirements/bcregistry-libraries.txt
jobs/update-legal-filings/requirements.txt
jobs/update-legal-filings/requirements/bcregistry-libraries.txt
legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
queue_services/entity-bn/requirements.txt
queue_services/entity-bn/requirements/bcregistry-libraries.txt
queue_services/entity-digital-credentials/requirements.txt
queue_services/entity-digital-credentials/requirements/bcregistry-libraries.txt
queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt

*Issue #:* /bcgov/entity#22998
- Point requirements back to main

22998 Point requirements back to main

---

legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/utils/legislation_datetime.py

*Issue #:* /bcgov/entity#25472
- Add putBackOff to stateFilings
- Update Company Status
- Change expiry time on existing Limited Restoration entry and Limited Restoration Application output to "11:59 pm Pacific time"

25472 - Update Outputs for Expired Limited Restoration

---

queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-APPROVED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-REJECTED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/continuation-application-details.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/cra-notice.html

*Issue #:* /bcgov/entity#24254
- remove extra border lines
- update text

24254 - continuation in email fixes

---

legal-api/src/legal_api/version.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-digital-credentials/src/entity_digital_credentials/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#22998
- Legal API v2.142.0
- entity-bn v2.142.0
- entity-digital-credentials v2.142.0
- entity-emailer v2.142.0
- entity-filer v2.142.0

22998 Bump versions to 2.142.0

---

legal-api/report-templates/template-parts/amalgamation/amalgamationStmt.html
legal-api/report-templates/template-parts/business-summary/stateTransition.html
legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/src/legal_api/utils/legislation_datetime.py
legal-api/src/legal_api/version.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
queue_services/entity-emailer/requirements.txt
queue_services/entity-emailer/src/entity_emailer/email_processors/notice_of_withdrawal_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-APPROVED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-PAID.html
queue_services/entity-emailer/src/entity_emailer/email_templates/CONT-IN-REJECTED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/NOW-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/continuation-application-details.html
queue_services/entity-emailer/src/entity_emailer/email_templates/common/cra-notice.html
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-emailer/tests/unit/email_processors/test_notice_of_withdrawal_notification.py
queue_services/entity-filer/src/entity_filer/filing_processors/put_back_off.py
queue_services/entity-filer/src/entity_filer/version.py
queue_services/entity-filer/tests/unit/filing_processors/test_put_back_off.py

*Issue #:* /bcgov/entity#26151
- Rebase `release-2.141.0` branch to main and merge the changes
- Bump up version to 2.143.0 for `legal-api`, `entity-emailer`, `entity-filer`

26151 - Rebase release branch and merge into main

---

data-tool/flows/common/auth_service.py
data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py
queue_services/entity-filer/tests/unit/filing_processors/filing_components/test_business_profile.py

*Issue #:* /bcgov/entity#25904

25904 Tombstone pipeline - push contact email to auth

---

legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/models/filing.py

*Issue #:* /bcgov/entity#26140 
- Add NOALU code for C to CUL Alteration

26140 - Add Alteration Code for C to CUL

---

python/common/sql-versioning/sql_versioning/__init__.py

*Issue #:* /bcgov/entity#23001 
- remove already deleted debugging decorator import

23001 - remove deleted debugging decorator import

---

.github/workflows/legal-api-cd.yml

*Issue #:* bcgov/entity#26205
- added CLI tool step

26205 Added missing (new) step

---

.github/workflows/business-pay-ocp-cd.yml
.github/workflows/colin-api-cd.yml
.github/workflows/data-reset-tool-cd.yml
.github/workflows/email-reminder-cd.yml
.github/workflows/entity-bn-cd.yml
.github/workflows/entity-digital-credentials-cd.yml
.github/workflows/entity-emailer-cd.yml
.github/workflows/entity-filer-cd.yml
.github/workflows/entity-pay-cd.yml
.github/workflows/expired-limited-restoration-cd.yml
.github/workflows/filings-notebook-report-cd.yml
.github/workflows/furnishings-cd.yml
.github/workflows/future-effective-filings-cd.yml
.github/workflows/involuntary-dissolutions-cd.yml
.github/workflows/sftp-icbc-report-cd.yml
.github/workflows/sftp-nuans-report-cd.yml
.github/workflows/update-colin-filings-cd.yml
.github/workflows/update-legal-filings-cd.yml

*Issue #:* bcgov/entity#26205
See https://github.com/bcgov/lear/pull/3265 for changes to Legal API CD only.
- added CLI tool steps

26205 Added missing (new) steps (rest of CD scripts)

---

data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_queries.py

*Issue #:* /bcgov/entity#26144
Getting duplicate row due to multiple entries in the `left join with corp_name`
In the failed 2964 businesses 

26144 Tombstone pipeline - duplicate row in filing query

---

.github/workflows/legal-api-ci.yml

- changed to use Ubuntu 22.04 in order to retain build compatibility with requirements

26204 changed to use Ubuntu 22.04

---

.github/workflows/legal-api-ci.yml

26204 added missing Python version

---

.github/workflows/legal-api-ci.yml

*Description:*
- revert to Ubuntu 24.04
- just run unit tests with Python 3.8

26204 Trying Ubuntu 24.04 again

---

.github/workflows/colin-api-ci.yml
.github/workflows/data-reset-tool-ci.yml
.github/workflows/email-reminder-ci.yml
.github/workflows/entity-bn-ci.yml
.github/workflows/entity-digital-credentials-ci.yml
.github/workflows/entity-emailer-ci.yml
.github/workflows/entity-filer-ci.yml
.github/workflows/entity-pay-ci.yml
.github/workflows/expired-limited-restoration-ci.yml
.github/workflows/filings-notebook-report-ci.yml
.github/workflows/furnishings-ci.yml
.github/workflows/future-effective-filings-ci.yml
.github/workflows/involuntary-dissolutions-ci.yml
.github/workflows/legal-api-ci.yml
.github/workflows/sftp-icbc-report-ci.yml
.github/workflows/sftp-nuans-report-ci.yml
.github/workflows/update-colin-filings-ci.yml
.github/workflows/update-legal-filings-ci.yml

- changed remaining setup-python to v5
- added missing strategy.matrix.python-version

26204 fixed remaining CI scripts

---

data-tool/flows/batch_delete_flow.py
data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_base_data.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py
data-tool/requirements.txt
data-tool/requirements/prefect.txt
data-tool/scripts/colin_corps_extract_postgres_ddl
legal-api/migrations/versions/b0937b915e6b_add_offices_held_table.py

*Issue #:* /bcgov/entity#25707
* Updated pipeline to support bringing officers data over
* Added alembic script to support officer data(`offices_held`, `offices_held_version`)
* Misc perf related updates
* Update delete flow to delete data from officer tables
* Added some initial experimentation pieces for DaskTaskRunner to test increasing throughput.  please ignore for now
**Note: was going to load some data into dev but can't because new tables need to be created first in dev db**

25707 Update tombstone pipeline to support bringing over officers + misc updates

---

data-tool/flows/tombstone/tombstone_base_data.py
data-tool/flows/tombstone/tombstone_utils.py
legal-api/migrations/versions/24b59f535ec3_add_currency_additional_to_share_classes.py
legal-api/migrations/versions/f1d010259785_modify_data_type_for_max_shares.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/models/share_class.py
legal-api/src/legal_api/models/share_series.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/services/business_details_version.py

*Issue #:* /bcgov/entity#26189
- Fix the following issues
- `psycopg2.errors.NumericValueOutOfRange) integer out of range`
- `psycopg2.errors.StringDataRightTruncation) value too long for type character varying(10)`
- `(sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter ...`
- `psycopg2.errors.NotNullViolation) null value in column "country" of relation "jurisdictions"`
- Misc updates to support tombstone corp loading in modernized system

26189 Fix misc issue from tombstone prelim dry run & misc updates

---

legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/filings/validations/amalgamation_application.py
legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py

*Issue #:* /bcgov/entity#26146

26146 - Allow Amalgamations with C Business as Primary or Holding

---

legal-api/report-templates/template-parts/notice-of-withdrawal/recordToBeWithdrawn.html

*Issue #:* /bcgov/entity#26248
- Update language on the NoW Outputs: Instead of "Record to be Withdrawn", display "Withdrawn Record"

26248 - Update NoW Output language

---

legal-api/src/legal_api/models/db.py
legal-api/src/legal_api/services/bootstrap.py

*Issue #:* /bcgov/entity#25831
- Removed debug decorator imports to resolve conflicts with main branch
- Updated AccountService to handle sandbox environment

25831 - Fix amalgamation affiliation error

---

legal-api/src/legal_api/services/bootstrap.py

*Issue #:* /bcgov/entity#25831
remove the previously added debug loggings

25831 - remove debug loggings

---

data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#26350
- Implement administer corp event
_Testing_
```python
BC1069185 # ADCORP
BC0718478 # ADCORP
BC1296963 # ADMIN
BC1186684 # ADFIRM
```
_Notes_
FYI, I got some auth issue when I re-migrate the same businesses, so I have to comment the codes out to make the re-migration happen

26350 Tombstone - implement administer corp event/filing

---

legal-api/requirements.txt
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/appoint_receiver.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_appoint_receiver.py

*Issue #:* /bcgov/entity#26331
Implement appoint receiver filing processor

26331 - Appoint receiver filing processor

---

data-tool/flows/corps_tombstone_flow.py

*Issue #:* /bcgov/entity#26359
- Fail the flow to indicate errors exist if
- User migration fails
- Collecting corp data fails
- Corp migration fails
- Some tweaks related to user migration error to mark corps FAILED
Note that the failed flow is not equal to all corp migrations fail in this flow.
_Testing_
Migrate several corps, and one corp fails. The flow is marked as FAILED.

26359 - Fail the flow if one of the migration tasks fails

---

legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#25778
bumped up version numbers for release 24.5

bumped up version numbers for release 24.5

---

data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py
queue_services/business-pay/src/business_pay/resources/pay_filer.py
queue_services/entity-filer/src/entity_filer/filing_processors/continuation_out.py
queue_services/entity-filer/tests/unit/filing_processors/test_continuation_out.py

*Issue #:* /bcgov/entity#25801
- Created a separate ticket to handle consent continuation out bcgov/entity#26421

25801 Tombstone pipeline - continuation out

---

data-tool/flows/config.py
data-tool/flows/corps_tombstone_flow.py

*Issue #:* /bcgov/entity#26444

26444 Tombstone pipeline - update to support custom contact email

---

data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py
queue_services/business-pay/src/business_pay/resources/pay_filer.py

*Issue #:* /bcgov/entity#26409

26409 Tombstone pipeline - timestamp with timezone

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py

*Issue #:* /bcgov/entity#25833
- Skip email notification in sandbox environment to avoid NATS connection errors
- Add logging for skipped email notifications in sandbox

25833 - Skip email notification in sandbox

---

queue_services/entity-filer/src/entity_filer/filing_processors/consent_continuation_out.py
queue_services/entity-filer/tests/unit/test_worker/test_consent_continuation_out.py

*Issue #:* /bcgov/entity#26511

26511 add consent_type to cco

---

legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#26487
- Fix the failed unit test in test_business.py

Fix 26487 - Fix Unit Test of Amalgamation Out

---

data-tool/.corps.env.sample
data-tool/Makefile
data-tool/flows/config.py
data-tool/flows/corps_verify_flow.py

*Issue #:* /bcgov/entity#26403
- Create a script to verify businesses in extract are also in target db
- Curently only do basic verification based on identifiers in this work, more will be done in future work

26403 - Create verify script for tombstone migration

---

data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#26511

26511 Tombstone pipeline - consent, amalgamation out

---

data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#26511

26511 Tombstone pipeline - skip no filing event filing types

---

legal-api/src/legal_api/services/bootstrap.py
legal-api/src/legal_api/services/filings/validations/amalgamation_out.py
legal-api/src/legal_api/services/filings/validations/validation.py
legal-api/tests/unit/services/filings/validations/test_amalgamation_out.py

*Issue #:* /bcgov/entity#26654
- implement validation for this filing as per the filing data stored (can refer to the updated schema)
- add/update tests

26654 - Validation Amalgamation Out Filing

---

colin-api/src/colin_api/errorhandlers.py
colin-api/src/colin_api/utils/util.py
colin-api/tests/unit/utils/test_util_cors.py

*Issue #:* /bcgov/entity#26665

26665 add app_name to allowalbe_header at colin api

---

colin-api/src/colin_api/version.py

*Issue #:* bcgov/entity#25777
- updated version to 2.145.0

25777 Update version.py

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* bcgov/entity#25777
- merge version update PRs from main branch to this release branch (because I created the release branch before the PRs); this will only be used for the GitHub release notes and possible future hotfixes

25777 Merge 4 PRs from main to this release branch

---

docs/business.yaml

Changed the Sandbox & Prod DNS names

Update business.yaml for new DNS names

---

queue_services/entity-bn/q_cli.py
queue_services/entity-bn/src/entity_bn/version.py
queue_services/entity-filer/q_cli.py

*Issue #:* /bcgov/entity#25777

25777 q_cli fix

---

queue_services/entity-filer/src/entity_filer/filing_processors/amalgamation_out.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py
queue_services/entity-filer/src/entity_filer/worker.py
queue_services/entity-filer/tests/unit/filing_processors/test_amalgamation_out.py

*Issue #:* /bcgov/entity#26688
- add Amalgamation Out filing processor
- add/update tests

26688 - Amalgamation Out Filer

---

data-tool/flows/tombstone/tombstone_mappings.py

*Issue #:* /bcgov/entity#26656
- Implement Amend AR
_Testing_
The following businesses are loaded in dev and affiliated to account `3446`
```
BC0556246
BC1279941
```

Tombstone - implement Amend AR

---

python/common/business-registry-model/poetry.lock
python/common/business-registry-model/pyproject.toml

*Issue #:* /bcgov/entity#26303
part 2
updating the pyproject.toml to use the sql-versioning-alt in this repo

chore(business-registry-model): update pyproject.toml to use the sql-versioning-alt in this repo

---

queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#26633
- Fix duplicate versioned record issue (applied to both lear corp & migrated corp)
_Local Testing After Fix_

26633 DB Versioning - fix duplicate versioned records for CoD/AR etc.

---

data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py
legal-api/src/legal_api/models/business.py
legal-api/tests/unit/resources/v1/test_business_tasks.py
legal-api/tests/unit/resources/v2/test_business_tasks.py
legal-api/tests/unit/services/filings/validations/annual_report/test_validate_ar_year.py

*Issue #:* /bcgov/entity#26611

26611 fix ar min/max date calculation

---

data-tool/flows/corps_tombstone_flow.py
legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/resources/v2/business/colin_sync.py
legal-api/src/legal_api/services/business_details_version.py

*Issue #:* /bcgov/entity#26570, /bcgov/entity#26720, /bcgov/entity#26685
* Update to get director & office related data displaying properly on NoA outputs
**Outputs after fix**
26570 NOA for CoD
26720 NOA for CoD
26685 NOA for Alteration

26570, 26720, 26685 Update business_details_version.py to return appropriate data for tombstone corps for offices and parties data

---

data-tool/flows/tombstone/tombstone_utils.py
legal-api/src/legal_api/services/filings/validations/common_validations.py

*Issue #:* /bcgov/entity#26692

26692 Tombstone pipeline - Share name must end with ' Shares'

---

docs/business.yaml

*Issue #:* /bcgov/entity#26566
Updates:
* Amalgamtion (Regular, Horizontal, Vertical)
* AGM Extension
* AGM Location change
* Alteration

26566 - Update api spec to sync with the latest Postman collection

---

docs/business.yaml

*Issue #:* /bcgov/entity#26621 
updating examples in API specs
- IA
- Cont. in
- AR
- CoD
- Consent to Cont. out
- Voluntary dissolution

26621 - sync api specs with postman collection

---

queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#26867 & /bcgov/entity#26726

26867 & 26726 Fix filer to update contact info

---

data-tool/flows/tombstone/tombstone_queries.py

*Issue #:* /bcgov/entity#26888

26888 Tombstone Fix - strip spaces for empty middle name

---

python/common/business-registry-model/pyproject.toml

Fixes an error when importing this into other places

Common model - toml tweak to fix import issue

---

legal-api/src/legal_api/models/party_role.py
legal-api/src/legal_api/services/business_details_version.py
legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#26893

26893-2 Legal API - filter out officer

---

queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt
queue_services/entity-filer/src/entity_filer/filing_processors/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/tests/unit/test_worker/test_correction_bcia.py

*Issue #:* /bcgov/entity#26706
Add commentOnly in filing_meta and skip all other updates

26706 - comment only corrections

---

legal-api/src/legal_api/models/party_role.py
legal-api/src/legal_api/services/business_details_version.py
legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#26893

Cut Hotfix branch to hide officers

---

legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/resources/v2/business/colin_sync.py
legal-api/src/legal_api/services/business_details_version.py

*Issue #:* /bcgov/entity#26943

26943 Update get_party_revision to return fallback data for tombstone corps

---

legal-api/src/legal_api/services/business_details_version.py

*Issue #:* /bcgov/entity#26979
- Exclude ceased tombstone director in NOA
- Before
- After

26979 Legal API - Remove ceased director info for migrated corps in NOA

---

colin-api/src/colin_api/models/filing.py

*Issue #:* /bcgov/entity#26830
Sync dissolution outputs
DEV:

26830 - Sync dissolution outputs

---

legal-api/src/legal_api/services/business_details_version.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#26979

Merge hotfix 2.145.0b back to main

---

data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#26663 /bcgov/entity#26664
- Implement appoint receiver
- Implement cease receiver
Note that the scenarios for ceased parties will be considered in another work
_Testing_
The following businesses are loaded in dev and affiliated to account `3446`
```python
BC1172545 # appoint & cease, receiver is person
BC1270858 # appoint, receiver is person
BC1323680 # appoint, receiver is organization
```

26663 & 26664 tombstone - implement appoint receiver & cease receiver

---

data-tool/flows/tombstone/tombstone_utils.py
legal-api/src/legal_api/core/filing.py
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/business_document.py
legal-api/src/legal_api/reports/report.py
legal-api/src/legal_api/resources/v2/business/colin_sync.py
legal-api/src/legal_api/services/business_details_version.py
legal-api/tests/unit/reports/test_report.py

*Issue #:* /bcgov/entity#27054 

27054 Update get_business_revision to return fallback data for tombstone corps

---

legal-api/report-templates/letterOfConsentAmalgamationOut.html
legal-api/src/legal_api/core/meta/filing.py
legal-api/src/legal_api/reports/report.py
queue_services/entity-emailer/src/entity_emailer/email_processors/consent_amalgamation_out_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/CAO-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/message_tracker/tracker.py
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-emailer/tests/unit/__init__.py
queue_services/entity-emailer/tests/unit/email_processors/test_consent_amalgamation_out_notification.py
queue_services/entity-emailer/tests/unit/test_tracker.py

*Issue #:* /bcgov/entity#27072
- send email
- display attributes
- attachments: Receipt, Filing Output (not designed yet, created an empty file), Letter of Consent (updated)
- Update Letter of Consent

27072 - Consent to Amalgamation Out Emailer

---

legal-api/src/legal_api/models/filing.py
legal-api/src/legal_api/services/business_details_version.py

*Issue #:* /bcgov/entity#27112 

27112 Remove fallback code to support tombstone data

---

data-tool/flows/corps_tombstone_flow.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#27111
- Add versioned record for tombstone, linking to transaction_id of tombstone filing and operation_type = 0
_Testing_
Loading the following corps to cover as many scenario as possibe in dev so that everyone can check the versioned records.
```python
C1533475 # continuation in
BC0047143 # comment (no version)
BC0435126 # TING
BC0292517 # TING
BC0690750 # TED
BC0087844 # share series
```

27111 Tombstone - populate versioned records for tombstone

---

docs/business.yaml

*Issue #:* /bcgov/entity#26882
Sync API specs with developer site style

26882 - update api spec with developer site style

---

data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#27113
- Notice that a new version is created without any change (only for upper case change)
Before: ![image](https://github.com/user-attachments/assets/385bb786-f84f-4d4b-9ef3-0c84cdbf3e60)
After (same in version table): ![image](https://github.com/user-attachments/assets/b0ebcb6d-a327-441d-92bd-7fcf6ffc1ccb)
- ref: https://github.com/bcgov/lear/blob/main/queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/__init__.py#L107

27113 align with entity-filer code

---

.github/workflows/common-business-model-ci.yml
python/common/business-registry-model/poetry.lock
python/common/business-registry-model/pyproject.toml
python/common/business-registry-model/src/business_model/models/business.py
python/common/business-registry-model/src/business_model/models/dc_definition.py
python/common/business-registry-model/tests/conftest.py
python/common/business-registry-model/tests/models/test_business.py
python/common/business-registry-model/tests/models/test_filing.py
python/common/business-registry-model/tests/models/test_naics_structure.py

Fix business.json

---

queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/business_profile.py
queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#27189
remove business profile updating check for sandbox

27189 - remove business profile updating check for sandbox

---

legal-api/src/legal_api/reports/registrar_meta.py

*Issue #:* /bcgov/entity#27215
- Change Sinead's start date to April 10 temporarily for testing

27215 - Override Registrar Signature Start Date for Testing

---

jobs/expired-limited-restoration/file_expired_limited_restoration.py
legal-api/src/legal_api/models/business.py
legal-api/src/legal_api/resources/v2/internal_services.py
legal-api/tests/unit/resources/v2/test_internal_services.py

*Issue #:* /bcgov/entity#25840
**Issue**: Businesses were not being synced back to COLIN as Historical after an expired limited restoration job run was complete.
Syncing was failing because legal type was not being set in filing json and Update Colin filings jobs expects it
Ref: https://github.com/bcgov/lear/blob/main/jobs/update-colin-filings/update_colin_filings.py#L80

25840 - update Legal API endpoint and  Expired limited Restoration job to add legal type

---

queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py

*Issue #:* /bcgov/entity#27201
- Create party address in correction if it's missing in db
Testing
- Before
- After 

27201 - Filer - add missing address for parties in correction

---

legal-api/report-templates/template-parts/common/businessDetails.html
legal-api/report-templates/transitionApplication.html

*Issue #:* /bcgov/entity#26661
Template updates from UX review
[Transition Application.pdf](https://github.com/user-attachments/files/19782794/Transition.Application.pdf)
[Transition NOA.pdf](https://github.com/user-attachments/files/19782795/Transition.NOA.pdf)

26661 - Transition filing output template updates

---

colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/filing.py

*Issue #:* /bcgov/entity#27237
DEV:

27237 - sync consent amalgamation out

---

jobs/correction-ben-statement/add_corrections.ipynb
queue_services/entity-emailer/src/entity_emailer/email_processors/correction_notification.py
queue_services/entity-emailer/src/entity_emailer/email_templates/BC-CRCTN-COMPLETED.html
queue_services/entity-emailer/src/entity_emailer/email_templates/BC-CRCTN-PAID.html
queue_services/entity-emailer/src/entity_emailer/worker.py
queue_services/entity-filer/src/entity_filer/worker.py

*Issue #:* /bcgov/entity#27268
Removed NOA text from email:

27268 - Remove NOA text from email templates

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#27308
- update version.py (several services)

27308 Entities Release 25.1

---

gcp-jobs/entity-bn/src/entity-bn/entity-bn.py

*Issue #:* /bcgov/entity#26590
Fixed how the path is computed for the python notebook

26590 Updated entity-bn to work in gcp (path needed updating)

---

gcp-jobs/email-reminder/src/email_reminder/config.py
gcp-jobs/update-legal-filings/Makefile
gcp-jobs/update-legal-filings/src/update_legal_filings/config.py
gcp-jobs/update-legal-filings/src/update_legal_filings/worker.py
queue_services/business-emailer/src/business_emailer/config.py

*Issue #:* [/bcgov/entity#26590](https://github.com/bcgov/entity/issues/26590)
- config updates for gcp db connection string and match env to 1pass values

GCP migration tweaks

---

gcp-jobs/future-effective-filings/src/future_effective_filings/file_future_effective.py

*Issue #:* /bcgov/entity#26242
change message format to match what Filer is expecting 
Business-Pay sandbox is using: https://github.com/bcgov/lear/blob/main/queue_services/business-pay/src/business_pay/services/__init__.py#L54
Filer GCP sandbox is expecting: https://github.com/bcgov/lear/blob/main/queue_services/business-filer/src/business_filer/common/filing_message.py#L51-L53

26242 - change message format to match what Filer is expecting

---

python/common/business-registry-common/src/business_common/core/__init__.py

*Issue #:* https://github.com/bcgov/entity/issues/26590

GCP migration fix business common

---

python/common/business-registry-common/src/business_common/__init__.py
python/common/business-registry-common/src/business_common/utils/__init__.py

*Issue #:* https://github.com/bcgov/entity/issues/26590

GCP migration - fix business common imports

---

legal-api/flags.json
legal-api/src/legal_api/resources/v2/business/business.py
legal-api/tests/unit/resources/v2/test_business.py

*Issue #:* /bcgov/entity#27121
- Cherry picked Patrick's PR to merge into sandbox

27121 Sandbox - Add auth check for legal-api business endpoint v2 (cherry-picked from main)

---

data-tool/flows/tombstone/tombstone_mappings.py

*Issue #:* /bcgov/entity#27269
- Implemented location DCR.
- All relevant party types and office types already implemented in previous PRs (once #3426 is merged)
_Testing_
The following businesses are loaded in dev.
```python
'BC0580328',
'BC0428029',
'BC0426376',
'BC0502634',
'BC0654830'
```

27269 Tombstone - Implement location DCR (liquidation)

---

data-tool/flows/tombstone/tombstone_mappings.py

*Issue #:* /bcgov/entity#27278 /bcgov/entity#27279
- implement amend liquidator, correct liquidator
_Testing_
The following businesses are loaded in dev and affiliated to account `3446`
```python
BC0752755
BC0318959
BC0721627
BC0515263
BC0685945
```

27278 & 27279 Tombstone - amend liquidator & correct liquidator

---

queue_services/business-emailer/src/business_emailer/email_processors/amalgamation_out_notification.py
queue_services/business-emailer/src/business_emailer/email_processors/consent_amalgamation_out_notification.py
queue_services/business-emailer/src/business_emailer/email_templates/AO-COMPLETED.html
queue_services/business-emailer/src/business_emailer/email_templates/CAO-COMPLETED.html
queue_services/business-emailer/src/business_emailer/email_templates/common/amalgamation-out-information.html
queue_services/business-emailer/src/business_emailer/email_templates/common/consent-letter-information.html
queue_services/business-emailer/src/business_emailer/resources/business_emailer.py
queue_services/business-emailer/src/business_emailer/services/versioned_business_details.py
queue_services/business-emailer/tests/unit/__init__.py
queue_services/business-emailer/tests/unit/email_processors/test_amalgamation_out_notification.py
queue_services/business-emailer/tests/unit/email_processors/test_consent_amalgamation_out_notification.py
queue_services/entity-emailer/tests/unit/__init__.py

*Issue #:* /bcgov/entity#27128
- replicate changes in #3386 #3418 and #3449 
For Amalgamation Out and CAO emailers, email templates, unit tests

27128 - Add Amalgamation Out emailers to Business Emailer

---

queue_services/business-emailer/src/business_emailer/email_processors/__init__.py

*Issue #:* /bcgov/entity#27128
- Add new template parts

Fix 27128 - Add Amalgamation Out emailers to Business Emailer

---

data-tool/flows/tombstone/tombstone_mappings.py

*Issue #:* /bcgov/entity#27273
- Add support for transfer records office to tombstone pipeline
Loaded following corps into dev under account 2596
- 'BC0809236', 'BC0659826', 'BC0386194', 'BC0662791', 'BC0099933', 'BC0430345', 'BC0422966', 'BC0368898', 'BC0476128'
Example UI + DB verification for BC0476128

27273 Add transfer records office to tombstone pipeline

---

colin-api/src/colin_api/models/corp_party.py
colin-api/src/colin_api/models/filing.py
colin-api/src/colin_api/resources/event.py
jobs/update-legal-filings/update_legal_filings.py
legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/resources/v2/business/colin_sync.py
queue_services/business-filer/src/business_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/requirements.txt
queue_services/entity-filer/requirements/bcregistry-libraries.txt

*Issue #:* /bcgov/entity#27482

27482 update legal filings for ben to bc business

---

queue_services/business-emailer/src/business_emailer/email_processors/affiliation_notification.py
queue_services/business-emailer/src/business_emailer/email_processors/bn_notification.py
queue_services/business-emailer/src/business_emailer/email_processors/involuntary_dissolution_stage_1_notification.py
queue_services/business-emailer/src/business_emailer/email_processors/name_request.py
queue_services/business-emailer/src/business_emailer/email_processors/nr_notification.py
queue_services/business-emailer/src/business_emailer/resources/business_emailer.py
queue_services/business-emailer/tests/unit/email_processors/test_affiliation_notification.py
queue_services/business-emailer/tests/unit/email_processors/test_bn_notification.py
queue_services/business-emailer/tests/unit/email_processors/test_involuntary_dissolution_stage_1_notification.py
queue_services/business-emailer/tests/unit/email_processors/test_nr_notification.py
queue_services/business-emailer/tests/unit/test_worker.py

*Issue #:* https://github.com/bcgov/entity/issues/26590
- updates for message integration discrepancies

GCP Migration - business-emailer tweaks

---

.github/workflows/legal-api-ci.yml
legal-api/src/legal_api/services/authz.py

*Issue #:* /bcgov/entity#26614
To fix the sandbox `filingSubmissionLink` issue,
Before:
Now:
Also brought in some legal-api-ci changes, otherwise, the CI tests and linting couldn't start for the sandbox branch

26614 - align filing url formatting

---

docs/business.yaml

*Issue #:* /bcgov/entity#27606
update the description for `effectiveDate` regarding it as a required property for CoD filings

27606 - update effectiveDate description regarding CoD filing

---

legal-api/report-templates/letterOfConsentAmalgamationOut.html

*Issue #:* /bcgov/entity#27568
- Update Amalgamation Out Consent Letter
Figma: https://www.figma.com/design/XGPA16tm4y28xS0ZPB586X/Consent-to-Amalgamate-Out---Amalgamate-Out?node-id=2672-15&m=dev

27568 - Update Amalgamation Out Consent Letter

---

data-tool/flows/tombstone/tombstone_mappings.py

*Issue #:* /bcgov/entity#27495
- Implemented NOC Address of Receiver/Receiver Manager
- All relevant party types and addresses already implemented
_Testing_
The following businesses are loaded in dev.
```python
'BC0049308',
'BC0107257',
'BC0240020',
'BC0873461',
'BC0876907',
'BC0873464',
'BC0016167',
'BC0865995',
'BC0189744',
'BC1151094',
'BC0722089'
```

27495 Tombstone - Implement NOC Address of Receiver/Receiver Manager

---

data-tool/scripts/transfer_cprd_corps.sql

*Issue #:* /bcgov/entity#25305
- include `BCOMPS` filing event

25305 Tombstone - Update extract script

---

legal-api/src/legal_api/exceptions/error_messages/codes.py
legal-api/src/legal_api/exceptions/error_messages/messages.py
legal-api/src/legal_api/resources/v2/business/business_filings/business_documents.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

check if a document is available to download

---

data-tool/scripts/transfer_cprd_corps.sql

*Issue #:* /bcgov/entity#27333 

27333 exclude businesses altered from BC to BEN then BEN to BC before directed launch

---

legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#28381
bumped version numbers up for release 25.3

28381 - bumped version numbers up for release 25.3

---

data-tool/flows/tombstone/tombstone_mappings.py

*Issue #:* /bcgov/entity#27494
- Implemented NOC Address Liquidator/ Liquidation Records Office
- All relevant party types and addresses already implemented
_Testing_
The following businesses are loaded in dev.
```python
'BC0203928',
'BC0431916',
'BC0522040'
```

27494 Tombstone - Implement NOC Address Liquidator/ Liquidation Records Office

---

legal-api/src/legal_api/services/filings/validations/schemas.py
legal-api/src/legal_api/utils/util.py

*Issue #:* /bcgov/entity#27507
- Improved API error response parsing by using the filter function.
- Returns the validation errors related to the filing in the current submission.
- If no relevant errors are found after filtering, all original validation errors are returned to the user.
Before:
After:

27507 - Improve API Error Response Parsing Message

---

legal-api/src/legal_api/services/digital_credentials.py

*Issue #:* https://github.com/bcgov/entity/issues/28524
See issue link above for details.
Add the goal code that the BC Wallet needs to present the loading UX for an OOB connection and attestation check

28524 Add a goal code to the digital credential invite

---

queue_services/business-filer/src/business_filer/filing_processors/dissolution.py
queue_services/entity-filer/src/entity_filer/filing_processors/dissolution.py

*Issue #:* /bcgov/entity#27570 

27570 - Expired Limited Restoration Job trying to file PBO for Dissolved Business

---

gcp-jobs/entity-bn/Makefile
gcp-jobs/entity-bn/run.sh
gcp-jobs/expired-limited-restoration/run.sh
gcp-jobs/filings-notebook-report/run.sh
gcp-jobs/future-effective-filings/run.sh
gcp-jobs/involuntary-dissolutions/run.sh
gcp-jobs/update-colin-filings/run.sh
gcp-jobs/update-legal-filings/run.sh

GCP Migration: tweaks to jobs run.sh

---

queue_services/business-filer/src/business_filer/filing_processors/filing_components/correction.py
queue_services/business-filer/src/business_filer/filing_processors/filing_components/parties.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/correction.py
queue_services/entity-filer/src/entity_filer/filing_processors/filing_components/parties.py

*Issue #:* /bcgov/entity#28414
- Update entity-filer and business-filer
- Skip db delete operation for unsupported roles
- (Safety check ) Update correction to cease specific roles

28414 Filer - skip operations for unsupported party roles

---

queue_services/entity-bn/requirements.txt
queue_services/entity-digital-credentials/requirements.txt
queue_services/entity-emailer/requirements.txt
queue_services/entity-filer/requirements.txt
queue_services/entity-pay/requirements.txt

fix: entity services build conflicts with legal-api import.

fix: entity services build conflicts with legal-api import.

---

data-tool/flows/tombstone/tombstone_mappings.py
data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#28654
Updates for `DISLV_NULL` event_file type:
- mapped to dissolution (subtype: voluntaryLiquidation)
- hide in ledger
_Testing_
The following businesses are loaded in dev
```
BC0923711
BC0515263
```

28654 Tombstone - implement Dissolution Voluntary Liquidation

---

python/common/business-registry-model/.devcontainer/Dockerfile
python/common/business-registry-model/.devcontainer/commands/post-create-command.sh
python/common/business-registry-model/.devcontainer/devcontainer.json
python/common/business-registry-model/README.md
python/common/business-registry-model/poetry.lock
python/common/business-registry-model/poetry.toml
python/common/business-registry-model/pyproject.toml
python/common/business-registry-model/src/business_model/utils/base.py
python/common/business-registry-model/tests/conftest.py
python/common/business-registry-model/tests/models/test_dc_connection.py
python/common/business-registry-model/tests/models/test_dc_definition.py
python/common/business-registry-model/tests/models/test_dc_issued_credential.py
python/common/business-registry-model/tests/models/test_filing.py
python/common/business-registry-model/tests/models/test_furnishing.py

*Issue #:* n/a
- add a .devcontainer setup to support testing
- add testcontainers to manage the postgres service in tests.

feat: add a .devcontainer and testcontainer for testing

---

data-tool/flows/tombstone/tombstone_mappings.py

*Issue #:* /bcgov/entity#28653
Updates for `FILE_ADCOL`
- mapped to `courtOrderedLiquidation` (not subtype of dissolution)
- not a state filing
- display in ledger
Updates for `FILE_ADVLQ` (no record up to now, just make it placeholder in code)
- mapped to `voluntaryLiquidation` (not subtype of dissolution)
- not a state filing 
- display in ledger
_Testing_
The following business is loaded in dev
```
BC0739207
```

28653 Tombstone - implement Court Ordered Liquidation & Voluntary Liquidation

---

legal-api/src/legal_api/models/filing.py

*Issue #:* /bcgov/entity#27120

27120 - exclude NOW for colin sync

---

python/common/business-registry-dissolution/tests/unit/test_involuntary_dissolution.py

*Issue #:* /bcgov/entity#28584

28584-2 Remove LIQUIDATION in business-registry-dissolution

---

python/common/business-registry-model/pyproject.toml
python/common/business-registry-model/src/business_model/models/__init__.py
python/common/business-registry-model/src/business_model/models/party_class.py
python/common/business-registry-model/src/business_model/models/party_role.py
python/common/business-registry-model/src/business_model/models/types/filings.py
python/common/business-registry-model/src/business_model/models/types/party_class_type.py
python/common/business-registry-model/src/business_model_migrations/versions/7fb9cd3e81bf_create_party_class_table.py
python/common/business-registry-model/tests/models/__init__.py
python/common/business-registry-model/tests/models/test_party_class.py

*Issue #:* /bcgov/entity#28815
- add PartyClass model to support officer change filing
- bulk insert of PartyClass descriptions still TBD

28815 - partyclass model

---

legal-api/migrations/versions/1dd76abf128a_add_party_class_model.py
legal-api/src/legal_api/models/__init__.py
legal-api/src/legal_api/models/party_class.py
legal-api/src/legal_api/models/party_role.py
legal-api/tests/unit/models/test_party_class.py

*Issue #:* bcgov/entity#28815
- add PartyClass model to legal-api models

28815 - add partyclass model to legal api

---

queue_services/business-filer/poetry.lock

*Issue #:* /bcgov/entity#28861

28861 model version update in filer

---

queue_services/business-filer/poetry.lock

pull recent commit for model

---

jobs/update-legal-filings/requirements.txt

*Issue #:* https://sbc-registries.atlassian.net/browse/ITOPS-183413

ITOPS-183413 add gcp-queue dependency

---

legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#25112
Updated Code to Forbidden Token is Present Action is not Allowed

25112 - "401 : Unauthorized"  message shows up in the Back End if the filing cant be performed as a result of allowable actions.

---

docs/business.yaml

*Issue #:* /bcgov/entity#28956
Legal API Spec Update

28956 - Legal API Spec Update

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#28916

28916 support party type change in changeOfRegistration (migrated data) output

---

legal-api/.devcontainer/devcontainer.json

*Issue #:* n/a
- added args and mounts for the devcontainer that should resolve some flaky connections to the host

chore(api) devcontainer additions based on flaky external DB connections

---

legal-api/src/legal_api/config.py
legal-api/src/legal_api/services/namex.py

*Issue #:* /bcgov/entity#29020

fix: GCP Namex integration issue

---

data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#29038

29038 tombstone - set last ar year in last_ar_reminder_year if email_log is missing

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#29070
Version Updated:
- Legal API
- Colin API
- Entity Filer

29070 Entities_Release_29.6 Version Bump

---

legal-api/migrations/versions/ed6645cc1530_add_alternate_name_field_to_party.py
legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/models/party.py
legal-api/src/legal_api/models/party_role.py
legal-api/src/legal_api/resources/v2/business/business_parties.py
legal-api/tests/unit/models/__init__.py
legal-api/tests/unit/models/test_party.py
legal-api/tests/unit/models/test_party_role.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py
legal-api/tests/unit/resources/v2/test_business_parties.py

*Issue #:* 
bcgov/entity#29016
bcgov/entity#29015
- update business schemas version
- add get by class type to PartyRole model
- add get by 'partyClass' param to business parties resource
- add alternate name field to Party model
- cleanup test after updating changeOfOfficers example data

29016 & 29015 - party updates legal api

---

legal-api/src/legal_api/services/filings/validations/common_validations.py

*Issue #:* /bcgov/entity#28460
fixed the issue we found for empty series list.

28460 - Fix series validation bug

---

legal-api/requirements.txt
legal-api/requirements/bcregistry-libraries.txt
legal-api/src/legal_api/models/party_role.py
legal-api/src/legal_api/resources/v2/business/business_parties.py
legal-api/src/legal_api/services/filings/validations/amalgamation_application.py
legal-api/src/legal_api/services/filings/validations/appoint_receiver.py
legal-api/src/legal_api/services/filings/validations/change_of_address.py
legal-api/src/legal_api/services/filings/validations/change_of_directors.py
legal-api/src/legal_api/services/filings/validations/change_of_officers.py
legal-api/src/legal_api/services/filings/validations/change_of_registration.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/continuation_in.py
legal-api/src/legal_api/services/filings/validations/conversion.py
legal-api/src/legal_api/services/filings/validations/correction.py
legal-api/src/legal_api/services/filings/validations/dissolution.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/src/legal_api/services/filings/validations/intent_to_liquidate.py
legal-api/src/legal_api/services/filings/validations/registration.py
legal-api/src/legal_api/services/filings/validations/restoration.py
legal-api/tests/unit/services/filings/validations/test_change_of_address.py
legal-api/tests/unit/services/filings/validations/test_common_validations.py

*Issue #:* /bcgov/entity#28496
- Add postal code validation for offices, parties
- Add common postal code validation for filings that is able to update the field
- Misc updates
_Testing_
- parties
- offices

28496 Legal API - update address postal code validation across filings

---

legal-api/report-templates/template-parts/business-summary/businessDetails.html

*Issue #:* /bcgov/entity#29142
- Update the In Liquidation flag to Yes when a Statement of Intent to Liquidate is filed

29142 - Update In Liquidation Flag in Business Summary

---

docs/business.yaml
legal-api/src/legal_api/resources/v2/business/business_filings/business_filings.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filings.py

*Issue #:* /bcgov/entity#28481
Replicate changes from main branch to update error message if user unable to file as a result of allowable action and update API specs
Reference PRs:
https://github.com/bcgov/lear/pull/3560/files
https://github.com/bcgov/lear/pull/3564/files

28481 - Improve errors return from allowable actions check

---

legal-api/migrations/versions/38730edc1543_accession_number.py
legal-api/src/legal_api/models/business.py
python/common/business-registry-model/pyproject.toml
python/common/business-registry-model/src/business_model/models/business.py
python/common/business-registry-model/src/business_model/models/filing.py
python/common/business-registry-model/src/business_model/utils/datetime.py
python/common/business-registry-model/src/business_model_migrations/versions/20250626_175036_dbf687803623_accession_number.py

*Issue #:* /bcgov/entity#28547

28547 add accession_number

---

.github/workflows/business-furnishings-cd.yml

Switch to use 1password service account.

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#29236

29236 - Entities Release Version Bump-2.153.0

---

legal-api/src/legal_api/resources/v2/admin/reviews.py

*Issue #:* /bcgov/entity#28974
Namex Payload Update for /review 

28974 - Namex Search Response Update

---

legal-api/src/legal_api/models/party_role.py
legal-api/src/legal_api/resources/v2/business/business_parties.py
legal-api/src/legal_api/version.py
legal-api/tests/unit/resources/v2/test_business_parties.py

*Issue #:* bcgov/entity#29237
- add new roleClass property to business parties response and PartyRole.json

29273 -  add role class to parties response legal api

---

legal-api/src/legal_api/services/filings/validations/dissolution.py
legal-api/tests/unit/resources/v2/test_admin/test_reviews.py
legal-api/tests/unit/services/filings/validations/test_dissolution.py

*Issue #:* /bcgov/entity#29319

29319 admin dissolution does not have parties

---

legal-api/devops/gcp/clouddeploy.yaml
queue_services/business-filer/devops/gcp/clouddeploy.yaml

*Issue #:* /bcgov/entity#29483
upped memory and cpu for filer in gcp dev/test/sandbox upped memory for business-api for dev/test/sandbox

up resource in dev test and sandbox for business api and filer

---

legal-api/src/legal_api/services/search_service.py

Hotfix for Search (#3634)

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py
queue_services/entity-emailer/src/entity_emailer/version.py
queue_services/entity-filer/src/entity_filer/version.py

*Issue #:* /bcgov/entity#29629
Version Updated for Release

29629 - Entities Release 25.7

---

colin-api/Dockerfile

*Issue #:* /bcgov/entity#29626

29626 colin api deployment fix

---

colin-api/src/colin_api/utils/util.py
colin-api/tests/unit/utils/test_util_cors.py

*Issue #:* /bcgov/entity#29677

29677 cors headers Account-Id and X-Apikey in colin-api

---

legal-api/src/legal_api/services/authz.py

*Issue #:* /bcgov/entity#29683

29683 allow maximus roles

---

python/common/business-registry-digital-credentials/poetry.lock
python/common/business-registry-digital-credentials/pyproject.toml

*Issue #:* /bcgov/entity#29608
Now that both business model changes, and new module are merged in, set correct dependency path.

Use main branch business model dependency

---

colin-api/src/colin_api/errorhandlers.py
legal-api/src/legal_api/errorhandlers.py

*Issue #:* /bcgov/entity#29746
- update COLIN api and Legal API  to accept spaces for header name in error handlers

29746 Update to support spaces in app header name

---

data-tool/notebooks/corps_onboarding_process_flow/migration_status_tracking.ipynb

*Issue #:* /bcgov/entity#29663
Fixed the bug when updating the excel file, the file path only been checked but not defined, which would cause issue when running the script

29663 - fix variable definition bug

---

gcp-jobs/update-legal-filings/devops/gcp/clouddeploy.yaml

*Issue #:* /bcgov/entity#29757
Set timeout and max retries for the legal filings job

set retries and timeout on legal filings gcp job

---

legal-api/src/legal_api/services/colin.py

*Issue #:* /bcgov/entity#29753
- updated secret and deployment config in OCP (test, prod)

29753 update colin api url

---

queue_services/business-filer/src/business_filer/config.py

fix the issue where the ncais url is incorrect due to the config changes and how is fetched from 1password

fix: add /naics at the end of url config

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#29864
Updated api version

Entities Release 26.2 Lear v2.152.3

---

colin-api/src/colin_api/version.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#29864
corrected version

Entities Release 26.2 v2.154.0

---

colin-api/src/colin_api/version.py
gcp-jobs/furnishings/src/furnishings/services/reports/registrar_meta.py
legal-api/src/legal_api/reports/registrar_meta.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#29716
- Update Registrar Signature date to Aug 12
- Update API version

29716 - Update New Registrar Signature Date

---

colin-api/src/colin_api/version.py
docs/business.yaml
gcp-jobs/furnishings/src/furnishings/services/reports/registrar_meta.py
legal-api/src/legal_api/reports/registrar_meta.py
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#29864

Registrar's date update

---

queue_services/business-pay/src/business_pay/config.py
queue_services/business-pay/src/business_pay/resources/pay_filer.py

*Issue #29930* /bcgov/entity#29930
fix: add missing BUSINESS_EMAILER_TOPIC to the config

fix: add missing BUSINESS_EMAILER_TOPIC to the config

---

legal-api/flags.json
legal-api/src/legal_api/reports/report.py

*Issue #:29984* /bcgov/entity#29984
add ff flag for DRS

chore: add ff flag for DRS

---

queue_services/business-emailer/src/business_emailer/resources/business_emailer.py

Add some emailer logs

---

gcp-jobs/furnishings/src/furnishings/services/reports/registrar_meta.py
legal-api/src/legal_api/reports/registrar_meta.py
legal-api/src/legal_api/version.py
legal-api/tests/unit/reports/test_registrar_meta.py

*Issue #:* bcgov/entity#30034
- commented out Kerry Taylor's record (x2)
- updated Legal API version = 2.154.2

30034 disable Aug 12 registrar change

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#30043

30043 use metadata for corrected alteration

---

queue_services/business-filer/src/business_filer/services/publish_event.py

*Issue #:* /bcgov/entity#29984

29984 Update identifier retrieval logic to cover NoW scenarios

---

colin-api/src/colin_api/exceptions/__init__.py
colin-api/src/colin_api/models/filing.py
gcp-jobs/update-colin-filings/src/update_colin_filings/worker.py

*Issue #:* /bcgov/entity#30094

30094 - create new director record after updating existing one

---

queue_services/business-filer/src/business_filer/common/services/account_service.py
queue_services/business-filer/src/business_filer/common/services/flag_manager.py
queue_services/business-filer/src/business_filer/filing_processors/amalgamation_application.py
queue_services/business-filer/src/business_filer/filing_processors/continuation_in.py
queue_services/business-filer/src/business_filer/filing_processors/filing_components/business_info.py
queue_services/business-filer/src/business_filer/filing_processors/filing_components/business_profile.py
queue_services/business-filer/src/business_filer/filing_processors/filing_components/name_request.py
queue_services/business-filer/src/business_filer/filing_processors/incorporation_filing.py
queue_services/business-filer/src/business_filer/filing_processors/registration.py
queue_services/business-filer/src/business_filer/services/filer.py
queue_services/business-filer/src/business_filer/services/publish_event.py
queue_services/business-filer/tests/unit/filing_processors/test_incorporation_filing.py
queue_services/business-filer/tests/unit/filing_processors/test_registration.py

refactor feature flag usage in filer

---

legal-api/src/legal_api/services/flags.py

* Update flag service to use LD context instead of dict which is req'd by LD SDK version we are using

Attempt to fix business-api LD dict error

---

data-tool/flows/tombstone/tombstone_queries.py
data-tool/flows/tombstone/tombstone_utils.py

Disable officer data in tombstone pipeline

---

legal-api/src/legal_api/services/authz.py
legal-api/src/legal_api/services/digital_credentials_auth.py
legal-api/src/legal_api/services/flags.py
legal-api/tests/unit/services/test_digital_credentials_auth.py
python/common/business-registry-digital-credentials/README.md
python/common/business-registry-digital-credentials/src/business_registry_digital_credentials/digital_credentials_auth.py
python/common/business-registry-digital-credentials/tests/unit/test_digital_credentials_auth.py

*Issue #:* /bcgov/entity#28908
Response change for fetching business, in DBC preconditions dict, to support PR in biz filings UI here: https://github.com/bcgov/business-filings-ui/pull/776
**Note**: this can merge in independently of the business UI PR (this one should just go in first)

DBC: Return additional details for preconditions

---

queue_services/business-filer/poetry.lock
queue_services/business-filer/src/business_filer/filing_processors/change_of_directors.py

*Issue #:* /bcgov/entity#30094

30094 filer - create new director record after updating existing one

---

legal-api/src/legal_api/core/meta/filing.py

*Issue #:* /bcgov/entity#29952

29952 COOP corrections no documents

---

data-tool/flows/tombstone/tombstone_utils.py

*Issue #:* /bcgov/entity#29735

29735 fix prop name

---

queue_services/business-filer/pyproject.toml
queue_services/business-filer/src/business_filer/filing_processors/filing_components/__init__.py
queue_services/business-filer/src/business_filer/filing_processors/filing_components/correction.py

*Issue #:* /bcgov/entity#30485

30485 update/create party address if provided

---

queue_services/business-filer/src/business_filer/filing_processors/intent_to_liquidate.py
queue_services/business-filer/src/business_filer/services/utils.py
queue_services/business-filer/tests/unit/__init__.py
queue_services/business-filer/tests/unit/filing_processors/test_incorporation_filing.py
queue_services/business-filer/tests/unit/filing_processors/test_registration.py
queue_services/business-filer/tests/unit/test_container/test_pubsub.py
queue_services/business-filer/tests/unit/test_filer/test_cease_receiver.py
queue_services/business-filer/tests/unit/test_filer/test_correction_bcia.py
queue_services/business-filer/tests/unit/test_filer/test_correction_firms.py
queue_services/business-filer/tests/unit/test_filer/test_intent_to_liquidate.py
queue_services/business-filer/tests/unit/test_filer/test_put_back_on.py
queue_services/business-filer/tests/unit/test_filer/test_restoration.py
queue_services/business-filer/tests/unit/test_resources/conftest.py
queue_services/business-filer/tests/unit/test_resources/test_push.py

filer - unit test fixes

---

legal-api/src/legal_api/services/filings/validations/alteration.py
legal-api/src/legal_api/services/filings/validations/amalgamation_application.py
legal-api/src/legal_api/services/filings/validations/common_validations.py
legal-api/src/legal_api/services/filings/validations/continuation_in.py
legal-api/src/legal_api/services/filings/validations/dissolution.py
legal-api/src/legal_api/services/filings/validations/incorporation_application.py
legal-api/tests/unit/services/filings/validations/test_alteration.py
legal-api/tests/unit/services/filings/validations/test_amalgamation_application.py
legal-api/tests/unit/services/filings/validations/test_continuation_in.py
legal-api/tests/unit/services/filings/validations/test_dissolution.py
legal-api/tests/unit/services/filings/validations/test_incorporation_application.py

*Issue #:* /bcgov/entity#30391 
- Refactor effective date validation method from **_incorporation application validations_** to **_common validations_**
- Update Alteration, Amalgamation, Continuation in, and Voluntary Dissolution Filings to validate effective date (to match UI)
- Update/add unit tests

30391 - Add Validation for Effective Date

---

legal-api/flags.json
legal-api/src/legal_api/services/business/validations/validator.py
legal-api/src/legal_api/services/filings/validations/agm_extension.py
legal-api/src/legal_api/services/filings/validations/agm_location_change.py
legal-api/src/legal_api/services/filings/validations/amalgamation_application.py
legal-api/src/legal_api/services/filings/validations/amalgamation_out.py
legal-api/src/legal_api/services/filings/validations/consent_amalgamation_out.py
legal-api/src/legal_api/services/filings/validations/consent_continuation_out.py
legal-api/src/legal_api/services/filings/validations/continuation_in.py
legal-api/src/legal_api/services/filings/validations/continuation_out.py
legal-api/src/legal_api/services/filings/validations/put_back_on.py

*Issue #:* /bcgov/entity#29852
- Discard Empty Flags 403

29852 - FF Discard Empty

---

legal-api/src/legal_api/version.py

*Issue #:* bcgov/entity#30235
- see title

Bump version to 2.155.2

---

legal-api/src/legal_api/version.py

*Issue #:* bcgov/entity#30235
- adding this version change to this release branch (part of downgrading Legal API in Test)
- main branch still have v2.155.2 for the next release

Update version to 2.155.1b

---

colin-api/src/colin_api/version.py
gcp-jobs/furnishings/pyproject.toml
legal-api/src/legal_api/version.py

*Issue #:* /bcgov/entity#30236
updated versions

30236 - Entities Release 26.5

---

legal-api/src/legal_api/core/filing.py
legal-api/tests/unit/resources/v2/test_business_filings/test_filing_documents.py

*Issue #:* /bcgov/entity#30528
Added No output filing

30528 - Disable Documents for OfficersChange Filings

---

legal-api/src/legal_api/reports/business_document.py

*Issue #:* /bcgov/entity#30535
Update roles >> full form 
eg. cfo >> chief financial officer

30535 - Updated Full Role Names for Officer Business Summary

---

legal-api/src/legal_api/reports/report.py

*Issue #:* /bcgov/entity#30725
- (cherry picked from commit a3e4018399634455423b935f265d4938a5e85981)

30725 - NOA generated for COD, effective date (Issued Date and Time) is the filing date

---

legal-api/src/legal_api/services/filings/validations/validation.py

*Issue #:* /bcgov/entity#30809
Holding certify Name change till Certify statement work is finalized

30809 - Certify Name Validation Removed

---

legal-api/src/legal_api/models/business.py
legal-api/tests/unit/models/test_business.py
python/common/business-registry-model/src/business_model/models/business.py
python/common/business-registry-model/src/business_model/models/types/filings.py
python/common/business-registry-model/tests/models/test_business.py

*Issue #:* /bcgov/entity#30689

30689 transaction needed when restored (full or limited to full)

---

legal-api/report-templates/registration.html

*Issue #:* /bcgov/entity#29975
[response.pdf](https://github.com/user-attachments/files/22518773/response.pdf)

29975 remove extra line registration output
